const datas =  [
  {
    id: 1,
    chinese: "你好。",
    pinyin: "Nǐ hǎo.",
    myanmar: "မင်္ဂလာပါ။",
  },
  {
    id: 2,
    chinese: "你好吗？",
    pinyin: "Nǐ hǎo ma?",
    myanmar: "နေကောင်းလား?",
  },
  {
    id: 3,
    chinese: "我很好。",
    pinyin: "Wǒ hěn hǎo.",
    myanmar: "ကျွန်တော် နေကောင်းပါတယ်။",
  },
  {
    id: 4,
    chinese: "你叫什么名字？",
    pinyin: "Nǐ jiào shénme míngzi?",
    myanmar: "မင်းနာမည် ဘာလဲ?",
  },
  {
    id: 5,
    chinese: "我叫小明。",
    pinyin: "Wǒ jiào Xiǎomíng.",
    myanmar: "ကျွန်တော့်နာမည် ရှောင်မင်ပါ။",
  },
  {
    id: 6,
    chinese: "他是谁？",
    pinyin: "Tā shì shéi?",
    myanmar: "သူက ဘယ်သူလဲ?",
  },
  {
    id: 7,
    chinese: "他是我的老师。",
    pinyin: "Tā shì wǒ de lǎoshī.",
    myanmar: "သူက ကျွန်တော့်ရဲ့ ဆရာပါ။",
  },
  {
    id: 8,
    chinese: "你是哪国人？",
    pinyin: "Nǐ shì nǎ guó rén?",
    myanmar: "မင်းက ဘယ်နိုင်ငံသားလဲ?",
  },
  {
    id: 9,
    chinese: "我是缅甸人。",
    pinyin: "Wǒ shì Miǎndiàn rén.",
    myanmar: "ကျွန်တော် မြန်မာနိုင်ငံသားပါ။",
  },
  {
    id: 10,
    chinese: "谢谢你。",
    pinyin: "Xièxie nǐ.",
    myanmar: "ကျေးဇူးတင်ပါတယ်။",
  },
  {
    id: 11,
    chinese: "不客气。",
    pinyin: "Bú kèqi.",
    myanmar: "ကိစ္စမရှိပါဘူး။",
  },
  {
    id: 12,
    chinese: "对不起。",
    pinyin: "Duìbuqǐ.",
    myanmar: "တောင်းပန်ပါတယ်။",
  },
  {
    id: 13,
    chinese: "没关系。",
    pinyin: "Méi guānxi.",
    myanmar: "ရပါတယ် (ဘာမှမဖြစ်ပါဘူး)။",
  },
  {
    id: 14,
    chinese: "你会说汉语吗？",
    pinyin: "Nǐ huì shuō Hànyǔ ma?",
    myanmar: "မင်း တရုတ်စကား ပြောတတ်လား?",
  },
  {
    id: 15,
    chinese: "我会说一点儿。",
    pinyin: "Wǒ huì shuō yìdiǎnr.",
    myanmar: "ကျွန်တော် နည်းနည်း ပြောတတ်ပါတယ်။",
  },
  {
    id: 16,
    chinese: "现在几点？",
    pinyin: "Xiànzài jǐ diǎn?",
    myanmar: "အခု ဘယ်နှစ်နာရီလဲ?",
  },
  {
    id: 17,
    chinese: "现在三点半。",
    pinyin: "Xiànzài sān diǎn bàn.",
    myanmar: "အခု သုံးနာရီခွဲပါ။",
  },
  {
    id: 18,
    chinese: "今天星期几？",
    pinyin: "Jīntiān xīngqī jǐ?",
    myanmar: "ဒီနေ့ ဘာနေ့လဲ?",
  },
  {
    id: 19,
    chinese: "今天星期五。",
    pinyin: "Jīntiān xīngqī wǔ.",
    myanmar: "ဒီနေ့ သောကြာနေ့ပါ။",
  },
  {
    id: 20,
    chinese: "你的生日是几月几号？",
    pinyin: "Nǐ de shēngrì shì jǐ yuè jǐ hào?",
    myanmar: "မင်းမွေးနေ့က ဘယ်လောက်လဲ?",
  },
  {
    id: 21,
    chinese: "你想吃什么？",
    pinyin: "Nǐ xiǎng chī shénme?",
    myanmar: "မင်း ဘာစားချင်လဲ?",
  },
  {
    id: 22,
    chinese: "我想吃面条。",
    pinyin: "Wǒ xiǎng chī miàntiáo.",
    myanmar: "ကျွန်တော် ခေါက်ဆွဲစားချင်တယ်။",
  },
  {
    id: 23,
    chinese: "这个多少钱？",
    pinyin: "Zhèige duōshǎo qián?",
    myanmar: "ဒါ ဘယ်လောက်လဲ?",
  },
  {
    id: 24,
    chinese: "太贵了。",
    pinyin: "Tài guì le.",
    myanmar: "ဈေးကြီးလွန်းတယ်။",
  },
  {
    id: 25,
    chinese: "你在哪儿工作？",
    pinyin: "Nǐ zài nǎr gōngzuò?",
    myanmar: "မင်း ဘယ်မှာ အလုပ်လုပ်လဲ?",
  },
  {
    id: 26,
    chinese: "我在医院工作。",
    pinyin: "Wǒ zài yīyuàn gōngzuò.",
    myanmar: "ကျွန်တော် ဆေးရုံမှာ အလုပ်လုပ်တယ်။",
  },
  {
    id: 27,
    chinese: "你在做什么？",
    pinyin: "Nǐ zài zuò shénme?",
    myanmar: "မင်း ဘာလုပ်နေတာလဲ?",
  },
  {
    id: 28,
    chinese: "我在看电视。",
    pinyin: "Wǒ zài kàn diànshì.",
    myanmar: "ကျွန်တော် တီဗွီကြည့်နေတယ်။",
  },
  {
    id: 29,
    chinese: "天气怎么样？",
    pinyin: "Tiānqì zěnmeyàng?",
    myanmar: "ရာသီဥတု ဘယ်လိုလဲ?",
  },
  {
    id: 30,
    chinese: "下雨了。",
    pinyin: "Xià yǔ le.",
    myanmar: "မိုးရွာနေပြီ။",
  },
  {
    id: 31,
    chinese: "我不去学校。",
    pinyin: "Wǒ bú qù xuéxiào.",
    myanmar: "ကျွန်တော် ကျောင်းမသွားဘူး။",
  },
  {
    id: 32,
    chinese: "请坐。",
    pinyin: "Qǐng zuò.",
    myanmar: "ထိုင်ပါ။",
  },
  {
    id: 33,
    chinese: "请喝茶。",
    pinyin: "Qǐng hē chá.",
    myanmar: "လက်ဖက်ရည်သောက်ပါ။",
  },
  {
    id: 34,
    chinese: "我爱吃水果。",
    pinyin: "Wǒ ài chī shuǐguǒ.",
    myanmar: "ကျွန်တော် အသီးစားရတာ ကြိုက်တယ်။",
  },
  {
    id: 35,
    chinese: "明天天气很好。",
    pinyin: "Míngtiān tiānqì hěn hǎo.",
    myanmar: "မနက်ဖြန် ရာသီဥတု အရမ်းကောင်းတယ်။",
  },
  {
    id: 36,
    chinese: "你会开车吗？",
    pinyin: "Nǐ huì kāi chē ma?",
    myanmar: "မင်း ကားမောင်းတတ်လား?",
  },
  {
    id: 37,
    chinese: "那个苹果很大。",
    pinyin: "Nàge píngguǒ hěn dà.",
    myanmar: "အဲဒီပန်းသီးက အရမ်းကြီးတယ်။",
  },
  {
    id: 38,
    chinese: "我不认识他。",
    pinyin: "Wǒ bù rènshi tā.",
    myanmar: "ကျွန်တော် သူ့ကို မသိဘူး။",
  },
  {
    id: 39,
    chinese: "我有三本书。",
    pinyin: "Wǒ yǒu sān běn shū.",
    myanmar: "ကျွန်တော့်မှာ စာအုပ် ၃ အုပ်ရှိတယ်။",
  },
  {
    id: 40,
    chinese: "你在家吗？",
    pinyin: "Nǐ zài jiā ma?",
    myanmar: "မင်း အိမ်မှာလား?",
  },
  {
    id: 41,
    chinese: "我在家。",
    pinyin: "Wǒ zài jiā.",
    myanmar: "ကျွန်တော် အိမ်မှာပါ။",
  },
  {
    id: 42,
    chinese: "商店在哪儿？",
    pinyin: "Shāngdiàn zài nǎr?",
    myanmar: "ဆိုင်က ဘယ်မှာလဲ?",
  },
  {
    id: 43,
    chinese: "他在打电话。",
    pinyin: "Tā zài dǎ diànhuà.",
    myanmar: "သူ ဖုန်းဆက်နေတယ်။",
  },
  {
    id: 44,
    chinese: "请写你的名字。",
    pinyin: "Qǐng xiě nǐ de míngzi.",
    myanmar: "မင်းနာမည် ရေးပေးပါ။",
  },
  {
    id: 45,
    chinese: "我们要去买东西。",
    pinyin: "Wǒmen yào qù mǎi dōngxi.",
    myanmar: "ငါတို့ ပစ္စည်းသွားဝယ်ရမယ်။",
  },
  {
    id: 46,
    chinese: "这件衣服很漂亮。",
    pinyin: "Zhè jiàn yīfu hěn piàoliang.",
    myanmar: "ဒီအကျီက အရမ်းလှတယ်။",
  },
  {
    id: 47,
    chinese: "桌子上有杯子。",
    pinyin: "Zhuōzi shang yǒu bēizi.",
    myanmar: "စားပွဲပေါ်မှာ ခွက်ရှိတယ်။",
  },
  {
    id: 48,
    chinese: "我不喜欢吃米饭。",
    pinyin: "Wǒ bù xǐhuan chī mǐfàn.",
    myanmar: "ကျွန်တော် ထမင်းစားရတာ မကြိုက်ဘူး။",
  },
  {
    id: 49,
    chinese: "我听懂了。",
    pinyin: "Wǒ tīng dǒng le.",
    myanmar: "ကျွန်တော် နားလည်သွားပြီ။",
  },
  {
    id: 50,
    chinese: "我们可以去吗？",
    pinyin: "Wǒmen kěyǐ qù ma?",
    myanmar: "ငါတို့ သွားလို့ရမလား?",
  },
  {
    id: 51,
    chinese: "我明白了。",
    pinyin: "Wǒ míngbai le.",
    myanmar: "ကျွန်တော် နားလည်သွားပြီ။",
  },
  {
    id: 52,
    chinese: "请给我一杯水。",
    pinyin: "Qǐng gěi wǒ yì bēi shuǐ.",
    myanmar: "ကျွန်တော့်ကို ရေတစ်ခွက် ပေးပါ။",
  },
  {
    id: 53,
    chinese: "这个字怎么读？",
    pinyin: "Zhèige zì zěnme dú?",
    myanmar: "ဒီစာလုံးကို ဘယ်လိုဖတ်ရမလဲ?",
  },
  {
    id: 54,
    chinese: "他是我哥哥。",
    pinyin: "Tā shì wǒ gēge.",
    myanmar: "သူက ကျွန်တော့်အစ်ကိုပါ။",
  },
  {
    id: 55,
    chinese: "妈妈在做饭。",
    pinyin: "Māma zài zuòfàn.",
    myanmar: "အမေ ထမင်းချက်နေတယ်။",
  },
  {
    id: 56,
    chinese: "你会跳舞吗？",
    pinyin: "Nǐ huì tiàowǔ ma?",
    myanmar: "မင်း ကတတ်လား?",
  },
  {
    id: 57,
    chinese: "我不会唱歌。",
    pinyin: "Wǒ bú huì chànggē.",
    myanmar: "ကျွန်တော် သီချင်းမဆိုတတ်ဘူး။",
  },
  {
    id: 58,
    chinese: "北京很大。",
    pinyin: "Běijīng hěn dà.",
    myanmar: "ပေကျင်းက အရမ်းကြီးတယ်။",
  },
  {
    id: 59,
    chinese: "今天很忙。",
    pinyin: "Jīntiān hěn máng.",
    myanmar: "ဒီနေ့ အလုပ်အရမ်းများတယ်။",
  },
  {
    id: 60,
    chinese: "请再说一遍。",
    pinyin: "Qǐng zài shuō yí biàn.",
    myanmar: "ကျေးဇူးပြုပြီး နောက်တစ်ခေါက် ထပ်ပြောပေးပါ။",
  },
  {
    id: 61,
    chinese: "那儿有两个人。",
    pinyin: "Nàr yǒu liǎng gè rén.",
    myanmar: "ဟိုမှာ လူနှစ်ယောက် ရှိတယ်။",
  },
  {
    id: 62,
    chinese: "我喜欢看电影。",
    pinyin: "Wǒ xǐhuan kàn diànyǐng.",
    myanmar: "ကျွန်တော် ရုပ်ရှင်ကြည့်ရတာ ကြိုက်တယ်။",
  },
  {
    id: 63,
    chinese: "你的汉语很好。",
    pinyin: "Nǐ de Hànyǔ hěn hǎo.",
    myanmar: "မင်းရဲ့ တရုတ်စာက အရမ်းကောင်းပါတယ်။",
  },
  {
    id: 64,
    chinese: "他在哪儿？",
    pinyin: "Tā zài nǎr?",
    myanmar: "သူ ဘယ်မှာလဲ?",
  },
  {
    id: 65,
    chinese: "他在学校后面。",
    pinyin: "Tā zài xuéxiào hòumiàn.",
    myanmar: "သူ ကျောင်းရဲ့ နောက်ဘက်မှာ ရှိတယ်။",
  },
  {
    id: 66,
    chinese: "我有一只猫。",
    pinyin: "Wǒ yǒu yì zhī māo.",
    myanmar: "ကျွန်တော့်မှာ ကြောင်တစ်ကောင် ရှိတယ်။",
  },
  {
    id: 67,
    chinese: "这是一本书。",
    pinyin: "Zhè shì yì běn shū.",
    myanmar: "ဒါက စာအုပ်တစ်အုပ်ပါ။",
  },
  {
    id: 68,
    chinese: "那不是我的杯子。",
    pinyin: "Nà bú shì wǒ de bēizi.",
    myanmar: "ဒါက ကျွန်တော့်ခွက် မဟုတ်ဘူး။",
  },
  {
    id: 69,
    chinese: "我们去看电影吧。",
    pinyin: "Wǒmen qù kàn diànyǐng ba.",
    myanmar: "ငါတို့ ရုပ်ရှင်သွားကြည့်ရအောင်။",
  },
  {
    id: 70,
    chinese: "外面冷吗？",
    pinyin: "Wàimiàn lěng ma?",
    myanmar: "အပြင်မှာ အေးလား?",
  },
  {
    id: 71,
    chinese: "外面不冷。",
    pinyin: "Wàimiàn bù lěng.",
    myanmar: "အပြင်မှာ မအေးပါဘူး။",
  },
  {
    id: 72,
    chinese: "你想喝什么？",
    pinyin: "Nǐ xiǎng hē shénme?",
    myanmar: "မင်း ဘာသောက်ချင်လဲ?",
  },
  {
    id: 73,
    chinese: "我想喝咖啡。",
    pinyin: "Wǒ xiǎng hē kāfēi.",
    myanmar: "ကျွန်တော် ကော်ဖီသောက်ချင်တယ်။",
  },
  {
    id: 74,
    chinese: "这儿有很多菜。",
    pinyin: "Zhèr yǒu hěnduō cài.",
    myanmar: "ဒီမှာ ဟင်းတွေ အများကြီး ရှိတယ်။",
  },
  {
    id: 75,
    chinese: "他在睡觉呢。",
    pinyin: "Tā zài shuìjiào ne.",
    myanmar: "သူ အိပ်နေတယ်။",
  },
  {
    id: 76,
    chinese: "你会写汉字吗？",
    pinyin: "Nǐ huì xiě Hànzì ma?",
    myanmar: "မင်း တရုတ်စာ ရေးတတ်လား?",
  },
  {
    id: 77,
    chinese: "我会写一点点。",
    pinyin: "Wǒ huì xiě yìdiǎndiǎn.",
    myanmar: "ကျွန်တော် နည်းနည်း ရေးတတ်ပါတယ်။",
  },
  {
    id: 78,
    chinese: "水果在那儿。",
    pinyin: "Shuǐguǒ zài nàr.",
    myanmar: "အသီးတွေက ဟိုမှာပါ။",
  },
  {
    id: 79,
    chinese: "这些苹果很好吃。",
    pinyin: "Zhèxiē píngguǒ hěn hǎochī.",
    myanmar: "ဒီပန်းသီးတွေက အရမ်းစားကောင်းတယ်။",
  },
  {
    id: 80,
    chinese: "你有几个孩子？",
    pinyin: "Nǐ yǒu jǐ gè háizi?",
    myanmar: "မင်းမှာ ကလေးဘယ်နှစ်ယောက် ရှိလဲ?",
  },
  {
    id: 81,
    chinese: "我有两个孩子。",
    pinyin: "Wǒ yǒu liǎng gè háizi.",
    myanmar: "ကျွန်တော့်မှာ ကလေးနှစ်ယောက် ရှိတယ်။",
  },
  {
    id: 82,
    chinese: "明天星期几？",
    pinyin: "Míngtiān xīngqī jǐ?",
    myanmar: "မနက်ဖြန် ဘာနေ့လဲ?",
  },
  {
    id: 83,
    chinese: "明天星期六。",
    pinyin: "Míngtiān xīngqī liù.",
    myanmar: "မနက်ဖြန် စနေနေ့ပါ။",
  },
  {
    id: 84,
    chinese: "你在读什么书？",
    pinyin: "Nǐ zài dú shénme shū?",
    myanmar: "မင်း ဘာစာအုပ် ဖတ်နေတာလဲ?",
  },
  {
    id: 85,
    chinese: "我在学汉语呢。",
    pinyin: "Wǒ zài xué Hànyǔ ne.",
    myanmar: "ကျွန်တော် တရုတ်စာ သင်နေတယ်။",
  },
  {
    id: 86,
    chinese: "医生在吗？",
    pinyin: "Yīshēng zài ma?",
    myanmar: "ဆရာဝန် ရှိလား?",
  },
  {
    id: 87,
    chinese: "医生不在医院。",
    pinyin: "Yīshēng bú zài yīyuàn.",
    myanmar: "ဆရာဝန် ဆေးရုံမှာ မရှိဘူး။",
  },
  {
    id: 88,
    chinese: "你会游泳吗？",
    pinyin: "Nǐ huì yóuyǒng ma?",
    myanmar: "မင်း ရေကူးတတ်လား?",
  },
  {
    id: 89,
    chinese: "我会游泳。",
    pinyin: "Wǒ huì yóuyǒng.",
    myanmar: "ကျွန်တော် ရေကူးတတ်တယ်။",
  },
  {
    id: 90,
    chinese: "这个太小了。",
    pinyin: "Zhèige tài xiǎo le.",
    myanmar: "ဒါက အရမ်း သေးလွန်းတယ်။",
  },
  {
    id: 91,
    chinese: "请看黑板。",
    pinyin: "Qǐng kàn hēibǎn.",
    myanmar: "ကျောက်သင်ပုန်းကို ကြည့်ပါ။",
  },
  {
    id: 92,
    chinese: "那是什么东西？",
    pinyin: "Nà shì shénme dōngxi?",
    myanmar: "ဟိုဟာ ဘာလဲ?",
  },
  {
    id: 93,
    chinese: "那是我买的衣服。",
    pinyin: "Nà shì wǒ mǎi de yīfu.",
    myanmar: "ဟိုဒါက ကျွန်တော် ဝယ်ထားတဲ့ အကျီပါ။",
  },
  {
    id: 94,
    chinese: "我不认识那个字。",
    pinyin: "Wǒ bù rènshi nàge zì.",
    myanmar: "ကျွန်တော် အဲဒီစာလုံးကို မသိဘူး။",
  },
  {
    id: 95,
    chinese: "我们走吧。",
    pinyin: "Wǒmen zǒu ba.",
    myanmar: "ငါတို့ သွားကြစို့။",
  },
  {
    id: 96,
    chinese: "你几点去？",
    pinyin: "Nǐ jǐ diǎn qù?",
    myanmar: "မင်း ဘယ်နှစ်နာရီ သွားမှာလဲ?",
  },
  {
    id: 97,
    chinese: "我八点去学校。",
    pinyin: "Wǒ bā diǎn qù xuéxiào.",
    myanmar: "ကျွန်တော် ရှစ်နာရီမှာ ကျောင်းသွားမယ်။",
  },
  {
    id: 98,
    chinese: "他还没到。",
    pinyin: "Tā hái méi dào.",
    myanmar: "သူ မရောက်သေးဘူး။",
  },
  {
    id: 99,
    chinese: "你喜欢喝茶吗？",
    pinyin: "Nǐ xǐhuan hē chá ma?",
    myanmar: "မင်း လက်ဖက်ရည် သောက်ရတာ ကြိုက်လား?",
  },
  {
    id: 100,
    chinese: "我很喜欢喝热茶。",
    pinyin: "Wǒ hěn xǐhuan hē rè chá.",
    myanmar: "ကျွန်တော် လက်ဖက်ရည်ပူပူ သောက်ရတာ အရမ်းကြိုက်တယ်။",
  },
  {
    id: 101,
    chinese: "你觉得这件衣服怎么样？",
    pinyin: "Nǐ juédé zhè jiàn yīfu zěnmeyàng?",
    myanmar: "ဒီအင်္ကျီက ဘယ်လိုလဲလို့ မင်းထင်လဲ?",
  },
  {
    id: 102,
    chinese: "我觉得很漂亮。",
    pinyin: "Wǒ juédé hěn piàoliang.",
    myanmar: "ကျွန်တော်ကတော့ အရမ်းလှတယ်လို့ ထင်တယ်။",
  },
  {
    id: 103,
    chinese: "你去过北京吗？",
    pinyin: "Nǐ qùguo Běijīng ma?",
    myanmar: "မင်း ပေကျင်းကို သွားဖူးလား?",
  },
  {
    id: 104,
    chinese: "我没去过北京。",
    pinyin: "Wǒ méi qùguo Běijīng.",
    myanmar: "ကျွန်တော် ပေကျင်းကို မသွားဖူးဘူး။",
  },
  {
    id: 105,
    chinese: "他在哪儿工作？",
    pinyin: "Tā zài nǎr gōngzuò?",
    myanmar: "သူ ဘယ်မှာ အလုပ်လုပ်တာလဲ?",
  },
  {
    id: 106,
    chinese: "他在火车站工作。",
    pinyin: "Tā zài huǒchēzhàn gōngzuò.",
    myanmar: "သူ မီးရထားဘူတာမှာ အလုပ်လုပ်တယ်။",
  },
  {
    id: 107,
    chinese: "你会踢足球吗？",
    pinyin: "Nǐ huì tī zúqiú ma?",
    myanmar: "မင်း ဘောလုံးကန်တတ်လား?",
  },
  {
    id: 108,
    chinese: "我最喜欢打篮球。",
    pinyin: "Wǒ zuì xǐhuan dǎ lánqiú.",
    myanmar: "ကျွန်တော် ဘတ်စကက်ဘော ကစားရတာ အကြိုက်ဆုံးပဲ။",
  },
  {
    id: 109,
    chinese: "外面在下雪。",
    pinyin: "Wàimiàn zài xiàxuě.",
    myanmar: "အပြင်မှာ နှင်းကျနေတယ်။",
  },
  {
    id: 110,
    chinese: "这个手机很贵。",
    pinyin: "Zhèige shǒujī hěn guì.",
    myanmar: "ဒီဖုန်းက အရမ်းဈေးကြီးတယ်။",
  },
  {
    id: 111,
    chinese: "你想买哪一个？",
    pinyin: "Nǐ xiǎng mǎi nǎ yí gè?",
    myanmar: "မင်း ဘယ်တစ်ခုကို ဝယ်ချင်လဲ?",
  },
  {
    id: 112,
    chinese: "我想买这个新的。",
    pinyin: "Wǒ xiǎng mǎi zhèige xīn de.",
    myanmar: "ကျွန်တော် ဒီအသစ်လေးကို ဝယ်ချင်တယ်။",
  },
  {
    id: 113,
    chinese: "那是谁的手机？",
    pinyin: "Nà shì shéi de shǒujī?",
    myanmar: "ဟိုဒါ ဘယ်သူ့ဖုန်းလဲ?",
  },
  {
    id: 114,
    chinese: "那是老师的手机。",
    pinyin: "Nà shì lǎoshī de shǒujī.",
    myanmar: "ဟိုဒါ ဆရာ့ရဲ့ ဖုန်းပါ။",
  },
  {
    id: 115,
    chinese: "你家离公司远吗？",
    pinyin: "Nǐ jiā lí gōngsī yuǎn ma?",
    myanmar: "မင်းအိမ်က ကုမ္ပဏီနဲ့ ဝေးလား?",
  },
  {
    id: 116,
    chinese: "我家离公司很近。",
    pinyin: "Wǒ jiā lí gōngsī hěn jìn.",
    myanmar: "ကျွန်တော့်အိမ်က ကုမ္ပဏီနဲ့ အရမ်းနီးတယ်။",
  },
  {
    id: 117,
    chinese: "你怎么去学校？",
    pinyin: "Nǐ zěnme qù xuéxiào?",
    myanmar: "မင်း ကျောင်းကို ဘယ်လိုသွားလဲ?",
  },
  {
    id: 118,
    chinese: "我坐公共汽车去学校。",
    pinyin: "Wǒ zuò gōnggòng qìchē qù xuéxiào.",
    myanmar: "ကျွန်တော် ဘတ်စကားစီးပြီး ကျောင်းသွားတယ်။",
  },
  {
    id: 119,
    chinese: "你在读什么书？",
    pinyin: "Nǐ zài dú shénme shū?",
    myanmar: "မင်း ဘာစာအုပ် ဖတ်နေတာလဲ?",
  },
  {
    id: 120,
    chinese: "我在读汉语书。",
    pinyin: "Wǒ zài dú Hànyǔ shū.",
    myanmar: "ကျွန်တော် တရုတ်စာအုပ် ဖတ်နေတယ်။",
  },
  {
    id: 121,
    chinese: "别说话，老师来了。",
    pinyin: "Bié shuōhuà, lǎoshī lái le.",
    myanmar: "စကားမပြောနဲ့တော့၊ ဆရာလာပြီ။",
  },
  {
    id: 122,
    chinese: "我病了，不能去上课。",
    pinyin: "Wǒ bìng le, bù néng qù shàngkè.",
    myanmar: "ကျွန်တော် နေမကောင်းလို့ အတန်းမတက်နိုင်ဘူး။",
  },
  {
    id: 123,
    chinese: "多喝点儿热开水。",
    pinyin: "Duō hē diǎnr rè kāishuǐ.",
    myanmar: "ရေနွေးများများ သောက်ပါ။",
  },
  {
    id: 124,
    chinese: "这个药一天吃三次。",
    pinyin: "Zhèige yào yì tiān chī sān cì.",
    myanmar: "ဒီဆေးကို တစ်နေ့ သုံးကြိမ်သောက်ပါ။",
  },
  {
    id: 125,
    chinese: "你准备好了吗？",
    pinyin: "Nǐ zhǔnbèi hǎo le ma?",
    myanmar: "မင်း အဆင်သင့်ဖြစ်ပြီလား?",
  },
  {
    id: 126,
    chinese: "我还没准备好。",
    pinyin: "Wǒ hái méi zhǔnbèi hǎo.",
    myanmar: "ကျွန်တော် အဆင်သင့် မဖြစ်သေးဘူး။",
  },
  {
    id: 127,
    chinese: "考试难不难？",
    pinyin: "Kǎoshì nán bù nán?",
    myanmar: "စာမေးပွဲ ခက်လား?",
  },
  {
    id: 128,
    chinese: "考试不难，很简单。",
    pinyin: "Kǎoshì bù nán, hěn jiǎndān.",
    myanmar: "စာမေးပွဲ မခက်ပါဘူး၊ အရမ်းလွယ်ပါတယ်။",
  },
  {
    id: 129,
    chinese: "请给我介绍一下。",
    pinyin: "Qǐng gěi wǒ jièshào yíxià.",
    myanmar: "ကျွန်တော့်ကို နည်းနည်းလောက် မိတ်ဆက်ပေးပါ။",
  },
  {
    id: 130,
    chinese: "这是我的好朋友。",
    pinyin: "Zhè shì wǒ de hǎo péngyou.",
    myanmar: "ဒါက ကျွန်တော့်ရဲ့ သူငယ်ချင်းကောင်းပါ။",
  },
  {
    id: 131,
    chinese: "认识你很高兴。",
    pinyin: "Rènshi nǐ hěn gāoxìng.",
    myanmar: "မင်းနဲ့ သိရတာ ဝမ်းသာပါတယ်။",
  },
  {
    id: 132,
    chinese: "我也很高兴。",
    pinyin: "Wǒ yě hěn gāoxìng.",
    myanmar: "ကျွန်တော်လည်း ဝမ်းသာပါတယ်။",
  },
  {
    id: 133,
    chinese: "你什么时候回家？",
    pinyin: "Nǐ shénme shíhou huíjiā?",
    myanmar: "မင်း အိမ်ကို ဘယ်တော့ပြန်မှာလဲ?",
  },
  {
    id: 134,
    chinese: "我下午五点回家。",
    pinyin: "Wǒ xiàwǔ wǔ diǎn huíjiā.",
    myanmar: "ကျွန်တော် ညနေ ၅ နာရီမှာ အိမ်ပြန်မယ်။",
  },
  {
    id: 135,
    chinese: "你会做中国菜吗？",
    pinyin: "Nǐ huì zuò Zhōngguó cài ma?",
    myanmar: "မင်း တရုတ်ဟင်း ချက်တတ်လား?",
  },
  {
    id: 136,
    chinese: "我会做一点儿。",
    pinyin: "Wǒ huì zuò yìdiǎnr.",
    myanmar: "ကျွန်တော် နည်းနည်း ချက်တတ်ပါတယ်။",
  },
  {
    id: 137,
    chinese: "这个菜太咸了。",
    pinyin: "Zhèige cài tài xián le.",
    myanmar: "ဒီဟင်းက အရမ်း ငန်လွန်းတယ်။",
  },
  {
    id: 138,
    chinese: "你等我一下。",
    pinyin: "Nǐ děng wǒ yíxià.",
    myanmar: "မင်း ကျွန်တော့်ကို ခဏစောင့်ပါ။",
  },
  {
    id: 139,
    chinese: "不要走，等我两分钟。",
    pinyin: "Búyào zǒu, děng wǒ liǎng fēnzhōng.",
    myanmar: "မသွားပါနဲ့ဦး၊ ကျွန်တော့်ကို နှစ်မိနစ်လောက် စောင့်ပါ။",
  },
  {
    id: 140,
    chinese: "我们要考试了。",
    pinyin: "Wǒmen yào kǎoshì le.",
    myanmar: "ငါတို့ စာမေးပွဲ ဖြေရတော့မယ်။",
  },
  {
    id: 141,
    chinese: "你在读什么大学？",
    pinyin: "Nǐ zài dú shénme dàxué?",
    myanmar: "မင်း ဘယ်တက္ကသိုလ်မှာ တက်နေတာလဲ?",
  },
  {
    id: 142,
    chinese: "他在看报纸呢。",
    pinyin: "Tā zài kàn bàozhǐ ne.",
    myanmar: "သူ သတင်းစာ ဖတ်နေတယ်။",
  },
  {
    id: 143,
    chinese: "你想找什么工作？",
    pinyin: "Nǐ xiǎng zhǎo shénme gōngzuò?",
    myanmar: "မင်း ဘယ်လိုအလုပ် ရှာနေတာလဲ?",
  },
  {
    id: 144,
    chinese: "我想当老师。",
    pinyin: "Wǒ xiǎng dāng lǎoshī.",
    myanmar: "ကျွန်တော် ဆရာ လုပ်ချင်တယ်။",
  },
  {
    id: 145,
    chinese: "外面天气很晴朗。",
    pinyin: "Wàimiàn tiānqì hěn qínglǎng.",
    myanmar: "အပြင်မှာ ရာသီဥတု အရမ်းသာယာတယ်။",
  },
  {
    id: 146,
    chinese: "今天没下雨。",
    pinyin: "Jīntiān méi xià yǔ.",
    myanmar: "ဒီနေ့ မိုးမရွာဘူး။",
  },
  {
    id: 147,
    chinese: "你喜欢哪个颜色？",
    pinyin: "Nǐ xǐhuan nǎge yánsè?",
    myanmar: "မင်း ဘယ်အရောင်ကို ကြိုက်လဲ?",
  },
  {
    id: 148,
    chinese: "我最喜欢红色。",
    pinyin: "Wǒ zuì xǐhuan hóngsè.",
    myanmar: "ကျွန်တော် အနီရောင်ကို အကြိုက်ဆုံးပဲ။",
  },
  {
    id: 149,
    chinese: "请把门关上。",
    pinyin: "Qǐng bǎ mén guānshang.",
    myanmar: "ကျေးဇူးပြုပြီး တံခါးပိတ်ပေးပါ။",
  },
  {
    id: 150,
    chinese: "门开着呢。",
    pinyin: "Mén kāizhe ne.",
    myanmar: "တံခါးက ပွင့်နေတယ်။",
  },
  {
    id: 151,
    chinese: "你看见我的钥匙了吗？",
    pinyin: "Nǐ kànjiàn wǒ de yàoshi le ma?",
    myanmar: "ကျွန်တော့်သော့ကို မင်းမြင်မိလား?",
  },
  {
    id: 152,
    chinese: "就在桌子上面。",
    pinyin: "Jiù zài zhuōzi shàngmiàn.",
    myanmar: "စားပွဲပေါ်မှာတင် ရှိပါတယ်။",
  },
  {
    id: 153,
    chinese: "这个西瓜多少钱一斤？",
    pinyin: "Zhèige xīguā duōshǎo qián yì jīn?",
    myanmar: "ဒီဖရဲသီး တစ်ပိဿာ (တစ်ကျင်း) ဘယ်လောက်လဲ?",
  },
  {
    id: 154,
    chinese: "你每天几点起床？",
    pinyin: "Nǐ měitiān jǐ diǎn qǐchuáng?",
    myanmar: "မင်း နေ့တိုင်း ဘယ်နှစ်နာရီ အိပ်ရာထလဲ?",
  },
  {
    id: 155,
    chinese: "我每天六点半起床。",
    pinyin: "Wǒ měitiān liù diǎn bàn qǐchuáng.",
    myanmar: "ကျွန်တော် နေ့တိုင်း ခြောက်နာရီခွဲ အိပ်ရာထတယ်။",
  },
  {
    id: 156,
    chinese: "外面有人在等你。",
    pinyin: "Wàimiàn yǒurén zài děng nǐ.",
    myanmar: "အပြင်မှာ တစ်ယောက်ယောက်က မင်းကို စောင့်နေတယ်။",
  },
  {
    id: 157,
    chinese: "是谁在等我？",
    pinyin: "Shì shéi zài děng wǒ?",
    myanmar: "ဘယ်သူက ကျွန်တော့်ကို စောင့်နေတာလဲ?",
  },
  {
    id: 158,
    chinese: "我不知道他是谁。",
    pinyin: "Wǒ bù zhīdào tā shì shéi.",
    myanmar: "သူဘယ်သူလဲဆိုတာ ကျွန်တော်မသိဘူး။",
  },
  {
    id: 159,
    chinese: "你为什么不高兴？",
    pinyin: "Nǐ wèishénme bù gāoxìng?",
    myanmar: "မင်း ဘာလို့ စိတ်မချမ်းသာဖြစ်နေတာလဲ?",
  },
  {
    id: 160,
    chinese: "因为我考试没考好。",
    pinyin: "Yīnwèi wǒ kǎoshì méi kǎo hǎo.",
    myanmar: "ဘာလို့လဲဆိုတော့ ကျွန်တော် စာမေးပွဲ သိပ်မကောင်းလို့ပါ။",
  },
  {
    id: 161,
    chinese: "别担心，下次加油。",
    pinyin: "Bié dānxīn, xiàcì jiāyóu.",
    myanmar: "မစိုးရိမ်ပါနဲ့၊ နောက်တစ်ခါ ကြိုးစားပါ။",
  },
  {
    id: 162,
    chinese: "今天比昨天冷。",
    pinyin: "Jīntiān bǐ zuótiān lěng.",
    myanmar: "ဒီနေ့က မနေ့ကထက် ပိုအေးတယ်။",
  },
  {
    id: 163,
    chinese: "你会游得很快吗？",
    pinyin: "Nǐ huì yóu de hěn kuài ma?",
    myanmar: "မင်း ရေအရမ်းမြန်မြန် ကူးတတ်လား?",
  },
  {
    id: 164,
    chinese: "我游得不快。",
    pinyin: "Wǒ yóu de bú kuài.",
    myanmar: "ကျွန်တော် ရေကူးတာ မမြန်ပါဘူး။",
  },
  {
    id: 165,
    chinese: "请问，洗手间在哪儿？",
    pinyin: "Qǐngwèn, xǐshǒujiān zài nǎr?",
    myanmar: "တစ်ဆိတ်လောက်ခင်ဗျာ၊ အိမ်သာ ဘယ်မှာလဲ?",
  },
  {
    id: 166,
    chinese: "洗手间在左边。",
    pinyin: "Xǐshǒujiān zài zuǒbiān.",
    myanmar: "အိမ်သာက ဘယ်ဘက်မှာ ရှိပါတယ်။",
  },
  {
    id: 167,
    chinese: "一直走，然后向右转。",
    pinyin: "Yìzhí zǒu, ránhòu xiàng yòu zhuǎn.",
    myanmar: "တည့်တည့်သွားပါ၊ ပြီးရင် ညာဘက်ကို ကွေ့ပါ။",
  },
  {
    id: 168,
    chinese: "你生病了吗？",
    pinyin: "Nǐ shēngbìng le ma?",
    myanmar: "မင်း နေမကောင်းဘူးလား?",
  },
  {
    id: 169,
    chinese: "我头疼，想休息一下。",
    pinyin: "Wǒ tóuténg, xiǎng xiūxi yíxià.",
    myanmar: "ကျွန်တော် ခေါင်းကိုက်လို့ ခဏနားချင်တယ်။",
  },
  {
    id: 170,
    chinese: "那里的风景很漂亮。",
    pinyin: "Nàlǐ de fēngjǐng hěn piàoliang.",
    myanmar: "ဟိုနေရာက ရှုခင်းက အရမ်းလှတယ်။",
  },
  {
    id: 171,
    chinese: "你想去旅游吗？",
    pinyin: "Nǐ xiǎng qù lǚyóu ma?",
    myanmar: "မင်း ခရီးသွားချင်လား?",
  },
  {
    id: 172,
    chinese: "我想去中国旅游。",
    pinyin: "Wǒ xiǎng qù Zhōngguó lǚyóu.",
    myanmar: "ကျွန်တော် တရုတ်နိုင်ငံကို ခရီးသွားချင်တယ်။",
  },
  {
    id: 173,
    chinese: "你有多少钱？",
    pinyin: "Nǐ yǒu duōshǎo qián?",
    myanmar: "မင်းမှာ ပိုက်ဆံ ဘယ်လောက်ရှိလဲ?",
  },
  {
    id: 174,
    chinese: "我有两百块钱。",
    pinyin: "Wǒ yǒu liǎngbǎi kuài qián.",
    myanmar: "ကျွန်တော့်မှာ ယွမ်နှစ်ရာ ရှိတယ်။",
  },
  {
    id: 175,
    chinese: "这里的菜很好吃。",
    pinyin: "Zhèlǐ de cài hěn hǎochī.",
    myanmar: "ဒီက ဟင်းတွေက အရမ်းစားကောင်းတယ်။",
  },
  {
    id: 176,
    chinese: "多吃点儿，别客气。",
    pinyin: "Duō chī diǎnr, bié kèqi.",
    myanmar: "များများစားပါ၊ အားမနာပါနဲ့။",
  },
  {
    id: 177,
    chinese: "你喜欢什么运动？",
    pinyin: "Nǐ xǐhuan shénme yùndòng?",
    myanmar: "မင်း ဘယ်လိုအားကစားမျိုး ကြိုက်လဲ?",
  },
  {
    id: 178,
    chinese: "我最喜欢跑步。",
    pinyin: "Wǒ zuì xǐhuan pǎobù.",
    myanmar: "ကျွန်တော် အပြေးလေ့ကျင့်တာ အကြိုက်ဆုံးပဲ။",
  },
  {
    id: 179,
    chinese: "你会下棋吗？",
    pinyin: "Nǐ huì xiàqí ma?",
    myanmar: "မင်း နယ်တုကစားတတ်လား?",
  },
  {
    id: 180,
    chinese: "我不会下棋，但我会跳舞。",
    pinyin: "Wǒ bú huì xiàqí, dàn wǒ huì tiàowǔ.",
    myanmar: "ကျွန်တော် နယ်တုမကစားတတ်ဘူး၊ ဒါပေမဲ့ ကတတ်ပါတယ်။",
  },
  {
    id: 181,
    chinese: "你想要哪个杯子？",
    pinyin: "Nǐ xiǎng yào nǎge bēizi?",
    myanmar: "မင်း ဘယ်ခွက်ကို လိုချင်လဲ?",
  },
  {
    id: 182,
    chinese: "我要那个绿色的。",
    pinyin: "Wǒ yào nàge lǜsè de.",
    myanmar: "ကျွန်တော် ဟိုအစိမ်းရောင်လေးကို လိုချင်တယ်။",
  },
  {
    id: 183,
    chinese: "你的汉语说得真流利。",
    pinyin: "Nǐ de Hànyǔ shuō de zhēn liúlì.",
    myanmar: "မင်းရဲ့ တရုတ်စကားပြောက တကယ်ကို ရေပန်းစား (ကျွမ်းကျင်) တာပဲ။",
  },
  {
    id: 184,
    chinese: "哪里哪里，还要继续学习。",
    pinyin: "Nǎlǐ nǎlǐ, hái yào jìxù xuéxí.",
    myanmar: "မဟုတ်ပါဘူးဗျာ၊ ဆက်ပြီးတော့ သင်ယူဖို့ လိုပါသေးတယ်။",
  },
  {
    id: 185,
    chinese: "你在看电视吗？",
    pinyin: "Nǐ zài kàn diànshì ma?",
    myanmar: "မင်း တီဗွီကြည့်နေတာလား?",
  },
  {
    id: 186,
    chinese: "我没看电视，我在学习。",
    pinyin: "Wǒ méi kàn diànshì, wǒ zài xuéxí.",
    myanmar: "ကျွန်တော် တီဗွီမကြည့်ပါဘူး၊ စာလုပ်နေတာပါ။",
  },
  {
    id: 187,
    chinese: "你的书在椅子下面。",
    pinyin: "Nǐ de shū zài yǐzi xiàmiàn.",
    myanmar: "မင်းစာအုပ်က ကုလားထိုင်အောက်မှာ။",
  },
  {
    id: 188,
    chinese: "谢谢你告诉我。",
    pinyin: "Xièxie nǐ gàosù wǒ.",
    myanmar: "ပြောပြပေးတဲ့အတွက် ကျေးဇူးတင်ပါတယ်။",
  },
  {
    id: 189,
    chinese: "没关系，不客气。",
    pinyin: "Méiguānxi, búkèqi.",
    myanmar: "ဘာမှမဖြစ်ပါဘူး၊ ရပါတယ်။",
  },
  {
    id: 190,
    chinese: "外面下大雨了，你别走。",
    pinyin: "Wàimiàn xià dàyǔ le, nǐ bié zǒu.",
    myanmar: "အပြင်မှာ မိုးအရမ်းရွာနေတယ်၊ မသွားပါနဲ့ဦး။",
  },
  {
    id: 191,
    chinese: "那我再等一会儿。",
    pinyin: "Nà wǒ zài děng yìhuǐr.",
    myanmar: "ဒါဆိုရင် ကျွန်တော် ခဏလောက် ထပ်စောင့်လိုက်မယ်။",
  },
  {
    id: 192,
    chinese: "这道题你会做吗？",
    pinyin: "Zhè dào tí nǐ huì zuò ma?",
    myanmar: "ဒီပုစ္ဆာကို မင်းတွက်တတ်လား?",
  },
  {
    id: 193,
    chinese: "这道题很难，我不会。",
    pinyin: "Zhè dào tí hěn nán, wǒ bú huì.",
    myanmar: "ဒီပုစ္ဆာက အရမ်းခက်တယ်၊ ကျွန်တော် မလုပ်တတ်ဘူး။",
  },
  {
    id: 194,
    chinese: "没关系，我教你。",
    pinyin: "Méiguānxi, wǒ jiāo nǐ.",
    myanmar: "ရပါတယ်၊ ကျွန်တော် သင်ပေးမယ်။",
  },
  {
    id: 195,
    chinese: "你几点睡觉？",
    pinyin: "Nǐ jǐ diǎn shuìjiào?",
    myanmar: "မင်း ဘယ်နှစ်နာရီ အိပ်လဲ?",
  },
  {
    id: 196,
    chinese: "我晚上十一点睡觉。",
    pinyin: "Wǒ wǎnshang shíyī diǎn shuìjiào.",
    myanmar: "ကျွန်တော် ည ၁၁ နာရီမှာ အိပ်တယ်။",
  },
  {
    id: 197,
    chinese: "你会写汉字吗？",
    pinyin: "Nǐ huì xiě Hànzì ma?",
    myanmar: "မင်း တရုတ်စာ ရေးတတ်လား?",
  },
  {
    id: 198,
    chinese: "我会写一点点。",
    pinyin: "Wǒ huì xiě yìdiǎndiǎn.",
    myanmar: "ကျွန်တော် နည်းနည်း ရေးတတ်ပါတယ်။",
  },
  {
    id: 199,
    chinese: "这里的空气很好。",
    pinyin: "Zhèlǐ de kōngqì hěn hǎo.",
    myanmar: "ဒီက လေထုက အရမ်းကောင်းတယ်။",
  },
  {
    id: 200,
    chinese: "我们可以去公园走走。",
    pinyin: "Wǒmen kěyǐ qù gōngyuán zǒuzǒu.",
    myanmar: "ငါတို့ ပန်းခြံထဲမှာ လမ်းလျှောက်သွားလို့ရတယ်။",
  },
];


export default datas