const datas = [
  {
    id: 1,
    chinese: "我",
    pinyin: "wǒ",
    myanmar: "ကျွန်တော်/ကျွန်မ",
    correct: "ကျွန်တော်/ကျွန်မ",
    wrong1: "မင်း",
    wrong2: "သူ",
    category: "Pronouns",
  },
  {
    id: 2,
    chinese: "你",
    pinyin: "nǐ",
    myanmar: "မင်း/သင်",
    correct: "မင်း/သင်",
    wrong1: "ကျွန်တော်",
    wrong2: "သူမ",
    category: "Pronouns",
  },
  {
    id: 3,
    chinese: "他",
    pinyin: "tā",
    myanmar: "သူ (ကျား)",
    correct: "သူ (ကျား)",
    wrong1: "သူမ",
    wrong2: "ကျွန်တော်တို့",
    category: "Pronouns",
  },
  {
    id: 4,
    chinese: "她",
    pinyin: "tā",
    myanmar: "သူမ (မ)",
    correct: "သူမ (မ)",
    wrong1: "သူ",
    wrong2: "မင်း",
    category: "Pronouns",
  },
  {
    id: 5,
    chinese: "我们",
    pinyin: "wǒmen",
    myanmar: "ကျွန်တော်တို့",
    correct: "ကျွန်တော်တို့",
    wrong1: "သင်တို့",
    wrong2: "အားလုံး",
    category: "Pronouns",
  },
  {
    id: 6,
    chinese: "这",
    pinyin: "zhè",
    myanmar: "ဒါ/ဒီ",
    correct: "ဒါ/ဒီ",
    wrong1: "ဟို",
    wrong2: "ဘယ်",
    category: "Pronouns",
  },
  {
    id: 7,
    chinese: "那",
    pinyin: "nà",
    myanmar: "ဟို/ထို",
    correct: "ဟို/ထို",
    wrong1: "ဒီ",
    wrong2: "ဘယ်ဟာ",
    category: "Pronouns",
  },
  {
    id: 8,
    chinese: "哪",
    pinyin: "nǎ",
    myanmar: "ဘယ်ဟာ",
    correct: "ဘယ်ဟာ",
    wrong1: "ဒါ",
    wrong2: "ဟို",
    category: "Pronouns",
  },
  {
    id: 9,
    chinese: "哪儿",
    pinyin: "nǎr",
    myanmar: "ဘယ်နေရာ",
    correct: "ဘယ်နေရာ",
    wrong1: "ဘယ်သူ",
    wrong2: "ဘာလဲ",
    category: "Pronouns",
  },
  {
    id: 10,
    chinese: "谁",
    pinyin: "shéi",
    myanmar: "ဘယ်သူ",
    correct: "ဘယ်သူ",
    wrong1: "ဘယ်နေရာ",
    wrong2: "ဘာလဲ",
    category: "Pronouns",
  },
  {
    id: 11,
    chinese: "什么",
    pinyin: "shénme",
    myanmar: "ဘာလဲ",
    correct: "ဘာလဲ",
    wrong1: "ဘယ်သူ",
    wrong2: "ဘယ်လို",
    category: "Pronouns",
  },
  {
    id: 12,
    chinese: "多少",
    pinyin: "duōshǎo",
    myanmar: "ဘယ်လောက်လဲ",
    correct: "ဘယ်လောက်လဲ",
    wrong1: "ဘယ်နှစ်ခု",
    wrong2: "ဘယ်လိုလဲ",
    category: "Numbers",
  },
  {
    id: 13,
    chinese: "几",
    pinyin: "jǐ",
    myanmar: "ဘယ်နှစ်ခု",
    correct: "ဘယ်နှစ်ခု",
    wrong1: "ဘယ်လောက်လဲ",
    wrong2: "အရမ်း",
    category: "Numbers",
  },
  {
    id: 14,
    chinese: "怎么",
    pinyin: "zěnme",
    myanmar: "ဘယ်လိုလဲ",
    correct: "ဘယ်လိုလဲ",
    wrong1: "ဘယ်လောက်လဲ",
    wrong2: "ဘယ်နှစ်ခု",
    category: "Adverbs",
  },
  {
    id: 15,
    chinese: "怎么样",
    pinyin: "zěnmeyàng",
    myanmar: "ဘယ်လိုနေလဲ",
    correct: "ဘယ်လိုနေလဲ",
    wrong1: "ဘယ်လိုလဲ",
    wrong2: "မ",
    category: "Adverbs",
  },
  {
    id: 16,
    chinese: "一",
    pinyin: "yī",
    myanmar: "တစ်",
    correct: "တစ်",
    wrong1: "နှစ်",
    wrong2: "သုံး",
    category: "Numbers",
  },
  {
    id: 17,
    chinese: "二",
    pinyin: "èr",
    myanmar: "နှစ်",
    correct: "နှစ်",
    wrong1: "တစ်",
    wrong2: "လေး",
    category: "Numbers",
  },
  {
    id: 18,
    chinese: "三",
    pinyin: "sān",
    myanmar: "သုံး",
    correct: "သုံး",
    wrong1: "နှစ်",
    wrong2: "ငါး",
    category: "Numbers",
  },
  {
    id: 19,
    chinese: "四",
    pinyin: "sì",
    myanmar: "လေး",
    correct: "လေး",
    wrong1: "သုံး",
    wrong2: "ခြောက်",
    category: "Numbers",
  },
  {
    id: 20,
    chinese: "五",
    pinyin: "wǔ",
    myanmar: "ငါး",
    correct: "ငါး",
    wrong1: "လေး",
    wrong2: "ခုနစ်",
    category: "Numbers",
  },
  {
    id: 21,
    chinese: "六",
    pinyin: "liù",
    myanmar: "ခြောက်",
    correct: "ခြောက်",
    wrong1: "ငါး",
    wrong2: "ရှစ်",
    category: "Numbers",
  },
  {
    id: 22,
    chinese: "七",
    pinyin: "qī",
    myanmar: "ခုနစ်",
    correct: "ခုနစ်",
    wrong1: "ခြောက်",
    wrong2: "ကိုး",
    category: "Numbers",
  },
  {
    id: 23,
    chinese: "八",
    pinyin: "bā",
    myanmar: "ရှစ်",
    correct: "ရှစ်",
    wrong1: "ခုနစ်",
    wrong2: "တစ်ဆယ်",
    category: "Numbers",
  },
  {
    id: 24,
    chinese: "九",
    pinyin: "jiǔ",
    myanmar: "ကိုး",
    correct: "ကိုး",
    wrong1: "ရှစ်",
    wrong2: "သုည",
    category: "Numbers",
  },
  {
    id: 25,
    chinese: "十",
    pinyin: "shí",
    myanmar: "တစ်ဆယ်",
    correct: "တစ်ဆယ်",
    wrong1: "ကိုး",
    wrong2: "သုည",
    category: "Numbers",
  },
  {
    id: 26,
    chinese: "零",
    pinyin: "líng",
    myanmar: "သုည",
    correct: "သုည",
    wrong1: "တစ်",
    wrong2: "တစ်ဆယ်",
    category: "Numbers",
  },
  {
    id: 27,
    chinese: "个",
    pinyin: "gè",
    myanmar: "ခု/ယောက်",
    correct: "ခု/ယောက်",
    wrong1: "အုပ်",
    wrong2: "အချို့",
    category: "Measure Words",
  },
  {
    id: 28,
    chinese: "岁",
    pinyin: "suì",
    myanmar: "အသက်",
    correct: "အသက်",
    wrong1: "ခု",
    wrong2: "အုပ်",
    category: "Measure Words",
  },
  {
    id: 29,
    chinese: "本",
    pinyin: "běn",
    myanmar: "အုပ် (စာအုပ်)",
    correct: "အုပ် (စာအုပ်)",
    wrong1: "ခု",
    wrong2: "ယွမ်",
    category: "Measure Words",
  },
  {
    id: 30,
    chinese: "些",
    pinyin: "xiē",
    myanmar: "အချို့",
    correct: "အချို့",
    wrong1: "အုပ်",
    wrong2: "အသက်",
    category: "Measure Words",
  },
  {
    id: 31,
    chinese: "块",
    pinyin: "kuài",
    myanmar: "ယွမ် (ငွေ)",
    correct: "ယွမ် (ငွေ)",
    wrong1: "ခု",
    wrong2: "အချို့",
    category: "Measure Words",
  },
  {
    id: 32,
    chinese: "不",
    pinyin: "bù",
    myanmar: "မ/မဟုတ်",
    correct: "မ/မဟုတ်",
    wrong1: "အရမ်း",
    wrong2: "လွန်း",
    category: "Adverbs",
  },
  {
    id: 33,
    chinese: "没",
    pinyin: "méi",
    myanmar: "မရှိ/မ",
    correct: "မရှိ/မ",
    wrong1: "မဟုတ်",
    wrong2: "အရမ်း",
    category: "Adverbs",
  },
  {
    id: 34,
    chinese: "很",
    pinyin: "hěn",
    myanmar: "အရမ်း",
    correct: "အရမ်း",
    wrong1: "မ",
    wrong2: "လွန်း",
    category: "Adverbs",
  },
  {
    id: 35,
    chinese: "太",
    pinyin: "tài",
    myanmar: "လွန်းသည်",
    correct: "လွန်းသည်",
    wrong1: "အရမ်း",
    wrong2: "အားလုံး",
    category: "Adverbs",
  },
  {
    id: 36,
    chinese: "都",
    pinyin: "dōu",
    myanmar: "အားလုံး",
    correct: "အားလုံး",
    wrong1: "လွန်း",
    wrong2: "မ",
    category: "Adverbs",
  },
  {
    id: 37,
    chinese: "和",
    pinyin: "hé",
    myanmar: "နှင့်",
    correct: "နှင့်",
    wrong1: "၏",
    wrong2: "ပြီ",
    category: "Conjunctions",
  },
  {
    id: 38,
    chinese: "在",
    pinyin: "zài",
    myanmar: "မှာ/ရှိသည်",
    correct: "မှာ/ရှိသည်",
    wrong1: "ဖြစ်သည်",
    wrong2: "ကြည့်",
    category: "Verbs",
  },
  {
    id: 39,
    chinese: "的",
    pinyin: "de",
    myanmar: "၏/ရဲ့",
    correct: "၏/ရဲ့",
    wrong1: "ပြီ",
    wrong2: "လား",
    category: "Particles",
  },
  {
    id: 40,
    chinese: "了",
    pinyin: "le",
    myanmar: "ပြီ",
    correct: "ပြီ",
    wrong1: "၏",
    wrong2: "ကော",
    category: "Particles",
  },
  {
    id: 41,
    chinese: "吗",
    pinyin: "ma",
    myanmar: "လား",
    correct: "လား",
    wrong1: "ပြီ",
    wrong2: "ကော",
    category: "Particles",
  },
  {
    id: 42,
    chinese: "呢",
    pinyin: "ne",
    myanmar: "ကော",
    correct: "ကော",
    wrong1: "လား",
    wrong2: "၏",
    category: "Particles",
  },
  {
    id: 43,
    chinese: "喂",
    pinyin: "wèi",
    myanmar: "ဟယ်လို",
    correct: "ဟယ်လို",
    wrong1: "ကျေးဇူး",
    wrong2: "နှုတ်ဆက်",
    category: "Interjections",
  },
  {
    id: 44,
    chinese: "家",
    pinyin: "jiā",
    myanmar: "အိမ်",
    correct: "အိမ်",
    wrong1: "ကျောင်း",
    wrong2: "ဆိုင်",
    category: "Nouns",
  },
  {
    id: 45,
    chinese: "学校",
    pinyin: "xuéxiào",
    myanmar: "ကျောင်း",
    correct: "ကျောင်း",
    wrong1: "အိမ်",
    wrong2: "ဆေးရုံ",
    category: "Nouns",
  },
  {
    id: 46,
    chinese: "饭馆",
    pinyin: "fànguǎn",
    myanmar: "စားသောက်ဆိုင်",
    correct: "စားသောက်ဆိုင်",
    wrong1: "ကျောင်း",
    wrong2: "ဘူတာရုံ",
    category: "Nouns",
  },
  {
    id: 47,
    chinese: "商店",
    pinyin: "shāngdiàn",
    myanmar: "ဆိုင်",
    correct: "ဆိုင်",
    wrong1: "စားသောက်ဆိုင်",
    wrong2: "ဆေးရုံ",
    category: "Nouns",
  },
  {
    id: 48,
    chinese: "医院",
    pinyin: "yīyuàn",
    myanmar: "ဆေးရုံ",
    correct: "ဆေးရုံ",
    wrong1: "ဘူတာရုံ",
    wrong2: "အိမ်",
    category: "Nouns",
  },
  {
    id: 49,
    chinese: "火车站",
    pinyin: "huǒchēzhàn",
    myanmar: "ဘူတာရုံ",
    correct: "ဘူတာရုံ",
    wrong1: "ဆေးရုံ",
    wrong2: "ကျောင်း",
    category: "Nouns",
  },
  {
    id: 50,
    chinese: "中国",
    pinyin: "zhōngguó",
    myanmar: "တရုတ်ပြည်",
    correct: "တရုတ်ပြည်",
    wrong1: "ပေကျင်း",
    wrong2: "အိမ်",
    category: "Nouns",
  },
  {
    id: 51,
    chinese: "北京",
    pinyin: "běijīng",
    myanmar: "ပေကျင်း",
    correct: "ပေကျင်း",
    wrong1: "တရုတ်ပြည်",
    wrong2: "ကျောင်း",
    category: "Nouns",
  },
  {
    id: 52,
    chinese: "上",
    pinyin: "shàng",
    myanmar: "အပေါ်",
    correct: "အပေါ်",
    wrong1: "အောက်",
    wrong2: "ရှေ့",
    category: "Nouns",
  },
  {
    id: 53,
    chinese: "下",
    pinyin: "xià",
    myanmar: "အောက်",
    correct: "အောက်",
    wrong1: "အပေါ်",
    wrong2: "နောက်",
    category: "Nouns",
  },
  {
    id: 54,
    chinese: "前面",
    pinyin: "qiánmiàn",
    myanmar: "ရှေ့",
    correct: "ရှေ့",
    wrong1: "နောက်",
    wrong2: "ထဲ",
    category: "Nouns",
  },
  {
    id: 55,
    chinese: "后面",
    pinyin: "hòumiàn",
    myanmar: "နောက်",
    correct: "နောက်",
    wrong1: "ရှေ့",
    wrong2: "အပေါ်",
    category: "Nouns",
  },
  {
    id: 56,
    chinese: "里",
    pinyin: "lǐ",
    myanmar: "ထဲ",
    correct: "ထဲ",
    wrong1: "ရှေ့",
    wrong2: "အောက်",
    category: "Nouns",
  },
  {
    id: 57,
    chinese: "今天",
    pinyin: "jīntiān",
    myanmar: "ဒီနေ့",
    correct: "ဒီနေ့",
    wrong1: "မနက်ဖြန်",
    wrong2: "မနေ့က",
    category: "Time",
  },
  {
    id: 58,
    chinese: "明天",
    pinyin: "míngtiān",
    myanmar: "မနက်ဖြန်",
    correct: "မနက်ဖြန်",
    wrong1: "ဒီနေ့",
    wrong2: "မနေ့က",
    category: "Time",
  },
  {
    id: 59,
    chinese: "昨天",
    pinyin: "zuótiān",
    myanmar: "မနေ့က",
    correct: "မနေ့က",
    wrong1: "ဒီနေ့",
    wrong2: "မနက်ဖြန်",
    category: "Time",
  },
  {
    id: 60,
    chinese: "上午",
    pinyin: "shàngwǔ",
    myanmar: "မနက်ခင်း",
    correct: "မနက်ခင်း",
    wrong1: "မွန်းတည့်",
    wrong2: "မွန်းလွဲ",
    category: "Time",
  },
  {
    id: 61,
    chinese: "中午",
    pinyin: "zhōngwǔ",
    myanmar: "မွန်းတည့်",
    correct: "မွန်းတည့်",
    wrong1: "မနက်ခင်း",
    wrong2: "မွန်းလွဲ",
    category: "Time",
  },
  {
    id: 62,
    chinese: "下午",
    pinyin: "xiàwǔ",
    myanmar: "မွန်းလွဲ",
    correct: "မွန်းလွဲ",
    wrong1: "မနက်ခင်း",
    wrong2: "မွန်းတည့်",
    category: "Time",
  },
  {
    id: 63,
    chinese: "年",
    pinyin: "nián",
    myanmar: "နှစ်",
    correct: "နှစ်",
    wrong1: "လ",
    wrong2: "ရက်",
    category: "Time",
  },
  {
    id: 64,
    chinese: "月",
    pinyin: "yuè",
    myanmar: "လ",
    correct: "လ",
    wrong1: "နှစ်",
    wrong2: "ရက်",
    category: "Time",
  },
  {
    id: 65,
    chinese: "日",
    pinyin: "rì",
    myanmar: "ရက်",
    correct: "ရက်",
    wrong1: "လ",
    wrong2: "နှစ်",
    category: "Time",
  },
  {
    id: 66,
    chinese: "星期",
    pinyin: "xīngqī",
    myanmar: "အပတ်",
    correct: "အပတ်",
    wrong1: "နှစ်",
    wrong2: "ရက်",
    category: "Time",
  },
  {
    id: 67,
    chinese: "点",
    pinyin: "diǎn",
    myanmar: "နာရီ",
    correct: "နာရီ",
    wrong1: "မိနစ်",
    wrong2: "အချိန်",
    category: "Time",
  },
  {
    id: 68,
    chinese: "分钟",
    pinyin: "fēnzhōng",
    myanmar: "မိနစ်",
    correct: "မိနစ်",
    wrong1: "နာရီ",
    wrong2: "ယခု",
    category: "Time",
  },
  {
    id: 69,
    chinese: "现在",
    pinyin: "xiànzài",
    myanmar: "ယခု",
    correct: "ယခု",
    wrong1: "အချိန်",
    wrong2: "မနက်ဖြန်",
    category: "Time",
  },
  {
    id: 70,
    chinese: "时候",
    pinyin: "shíhou",
    myanmar: "အချိန်",
    correct: "အချိန်",
    wrong1: "ယခု",
    wrong2: "နာရီ",
    category: "Time",
  },
  {
    id: 71,
    chinese: "爸爸",
    pinyin: "bàba",
    myanmar: "အဖေ",
    correct: "အဖေ",
    wrong1: "အမေ",
    wrong2: "သား",
    category: "Family",
  },
  {
    id: 72,
    chinese: "妈妈",
    pinyin: "māma",
    myanmar: "အမေ",
    correct: "အမေ",
    wrong1: "အဖေ",
    wrong2: "သမီး",
    category: "Family",
  },
  {
    id: 73,
    chinese: "儿子",
    pinyin: "érzi",
    myanmar: "သား",
    correct: "သား",
    wrong1: "သမီး",
    wrong2: "အဖေ",
    category: "Family",
  },
  {
    id: 74,
    chinese: "女儿",
    pinyin: "nǚ'ér",
    myanmar: "သမီး",
    correct: "သမီး",
    wrong1: "သား",
    wrong2: "အမေ",
    category: "Family",
  },
  {
    id: 75,
    chinese: "老师",
    pinyin: "lǎoshī",
    myanmar: "ဆရာ",
    correct: "ဆရာ",
    wrong1: "ကျောင်းသား",
    wrong2: "အတန်းဖော်",
    category: "People",
  },
  {
    id: 76,
    chinese: "学生",
    pinyin: "xuéshēn",
    myanmar: "ကျောင်းသား",
    correct: "ကျောင်းသား",
    wrong1: "ဆရာ",
    wrong2: "သူငယ်ချင်း",
    category: "People",
  },
  {
    id: 77,
    chinese: "同学",
    pinyin: "tóngxué",
    myanmar: "အတန်းဖော်",
    correct: "အတန်းဖော်",
    wrong1: "ကျောင်းသား",
    wrong2: "ဆရာဝန်",
    category: "People",
  },
  {
    id: 78,
    chinese: "朋友",
    pinyin: "péngyou",
    myanmar: "သူငယ်ချင်း",
    correct: "သူငယ်ချင်း",
    wrong1: "အတန်းဖော်",
    wrong2: "ဆရာ",
    category: "People",
  },
  {
    id: 79,
    chinese: "医生",
    pinyin: "yīshēng",
    myanmar: "ဆရာဝန်",
    correct: "ဆရာဝန်",
    wrong1: "ဦး",
    wrong2: "မမ",
    category: "People",
  },
  {
    id: 80,
    chinese: "先生",
    pinyin: "xiānsheng",
    myanmar: "ဦး",
    correct: "ဦး",
    wrong1: "မမ",
    wrong2: "ဆရာဝန်",
    category: "People",
  },
  {
    id: 81,
    chinese: "小姐",
    pinyin: "xiǎojiě",
    myanmar: "မမ",
    correct: "မမ",
    wrong1: "ဦး",
    wrong2: "ကျောင်းသား",
    category: "People",
  },
  {
    id: 82,
    chinese: "衣服",
    pinyin: "yīfu",
    myanmar: "အဝတ်အစား",
    correct: "အဝတ်အစား",
    wrong1: "ရေ",
    wrong2: "ဟင်း",
    category: "Nouns",
  },
  {
    id: 83,
    chinese: "水",
    pinyin: "shuǐ",
    myanmar: "ရေ",
    correct: "ရေ",
    wrong1: "ထမင်း",
    wrong2: "သစ်သီး",
    category: "Food",
  },
  {
    id: 84,
    chinese: "菜",
    pinyin: "cài",
    myanmar: "ဟင်း/ဟင်းသီးဟင်းရွက်",
    correct: "ဟင်း/ဟင်းသီးဟင်းရွက်",
    wrong1: "ရေ",
    wrong2: "ထမင်း",
    category: "Food",
  },
  {
    id: 85,
    chinese: "米饭",
    pinyin: "mǐfàn",
    myanmar: "ထမင်း",
    correct: "ထမင်း",
    wrong1: "ဟင်း",
    wrong2: "ပန်းသီး",
    category: "Food",
  },
  {
    id: 86,
    chinese: "水果",
    pinyin: "shuǐguǒ",
    myanmar: "သစ်သီး",
    correct: "သစ်သီး",
    wrong1: "လက်ဖက်ရည်",
    wrong2: "ရေ",
    category: "Food",
  },
  {
    id: 87,
    chinese: "苹果",
    pinyin: "píngguǒ",
    myanmar: "ပန်းသီး",
    correct: "ပန်းသီး",
    wrong1: "သစ်သီး",
    wrong2: "လက်ဖက်ရည်",
    category: "Food",
  },
  {
    id: 88,
    chinese: "茶",
    pinyin: "chá",
    myanmar: "လက်ဖက်ရည်",
    correct: "လက်ဖက်ရည်",
    wrong1: "ပန်းသီး",
    wrong2: "ရေ",
    category: "Food",
  },
  {
    id: 89,
    chinese: "杯子",
    pinyin: "bēizi",
    myanmar: "ခွက်",
    correct: "ခွက်",
    wrong1: "ပိုက်ဆံ",
    wrong2: "လေယာဉ်",
    category: "Nouns",
  },
  {
    id: 90,
    chinese: "钱",
    pinyin: "qián",
    myanmar: "ပိုက်ဆံ",
    correct: "ပိုက်ဆံ",
    wrong1: "ခွက်",
    wrong2: "တက္ကစီ",
    category: "Nouns",
  },
  {
    id: 91,
    chinese: "飞机",
    pinyin: "fēijī",
    myanmar: "လေယာဉ်",
    correct: "လေယာဉ်",
    wrong1: "တက္ကစီ",
    wrong2: "တီဗွီ",
    category: "Nouns",
  },
  {
    id: 92,
    chinese: "出租车",
    pinyin: "chūzūchē",
    myanmar: "တက္ကစီ",
    correct: "တက္ကစီ",
    wrong1: "လေယာဉ်",
    wrong2: "ကွန်ပျူတာ",
    category: "Nouns",
  },
  {
    id: 93,
    chinese: "电视",
    pinyin: "diànshì",
    myanmar: "တီဗွီ",
    correct: "တီဗွီ",
    wrong1: "ကွန်ပျူတာ",
    wrong2: "ရုပ်ရှင်",
    category: "Nouns",
  },
  {
    id: 94,
    chinese: "电脑",
    pinyin: "diànnǎo",
    myanmar: "ကွန်ပျူတာ",
    correct: "ကွန်ပျူတာ",
    wrong1: "တီဗွီ",
    wrong2: "လေယာဉ်",
    category: "Nouns",
  },
  {
    id: 95,
    chinese: "电影",
    pinyin: "diànyǐng",
    myanmar: "ရုပ်ရှင်",
    correct: "ရုပ်ရှင်",
    wrong1: "တီဗွီ",
    wrong2: "ကွန်ပျူတာ",
    category: "Nouns",
  },
  {
    id: 96,
    chinese: "天气",
    pinyin: "tiānqì",
    myanmar: "ရာသီဥတု",
    correct: "ရာသီဥတု",
    wrong1: "ကြောင်",
    wrong2: "ခွေး",
    category: "Nouns",
  },
  {
    id: 97,
    chinese: "猫",
    pinyin: "māo",
    myanmar: "ကြောင်",
    correct: "ကြောင်",
    wrong1: "ခွေး",
    wrong2: "ပစ္စည်း",
    category: "Animals",
  },
  {
    id: 98,
    chinese: "狗",
    pinyin: "gǒu",
    myanmar: "ခွေး",
    correct: "ခွေး",
    wrong1: "ကြောင်",
    wrong2: "လူ",
    category: "Animals",
  },
  {
    id: 99,
    chinese: "东西",
    pinyin: "dōngxi",
    myanmar: "ပစ္စည်း",
    correct: "ပစ္စည်း",
    wrong1: "လူ",
    wrong2: "နာမည်",
    category: "Nouns",
  },
  {
    id: 100,
    chinese: "人",
    pinyin: "rén",
    myanmar: "လူ",
    correct: "လူ",
    wrong1: "ပစ္စည်း",
    wrong2: "စာအုပ်",
    category: "Nouns",
  },
  {
    id: 101,
    chinese: "名字",
    pinyin: "míngzi",
    myanmar: "နာမည်",
    correct: "နာမည်",
    wrong1: "စာအုပ်",
    wrong2: "တရုတ်စကား",
    category: "Nouns",
  },
  {
    id: 102,
    chinese: "书",
    pinyin: "shū",
    myanmar: "စာအုပ်",
    correct: "စာအုပ်",
    wrong1: "နာမည်",
    wrong2: "စာလုံး",
    category: "Nouns",
  },
  {
    id: 103,
    chinese: "汉语",
    pinyin: "hànyǔ",
    myanmar: "တရုတ်စကား",
    correct: "တရုတ်စကား",
    wrong1: "စာလုံး",
    wrong2: "စာအုပ်",
    category: "Nouns",
  },
  {
    id: 104,
    chinese: "字",
    pinyin: "zì",
    myanmar: "စာလုံး",
    correct: "စာလုံး",
    wrong1: "တရုတ်စကား",
    wrong2: "စားပွဲ",
    category: "Nouns",
  },
  {
    id: 105,
    chinese: "桌子",
    pinyin: "zhuōzi",
    myanmar: "စားပွဲ",
    correct: "စားပွဲ",
    wrong1: "ကုလားထိုင်",
    wrong2: "စာအုပ်",
    category: "Nouns",
  },
  {
    id: 106,
    chinese: "椅子",
    pinyin: "yǐzi",
    myanmar: "ကုလားထိုင်",
    correct: "ကုလားထိုင်",
    wrong1: "စားပွဲ",
    wrong2: "ခွက်",
    category: "Nouns",
  },
  {
    id: 107,
    chinese: "谢谢",
    pinyin: "xièxie",
    myanmar: "ကျေးဇူးတင်ပါတယ်",
    correct: "ကျေးဇူးတင်ပါတယ်",
    wrong1: "ရပါတယ်",
    wrong2: "နှုတ်ဆက်ပါတယ်",
    category: "Verbs",
  },
  {
    id: 108,
    chinese: "不客气",
    pinyin: "bú kèqi",
    myanmar: "ရပါတယ်",
    correct: "ရပါတယ်",
    wrong1: "ကျေးဇူးတင်ပါတယ်",
    wrong2: "တောင်းပန်ပါတယ်",
    category: "Verbs",
  },
  {
    id: 109,
    chinese: "再见",
    pinyin: "zàijiàn",
    myanmar: "နှုတ်ဆက်ပါတယ်",
    correct: "နှုတ်ဆက်ပါတယ်",
    wrong1: "ရပါတယ်",
    wrong2: "ကျေးဇူးတင်ပါတယ်",
    category: "Verbs",
  },
  {
    id: 110,
    chinese: "请",
    pinyin: "qǐng",
    myanmar: "ကျေးဇူးပြု၍",
    correct: "ကျေးဇူးပြု၍",
    wrong1: "တောင်းပန်ပါတယ်",
    wrong2: "ကိစ္စမရှိပါဘူး",
    category: "Verbs",
  },
  {
    id: 111,
    chinese: "对不起",
    pinyin: "duìbuqǐ",
    myanmar: "တောင်းပန်ပါတယ်",
    correct: "တောင်းပန်ပါတယ်",
    wrong1: "ကိစ္စမရှိပါဘူး",
    wrong2: "ကျေးဇူးတင်ပါတယ်",
    category: "Verbs",
  },
  {
    id: 112,
    chinese: "没关系",
    pinyin: "méi guānxi",
    myanmar: "ကိစ္စမရှိပါဘူး",
    correct: "ကိစ္စမရှိပါဘူး",
    wrong1: "တောင်းပန်ပါတယ်",
    wrong2: "ရပါတယ်",
    category: "Verbs",
  },
  {
    id: 113,
    chinese: "是",
    pinyin: "shì",
    myanmar: "ဖြစ်သည်",
    correct: "ဖြစ်သည်",
    wrong1: "ရှိသည်",
    wrong2: "ကြည့်သည်",
    category: "Verbs",
  },
  {
    id: 114,
    chinese: "有",
    pinyin: "yǒu",
    myanmar: "ရှိသည်",
    correct: "ရှိသည်",
    wrong1: "ဖြစ်သည်",
    wrong2: "နားထောင်သည်",
    category: "Verbs",
  },
  {
    id: 115,
    chinese: "看",
    pinyin: "kàn",
    myanmar: "ကြည့်သည်",
    correct: "ကြည့်သည်",
    wrong1: "နားထောင်သည်",
    wrong2: "စကားပြောသည်",
    category: "Verbs",
  },
  {
    id: 116,
    chinese: "听",
    pinyin: "tīng",
    myanmar: "နားထောင်သည်",
    correct: "နားထောင်သည်",
    wrong1: "ကြည့်သည်",
    wrong2: "ဖတ်သည်",
    category: "Verbs",
  },
  {
    id: 117,
    chinese: "说话",
    pinyin: "shuōhuà",
    myanmar: "စကားပြောသည်",
    correct: "စကားပြောသည်",
    wrong1: "ဖတ်သည်",
    wrong2: "ရေးသည်",
    category: "Verbs",
  },
  {
    id: 118,
    chinese: "读",
    pinyin: "dú",
    myanmar: "ဖတ်သည်",
    correct: "ဖတ်သည်",
    wrong1: "ရေးသည်",
    wrong2: "မြင်သည်",
    category: "Verbs",
  },
  {
    id: 119,
    chinese: "写",
    pinyin: "xiě",
    myanmar: "ရေးသည်",
    correct: "ရေးသည်",
    wrong1: "ဖတ်သည်",
    wrong2: "ကြားသည်",
    category: "Verbs",
  },
  {
    id: 120,
    chinese: "看见",
    pinyin: "kànjiàn",
    myanmar: "မြင်သည်",
    correct: "မြင်သည်",
    wrong1: "ကြားသည်",
    wrong2: "ခေါ်သည်",
    category: "Verbs",
  },
  {
    id: 121,
    chinese: "听见",
    pinyin: "tīngjiàn",
    myanmar: "ကြားသည်",
    correct: "ကြားသည်",
    wrong1: "မြင်သည်",
    wrong2: "ဝယ်သည်",
    category: "Verbs",
  },
  {
    id: 122,
    chinese: "叫",
    pinyin: "jiào",
    myanmar: "ခေါ်သည်",
    correct: "ခေါ်သည်",
    wrong1: "ဝယ်သည်",
    wrong2: "ဖွင့်သည်",
    category: "Verbs",
  },
  {
    id: 123,
    chinese: "买",
    pinyin: "mǎi",
    myanmar: "ဝယ်သည်",
    correct: "ဝယ်သည်",
    wrong1: "ခေါ်သည်",
    wrong2: "ထိုင်သည်",
    category: "Verbs",
  },
  {
    id: 124,
    chinese: "开",
    pinyin: "kāi",
    myanmar: "ဖွင့်သည်",
    correct: "ဖွင့်သည်",
    wrong1: "ထိုင်သည်",
    wrong2: "နေထိုင်သည်",
    category: "Verbs",
  },
  {
    id: 125,
    chinese: "坐",
    pinyin: "zuò",
    myanmar: "ထိုင်သည်",
    correct: "ထိုင်သည်",
    wrong1: "ဖွင့်သည်",
    wrong2: "လာသည်",
    category: "Verbs",
  },
  {
    id: 126,
    chinese: "住",
    pinyin: "zhù",
    myanmar: "နေထိုင်သည်",
    correct: "နေထိုင်သည်",
    wrong1: "သွားသည်",
    wrong2: "ပြန်သည်",
    category: "Verbs",
  },
  {
    id: 127,
    chinese: "来",
    pinyin: "lái",
    myanmar: "လာသည်",
    correct: "လာသည်",
    wrong1: "သွားသည်",
    wrong2: "စဉ်းစားသည်",
    category: "Verbs",
  },
  {
    id: 128,
    chinese: "去",
    pinyin: "qù",
    myanmar: "သွားသည်",
    correct: "သွားသည်",
    wrong1: "လာသည်",
    wrong2: "ပြန်သည်",
    category: "Verbs",
  },
  {
    id: 129,
    chinese: "回",
    pinyin: "huí",
    myanmar: "ပြန်သည်",
    correct: "ပြန်သည်",
    wrong1: "သွားသည်",
    wrong2: "လာသည်",
    category: "Verbs",
  },
  {
    id: 130,
    chinese: "想",
    pinyin: "xiǎng",
    myanmar: "စဉ်းစားသည်/ချင်သည်",
    correct: "စဉ်းစားသည်/ချင်သည်",
    wrong1: "စားသည်",
    wrong2: "သောက်သည်",
    category: "Verbs",
  },
  {
    id: 131,
    chinese: "吃",
    pinyin: "chī",
    myanmar: "စားသည်",
    correct: "စားသည်",
    wrong1: "သောက်သည်",
    wrong2: "အိပ်သည်",
    category: "Verbs",
  },
  {
    id: 132,
    chinese: "喝",
    pinyin: "hē",
    myanmar: "သောက်သည်",
    correct: "သောက်သည်",
    wrong1: "စားသည်",
    wrong2: "ဖုန်းဆက်သည်",
    category: "Verbs",
  },
  {
    id: 133,
    chinese: "睡觉",
    pinyin: "shuìjiào",
    myanmar: "အိပ်သည်",
    correct: "အိပ်သည်",
    wrong1: "ဖုန်းဆက်သည်",
    wrong2: "ပြုလုပ်သည်",
    category: "Verbs",
  },
  {
    id: 134,
    chinese: "打电话",
    pinyin: "dǎ diànhuà",
    myanmar: "ဖုန်းဆက်သည်",
    correct: "ဖုန်းဆက်သည်",
    wrong1: "အိပ်သည်",
    wrong2: "အလုပ်လုပ်သည်",
    category: "Verbs",
  },
  {
    id: 135,
    chinese: "做",
    pinyin: "zuò",
    myanmar: "ပြုလုပ်သည်",
    correct: "ပြုလုပ်သည်",
    wrong1: "လေ့လာသည်",
    wrong2: "တတ်မြောက်သည်",
    category: "Verbs",
  },
  {
    id: 136,
    chinese: "工作",
    pinyin: "gōngzuò",
    myanmar: "အလုပ်လုပ်သည်",
    correct: "အလုပ်လုပ်သည်",
    wrong1: "ပြုလုပ်သည်",
    wrong2: "လေ့လာသည်",
    category: "Verbs",
  },
  {
    id: 137,
    chinese: "学习",
    pinyin: "xuéxí",
    myanmar: "လေ့လာသည်",
    correct: "လေ့လာသည်",
    wrong1: "အလုပ်လုပ်သည်",
    wrong2: "တတ်မြောက်သည်",
    category: "Verbs",
  },
  {
    id: 138,
    chinese: "会",
    pinyin: "huì",
    myanmar: "တတ်မြောက်သည်",
    correct: "တတ်မြောက်သည်",
    wrong1: "နိုင်သည်",
    wrong2: "သိကျွမ်းသည်",
    category: "Verbs",
  },
  {
    id: 139,
    chinese: "能",
    pinyin: "néng",
    myanmar: "နိုင်သည်",
    correct: "နိုင်သည်",
    wrong1: "တတ်မြောက်သည်",
    wrong2: "ရိုက်သည်",
    category: "Verbs",
  },
  {
    id: 140,
    chinese: "好",
    pinyin: "hǎo",
    myanmar: "ကောင်းသော",
    correct: "ကောင်းသော",
    wrong1: "ကြီးသော",
    wrong2: "သေးသော",
    category: "Adjectives",
  },
  {
    id: 141,
    chinese: "大",
    pinyin: "dà",
    myanmar: "ကြီးသော",
    correct: "ကြီးသော",
    wrong1: "ကောင်းသော",
    wrong2: "များသော",
    category: "Adjectives",
  },
  {
    id: 142,
    chinese: "小",
    pinyin: "xiǎo",
    myanmar: "သေးသော",
    correct: "သေးသော",
    wrong1: "ကြီးသော",
    wrong2: "နည်းသော",
    category: "Adjectives",
  },
  {
    id: 143,
    chinese: "多",
    pinyin: "duō",
    myanmar: "များသော",
    correct: "များသော",
    wrong1: "နည်းသော",
    wrong2: "အေးသော",
    category: "Adjectives",
  },
  {
    id: 144,
    chinese: "少",
    pinyin: "shǎo",
    myanmar: "နည်းသော",
    correct: "နည်းသော",
    wrong1: "များသော",
    wrong2: "ပူသော",
    category: "Adjectives",
  },
  {
    id: 145,
    chinese: "冷",
    pinyin: "lěng",
    myanmar: "အေးသော",
    correct: "အေးသော",
    wrong1: "ပူသော",
    wrong2: "ပျော်ရွှင်သော",
    category: "Adjectives",
  },
  {
    id: 146,
    chinese: "热",
    pinyin: "rè",
    myanmar: "ပူသော",
    correct: "ပူသော",
    wrong1: "အေးသော",
    wrong2: "လှပသော",
    category: "Adjectives",
  },
  {
    id: 147,
    chinese: "高兴",
    pinyin: "gāoxìng",
    myanmar: "ပျော်ရွှင်သော",
    correct: "ပျော်ရွှင်သော",
    wrong1: "လှပသော",
    wrong2: "ကောင်းသော",
    category: "Adjectives",
  },
  {
    id: 148,
    chinese: "漂亮",
    pinyin: "piàoliang",
    myanmar: "လှပသော",
    correct: "လှပသော",
    wrong1: "ပျော်ရွှင်သော",
    wrong2: "ကြီးသော",
    category: "Adjectives",
  },
  {
    id: 149,
    chinese: "认识",
    pinyin: "rènshi",
    myanmar: "သိကျွမ်းသည်",
    correct: "သိကျွမ်းသည်",
    wrong1: "ရိုက်သည်",
    wrong2: "တတ်မြောက်သည်",
    category: "Verbs",
  },
  {
    id: 150,
    chinese: "打",
    pinyin: "dǎ",
    myanmar: "ရိုက်သည်/ကစားသည်",
    correct: "ရိုက်သည်/ကစားသည်",
    wrong1: "သိကျွမ်းသည်",
    wrong2: "နိုင်သည်",
    category: "Verbs",
  },
];
  export default datas