 export const data = [
   {
     id: 1,
     kanji: "明け方",
     hiragana: "あけがた",
     type: "Noun",
     myanmar: "အရုဏ်တက်ချိန် / မိုးသောက်ချိန်",
     flashcard: {
       question: "明け方 (あけがた) means?",
       correct_answer: "အရုဏ်တက်ချိန်",
       false_answers: ["နေဝင်ချိန်", "သန်းခေါင်ယံ"],
     },
   },
   {
     id: 2,
     kanji: "青白い",
     hiragana: "あおじろい",
     type: "い-adjective",
     myanmar: "ဖြူဖျော့သော / ပြာနှမ်းနှမ်းဖြူသော",
     flashcard: {
       question: "青白い (あおじろい) means?",
       correct_answer: "ဖြူဖျော့သော",
       false_answers: ["နီရဲသော", "စိုပြေသော"],
     },
   },
   {
     id: 3,
     kanji: "足跡",
     hiragana: "あしあと",
     type: "Noun",
     myanmar: "ခြေရာ",
     flashcard: {
       question: "足跡 (あしあと) means?",
       correct_answer: "ခြေရာ",
       false_answers: ["လက်ရာ", "အသံ"],
     },
   },
   {
     id: 4,
     kanji: "売買",
     hiragana: "ばいばい",
     type: "Noun, Suru verb",
     myanmar: "အရောင်းအဝယ်ပြုလုပ်ခြင်း",
     flashcard: {
       question: "売買 (ばいばい) means?",
       correct_answer: "အရောင်းအဝယ်",
       false_answers: ["အငှား", "လက်ဆောင်"],
     },
   },
   {
     id: 5,
     kanji: "売店",
     hiragana: "ばいてん",
     type: "Noun",
     myanmar: "အရောင်းဆိုင် / ဆိုင်ခန်းငယ်",
     flashcard: {
       question: "売店 (ばいてん) means?",
       correct_answer: "အရောင်းဆိုင်",
       false_answers: ["စက်ရုံ", "စာကြည့်တိုက်"],
     },
   },
   {
     id: 6,
     kanji: "募集",
     hiragana: "ぼしゅう",
     type: "Noun, Suru verb",
     myanmar: "လူခေါ်ခြင်း / လျှောက်လွှာခေါ်ယူခြင်း",
     flashcard: {
       question: "募集 (ぼしゅう) means?",
       correct_answer: "လူခေါ်ခြင်း",
       false_answers: ["အလုပ်ထွက်ခြင်း", "ငြင်းပယ်ခြင်း"],
     },
   },
   {
     id: 7,
     kanji: "長男",
     hiragana: "ちょうなん",
     type: "Noun",
     myanmar: "သားကြီး / အကြီးဆုံးသား",
     flashcard: {
       question: "長男 (ちょうなん) means?",
       correct_answer: "သားဦး/သားကြီး",
       false_answers: ["သမီးကြီး", "သားထွေး"],
     },
   },
   {
     id: 8,
     kanji: "楕円",
     hiragana: "だえん",
     type: "Noun",
     myanmar: "ဘဲဥပုံ",
     flashcard: {
       question: "楕円 (だえん) means?",
       correct_answer: "ဘဲဥပုံ",
       false_answers: ["စတုရန်းပုံ", "စက်ဝိုင်းပုံ"],
     },
   },
   {
     id: 9,
     kanji: "大学院",
     hiragana: "だいがくいん",
     type: "Noun",
     myanmar: "ဘွဲ့လွန်တက္ကသိုလ်",
     flashcard: {
       question: "大学院 means?",
       correct_answer: "ဘွဲ့လွန်တက္ကသိုလ်",
       false_answers: ["မူလတန်းကျောင်း", "အထက်တန်းကျောင်း"],
     },
   },
   {
     id: 10,
     kanji: "出入口",
     hiragana: "でいりぐち",
     type: "Noun",
     myanmar: "အဝင်အထွက်ပေါက်",
     flashcard: {
       question: "出入口 means?",
       correct_answer: "အဝင်အထွက်ပေါက်",
       false_answers: ["ပြတင်းပေါက်", "ခေါင်မိုး"],
     },
   },
   {
     id: 11,
     kanji: "宴会",
     hiragana: "えんかい",
     type: "Noun",
     myanmar: "ထမင်းစားပွဲ / ပါတီ",
     flashcard: {
       question: "宴会 (えんかい) means?",
       correct_answer: "ပါတီ/စားပွဲ",
       false_answers: ["အစည်းအဝေး", "စာမေးပွဲ"],
     },
   },
   {
     id: 12,
     kanji: "円周",
     hiragana: "えんしゅう",
     type: "Noun",
     myanmar: "စက်ဝိုင်းအနားပတ်လည်",
     flashcard: {
       question: "円周 (enshuu) means?",
       correct_answer: "စက်ဝိုင်းအနား",
       false_answers: ["ဗဟိုချက်", "အချင်း"],
     },
   },
   {
     id: 13,
     kanji: "遠足",
     hiragana: "えんそく",
     type: "Noun, Suru verb",
     myanmar: "အပျော်ခရီးထွက်ခြင်း / အဝေးခြေလျင်ခရီး",
     flashcard: {
       question: "遠足 (えんそく) means?",
       correct_answer: "အပျော်ခရီးထွက်ခြင်း",
       false_answers: ["အိမ်ပြန်ခြင်း", "အလုပ်သွားခြင်း"],
     },
   },
   {
     id: 14,
     kanji: "父母",
     hiragana: "ふぼ",
     type: "Noun",
     myanmar: "မိဘနှစ်ပါး",
     flashcard: {
       question: "父母 (fubo) means?",
       correct_answer: "မိဘ",
       false_answers: ["မောင်နှမ", "သူငယ်ချင်း"],
     },
   },
   {
     id: 15,
     kanji: "学科",
     hiragana: "がっか",
     type: "Noun",
     myanmar: "ဘာသာရပ် / သင်ရိုးဌာန",
     flashcard: {
       question: "学科 (gakka) means?",
       correct_answer: "ဘာသာရပ်",
       false_answers: ["အားကစား", "ကျောင်းဝင်း"],
     },
   },
   {
     id: 16,
     kanji: "学会",
     hiragana: "ぎっかい",
     type: "Noun",
     myanmar: "ပညာရပ်ဆိုင်ရာအစည်းအဝေး / ပညာရှင်များအသင်း",
     flashcard: {
       question: "学会 (gakkai) means?",
       correct_answer: "ပညာရပ်ဆိုင်ရာအစည်းအဝေး",
       false_answers: ["ပွဲတော်", "ဈေးရောင်းပွဲ"],
     },
   },
   {
     id: 17,
     kanji: "学力",
     hiragana: "がくりょく",
     type: "Noun",
     myanmar: "စာပေတတ်မြောက်မှု / ပညာရည်စွမ်းအား",
     flashcard: {
       question: "学力 (gakuryoku) means?",
       correct_answer: "ပညာရည်စွမ်းအား",
       false_answers: ["ကာယဗလ", "ငွေကြေး"],
     },
   },
   {
     id: 18,
     kanji: "外科",
     hiragana: "げか",
     type: "Noun",
     myanmar: "ခွဲစိတ်ကုသမှုဌာန",
     flashcard: {
       question: "外科 (geka) means?",
       correct_answer: "ခွဲစိတ်ဌာန",
       false_answers: ["ဆေးကုဌာန", "အရေပြားဌာန"],
     },
   },
   {
     id: 19,
     kanji: "花火",
     hiragana: "はなび",
     type: "Noun",
     myanmar: "မီးရှူးမီးပန်း",
     flashcard: {
       question: "花火 means?",
       correct_answer: "မီးရှူးမီးပန်း",
       false_answers: ["ပန်း", "မီးအိမ်"],
     },
   },
   {
     id: 20,
     kanji: "半径",
     hiragana: "はんけい",
     type: "Noun",
     myanmar: "အချင်းဝက်",
     flashcard: {
       question: "半径 (hankei) means?",
       correct_answer: "အချင်းဝက်",
       false_answers: ["အချင်း", "ဧရိယာ"],
     },
   },
   {
     id: 21,
     kanji: "半島",
     hiragana: "はんとう",
     type: "Noun",
     myanmar: "ကျွန်းဆွယ်",
     flashcard: {
       question: "半島 (hantou) means?",
       correct_answer: "ကျွန်းဆွယ်",
       false_answers: ["ပင်လယ်", "တောင်တန်း"],
     },
   },
   {
     id: 22,
     kanji: "発売",
     hiragana: "はつばい",
     type: "Noun, Suru verb",
     myanmar: "ထုတ်ဝေရောင်းချခြင်း",
     flashcard: {
       question: "発売 means?",
       correct_answer: "ထုတ်ဝေရောင်းချခြင်း",
       false_answers: ["ဝယ်ယူခြင်း", "ပြန်သိမ်းခြင်း"],
     },
   },
   {
     id: 23,
     kanji: "早口",
     hiragana: "はやぐち",
     type: "Noun",
     myanmar: "စကားပြောမြန်ခြင်း",
     flashcard: {
       question: "早口 (hayaguchi) means?",
       correct_answer: "စကားပြောမြန်ခြင်း",
       false_answers: ["စကားထစ်ခြင်း", "စကားနည်းခြင်း"],
     },
   },
   {
     id: 24,
     kanji: "外れる",
     hiragana: "はずれる",
     type: "Verb",
     myanmar: "လွဲချော်သည် / ပြုတ်ထွက်သည်",
     flashcard: {
       question: "外れる means?",
       correct_answer: "လွဲချော်သည်",
       false_answers: ["ကိုက်ညီသည်", "ကပ်သည်"],
     },
   },
   {
     id: 25,
     kanji: "閉会",
     hiragana: "へいかい",
     type: "Suru verb",
     myanmar: "အခမ်းအနားရုပ်သိမ်းခြင်း / ပိတ်ခြင်း",
     flashcard: {
       question: "閉会 means?",
       correct_answer: "အခမ်းအနားပိတ်ခြင်း",
       false_answers: ["ဖွင့်လှစ်ခြင်း", "စောင့်ဆိုင်းခြင်း"],
     },
   },
   {
     id: 26,
     kanji: "昼寝",
     hiragana: "ひるね",
     type: "Noun, Suru verb",
     myanmar: "နေ့လယ်ခဏအိပ်ခြင်း",
     flashcard: {
       question: "昼寝 means?",
       correct_answer: "နေ့လယ်တစ်ရေးအိပ်ခြင်း",
       false_answers: ["ညအိပ်ခြင်း", "လမ်းလျှောက်ခြင်း"],
     },
   },
   {
     id: 27,
     kanji: "意地悪",
     hiragana: "いじわる",
     type: "Noun, な-adjective",
     myanmar: "စိတ်ပုတ်သော / ကောက်ကျစ်သော",
     flashcard: {
       question: "意地悪 (ijiwaru) means?",
       correct_answer: "စိတ်ပုတ်သော",
       false_answers: ["ကြင်နာသော", "ရိုးသားသော"],
     },
   },
   {
     id: 28,
     kanji: "移転",
     hiragana: "いてん",
     type: "Noun, Suru verb",
     myanmar: "ပြောင်းရွှေ့ခြင်း (နေရာ/လိပ်စာ)",
     flashcard: {
       question: "移転 (iten) means?",
       correct_answer: "ပြောင်းရွှေ့ခြင်း",
       false_answers: ["နေမြဲနေခြင်း", "ဖျက်ဆီးခြင်း"],
     },
   },
   {
     id: 29,
     kanji: "一旦",
     hiragana: "いったん",
     type: "Adverb",
     myanmar: "ခဏတဖြုတ် / တစ်ခဏ",
     flashcard: {
       question: "一旦 means?",
       correct_answer: "ခဏတဖြုတ်",
       false_answers: ["အမြဲတမ်း", "ဘယ်တော့မှ"],
     },
   },
   {
     id: 30,
     kanji: "寺院",
     hiragana: "じいん",
     type: "Noun",
     myanmar: "ဘုန်းကြီးကျောင်း / ဘာသာရေးအဆောက်အအုံ",
     flashcard: {
       question: "寺院 (ji'in) means?",
       correct_answer: "ဘုန်းကြီးကျောင်း",
       false_answers: ["ဈေးဆိုင်", "ဆေးရုံ"],
     },
   },
   {
     id: 31,
     kanji: "人文科学",
     hiragana: "じんぶんかがく",
     type: "Noun",
     myanmar: "လူမှုဗေဒနှင့် ဝိဇ္ဇာပညာရပ်များ",
     flashcard: {
       question: "人文科学 means?",
       correct_answer: "လူမှုဗေဒ",
       false_answers: ["သဘာဝသိပ္ပံ", "အင်ဂျင်နီယာ"],
     },
   },
   {
     id: 32,
     kanji: "自習",
     hiragana: "じしゅう",
     type: "Noun, Suru verb",
     myanmar: "ကိုယ်တိုင်လေ့လာခြင်း",
     flashcard: {
       question: "自習 (jishuu) means?",
       correct_answer: "ကိုယ်တိုင်လေ့လာခြင်း",
       false_answers: ["သင်ကြားခြင်း", "ကစားခြင်း"],
     },
   },
   {
     id: 33,
     kanji: "時速",
     hiragana: "じそく",
     type: "Noun",
     myanmar: "တစ်နာရီအမြန်နှုန်း",
     flashcard: {
       question: "時速 (jisoku) means?",
       correct_answer: "တစ်နာရီအမြန်နှုန်း",
       false_answers: ["အကွာအဝေး", "အလေးချိန်"],
     },
   },
   {
     id: 34,
     kanji: "実習",
     hiragana: "じっしゅう",
     type: "Noun, Suru verb",
     myanmar: "လက်တွေ့လေ့ကျင့်ခြင်း",
     flashcard: {
       question: "実習 (jisshuu) means?",
       correct_answer: "လက်တွေ့လေ့ကျင့်ခြင်း",
       false_answers: ["စာရွက်ပေါ်တွင်ဖြေခြင်း", "နားထောင်ခြင်း"],
     },
   },
   {
     id: 35,
     kanji: "過半数",
     hiragana: "かはんすう",
     type: "Noun",
     myanmar: "ထက်ဝက်ကျော် / အများစု",
     flashcard: {
       question: "過半数 means?",
       correct_answer: "ထက်ဝက်ကျော်",
       false_answers: ["ထက်ဝက်အောက်", "နည်းပါးသော"],
     },
   },
   {
     id: 36,
     kanji: "開会",
     hiragana: "かいかい",
     type: "Noun, Suru verb",
     myanmar: "အခမ်းအနားဖွင့်လှစ်ခြင်း",
     flashcard: {
       question: "開会 means?",
       correct_answer: "ဖွင့်လှစ်ခြင်း",
       false_answers: ["ပိတ်သိမ်းခြင်း", "ရပ်နားခြင်း"],
     },
   },
   {
     id: 37,
     kanji: "会館",
     hiragana: "かいかん",
     type: "Noun",
     myanmar: "အစည်းအဝေးခန်းမ",
     flashcard: {
       question: "会館 (kaikan) means?",
       correct_answer: "အစည်းအဝေးခန်းမ",
       false_answers: ["ပန်းခြံ", "စာသင်ခန်း"],
     },
   },
   {
     id: 38,
     kanji: "回転",
     hiragana: "かいてん",
     type: "Noun, Suru verb",
     myanmar: "လည်ပတ်ခြင်း / ဝိုင်းခြင်း",
     flashcard: {
       question: "回転 (kaiten) means?",
       correct_answer: "လည်ပတ်ခြင်း",
       false_answers: ["ရပ်တန့်ခြင်း", "ခုန်ခြင်း"],
     },
   },
   {
     id: 39,
     kanji: "加速",
     hiragana: "かそく",
     type: "Noun, Suru verb",
     myanmar: "အရှိန်မြှင့်ခြင်း",
     flashcard: {
       question: "加速 (kasoku) means?",
       correct_answer: "အရှိန်မြှင့်ခြင်း",
       false_answers: ["အရှိန်လျှော့ခြင်း", "ရပ်ခြင်း"],
     },
   },
   {
     id: 40,
     kanji: "加速度",
     hiragana: "かそくど",
     type: "Noun",
     myanmar: "အရှိန်နှုန်း (Acceleration)",
     flashcard: {
       question: "加速度 means?",
       correct_answer: "အရှိန်နှုန်း",
       false_answers: ["အလေးချိန်", "အပူချိန်"],
     },
   },
   {
     id: 41,
     kanji: "見学",
     hiragana: "けんがく",
     type: "Noun, Suru verb",
     myanmar: "လေ့လာရေးခရီးသွားခြင်း",
     flashcard: {
       question: "見学 (kengaku) means?",
       correct_answer: "လေ့လာရေးခရီး",
       false_answers: ["အိမ်စာလုပ်ခြင်း", "အိပ်ခြင်း"],
     },
   },
   {
     id: 42,
     kanji: "国王",
     hiragana: "こくおう",
     type: "Noun",
     myanmar: "ဘုရင် / နိုင်ငံအကြီးအကဲ",
     flashcard: {
       question: "国王 (kokuou) means?",
       correct_answer: "ဘုရင်",
       false_answers: ["စစ်သား", "တောင်သူ"],
     },
   },
   {
     id: 43,
     kanji: "国立",
     hiragana: "こくりつ",
     type: "Noun",
     myanmar: "နိုင်ငံတော်ပိုင် / အစိုးရပိုင်",
     flashcard: {
       question: "国立 means?",
       correct_answer: "နိုင်ငံတော်ပိုင်",
       false_answers: ["ပုဂ္ဂလိကပိုင်", "နိုင်ငံခြားပိုင်"],
     },
   },
   {
     id: 44,
     kanji: "国籍",
     hiragana: "こくせき",
     type: "Noun",
     myanmar: "နိုင်ငံသားဖြစ်မှု / နိုင်ငံသား",
     flashcard: {
       question: "国籍 (kokuseki) means?",
       correct_answer: "နိုင်ငံသား",
       false_answers: ["အမည်", "လိပ်စာ"],
     },
   },
   {
     id: 45,
     kanji: "転がる",
     hiragana: "ころがる",
     type: "Verb",
     myanmar: "လိမ့်သည် / လဲကျသည်",
     flashcard: {
       question: "転がる (korogaru) means?",
       correct_answer: "လိမ့်သည်",
       false_answers: ["ခုန်သည်", "ရပ်သည်"],
     },
   },
   {
     id: 46,
     kanji: "転がす",
     hiragana: "ころがす",
     type: "Verb",
     myanmar: "လိမ့်စေသည် / လှိမ့်သည်",
     flashcard: {
       question: "転がす (korogasu) means?",
       correct_answer: "လှိမ့်သည်",
       false_answers: ["ကိုင်ထားသည်", "ပစ်လိုက်သည်"],
     },
   },
   {
     id: 47,
     kanji: "校舎",
     hiragana: "こうしゃ",
     type: "Noun",
     myanmar: "ကျောင်းဆောင်",
     flashcard: {
       question: "校舎 (kousha) means?",
       correct_answer: "ကျောင်းဆောင်",
       false_answers: ["ပန်းခြံ", "စာကြည့်တိုက်"],
     },
   },
   {
     id: 48,
     kanji: "校庭",
     hiragana: "こうてい",
     type: "Noun",
     myanmar: "ကျောင်းဝင်း / ကစားကွင်း",
     flashcard: {
       question: "校庭 (koutei) means?",
       correct_answer: "ကျောင်းဝင်း",
       false_answers: ["စာသင်ခန်း", "ရုံးခန်း"],
     },
   },
   {
     id: 49,
     kanji: "待合室",
     hiragana: "まちあいしつ",
     type: "Noun",
     myanmar: "စောင့်ဆိုင်းခန်း",
     flashcard: {
       question: "待合室 means?",
       correct_answer: "စောင့်ဆိုင်းခန်း",
       false_answers: ["မီးဖိုချောင်", "အိမ်သာ"],
     },
   },
   {
     id: 50,
     kanji: "待ち合わせる",
     hiragana: "まちあわせる",
     type: "Verb",
     myanmar: "ချိန်းဆိုတွေ့ဆုံသည်",
     flashcard: {
       question: "待ち合わせる means?",
       correct_answer: "ချိန်းတွေ့သည်",
       false_answers: ["လမ်းခွဲသည်", "မေ့သည်"],
     },
   },
   {
     id: 51,
     kanji: "窓口",
     hiragana: "まどぐち",
     type: "Noun",
     myanmar: "ဝန်ဆောင်မှုကောင်တာ / ပြတင်းပေါက်ပေါက်",
     flashcard: {
       question: "窓口 (madoguchi) means?",
       correct_answer: "ကောင်တာ",
       false_answers: ["တံခါးမကြီး", "လှေကား"],
     },
   },
   {
     id: 52,
     kanji: "毎度",
     hiragana: "まいど",
     type: "Noun",
     myanmar: "အခါတိုင်း / အမြဲတမ်း",
     flashcard: {
       question: "毎度 (maido) means?",
       correct_answer: "အခါတိုင်း",
       false_answers: ["တစ်ခါတလေ", "ဘယ်တော့မှ"],
     },
   },
   {
     id: 53,
     kanji: "真っ青",
     hiragana: "まっさお",
     type: "Noun, な-adjective",
     myanmar: "ရဲရဲပြာသော / ဖြူဖျော့တုန်ရီသော",
     flashcard: {
       question: "真っ青 (massao) means?",
       correct_answer: "ရဲရဲပြာသော",
       false_answers: ["ရဲရဲနီသော", "စိမ်းလန်းသော"],
     },
   },
   {
     id: 54,
     kanji: "真っ白",
     hiragana: "まっしろ",
     type: "Noun, な-adjective",
     myanmar: "ဖွေးဖွေးဖြူသော",
     flashcard: {
       question: "真っ白 means?",
       correct_answer: "ဖွေးဖွေးဖြူသော",
       false_answers: ["မည်းနက်သော", "ဝါသော"],
     },
   },
   {
     id: 55,
     kanji: "名刺",
     hiragana: "めいし",
     type: "Noun",
     myanmar: "လိပ်စာကတ်",
     flashcard: {
       question: "名刺 (meishi) means?",
       correct_answer: "လိပ်စာကတ်",
       false_answers: ["စာအုပ်", "ပိုက်ဆံအိတ်"],
     },
   },
   {
     id: 56,
     kanji: "店屋",
     hiragana: "みせや",
     type: "Noun",
     myanmar: "ဆိုင် / အရောင်းဆိုင်",
     flashcard: {
       question: "店屋 means?",
       correct_answer: "ဆိုင်",
       false_answers: ["အိမ်", "ကျောင်း"],
     },
   },
   {
     id: 57,
     kanji: "木材",
     hiragana: "もくざい",
     type: "Noun",
     myanmar: "သစ်သားကုန်ကြမ်း",
     flashcard: {
       question: "木材 (mokuzai) means?",
       correct_answer: "သစ်သား",
       false_answers: ["သံမဏိ", "ကျောက်ခဲ"],
     },
   },
   {
     id: 58,
     kanji: "元々",
     hiragana: "もともと",
     type: "Adverb",
     myanmar: "မူလကတည်းက",
     flashcard: {
       question: "元々 (motomoto) means?",
       correct_answer: "မူလကတည်းက",
       false_answers: ["နောင်တွင်", "မကြာမီ"],
     },
   },
   {
     id: 59,
     kanji: "内科",
     hiragana: "ないか",
     type: "Noun",
     myanmar: "အတွင်းလူနာဌာန / ဆေးကုဌာန",
     flashcard: {
       question: "内科 (naika) means?",
       correct_answer: "ဆေးကုဌာန",
       false_answers: ["ခွဲစိတ်ဌာန", "သွားဌာန"],
     },
   },
   {
     id: 60,
     kanji: "並木",
     hiragana: "なみき",
     type: "Noun",
     myanmar: "လမ်းဘေးတစ်လျှောက်ရှိ သစ်ပင်တန်း",
     flashcard: {
       question: "並木 (namiki) means?",
       correct_answer: "သစ်ပင်တန်း",
       false_answers: ["မြက်ခင်း", "ပန်းခြံ"],
     },
   },
   {
     id: 61,
     kanji: "入社",
     hiragana: "にゅうしゃ",
     type: "Noun, Suru verb",
     myanmar: "ကုမ္ပဏီသို့ အလုပ်ဝင်ခြင်း",
     flashcard: {
       question: "入社 means?",
       correct_answer: "အလုပ်ဝင်ခြင်း",
       false_answers: ["အလုပ်ထွက်ခြင်း", "ကျောင်းတက်ခြင်း"],
     },
   },
   {
     id: 62,
     kanji: "押さえる",
     hiragana: "おさえる",
     type: "Verb",
     myanmar: "ဖိထားသည် / ချုပ်ကိုင်ထားသည်",
     flashcard: {
       question: "押さえる (osaeru) means?",
       correct_answer: "ဖိထားသည်",
       false_answers: ["လွှတ်လိုက်သည်", "ဆွဲသည်"],
     },
   },
   {
     id: 63,
     kanji: "理科",
     hiragana: "りか",
     type: "Noun",
     myanmar: "သိပ္ပံဘာသာရပ်",
     flashcard: {
       question: "理科 (rika) means?",
       correct_answer: "သိပ္ပံ",
       false_answers: ["သမိုင်း", "စာပေ"],
     },
   },
   {
     id: 64,
     kanji: "領収",
     hiragana: "りょうしゅう",
     type: "Noun, Suru verb",
     myanmar: "ငွေလက်ခံရရှိခြင်း",
     flashcard: {
       question: "領収 means?",
       correct_answer: "ငွေလက်ခံခြင်း",
       false_answers: ["ငွေပေးခြင်း", "ချေးခြင်း"],
     },
   },
   {
     id: 65,
     kanji: "再三",
     hiragana: "さいさん",
     type: "Adverb",
     myanmar: "ခဏခဏ / အကြိမ်ကြိမ်",
     flashcard: {
       question: "再三 (saisan) means?",
       correct_answer: "အကြိမ်ကြိမ်",
       false_answers: ["တစ်ခါတည်း", "ဘယ်တော့မှ"],
     },
   },
   {
     id: 66,
     kanji: "刺さる",
     hiragana: "ささる",
     type: "Verb",
     myanmar: "စူးဝင်သည် / စိုက်ဝင်သည်",
     flashcard: {
       question: "刺さる (sasaru) means?",
       correct_answer: "စူးဝင်သည်",
       false_answers: ["ပြုတ်သည်", "ကွဲသည်"],
     },
   },
   {
     id: 67,
     kanji: "刺身",
     hiragana: "さしみ",
     type: "Noun",
     myanmar: "ငါးအစိမ်းလွှာ",
     flashcard: {
       question: "刺身 means?",
       correct_answer: "ငါးအစိမ်းလွှာ",
       false_answers: ["ငါးကင်", "ဟင်းသီးဟင်းရွက်"],
     },
   },
   {
     id: 68,
     kanji: "早速",
     hiragana: "さっそく",
     type: "Adverb",
     myanmar: "ချက်ချင်း / မဆိုင်းမတွ",
     flashcard: {
       question: "早速 (sassoku) means?",
       correct_answer: "ချက်ချင်း",
       false_answers: ["နောက်မှ", "ဖြည်းဖြည်း"],
     },
   },
   {
     id: 69,
     kanji: "刺す",
     hiragana: "さす",
     type: "Verb",
     myanmar: "ထိုးသည် / စိုက်သည် / ကိုက်သည်(အင်းဆက်)",
     flashcard: {
       question: "刺す (sasu) means?",
       correct_answer: "ထိုး/ကိုက်သည်",
       false_answers: ["ပွတ်သည်", "ဆေးသည်"],
     },
   },
   {
     id: 70,
     kanji: "青少年",
     hiragana: "せいしょうねん",
     type: "Noun",
     myanmar: "လူငယ်မောင်မယ်များ",
     flashcard: {
       question: "青少年 means?",
       correct_answer: "လူငယ်များ",
       false_answers: ["သက်ကြီးရွယ်အို", "ကလေးငယ်"],
     },
   },
   {
     id: 71,
     kanji: "赤道",
     hiragana: "せきどう",
     type: "Noun",
     myanmar: "အီကွေတာ",
     flashcard: {
       question: "赤道 (sekidou) means?",
       correct_answer: "အီကွေတာ",
       false_answers: ["ဝင်ရိုးစွန်း", "ပင်လယ်"],
     },
   },
   {
     id: 72,
     kanji: "社会科学",
     hiragana: "しゃかいかがく",
     type: "Noun",
     myanmar: "လူမှုသိပ္ပံပညာရပ်",
     flashcard: {
       question: "社会科学 means?",
       correct_answer: "လူမှုသိပ္ပံ",
       false_answers: ["အနုပညာ", "ရူပဗေဒ"],
     },
   },
   {
     id: 73,
     kanji: "社説",
     hiragana: "しゃせつ",
     type: "Noun",
     myanmar: "အယ်ဒီတာ့အာဘော်",
     flashcard: {
       question: "社説 (shasetsu) means?",
       correct_answer: "အယ်ဒီတာ့အာဘော်",
       false_answers: ["ကြော်ငြာ", "ပုံပြင်"],
     },
   },
   {
     id: 74,
     kanji: "司会",
     hiragana: "しかい",
     type: "Noun, Suru verb",
     myanmar: "အခမ်းအနားမှူး / အစီအစဉ်တင်ဆက်သူ",
     flashcard: {
       question: "司会 (shikai) means?",
       correct_answer: "အခမ်းအနားမှူး",
       false_answers: ["ဧည့်သည်", "အလုပ်သမား"],
     },
   },
   {
     id: 75,
     kanji: "新幹線",
     hiragana: "しんかんせん",
     type: "Noun",
     myanmar: "ကျည်ဆန်ရထား",
     flashcard: {
       question: "新幹線 means?",
       correct_answer: "ကျည်ဆန်ရထား",
       false_answers: ["ဘတ်စ်ကား", "လေယာဉ်"],
     },
   },
   {
     id: 76,
     kanji: "白髪",
     hiragana: "しらが",
     type: "Noun",
     myanmar: "ဆံပင်ဖြူ",
     flashcard: {
       question: "白髪 (shiraga) means?",
       correct_answer: "ဆံပင်ဖြူ",
       false_answers: ["ဆံပင်နက်", "မျက်တောင်"],
     },
   },
   {
     id: 77,
     kanji: "自然科学",
     hiragana: "しぜんかがく",
     type: "Noun",
     myanmar: "သဘာဝသိပ္ပံပညာရပ်",
     flashcard: {
       question: "自然科学 means?",
       correct_answer: "သဘာဝသိပ္ပံ",
       false_answers: ["ဘာသာဗေဒ", "ဒဿနဗေဒ"],
     },
   },
   {
     id: 78,
     kanji: "書店",
     hiragana: "しょてん",
     type: "Noun",
     myanmar: "စာအုပ်ဆိုင်",
     flashcard: {
       question: "書店 (shoten) means?",
       correct_answer: "စာအုပ်ဆိုင်",
       false_answers: ["ပန်းဆိုင်", "ဆေးဆိုင်"],
     },
   },
   {
     id: 79,
     kanji: "商社",
     hiragana: "しょうしゃ",
     type: "Noun",
     myanmar: "ကုန်သွယ်ရေးကုမ္ပဏီ",
     flashcard: {
       question: "商社 (shousha) means?",
       correct_answer: "ကုန်သွယ်ရေးကုမ္ပဏီ",
       false_answers: ["ကျောင်း", "ဘုရားကျောင်း"],
     },
   },
   {
     id: 80,
     kanji: "商店",
     hiragana: "しょうてん",
     type: "Noun",
     myanmar: "ဆိုင် / ကုန်စုံဆိုင်",
     flashcard: {
       question: "商店 (shouten) means?",
       correct_answer: "ဆိုင်",
       false_answers: ["ရုံး", "အိမ်"],
     },
   },
   {
     id: 81,
     kanji: "集合",
     hiragana: "しゅうごう",
     type: "Noun, Suru verb",
     myanmar: "စုဝေးခြင်း / စုရုံးခြင်း",
     flashcard: {
       question: "集合 (shuugou) means?",
       correct_answer: "စုဝေးခြင်း",
       false_answers: ["လူစုခွဲခြင်း", "အိပ်ခြင်း"],
     },
   },
   {
     id: 82,
     kanji: "習字",
     hiragana: "しゅうじ",
     type: "Noun",
     myanmar: "လက်ရေးလှပညာ",
     flashcard: {
       question: "習字 (shuuji) means?",
       correct_answer: "လက်ရေးလှ",
       false_answers: ["ပန်းချီ", "ဂီတ"],
     },
   },
   {
     id: 83,
     kanji: "集会",
     hiragana: "しゅうかい",
     type: "Noun, Suru verb",
     myanmar: "အစည်းအဝေး / လူစုလူဝေး",
     flashcard: {
       question: "集会 (shuukai) means?",
       correct_answer: "အစည်းအဝေး",
       false_answers: ["ဈေးဝယ်ခြင်း", "လမ်းလျှောက်ခြင်း"],
     },
   },
   {
     id: 84,
     kanji: "速力",
     hiragana: "そくりょく",
     type: "Noun",
     myanmar: "အရှိန်အဟုန် / အမြန်နှုန်း",
     flashcard: {
       question: "速力 (sokuryoku) means?",
       correct_answer: "အရှိန်အဟုန်",
       false_answers: ["အလေးချိန်", "အမြင့်"],
     },
   },
   {
     id: 85,
     kanji: "速達",
     hiragana: "そくたつ",
     type: "Noun, Suru verb",
     myanmar: "အမြန်စာပို့စနစ်",
     flashcard: {
       question: "速達 (sokutatsu) means?",
       correct_answer: "အမြန်စာပို့",
       false_answers: ["ရိုးရိုးစာပို့", "ဖုန်းခေါ်ခြင်း"],
     },
   },
   {
     id: 86,
     kanji: "足袋",
     hiragana: "たび",
     type: "Noun",
     myanmar: "ဂျပန်ခြေအိတ် (ခြေမကွဲ)",
     flashcard: {
       question: "足袋 (tabi) means?",
       correct_answer: "ခြေအိတ်",
       false_answers: ["လက်အိတ်", "ဦးထုပ်"],
     },
   },
   {
     id: 87,
     kanji: "足る",
     hiragana: "たる",
     type: "Verb",
     myanmar: "လုံလောက်သည်",
     flashcard: {
       question: "足る (taru) means?",
       correct_answer: "လုံလောက်သည်",
       false_answers: ["လိုနေသည်", "ပိုနေသည်"],
     },
   },
   {
     id: 88,
     kanji: "特売",
     hiragana: "とくばい",
     type: "Noun, Suru verb",
     myanmar: "အထူးဈေးနှုန်းဖြင့် ရောင်းချခြင်း",
     flashcard: {
       question: "特売 means?",
       correct_answer: "အထူးရောင်းချခြင်း",
       false_answers: ["ဈေးတင်ရောင်းခြင်း", "ဈေးပိတ်ခြင်း"],
     },
   },
   {
     id: 189,
     kanji: "透明",
     hiragana: "とうめい",
     type: "Noun, な-adjective",
     myanmar: "ကြည်လင်သော / ဖောက်ထွင်းမြင်ရသော",
     flashcard: {
       question: "透明 (toumei) means?",
       correct_answer: "ကြည်လင်သော",
       false_answers: ["ဝေဝါးသော", "မည်းသော"],
     },
   },
   {
     id: 90,
     kanji: "東洋",
     hiragana: "とうよう",
     type: "Noun",
     myanmar: "အရှေ့တိုင်း",
     flashcard: {
       question: "東洋 (touyou) means?",
       correct_answer: "အရှေ့တိုင်း",
       false_answers: ["အနောက်တိုင်း", "တောင်ဘက်"],
     },
   },
   {
     id: 91,
     kanji: "売れ行き",
     hiragana: "うれゆき",
     type: "Noun",
     myanmar: "အရောင်းရရှိမှုအခြေအနေ",
     flashcard: {
       question: "売れ行き means?",
       correct_answer: "အရောင်းအခြေအနေ",
       false_answers: ["ဝယ်ယူမှု", "အရှုံး"],
     },
   },
   {
     id: 92,
     kanji: "売上",
     hiragana: "うりあげ",
     type: "Noun",
     myanmar: "ရောင်းရငွေစုစုပေါင်း",
     flashcard: {
       question: "売上 (uriage) means?",
       correct_answer: "ရောင်းရငွေ",
       false_answers: ["ရင်းနှီးငွေ", "အကြွေး"],
     },
   },
   {
     id: 93,
     kanji: "売り切れ",
     hiragana: "うりきれ",
     type: "Noun",
     myanmar: "ပစ္စည်းကုန်သွားခြင်း",
     flashcard: {
       question: "売り切れ means?",
       correct_answer: "ပစ္စည်းကုန်ခြင်း",
       false_answers: ["အသစ်ရောက်ခြင်း", "ဈေးလျှော့ခြင်း"],
     },
   },
   {
     id: 94,
     kanji: "売り切れる",
     hiragana: "うりきれる",
     type: "Verb",
     myanmar: "ရောင်းကုန်သွားသည်",
     flashcard: {
       question: "売り切れる means?",
       correct_answer: "ရောင်းကုန်သည်",
       false_answers: ["ဝယ်သည်", "ရောင်းရခက်သည်"],
     },
   },
   {
     id: 95,
     kanji: "我が",
     hiragana: "わが",
     type: "Pre-noun adjectival",
     myanmar: "ငါတို့၏ / မိမိ၏",
     flashcard: {
       question: "我が (waga) means?",
       correct_answer: "ငါတို့၏",
       false_answers: ["သူတို့၏", "၎င်း၏"],
     },
   },
   {
     id: 96,
     kanji: "洋品店",
     hiragana: "ようひんてん",
     type: "Noun",
     myanmar: "အနောက်တိုင်းဝတ်စုံနှင့် အသုံးအဆောင်ဆိုင်",
     flashcard: {
       question: "洋品店 means?",
       correct_answer: "အနောက်တိုင်းဝတ်စုံဆိုင်",
       false_answers: ["ဂျပန်စာအုပ်ဆိုင်", "သစ်သီးဆိုင်"],
     },
   },
   {
     id: 97,
     kanji: "輸血",
     hiragana: "ゆけつ",
     type: "Noun, Suru verb",
     myanmar: "သွေးသွင်းခြင်း",
     flashcard: {
       question: "輸血 (yuketsu) means?",
       correct_answer: "သွေးသွင်းခြင်း",
       false_answers: ["သွေးဖောက်ခြင်း", "ခွဲစိတ်ခြင်း"],
     },
   },
   {
     id: 98,
     kanji: "輸送",
     hiragana: "ゆそう",
     type: "Noun, Suru verb",
     myanmar: "သယ်ယူပို့ဆောင်ရေး",
     flashcard: {
       question: "輸送 (yusou) means?",
       correct_answer: "သယ်ယူပို့ဆောင်ရေး",
       false_answers: ["သိုလှောင်ခြင်း", "ရောင်းချခြင်း"],
     },
   },
   {
     id: 99,
     kanji: "材木",
     hiragana: "ざいもく",
     type: "Noun",
     myanmar: "သစ်တုံး / သစ်သား",
     flashcard: {
       question: "材木 (zaimoku) means?",
       correct_answer: "သစ်သား",
       false_answers: ["သံ", "အုတ်"],
     },
   },
 ]
 
 
 
 export const n2kanjin = [{
     id: 1,
     kanji: "党",
     onyomi: "トウ",
     kunyomi: "なかま",
     type: "Noun",
     myanmar: "ပါတီ / အဖွဲ့အစည်း",
     flashcard: {
       question: "党 (とう) means?",
       correct_answer: "ပါတီ",
       false_answers: ["အစိုးရ", "ကျောင်း"],
     },
   },
   {
     id: 2,
     kanji: "協",
     onyomi: "キョウ",
     kunyomi: "-",
     type: "Noun/Prefix",
     myanmar: "ပူးပေါင်းဆောင်ရွက်ခြင်း",
     flashcard: {
       question: "協 (きょう) is related to?",
       correct_answer: "ပူးပေါင်းဆောင်ရွက်ခြင်း",
       false_answers: ["အတိုက်အခံ", "တစ်ကိုယ်တော်"],
     },
   },
   {
     id: 3,
     kanji: "総",
     onyomi: "ソウ",
     kunyomi: "すべ(て)",
     type: "Noun/Prefix",
     myanmar: "အားလုံး / စုစုပေါင်း / အထွေထွေ",
     flashcard: {
       question: "総 (そう) means?",
       correct_answer: "အားလုံး/စုစုပေါင်း",
       false_answers: ["တစ်စိတ်တစ်ပိုင်း", "အနည်းငယ်"],
     },
   },
   {
     id: 4,
     kanji: "区",
     onyomi: "ク",
     kunyomi: "-",
     type: "Noun",
     myanmar: "ရပ်ကွက် / နယ်မြေ / ခရိုင်",
     flashcard: {
       question: "区 (く) means?",
       correct_answer: "ရပ်ကွက်",
       false_answers: ["နိုင်ငံ", "ပင်လယ်"],
     },
   },
   {
     id: 5,
     kanji: "領",
     onyomi: "リョウ",
     kunyomi: "-",
     type: "Noun/Suffix",
     myanmar: "ပိုင်နက် / အုပ်ချုပ်မှုနယ်မြေ",
     flashcard: {
       question: "領 (りょう) relates to?",
       correct_answer: "ပိုင်နက်",
       false_answers: ["ခရီးသွား", "အစားအစာ"],
     },
   },
   {
     id: 6,
     kanji: "県",
     onyomi: "ケン",
     kunyomi: "-",
     type: "Noun",
     myanmar: "စီရင်စု / ခရိုင် (Prefecture)",
     flashcard: {
       question: "県 (けん) means?",
       correct_answer: "စီရင်စု",
       false_answers: ["မြို့တော်", "ရွာ"],
     },
   },
   {
     id: 7,
     kanji: "設",
     onyomi: "セツ",
     kunyomi: "もう(ける)",
     type: "Verb/Noun",
     myanmar: "တည်ထောင်ခြင်း / ပြင်ဆင်သတ်မှတ်ခြင်း",
     flashcard: {
       question: "設 (せつ) means?",
       correct_answer: "တည်ထောင်ခြင်း",
       false_answers: ["ဖျက်သိမ်းခြင်း", "ရောင်းချခြင်း"],
     },
   },
   {
     id: 8,
     kanji: "保",
     onyomi: "ホ",
     kunyomi: "たも(つ)",
     type: "Verb/Noun",
     myanmar: "ထိန်းသိမ်းခြင်း / စောင့်ရှောက်ခြင်း / အာမခံခြင်း",
     flashcard: {
       question: "保 (ほ) means?",
       correct_answer: "ထိန်းသိမ်းခြင်း",
       false_answers: ["စွန့်ပစ်ခြင်း", "ပြောင်းလဲခြင်း"],
     },
   },
   {
     id: 9,
     kanji: "改",
     onyomi: "カイ",
     kunyomi: "あらた(める)",
     type: "Verb/Noun",
     myanmar: "ပြုပြင်ပြောင်းလဲခြင်း / ပြင်ဆင်ခြင်း",
     flashcard: {
       question: "改 (かい) means?",
       correct_answer: "ပြုပြင်ခြင်း",
       false_answers: ["အတည်ပြုခြင်း", "ဖျက်ဆီးခြင်း"],
     },
   },
   {
     id: 10,
     kanji: "第",
     onyomi: "ダイ",
     kunyomi: "-",
     type: "Prefix",
     myanmar: "အမှတ်စဉ် (နံပါတ်)",
     flashcard: {
       question: "第 (だい) is used for?",
       correct_answer: "နံပါတ်စဉ်",
       false_answers: ["နာမည်", "လိပ်စာ"],
     },
   },
   {
     id: 11,
     kanji: "結",
     onyomi: "ケツ",
     kunyomi: "むす(ぶ)",
     type: "Verb/Noun",
     myanmar: "ချည်နှောင်ခြင်း / အဆုံးသတ်ခြင်း / ချုပ်ဆိုခြင်း",
     flashcard: {
       question: "結 (けつ) means?",
       correct_answer: "ချည်နှောင်ခြင်း",
       false_answers: ["ဖြေလွှတ်ခြင်း", "စတင်ခြင်း"],
     },
   },
   {
     id: 12,
     kanji: "派",
     onyomi: "ハ",
     kunyomi: "-",
     type: "Noun/Suffix",
     myanmar: "ဂိုဏ်း / အုပ်စု / အဖွဲ့အနွယ်",
     flashcard: {
       question: "派 (は) means?",
       correct_answer: "ဂိုဏ်း/အုပ်စု",
       false_answers: ["တစ်ဦးတည်း", "လမ်း"],
     },
   },
   {
     id: 13,
     kanji: "府",
     onyomi: "フ",
     kunyomi: "-",
     type: "Noun",
     myanmar: "အစိုးရရုံးစိုက်ရာမြို့ပြစီရင်စု (ဥပမာ-Osaka-fu)",
     flashcard: {
       question: "府 (ふ) refers to?",
       correct_answer: "မြို့ပြစီရင်စု",
       false_answers: ["ရွာငယ်", "တောင်တန်း"],
     },
   },
   {
     id: 14,
     kanji: "査",
     onyomi: "サ",
     kunyomi: "-",
     type: "Noun/Suffix",
     myanmar: "စစ်ဆေးခြင်း / စုံစမ်းခြင်း",
     flashcard: {
       question: "査 (さ) means?",
       correct_answer: "စစ်ဆေးခြင်း",
       false_answers: ["ကစားခြင်း", "အိပ်ခြင်း"],
     },
   },
   {
     id: 15,
     kanji: "委",
     onyomi: "イ",
     kunyomi: "ゆだ(ねる)",
     type: "Verb/Noun",
     myanmar: "အပ်နှံခြင်း / ကော်မတီ",
     flashcard: {
       question: "委 (い) means?",
       correct_answer: "အပ်နှံခြင်း/ကော်မတီ",
       false_answers: ["ငြင်းပယ်ခြင်း", "ခိုးယူခြင်း"],
     },
   },
   {
     id: 16,
     kanji: "軍",
     onyomi: "グン",
     kunyomi: "-",
     type: "Noun",
     myanmar: "စစ်တပ် / တပ်မတော်",
     flashcard: {
       question: "軍 (ぐん) means?",
       correct_answer: "စစ်တပ်",
       false_answers: ["ဆေးရုံ", "ဈေး"],
     },
   },
   {
     id: 17,
     kanji: "案",
     onyomi: "アン",
     kunyomi: "-",
     type: "Noun",
     myanmar: "အစီအစဉ် / အကြံပြုချက် / မူကြမ်း",
     flashcard: {
       question: "案 (あん) means?",
       correct_answer: "အစီအစဉ်/မူကြမ်း",
       false_answers: ["ရလဒ်", "အတိတ်"],
     },
   },
   {
     id: 18,
     kanji: "策",
     onyomi: "サク",
     kunyomi: "-",
     type: "Noun",
     myanmar: "ပေါ်လစီ / နည်းဗျူဟာ / အစီအမံ",
     flashcard: {
       question: "策 (さく) means?",
       correct_answer: "နည်းဗျူဟာ",
       false_answers: ["အမှား", "အနားယူခြင်း"],
     },
   },
   {
     id: 19,
     kanji: "団",
     onyomi: "ダン",
     kunyomi: "-",
     type: "Noun/Suffix",
     myanmar: "အဖွဲ့ / အသင်းအဖွဲ့",
     flashcard: {
       question: "団 (だん) means?",
       correct_answer: "အဖွဲ့အစည်း",
       false_answers: ["တစ်ဦးချင်း", "အဆောက်အအုံ"],
     },
   },
   {
     id: 20,
     kanji: "各",
     onyomi: "カク",
     kunyomi: "おのおの",
     type: "Adverb/Prefix",
     myanmar: "တစ်ခုချင်းစီ / အသီးသီး",
     flashcard: {
       question: "各 (かく) means?",
       correct_answer: "တစ်ခုချင်းစီ",
       false_answers: ["အားလုံးပေါင်း", "ဘယ်သူမှမရှိ"],
     },
   },
   {
     id: 21,
     kanji: "島",
     onyomi: "トウ",
     kunyomi: "しま",
     type: "Noun",
     myanmar: "ကျွန်း",
     flashcard: {
       question: "島 (しま) means?",
       correct_answer: "ကျွန်း",
       false_answers: ["တောင်", "မြစ်"],
     },
   },
   {
     id: 22,
     kanji: "革",
     onyomi: "カク",
     kunyomi: "かわ",
     type: "Noun/Verb",
     myanmar: "သားရေ / ပြုပြင်ပြောင်းလဲခြင်း",
     flashcard: {
       question: "革 (かわ) means?",
       correct_answer: "သားရေ",
       false_answers: ["စက္ကူ", "သံ"],
     },
   },
   {
     id: 23,
     kanji: "村",
     onyomi: "ソン",
     kunyomi: "むら",
     type: "Noun",
     myanmar: "ကျေးရွာ",
     flashcard: {
       question: "村 (むら) means?",
       correct_answer: "ကျေးရွာ",
       false_answers: ["မြို့ကြီး", "တိုက်ခန်း"],
     },
   },
   {
     id: 24,
     kanji: "勢",
     onyomi: "セイ",
     kunyomi: "いきお(い)",
     type: "Noun",
     myanmar: "အရှိန်အဟုန် / အင်အားစု",
     flashcard: {
       question: "勢 (いきおい) means?",
       correct_answer: "အရှိန်အဟုန်/အင်အား",
       false_answers: ["အားနည်းချက်", "အိပ်စက်ခြင်း"],
     },
   },
   {
     id: 25,
     kanji: "減",
     onyomi: "ゲン",
     kunyomi: "へ(る)",
     type: "Verb",
     myanmar: "လျော့နည်းသွားသည် / လျှော့ချသည်",
     flashcard: {
       question: "減 (げん) means?",
       correct_answer: "လျော့နည်းခြင်း",
       false_answers: ["တိုးပွားခြင်း", "တန့်နေခြင်း"],
     },
   },
   {
     id: 26,
     kanji: "再",
     onyomi: "サイ",
     kunyomi: "ふたた(び)",
     type: "Prefix/Adverb",
     myanmar: "ထပ်မံ၍ / ဒုတိယအကြိမ်",
     flashcard: {
       question: "再 (さい) means?",
       correct_answer: "ထပ်မံ၍",
       false_answers: ["ပထမဆုံး", "နောက်ဆုံး"],
     },
   },
   {
     id: 27,
     kanji: "税",
     onyomi: "ゼイ",
     kunyomi: "-",
     type: "Noun",
     myanmar: "အခွန်",
     flashcard: {
       question: "税 (ぜい) means?",
       correct_answer: "အခွန်",
       false_answers: ["လစာ", "လက်ဆောင်"],
     },
   },
   {
     id: 28,
     kanji: "営",
     onyomi: "エイ",
     kunyomi: "いとな(む)",
     type: "Verb/Noun",
     myanmar: "စီမံခန့်ခွဲခြင်း / လုပ်ကိုင်ခြင်း (စီးပွားရေး)",
     flashcard: {
       question: "営 (えい) means?",
       correct_answer: "စီမံခန့်ခွဲခြင်း",
       false_answers: ["အနားယူခြင်း", "ကစားခြင်း"],
     },
   },
   {
     id: 29,
     kanji: "比",
     onyomi: "ヒ",
     kunyomi: "くら(べる)",
     type: "Verb/Noun",
     myanmar: "နှိုင်းယှဉ်ခြင်း / အချိုးအစား",
     flashcard: {
       question: "比 (くらべる) means?",
       correct_answer: "နှိုင်းယှဉ်ခြင်း",
       false_answers: ["ပေါင်းစပ်ခြင်း", "ခွဲခြားခြင်း"],
     },
   },
   {
     id: 30,
     kanji: "防",
     onyomi: "ボウ",
     kunyomi: "ふせ(ぐ)",
     type: "Verb/Noun",
     myanmar: "ကာကွယ်ခြင်း / တားဆီးခြင်း",
     flashcard: {
       question: "防 (ふせぐ) means?",
       correct_answer: "ကာကွယ်ခြင်း",
       false_answers: ["တိုက်ခိုက်ခြင်း", "ဖွင့်ပေးခြင်း"],
     },
   },
   {
     id: 31,
     kanji: "補",
     onyomi: "ホ",
     kunyomi: "おぎな(う)",
     type: "Verb/Noun",
     myanmar: "ဖြည့်စွက်ခြင်း / အစားထိုးခြင်း",
     flashcard: {
       question: "補 (おぎなう) means?",
       correct_answer: "ဖြည့်စွက်ခြင်း",
       false_answers: ["ဖယ်ထုတ်ခြင်း", "လျှော့ချခြင်း"],
     },
   },
   {
     id: 32,
     kanji: "境",
     onyomi: "キョウ",
     kunyomi: "さかい",
     type: "Noun",
     myanmar: "နယ်နိမိတ် / အနားသတ်",
     flashcard: {
       question: "境 (さかい) means?",
       correct_answer: "နယ်နိမိတ်",
       false_answers: ["ဗဟို", "လမ်းမ"],
     },
   },
   {
     id: 33,
     kanji: "導",
     onyomi: "ドウ",
     kunyomi: "みちび(く)",
     type: "Verb/Noun",
     myanmar: "လမ်းညွှန်ပြသခြင်း / ဦးဆောင်ခြင်း",
     flashcard: {
       question: "導 (みちびく) means?",
       correct_answer: "လမ်းညွှန်ခြင်း",
       false_answers: ["နောက်လိုက်ခြင်း", "မျက်စိလည်ခြင်း"],
     },
   },
   {
     id: 34,
     kanji: "副",
     onyomi: "フク",
     kunyomi: "-",
     type: "Prefix",
     myanmar: "ဒုတိယ / လက်ထောက်",
     flashcard: {
       question: "副 (ふく) means?",
       correct_answer: "ဒုတိယ/လက်ထောက်",
       false_answers: ["အကြီးဆုံး", "တစ်ခုတည်းသော"],
     },
   },
   {
     id: 35,
     kanji: "算",
     onyomi: "サン",
     kunyomi: "-",
     type: "Noun/Verb",
     myanmar: "တွက်ချက်ခြင်း / အရေအတွက်",
     flashcard: {
       question: "算 (さん) means?",
       correct_answer: "တွက်ချက်ခြင်း",
       false_answers: ["စာဖတ်ခြင်း", "သီချင်းဆိုခြင်း"],
     },
   },
   {
     id: 36,
     kanji: "輸",
     onyomi: "ユ",
     kunyomi: "-",
     type: "Noun/Verb",
     myanmar: "တင်ပို့ခြင်း / သယ်ယူပို့ဆောင်ခြင်း",
     flashcard: {
       question: "輸 (ゆ) is used for?",
       correct_answer: "သယ်ယူပို့ဆောင်ရေး",
       false_answers: ["စိုက်ပျိုးရေး", "ချက်ပြုတ်ရေး"],
     },
   },
   {
     id: 37,
     kanji: "述",
     onyomi: "ジュツ",
     kunyomi: "の(べる)",
     type: "Verb",
     myanmar: "ပြောကြားသည် / ဖော်ပြသည်",
     flashcard: {
       question: "述 (のべる) means?",
       correct_answer: "ပြောကြားသည်",
       false_answers: ["နားထောင်သည်", "ကြည့်သည်"],
     },
   },
   {
     id: 38,
     kanji: "線",
     onyomi: "セン",
     kunyomi: "-",
     type: "Noun",
     myanmar: "မျဉ်းကြောင်း / ရထားလမ်းကြောင်း",
     flashcard: {
       question: "線 (せん) means?",
       correct_answer: "မျဉ်းကြောင်း",
       false_answers: ["အဝိုင်း", "အမှတ်"],
     },
   },
   {
     id: 39,
     kanji: "農",
     onyomi: "ノウ",
     kunyomi: "-",
     type: "Noun",
     myanmar: "စိုက်ပျိုးရေး / လယ်ယာ",
     flashcard: {
       question: "農 (のう) means?",
       correct_answer: "စိုက်ပျိုးရေး",
       false_answers: ["စက်မှု", "စီးပွားရေး"],
     },
   },
   {
     id: 40,
     kanji: "州",
     onyomi: "シュウ",
     kunyomi: "-",
     type: "Noun",
     myanmar: "ပြည်နယ်",
     flashcard: {
       question: "州 (しゅう) means?",
       correct_answer: "ပြည်နယ်",
       false_answers: ["မြို့", "ရွာ"],
     },
   },
   {
     id: 41,
     kanji: "武",
     onyomi: "ブ",
     kunyomi: "-",
     type: "Noun",
     myanmar: "စစ်သည်တော် / လက်နက်ကိုင်",
     flashcard: {
       question: "武 (ぶ) means?",
       correct_answer: "စစ်သည်တော်/လက်နက်",
       false_answers: ["ပညာရှိ", "ကုန်သည်"],
     },
   },
   {
     id: 42,
     kanji: "象",
     onyomi: "ゾウ",
     kunyomi: "-",
     type: "Noun",
     myanmar: "ဆင် / ပုံရိပ်",
     flashcard: {
       question: "象 (ぞう) means?",
       correct_answer: "ဆင်",
       false_answers: ["ကျား", "ခြင်္သေ့"],
     },
   },
   {
     id: 43,
     kanji: "域",
     onyomi: "イキ",
     kunyomi: "-",
     type: "Noun/Suffix",
     myanmar: "ဧရိယာ / နယ်ပယ်",
     flashcard: {
       question: "域 (いき) means?",
       correct_answer: "ဧရိယာ",
       false_answers: ["အချိန်", "အကွာအဝေး"],
     },
   },
   {
     id: 44,
     kanji: "額",
     onyomi: "ガク",
     kunyomi: "ひたい",
     type: "Noun",
     myanmar: "နဖူး / ပမာဏစုစုပေါင်း",
     flashcard: {
       question: "額 (がく) can mean?",
       correct_answer: "ပမာဏ/နဖူး",
       false_answers: ["ခြေထောက်", "လက်"],
     },
   },
   {
     id: 45,
     kanji: "欧",
     onyomi: "オウ",
     kunyomi: "-",
     type: "Noun",
     myanmar: "ဥရောပ",
     flashcard: {
       question: "欧 (おう) refers to?",
       correct_answer: "ဥရောပ",
       false_answers: ["အာရှ", "အာဖရိက"],
     },
   },
   {
     id: 46,
     kanji: "担",
     onyomi: "タン",
     kunyomi: "にな(う)",
     type: "Verb/Noun",
     myanmar: "တာဝန်ယူခြင်း / ထမ်းဆောင်ခြင်း",
     flashcard: {
       question: "担 (たん) means?",
       correct_answer: "တာဝန်ယူခြင်း",
       false_answers: ["အပျော်လုပ်ခြင်း", "စွန့်ပစ်ခြင်း"],
     },
   },
   {
     id: 47,
     kanji: "準",
     onyomi: "ジュン",
     kunyomi: "-",
     type: "Noun/Prefix",
     myanmar: "စံနှုန်း / ကြိုတင်ပြင်ဆင်ခြင်း / တစ်ဆင့်နိမ့်",
     flashcard: {
       question: "準 (じゅန်) is in?",
       correct_answer: "準備 (ပြင်ဆင်ခြင်း)",
       false_answers: ["練習 (လေ့ကျင့်ခြင်း)", "発表 (ထုတ်ပြန်ခြင်း)"],
     },
   },
   {
     id: 48,
     kanji: "賞",
     onyomi: "ショウ",
     kunyomi: "ほ(める)",
     type: "Noun/Verb",
     myanmar: "ဆု / ချီးမြှောက်ခြင်း",
     flashcard: {
       question: "賞 (しょう) means?",
       correct_answer: "ဆု",
       false_answers: ["ပြစ်ဒဏ်", "အလုပ်"],
     },
   },
   {
     id: 49,
     kanji: "辺",
     onyomi: "ヘン",
     kunyomi: "あた(り)",
     type: "Noun",
     myanmar: "ပတ်ဝန်းကျင် / အနီးအနား",
     flashcard: {
       question: "辺 (あたり) means?",
       correct_answer: "အနီးအနား",
       false_answers: ["အဝေးကြီး", "အလယ်ဗဟို"],
     },
   },
   {
     id: 50,
     kanji: "造",
     onyomi: "ゾウ",
     kunyomi: "つく(る)",
     type: "Verb/Noun",
     myanmar: "တည်ဆောက်ခြင်း / ပြုလုပ်ခြင်း",
     flashcard: {
       question: "造 (ぞう) means?",
       correct_answer: "ပြုလုပ်ခြင်း",
       false_answers: ["ဖျက်ဆီးခြင်း", "ဝယ်ယူခြင်း"],
     },
   },
   {
     id: 51,
     kanji: "被",
     onyomi: "ヒ",
     kunyomi: "こうむ(る)",
     type: "Verb/Prefix",
     myanmar: "ခံရခြင်း / လွှမ်းခြုံခြင်း",
     flashcard: {
       question: "被 (ひ) relates to?",
       correct_answer: "ခံရခြင်း",
       false_answers: ["ပြုလုပ်ခြင်း", "ပေးကမ်းခြင်း"],
     },
   },
   {
     id: 52,
     kanji: "技",
     onyomi: "ギ",
     kunyomi: "waza",
     type: "Noun",
     myanmar: "နည်းပညာ / ကျွမ်းကျင်မှု",
     flashcard: {
       question: "技 (わざ) means?",
       correct_answer: "ကျွမ်းကျင်မှု",
       false_answers: ["ကံကောင်းခြင်း", "ပျင်းရိခြင်း"],
     },
   },
   {
     id: 53,
     kanji: "低",
     onyomi: "テイ",
     kunyomi: "ひく(い)",
     type: "Adjective",
     myanmar: "နိမ့်သော",
     flashcard: {
       question: "低 (ひくい) means?",
       correct_answer: "နိမ့်သော",
       false_answers: ["မြင့်သော", "ဝေးသော"],
     },
   },
   {
     id: 54,
     kanji: "復",
     onyomi: "フク",
     kunyomi: "-",
     type: "Noun/Verb",
     myanmar: "ပြန်လည်ဖြစ်ပေါ်ခြင်း / နဂိုအတိုင်းဖြစ်ခြင်း",
     flashcard: {
       question: "復 (ふく) relates to?",
       correct_answer: "ပြန်လည်ဖြစ်ပေါ်ခြင်း",
       false_answers: ["အသစ်စခြင်း", "ရပ်တန့်ခြင်း"],
     },
   },
   {
     id: 55,
     kanji: "移",
     onyomi: "イ",
     kunyomi: "うつ(る)",
     type: "Verb",
     myanmar: "ရွှေ့ပြောင်းသည်",
     flashcard: {
       question: "移 (うつる) means?",
       correct_answer: "ရွှေ့ပြောင်းသည်",
       false_answers: ["ရပ်နေသည်", "ပျောက်ကွယ်သည်"],
     },
   },
   {
     id: 56,
     kanji: "個",
     onyomi: "コ",
     kunyomi: "-",
     type: "Counter",
     myanmar: "တစ်ခု (အရာဝတ္ထုရေတွက်ပုံ)",
     flashcard: {
       question: "個 (こ) is a counter for?",
       correct_answer: "အရာဝတ္ထုများ",
       false_answers: ["လူ", "တိရစ္ဆာန်"],
     },
   },
   {
     id: 57,
     kanji: "門",
     onyomi: "モン",
     kunyomi: "かど",
     type: "Noun",
     myanmar: "တံခါးမကြီး",
     flashcard: {
       question: "門 (もん) means?",
       correct_answer: "တံခါးမကြီး",
       false_answers: ["ပြတင်းပေါက်", "ခေါင်မိုး"],
     },
   },
   {
     id: 58,
     kanji: "課",
     onyomi: "カ",
     kunyomi: "-",
     type: "Noun/Suffix",
     myanmar: "ဌာန / သင်ခန်းစာ",
     flashcard: {
       question: "課 (か) can mean?",
       correct_answer: "ဌာန/သင်ခန်းစာ",
       false_answers: ["ဈေးဝယ်စင်တာ", "ပန်းခြံ"],
     },
   },
   {
     id: 59,
     kanji: "脳",
     onyomi: "ノウ",
     kunyomi: "-",
     type: "Noun",
     myanmar: "ဦးနှောက်",
     flashcard: {
       question: "脳 (のう) means?",
       correct_answer: "ဦးနှောက်",
       false_answers: ["နှလုံး", "အသည်း"],
     },
   },
   {
     id: 60,
     kanji: "極",
     onyomi: "キョク",
     kunyomi: "きわ(める)",
     type: "Noun/Verb",
     myanmar: "အစွန်း / အထွတ်အထိပ် / ဝင်ရိုးစွန်း",
     flashcard: {
       question: "極 (きょく) means?",
       correct_answer: "အစွန်း/အထွတ်အထိပ်",
       false_answers: ["အလယ်", "အစ"],
     },
   },
   {
     id: 61,
     kanji: "含",
     onyomi: "ガン",
     kunyomi: "ふく(む)",
     type: "Verb",
     myanmar: "ပါဝင်သည် / ငုံသည်",
     flashcard: {
       question: "含 (ふくむ) means?",
       correct_answer: "ပါဝင်သည်",
       false_answers: ["ဖယ်ထုတ်သည်", "ရောင်းသည်"],
     },
   },
   {
     id: 62,
     kanji: "蔵",
     onyomi: "ゾウ",
     kunyomi: "くら",
     type: "Noun",
     myanmar: "ကုန်လှောင်ရုံ",
     flashcard: {
       question: "蔵 (くら) means?",
       correct_answer: "ကုန်လှောင်ရုံ",
       false_answers: ["ဧည့်ခန်း", "မီးဖိုချောင်"],
     },
   },
   {
     id: 63,
     kanji: "量",
     onyomi: "リョウ",
     kunyomi: "はか(る)",
     type: "Noun/Verb",
     myanmar: "ပမာဏ / တိုင်းတာသည်",
     flashcard: {
       question: "量 (りょう) means?",
       correct_answer: "ပမာဏ",
       false_answers: ["အရောင်", "အသံ"],
     },
   },
   {
     id: 64,
     kanji: "型",
     onyomi: "ケイ",
     kunyomi: "かた",
     type: "Noun/Suffix",
     myanmar: "ပုံစံ / မော်ဒယ်",
     flashcard: {
       question: "型 (かた) means?",
       correct_answer: "ပုံစံ",
       false_answers: ["အမည်", "လိပ်စာ"],
     },
   },
   {
     id: 65,
     kanji: "況",
     onyomi: "キョウ",
     kunyomi: "-",
     type: "Noun",
     myanmar: "အခြေအနေ",
     flashcard: {
       question: "況 (きょう) relates to?",
       correct_answer: "အခြေအနေ (狀況)",
       false_answers: ["အစားအစာ", "အဝတ်အစား"],
     },
   },
   {
     id: 66,
     kanji: "針",
     onyomi: "シン",
     kunyomi: "はり",
     type: "Noun",
     myanmar: "အပ် / လက်တံ",
     flashcard: {
       question: "針 (はり) means?",
       correct_answer: "အပ်",
       false_answers: ["ဓား", "ကျောက်ခဲ"],
     },
   },
   {
     id: 67,
     kanji: "専",
     onyomi: "セン",
     kunyomi: "もっぱ(ら)",
     type: "Prefix",
     myanmar: "အထူးပြု / သီးသန့်",
     flashcard: {
       question: "専 (せん) is in?",
       correct_answer: "専門 (အထူးပြု)",
       false_answers: ["散歩 (လမ်းလျှောက်ခြင်း)", "料理 (ချက်ပြုတ်ခြင်း)"],
     },
   },
   {
     id: 68,
     kanji: "谷",
     onyomi: "コク",
     kunyomi: "たに",
     type: "Noun",
     myanmar: "ချိုင့်ဝှမ်း / တောင်ကြား",
     flashcard: {
       question: "谷 (たに) means?",
       correct_answer: "ချိုင့်ဝှမ်း",
       false_answers: ["တောင်ထိပ်", "ပင်လယ်"],
     },
   },
   {
     id: 69,
     kanji: "史",
     onyomi: "シ",
     kunyomi: "-",
     type: "Noun",
     myanmar: "သမိုင်း",
     flashcard: {
       question: "史 (し) means?",
       correct_answer: "သမိုင်း",
       false_answers: ["အနာဂတ်", "သိပ္ပံ"],
     },
   },
   {
     id: 70,
     kanji: "階",
     onyomi: "カイ",
     kunyomi: "-",
     type: "Noun/Counter",
     myanmar: "အထပ် (အဆောက်အအုံ)",
     flashcard: {
       question: "階 (かい) counts?",
       correct_answer: "အဆောက်အအုံအထပ်",
       false_answers: ["လူ", "စာအုပ်"],
     },
   },
   {
     id: 71,
     kanji: "管",
     onyomi: "カン",
     kunyomi: "くだ",
     type: "Noun/Verb",
     myanmar: "ပိုက်လိုင်း / စီမံအုပ်ချုပ်ခြင်း",
     flashcard: {
       question: "管 (くだ) means?",
       correct_answer: "ပိုက်လိုင်း",
       false_answers: ["တံခါး", "သစ်ပင်"],
     },
   },
   {
     id: 72,
     kanji: "兵",
     onyomi: "ヘイ",
     kunyomi: "-",
     type: "Noun",
     myanmar: "စစ်သည် / တပ်သား",
     flashcard: {
       question: "兵 (へい) means?",
       correct_answer: "စစ်သည်",
       false_answers: ["ဆရာဝန်", "ကျောင်းသား"],
     },
   },
   {
     id: 73,
     kanji: "接",
     onyomi: "セツ",
     kunyomi: "つ(ぐ)",
     type: "Verb/Noun",
     myanmar: "ထိတွေ့ခြင်း / ဆက်သွယ်ခြင်း",
     flashcard: {
       question: "接 (せつ) means?",
       correct_answer: "ထိတွေ့ခြင်း",
       false_answers: ["ခွဲခွာခြင်း", "မေ့လျော့ခြင်း"],
     },
   },
   {
     id: 74,
     kanji: "細",
     onyomi: "サイ",
     kunyomi: "ほそ(i)",
     type: "Adjective",
     myanmar: "သေးသွယ်သော / အသေးစိတ်သော",
     flashcard: {
       question: "細 (ほそい) means?",
       correct_answer: "သေးသွယ်သော",
       false_answers: ["ထူသော", "ကြီးသော"],
     },
   },
   {
     id: 75,
     kanji: "効",
     onyomi: "コウ",
     kunyomi: "き(く)",
     type: "Verb/Noun",
     myanmar: "အာနိသင်ရှိသည် / ထိရောက်သည်",
     flashcard: {
       question: "効 (きく) means?",
       correct_answer: "အာနိသင်ရှိသည်",
       false_answers: ["ပျက်စီးသည်", "အိပ်သည်"],
     },
   },
   {
     id: 76,
     kanji: "丸",
     onyomi: "ガン",
     kunyomi: "まる",
     type: "Noun",
     myanmar: "အဝိုင်း / လုံးဝန်းသော",
     flashcard: {
       question: "丸 (まる) means?",
       correct_answer: "အဝိုင်း",
       false_answers: ["စတုရန်း", "တြိဂံ"],
     },
   },
   {
     id: 77,
     kanji: "湾",
     onyomi: "ワン",
     kunyomi: "-",
     type: "Noun",
     myanmar: "ပင်လယ်ကွေ့",
     flashcard: {
       question: "湾 (わん) means?",
       correct_answer: "ပင်လယ်ကွေ့",
       false_answers: ["သဲကန္တာရ", "တောအုပ်"],
     },
   },
   {
     id: 78,
     kanji: "録",
     onyomi: "ロク",
     kunyomi: "-",
     type: "Noun/Verb",
     myanmar: "မှတ်တမ်းတင်ခြင်း",
     flashcard: {
       question: "録 (ろく) is in?",
       correct_answer: "記録 (မှတ်တမ်း)",
       false_answers: ["読書 (စာဖတ်ခြင်း)", "運動 (လေ့ကျင့်ခန်း)"],
     },
   },
   {
     id: 79,
     kanji: "省",
     onyomi: "ショウ",
     kunyomi: "はぶ(く)",
     type: "Noun/Verb",
     myanmar: "ဝန်ကြီးဌာန / ချန်လှပ်သည် / ပြန်လည်ဆင်ခြင်သည်",
     flashcard: {
       question: "省 (しょう) can mean?",
       correct_answer: "ဝန်ကြီးဌာန",
       false_answers: ["ဈေး", "ဘူတာရုံ"],
     },
   },
   {
     id: 80,
     kanji: "旧",
     onyomi: "キュウ",
     kunyomi: "ふる(い)",
     type: "Adjective/Prefix",
     myanmar: "ဟောင်းနွမ်းသော / ယခင်က",
     flashcard: {
       question: "旧 (きゅう) means?",
       correct_answer: "ယခင်/ဟောင်း",
       false_answers: ["အသစ်", "ခေတ်မီ"],
     },
   },
   {
     id: 81,
     kanji: "橋",
     onyomi: "キョウ",
     kunyomi: "はし",
     type: "Noun",
     myanmar: "တံတား",
     flashcard: {
       question: "橋 (はし) means?",
       correct_answer: "တံတား",
       false_answers: ["လှေကား", "တံခါး"],
     },
   },
   {
     id: 82,
     kanji: "岸",
     onyomi: "ガン",
     kunyomi: "きし",
     type: "Noun",
     myanmar: "ကမ်းခြေ / ကမ်းပါး",
     flashcard: {
       question: "岸 (きし) means?",
       correct_answer: "ကမ်းခြေ",
       false_answers: ["တောင်ထိပ်", "လမ်း"],
     },
   },
   {
     id: 83,
     kanji: "周",
     onyomi: "シュウ",
     kunyomi: "まわ(り)",
     type: "Noun",
     myanmar: "ပတ်လည် / အနားပတ်",
     flashcard: {
       question: "周 (まわり) means?",
       correct_answer: "ပတ်လည်",
       false_answers: ["အလယ်", "အထက်"],
     },
   },
   {
     id: 84,
     kanji: "材",
     onyomi: "ザイ",
     kunyomi: "-",
     type: "Noun",
     myanmar: "ကုန်ကြမ်း / သစ်သား / အထောက်အထား",
     flashcard: {
       question: "材 (ざい) relates to?",
       correct_answer: "ကုန်ကြမ်း/သစ်သား",
       false_answers: ["ရေ", "လေ"],
     },
   },
   {
     id: 85,
     kanji: "戸",
     onyomi: "コ",
     kunyomi: "と",
     type: "Noun",
     myanmar: "တံခါး / အိမ်ထောင်စု",
     flashcard: {
       question: "戸 (と) means?",
       correct_answer: "တံခါး",
       false_answers: ["ပြတင်းပေါက်", "ခေါင်မိုး"],
     },
   },
   {
     id: 86,
     kanji: "央",
     onyomi: "オウ",
     kunyomi: "-",
     type: "Noun",
     myanmar: "ဗဟို / အလယ်",
     flashcard: {
       question: "央 (おう) is in?",
       correct_answer: "中央 (ဗဟို)",
       false_answers: ["端 (အစွန်း)", "下 (အောက်)"],
     },
   },
   {
     id: 87,
     kanji: "券",
     onyomi: "ケン",
     kunyomi: "-",
     type: "Noun",
     myanmar: "လက်မှတ် / ကူပွန်",
     flashcard: {
       question: "券 (けん) means?",
       correct_answer: "လက်မှတ်",
       false_answers: ["စာအုပ်", "ပိုက်ဆံ"],
     },
   },
   {
     id: 88,
     kanji: "編",
     onyomi: "ヘン",
     kunyomi: "あ(む)",
     type: "Verb/Noun",
     myanmar: "ထိုးခြင်း (သိုးမွှေး) / တည်းဖြတ်ခြင်း",
     flashcard: {
       question: "編 (あむ) means?",
       correct_answer: "ထိုးခြင်း/တည်းဖြတ်ခြင်း",
       false_answers: ["ပြေးခြင်း", "ချက်ခြင်း"],
     },
   },
   {
     id: 89,
     kanji: "捜",
     onyomi: "ソウ",
     kunyomi: "さが(す)",
     type: "Verb",
     myanmar: "ရှာဖွေသည် (ပျောက်ဆုံးနေသူ/တရားခံ)",
     flashcard: {
       question: "捜 (さがす) means?",
       correct_answer: "ရှာဖွေသည်",
       false_answers: ["ဝှက်ထားသည်", "တွေ့ရှိသည်"],
     },
   },
   {
     id: 90,
     kanji: "竹",
     onyomi: "チク",
     kunyomi: "たけ",
     type: "Noun",
     myanmar: "ဝါး",
     flashcard: {
       question: "竹 (たけ) means?",
       correct_answer: "ဝါး",
       false_answers: ["သစ်ပင်", "မြက်"],
     },
   },
   {
     id: 91,
     kanji: "超",
     onyomi: "チョウ",
     kunyomi: "こ(える)",
     type: "Verb/Prefix",
     myanmar: "ကျော်လွန်သည် / အလွန်အမင်း",
     flashcard: {
       question: "超 (ちょう) means?",
       correct_answer: "ကျော်လွန်သည်",
       false_answers: ["နိမ့်ကျသည်", "တူညီသည်"],
     },
   },
   {
     id: 92,
     kanji: "並",
     onyomi: "ヘイ",
     kunyomi: "な(み)",
     type: "Verb/Adjective",
     myanmar: "တန်းစီသည် / သာမန်",
     flashcard: {
       question: "並 (なみ) means?",
       correct_answer: "တန်းစီသည်/သာမန်",
       false_answers: ["အထူး", "ဖရိုဖရဲ"],
     },
   },
   {
     id: 93,
     kanji: "療",
     onyomi: "リョウ",
     kunyomi: "-",
     type: "Noun",
     myanmar: "ကုသမှု",
     flashcard: {
       question: "療 (りょう) is in?",
       correct_answer: "治療 (ကုသမှု)",
       false_answers: ["勉強 (စာသင်ခြင်း)", "旅行 (ခရီးသွားခြင်း)"],
     },
   },
   {
     id: 94,
     kanji: "採",
     onyomi: "サイ",
     kunyomi: "と(る)",
     type: "Verb",
     myanmar: "ကောက်ယူသည် / ခေါ်ယူသည် (အလုပ်)",
     flashcard: {
       question: "採 (とる) means?",
       correct_answer: "ကောက်ယူသည်",
       false_answers: ["ပစ်ချသည်", "ဝှက်သည်"],
     },
   },
   {
     id: 95,
     kanji: "森",
     onyomi: "シン",
     kunyomi: "もり",
     type: "Noun",
     myanmar: "တောအုပ်",
     flashcard: {
       question: "森 (もり) means?",
       correct_answer: "တောအုပ်",
       false_answers: ["ပန်းခြံ", "လယ်ကွင်း"],
     },
   },
   {
     id: 96,
     kanji: "競",
     onyomi: "キョウ",
     kunyomi: "きそ(う)",
     type: "Verb",
     myanmar: "ယှဉ်ပြိုင်သည်",
     flashcard: {
       question: "競 (きそう) means?",
       correct_answer: "ယှဉ်ပြိုင်သည်",
       false_answers: ["ပူးပေါင်းသည်", "ရှုံးနိမ့်သည်"],
     },
   },
   {
     id: 97,
     kanji: "介",
     onyomi: "カイ",
     kunyomi: "-",
     type: "Noun/Verb",
     myanmar: "ကြားဝင်ဆောင်ရွက်ခြင်း / မိတ်ဆက်ခြင်း",
     flashcard: {
       question: "介 (かい) is in?",
       correct_answer: "紹介 (မိတ်ဆက်ခြင်း)",
       false_answers: ["介入 (ကြားဖြတ်ခြင်း)", "အထက်ပါနှစ်ခုလုံး"],
     },
   },
   {
     id: 98,
     kanji: "根",
     onyomi: "コン",
     kunyomi: "ね",
     type: "Noun",
     myanmar: "အမြစ်",
     flashcard: {
       question: "根 (ね) means?",
       correct_answer: "အမြစ်",
       false_answers: ["သစ်ကိုင်း", "သစ်ရွက်"],
     },
   },
   {
     id: 99,
     kanji: "販",
     onyomi: "ハン",
     kunyomi: "-",
     type: "Noun/Verb",
     myanmar: "ရောင်းချခြင်း",
     flashcard: {
       question: "販 (はん) is in?",
       correct_answer: "販売 (ရောင်းချခြင်း)",
       false_answers: ["購入 (ဝယ်ယူခြင်း)", "貸出 (ငှားရမ်းခြင်း)"],
     },
   },
   {
     id: 100,
     kanji: "歴",
     onyomi: "レキ",
     kunyomi: "-",
     type: "Noun/Suffix",
     myanmar: "ဖြတ်သန်းမှုမှတ်တမ်း / သမိုင်းအစဉ်အလာ",
     flashcard: {
       question: "歴 (れき) relates to?",
       correct_answer: "ဖြတ်သန်းမှုမှတ်တမ်း",
       false_answers: ["အနာဂတ်အစီအစဉ်", "လက်ရှိအခြေအနေ"],
     },
   }
 ];