const datas = [
  {
    id: 1,
    chinese: "阿姨",
    pinyin: "āyí",
    myanmar: "ဒေါ်ဒေါ်/အဒေါ်",
    options: {
      correct: "ဒေါ်ဒေါ်/အဒေါ်",
      wrong: ["သူငယ်ချင်း", "ညီမလေး", "ဆရာမ"],
    },
  },
  {
    id: 2,
    chinese: "啊",
    pinyin: "a",
    myanmar: "အာ (အာမေဍိတ်)",
    options: {
      correct: "အာ (အာမေဍိတ်)",
      wrong: ["သွားပါ", "စားပါ", "ဟုတ်ကဲ့"],
    },
  },
  {
    id: 3,
    chinese: "矮",
    pinyin: "ǎi",
    myanmar: "ပုသော",
    options: {
      correct: "ပုသော",
      wrong: ["ရှည်သော", "ဝသော", "လှသော"],
    },
  },
  {
    id: 4,
    chinese: "爱好",
    pinyin: "àihào",
    myanmar: "ဝါသနာ",
    options: {
      correct: "ဝါသနာ",
      wrong: ["အလုပ်", "ကျောင်း", "အစားအစာ"],
    },
  },
  {
    id: 5,
    chinese: "安静",
    pinyin: "ānjìng",
    myanmar: "တိတ်ဆိတ်သော",
    options: {
      correct: "တိတ်ဆိတ်သော",
      wrong: ["ဆူညံသော", "ပျော်စရာကောင်းသော", "မြန်သော"],
    },
  },
  {
    id: 6,
    chinese: "把",
    pinyin: "bǎ",
    myanmar: "ကို (ကိုင်တွယ်မှုပြ)",
    options: {
      correct: "ကို (ကိုင်တွယ်မှုပြ)",
      wrong: ["မှ", "သို့", "တွင်"],
    },
  },
  {
    id: 7,
    chinese: "班",
    pinyin: "bān",
    myanmar: "အတန်း/အလုပ်ဆင်းချိန်",
    options: {
      correct: "အတန်း/အလုပ်ဆင်းချိန်",
      wrong: ["ဈေးဝယ်ခြင်း", "ခရီးသွားခြင်း", "ဂိမ်းကစားခြင်း"],
    },
  },
  {
    id: 8,
    chinese: "搬",
    pinyin: "bān",
    myanmar: "ရွှေ့သည်/သယ်သည်",
    options: {
      correct: "ရွှေ့သည်/သယ်သည်",
      wrong: ["ထိုင်သည်", "အိပ်သည်", "ခုန်သည်"],
    },
  },
  {
    id: 9,
    chinese: "半",
    pinyin: "bàn",
    myanmar: "တစ်ဝက်",
    options: {
      correct: "တစ်ဝက်",
      wrong: ["အားလုံး", "အနည်းငယ်", "အများကြီး"],
    },
  },
  {
    id: 10,
    chinese: "办法",
    pinyin: "bànfǎ",
    myanmar: "နည်းလမ်း",
    options: {
      correct: "နည်းလမ်း",
      wrong: ["ပြဿနာ", "အဖြေ", "မေးခွန်း"],
    },
  },
  {
    id: 11,
    chinese: "办公室",
    pinyin: "bàngōngshì",
    myanmar: "ရုံးခန်း",
    options: {
      correct: "ရုံးခန်း",
      wrong: ["စာကြည့်တိုက်", "ရေချိုးခန်း", "အိပ်ခန်း"],
    },
  },
  {
    id: 12,
    chinese: "帮忙",
    pinyin: "bāngmáng",
    myanmar: "ကူညီသည်",
    options: {
      correct: "ကူညီသည်",
      wrong: ["နှောင့်ယှက်သည်", "ကြည့်သည်", "ပြောသည်"],
    },
  },
  {
    id: 13,
    chinese: "包",
    pinyin: "bāo",
    myanmar: "အိတ်/အထုပ်",
    options: {
      correct: "အိတ်/အထုပ်",
      wrong: ["ဖိနပ်", "ဦးထုပ်", "အင်္ကျီ"],
    },
  },
  {
    id: 14,
    chinese: "饱",
    pinyin: "bǎo",
    myanmar: "ဗိုက်ဝသော",
    options: {
      correct: "ဗိုက်ဝသော",
      wrong: ["ဗိုက်ဆာသော", "ရေငတ်သော", "ပင်ပန်းသော"],
    },
  },
  {
    id: 15,
    chinese: "北方",
    pinyin: "běifāng",
    myanmar: "မြောက်ဘက်",
    options: {
      correct: "မြောက်ဘက်",
      wrong: ["တောင်ဘက်", "အရှေ့ဘက်", "အနောက်ဘက်"],
    },
  },
  {
    id: 16,
    chinese: "被",
    pinyin: "bèi",
    myanmar: "ခြင်းခံရသည်",
    options: {
      correct: "ခြင်းခံရသည်",
      wrong: ["လုပ်သည်", "သွားသည်", "ပေးသည်"],
    },
  },
  {
    id: 17,
    chinese: "鼻子",
    pinyin: "bízi",
    myanmar: "နှာခေါင်း",
    options: {
      correct: "နှာခေါင်း",
      wrong: ["မျက်စိ", "နားရွက်", "ပါးစပ်"],
    },
  },
  {
    id: 18,
    chinese: "比较",
    pinyin: "bǐjiào",
    myanmar: "နှိုင်းယှဉ်သည်/အတော်အတန်",
    options: {
      correct: "နှိုင်းယှဉ်သည်/အတော်အတန်",
      wrong: ["အတူတူ", "အမြဲတမ်း", "မတူညီသော"],
    },
  },
  {
    id: 19,
    chinese: "比赛",
    pinyin: "bǐsài",
    myanmar: "ပြိုင်ပွဲ",
    options: {
      correct: "ပြိုင်ပွဲ",
      wrong: ["လေ့ကျင့်ခန်း", "အစည်းအဝေး", "စာသင်ခြင်း"],
    },
  },
  {
    id: 20,
    chinese: "笔记本",
    pinyin: "bǐjìběn",
    myanmar: "မှတ်စုစာအုပ်",
    options: {
      correct: "မှတ်စုစာအုပ်",
      wrong: ["မဂ္ဂဇင်း", "သတင်းစာ", "ပုံပြင်စာအုပ်"],
    },
  },
  {
    id: 21,
    chinese: "必须",
    pinyin: "bìxū",
    myanmar: "မဖြစ်မနေ/ရမည်",
    options: {
      correct: "မဖြစ်မနေ/ရမည်",
      wrong: ["ဖြစ်နိုင်သည်", "မလုပ်ပါ", "တစ်ခါတစ်ရံ"],
    },
  },
  {
    id: 22,
    chinese: "变化",
    pinyin: "biànhuà",
    myanmar: "ပြောင်းလဲမှု",
    options: {
      correct: "ပြောင်းလဲမှု",
      wrong: ["တည်ငြိမ်မှု", "အစ", "အဆုံး"],
    },
  },
  {
    id: 23,
    chinese: "别人",
    pinyin: "biéren",
    myanmar: "အခြားသူ",
    options: {
      correct: "အခြားသူ",
      wrong: ["မိမိကိုယ်တိုင်", "သူငယ်ချင်း", "မိသားစု"],
    },
  },
  {
    id: 24,
    chinese: "冰箱",
    pinyin: "bīngxiāng",
    myanmar: "ရေခဲသေတ္တာ",
    options: {
      correct: "ရေခဲသေတ္တာ",
      wrong: ["တီဗွီ", "အဝတ်လျှော်စက်", "မီးဖို"],
    },
  },
  {
    id: 25,
    chinese: "菜单",
    pinyin: "càidān",
    myanmar: "ဟင်းစာရင်း/မီနူး",
    options: {
      correct: "ဟင်းစာရင်း/မီနူး",
      wrong: ["ငွေတောင်းခံလွှာ", "မြေပုံ", "လက်မှတ်"],
    },
  },
  {
    id: 26,
    chinese: "参加",
    pinyin: "cānjiā",
    myanmar: "ပါဝင်ဆင်နွှဲသည်",
    options: {
      correct: "ပါဝင်ဆင်နွှဲသည်",
      wrong: ["ထွက်ခွာသည်", "ရပ်နားသည်", "ကြည့်ရှုသည်"],
    },
  },
  {
    id: 27,
    chinese: "草",
    pinyin: "cǎo",
    myanmar: "မြက်",
    options: {
      correct: "မြက်",
      wrong: ["သစ်ပင်", "ပန်း", "အရွက်"],
    },
  },
  {
    id: 28,
    chinese: "层",
    pinyin: "céng",
    myanmar: "အလွှာ/အထပ်",
    options: {
      correct: "အလွှာ/အထပ်",
      wrong: ["အခန်း", "တံခါး", "ပြတင်းပေါက်"],
    },
  },
  {
    id: 29,
    chinese: "差",
    pinyin: "chà",
    myanmar: "ညံ့သော/ကွာခြားသော",
    options: {
      correct: "ညံ့သော/ကွာခြားသော",
      wrong: ["ကောင်းသော", "တော်သော", "လှသော"],
    },
  },
  {
    id: 30,
    chinese: "超市",
    pinyin: "chāoshì",
    myanmar: "စူပါမားကတ်",
    options: {
      correct: "စူပါမားကတ်",
      wrong: ["စာသင်ကျောင်း", "ဆေးရုံ", "ရဲစခန်း"],
    },
  },
  {
    id: 31,
    chinese: "衬衫",
    pinyin: "chènshān",
    myanmar: "ရှပ်အင်္ကျီ",
    options: {
      correct: "ရှပ်အင်္ကျီ",
      wrong: ["ဘောင်းဘီ", "စကတ်", "ခြေအိတ်"],
    },
  },
  {
    id: 32,
    chinese: "成绩",
    pinyin: "chéngjì",
    myanmar: "ရမှတ်/အောင်မြင်မှု",
    options: {
      correct: "ရမှတ်/အောင်မြင်မှု",
      wrong: ["စာမေးပွဲ", "ကျောင်းခေါ်ချိန်", "အားလပ်ရက်"],
    },
  },
  {
    id: 33,
    chinese: "城市",
    pinyin: "chéngshì",
    myanmar: "မြို့",
    options: {
      correct: "မြို့",
      wrong: ["ကျေးရွာ", "တောင်တန်း", "ပင်လယ်"],
    },
  },
  {
    id: 34,
    chinese: "迟到",
    pinyin: "chídào",
    myanmar: "နောက်ကျသည်",
    options: {
      correct: "နောက်ကျသည်",
      wrong: ["စောသည်", "မြန်သည်", "မှန်သည်"],
    },
  },
  {
    id: 35,
    chinese: "除了",
    pinyin: "chúle",
    myanmar: "မှလွဲ၍/အပြင်",
    options: {
      correct: "မှလွဲ၍/အပြင်",
      wrong: ["အတွင်း", "အောက်", "အပေါ်"],
    },
  },
  {
    id: 36,
    chinese: "船",
    pinyin: "chuán",
    myanmar: "သင်္ဘော/လှေ",
    options: {
      correct: "သင်္ဘော/လှေ",
      wrong: ["လေယာဉ်", "ကား", "စက်ဘီး"],
    },
  },
  {
    id: 37,
    chinese: "春",
    pinyin: "chūn",
    myanmar: "နွေဦးရာသီ",
    options: {
      correct: "နွေဦးရာသီ",
      wrong: ["နွေရာသီ", "မိုးရာသီ", "ဆောင်ရာသီ"],
    },
  },
  {
    id: 38,
    chinese: "词典",
    pinyin: "cídiǎn",
    myanmar: "အဘိဓာန်",
    options: {
      correct: "အဘိဓာန်",
      wrong: ["မှတ်စုစာအုပ်", "ပုံပြင်စာအုပ်", "လေ့ကျင့်ခန်းစာအုပ်"],
    },
  },
  {
    id: 39,
    chinese: "聪明",
    pinyin: "cōngming",
    myanmar: "ဉာဏ်ကောင်းသော/ထက်မြက်သော",
    options: {
      correct: "ဉာဏ်ကောင်းသော/ထက်မြက်သော",
      wrong: ["ပျင်းရိသော", "ထိုင်းမှိုင်းသော", "ရိုးအသော"],
    },
  },
  {
    id: 40,
    chinese: "打扫",
    pinyin: "dǎsǎo",
    myanmar: "သန့်ရှင်းရေးလုပ်သည်",
    options: {
      correct: "သန့်ရှင်းရေးလုပ်သည်",
      wrong: ["ညစ်ပတ်အောင်လုပ်သည်", "အိပ်သည်", "စားသည်"],
    },
  },
  {
    id: 41,
    chinese: "打算",
    pinyin: "dǎsuàn",
    myanmar: "စီစဉ်သည်/ရည်ရွယ်သည်",
    options: {
      correct: "စီစဉ်သည်/ရည်ရွယ်သည်",
      wrong: ["မေ့လျော့သည်", "ရပ်နားသည်", "ပြီးဆုံးသည်"],
    },
  },
  {
    id: 42,
    chinese: "带",
    pinyin: "dài",
    myanmar: "ယူဆောင်သည်/ခေါ်ဆောင်သည်",
    options: {
      correct: "ယူဆောင်သည်/ခေါ်ဆောင်သည်",
      wrong: ["ထားခဲ့သည်", "ပေးသည်", "လဲလှယ်သည်"],
    },
  },
  {
    id: 43,
    chinese: "担心",
    pinyin: "dānxīn",
    myanmar: "စိုးရိမ်သည်",
    options: {
      correct: "စိုးရိမ်သည်",
      wrong: ["ပျော်ရွှင်သည်", "စိတ်ချသည်", "စိတ်လှုပ်ရှားသည်"],
    },
  },
  {
    id: 44,
    chinese: "蛋糕",
    pinyin: "dàngāo",
    myanmar: "ကိတ်မုန့်",
    options: {
      correct: "ကိတ်မုန့်",
      wrong: ["ထမင်း", "ခေါက်ဆွဲ", "ပေါင်မုန့်"],
    },
  },
  {
    id: 45,
    chinese: "当然",
    pinyin: "dāngrán",
    myanmar: "သေချာပေါက်/ဒါပေါ့",
    options: {
      correct: "သေချာပေါက်/ဒါပေါ့",
      wrong: ["မသေချာပါ", "မဖြစ်နိုင်ပါ", "တစ်ခါတစ်ရံ"],
    },
  },
  {
    id: 46,
    chinese: "地",
    pinyin: "de",
    myanmar: "စွာ (ကြိယာဝိသေသနပြုလုပ်စကားလုံး)",
    options: {
      correct: "စွာ (ကြိယာဝိသေသနပြုလုပ်စကားလုံး)",
      wrong: ["၏", "ကို", "မှ"],
    },
  },
  {
    id: 47,
    chinese: "灯",
    pinyin: "dēng",
    myanmar: "မီးအိမ်/မီးသီး",
    options: {
      correct: "မီးအိမ်/မီးသီး",
      wrong: ["နေမင်း", "လမင်း", "ကြယ်"],
    },
  },
  {
    id: 48,
    chinese: "地方",
    pinyin: "dìfang",
    myanmar: "နေရာ",
    options: {
      correct: "နေရာ",
      wrong: ["အချိန်", "လူ", "အစားအစာ"],
    },
  },
  {
    id: 49,
    chinese: "地铁",
    pinyin: "dìtiě",
    myanmar: "မြေအောက်ရထား",
    options: {
      correct: "မြေအောက်ရထား",
      wrong: ["ဘတ်စ်ကား", "တက္ကစီ", "စက်ဘီး"],
    },
  },
  {
    id: 50,
    chinese: "地图",
    pinyin: "dìtú",
    myanmar: "မြေပုံ",
    options: {
      correct: "မြေပုံ",
      wrong: ["ဓာတ်ပုံ", "ပန်းချီကား", "မှန်"],
    },
  },
  {
    id: 51,
    chinese: "电梯",
    pinyin: "diàntī",
    myanmar: "ဓာတ်လှေကား",
    options: {
      correct: "ဓာတ်လှေကား",
      wrong: ["လှေကား", "တံခါး", "ကြမ်းပြင်"],
    },
  },
  {
    id: 52,
    chinese: "电子邮件",
    pinyin: "diànzǐyóujiàn",
    myanmar: "အီးမေးလ်",
    options: {
      correct: "အီးမေးလ်",
      wrong: ["စာအုပ်", "သတင်းစာ", "ဖုန်းနံပါတ်"],
    },
  },
  {
    id: 53,
    chinese: "东",
    pinyin: "dōng",
    myanmar: "အရှေ့ဘက်",
    options: {
      correct: "အရှေ့ဘက်",
      wrong: ["အနောက်ဘက်", "တောင်ဘက်", "မြောက်ဘက်"],
    },
  },
  {
    id: 54,
    chinese: "冬",
    pinyin: "dōng",
    myanmar: "ဆောင်းရာသီ",
    options: {
      correct: "ဆောင်းရာသီ",
      wrong: ["နွေရာသီ", "မိုးရာသီ", "နွေဦးရာသီ"],
    },
  },
  {
    id: 55,
    chinese: "动物",
    pinyin: "dòngwù",
    myanmar: "တိရစ္ဆာန်",
    options: {
      correct: "တိရစ္ဆာန်",
      wrong: ["အပင်", "လူသား", "ကျောက်ခဲ"],
    },
  },
  {
    id: 56,
    chinese: "短",
    pinyin: "duǎn",
    myanmar: "တိုသော",
    options: {
      correct: "တိုသော",
      wrong: ["ရှည်သော", "ကြီးသော", "သေးသော"],
    },
  },
  {
    id: 57,
    chinese: "段",
    pinyin: "duàn",
    myanmar: "အပိုင်း/ပိုဒ်",
    options: {
      correct: "အပိုင်း/ပိုဒ်",
      wrong: ["လုံးဝ", "အမြဲတမ်း", "စုစုပေါင်း"],
    },
  },
  {
    id: 58,
    chinese: "锻炼",
    pinyin: "duànliàn",
    myanmar: "ကိုယ်လက်လှုပ်ရှားလေ့ကျင့်ခန်းလုပ်သည်",
    options: {
      correct: "ကိုယ်လက်လှုပ်ရှားလေ့ကျင့်ခန်းလုပ်သည်",
      wrong: ["အိပ်စက်သည်", "စာဖတ်သည်", "ချက်ပြုတ်သည်"],
    },
  },
  {
    id: 59,
    chinese: "多么",
    pinyin: "duōme",
    myanmar: "ဘယ်လောက်တောင်မှ",
    options: {
      correct: "ဘယ်လောက်တောင်မှ",
      wrong: ["အနည်းငယ်", "ဘာကြောင့်", "ဘယ်လို"],
    },
  },
  {
    id: 60,
    chinese: "饿",
    pinyin: "è",
    myanmar: "ဗိုက်ဆာသော",
    options: {
      correct: "ဗိုက်ဆာသော",
      wrong: ["ဗိုက်ဝသော", "ရေငတ်သော", "အိပ်ချင်သော"],
    },
  },
  {
    id: 61,
    chinese: "不但……而且……",
    pinyin: "búdàn…érqiě…",
    myanmar: "ရုံတင်မကဘဲ……အပြင်……",
    options: {
      correct: "ရုံတင်မကဘဲ……အပြင်……",
      wrong: ["ဒါမှမဟုတ်", "ဘာလို့လဲဆိုတော့", "ဒါပေမယ့်"],
    },
  },
  {
    id: 62,
    chinese: "耳朵",
    pinyin: "ěrduo",
    myanmar: "နားရွက်",
    options: {
      correct: "နားရွက်",
      wrong: ["မျက်လုံး", "နှာခေါင်း", "လက်"],
    },
  },
  {
    id: 63,
    chinese: "发",
    pinyin: "fā",
    myanmar: "ပေးပို့သည်/ထုတ်လွှင့်သည်",
    options: {
      correct: "ပေးပို့သည်/ထုတ်လွှင့်သည်",
      wrong: ["လက်ခံသည်", "ဖတ်သည်", "စားသည်"],
    },
  },
  {
    id: 64,
    chinese: "发烧",
    pinyin: "fāshāo",
    myanmar: "ဖျားသည်",
    options: {
      correct: "ဖျားသည်",
      wrong: ["ချောင်းဆိုးသည်", "နှာစေးသည်", "ဗိုက်နာသည်"],
    },
  },
  {
    id: 65,
    chinese: "发现",
    pinyin: "fāxiàn",
    myanmar: "တွေ့ရှိသည်/သတိထားမိသည်",
    options: {
      correct: "တွေ့ရှိသည်/သတိထားမိသည်",
      wrong: ["ပျောက်ဆုံးသည်", "မေ့လျော့သည်", "ဖုံးကွယ်သည်"],
    },
  },
  {
    id: 66,
    chinese: "方便",
    pinyin: "fāngbiàn",
    myanmar: "အဆင်ပြေသော/လွယ်ကူသော",
    options: {
      correct: "အဆင်ပြေသော/လွယ်ကူသော",
      wrong: ["ခက်ခဲသော", "ဝေးလံသော", "ဈေးကြီးသော"],
    },
  },
  {
    id: 67,
    chinese: "放",
    pinyin: "fàng",
    myanmar: "ချထားသည်/လွှတ်သည်",
    options: {
      correct: "ချထားသည်/လွှတ်သည်",
      wrong: ["ယူသည်", "ကိုင်သည်", "လဲသည်"],
    },
  },
  {
    id: 68,
    chinese: "放心",
    pinyin: "fàngxīn",
    myanmar: "စိတ်ချသည်",
    options: {
      correct: "စိတ်ချသည်",
      wrong: ["စိုးရိမ်သည်", "ကြောက်သည်", "ရှက်သည်"],
    },
  },
  {
    id: 69,
    chinese: "分",
    pinyin: "fēn",
    myanmar: "မိနစ်/ခွဲဝေသည်",
    options: {
      correct: "မိနစ်/ခွဲဝေသည်",
      wrong: ["နာရီ", "နေ့", "လ"],
    },
  },
  {
    id: 70,
    chinese: "附近",
    pinyin: "fùjìn",
    myanmar: "အနီးအနား",
    options: {
      correct: "အနီးအနား",
      wrong: ["အဝေးကြီး", "အလယ်", "အတွင်း"],
    },
  },
  {
    id: 71,
    chinese: "复习",
    pinyin: "fùxí",
    myanmar: "ပြန်လည်လေ့ကျင့်သည်/စာပြန်နွှေးသည်",
    options: {
      correct: "ပြန်လည်လေ့ကျင့်သည်/စာပြန်နွှေးသည်",
      wrong: ["အသစ်သင်သည်", "ကစားသည်", "အိပ်သည်"],
    },
  },
  {
    id: 72,
    chinese: "干净",
    pinyin: "gānjìng",
    myanmar: "သန့်ရှင်းသော",
    options: {
      correct: "သန့်ရှင်းသော",
      wrong: ["ညစ်ပတ်သော", "ဟောင်းသော", "စိုစွတ်သော"],
    },
  },
  {
    id: 73,
    chinese: "感兴趣",
    pinyin: "gǎnxìngqù",
    myanmar: "စိတ်ဝင်စားသည်",
    options: {
      correct: "စိတ်ဝင်စားသည်",
      wrong: ["ပျင်းသည်", "မုန်းသည်", "ကြောက်သည်"],
    },
  },
  {
    id: 74,
    chinese: "感冒",
    pinyin: "gǎnmào",
    myanmar: "အအေးမိသည်",
    options: {
      correct: "အအေးမိသည်",
      wrong: ["ထိခိုက်နာကျင်သည်", "ဗိုက်နာသည်", "ခေါင်းကိုက်သည်"],
    },
  },
  {
    id: 75,
    chinese: "刚才",
    pinyin: "gāngcái",
    myanmar: "ခုနလေးတင်",
    options: {
      correct: "ခုနလေးတင်",
      wrong: ["နောက်မှ", "မနက်ဖြန်", "အနာဂတ်"],
    },
  },
  {
    id: 76,
    chinese: "个子",
    pinyin: "gèzi",
    myanmar: "အရပ်အမောင်း",
    options: {
      correct: "အရပ်အမောင်း",
      wrong: ["အလေးချိန်", "အသက်", "နာမည်"],
    },
  },
  {
    id: 77,
    chinese: "跟",
    pinyin: "gēn",
    myanmar: "နှင့်အတူ",
    options: {
      correct: "နှင့်အတူ",
      wrong: ["မပါဘဲ", "တစ်ယောက်တည်း", "အဝေးမှာ"],
    },
  },
  {
    id: 78,
    chinese: "根据",
    pinyin: "gēnjù",
    myanmar: "အရ/အခြေခံ၍",
    options: {
      correct: "အရ/အခြေခံ၍",
      wrong: ["ဆန့်ကျင်လျက်", "မတော်တဆ", "ဖြစ်နိုင်သည်"],
    },
  },
  {
    id: 100,
    chinese: "欢迎",
    pinyin: "huānyíng",
    myanmar: "ကြိုဆိုသည်",
    options: {
      correct: "ကြိုဆိုသည်",
      wrong: ["နှုတ်ဆက်သည်", "ထွက်သွားသည်", "ငြင်းပယ်သည်"],
    },
  },
  {
    id: 101,
    chinese: "还",
    pinyin: "huán",
    myanmar: "ပြန်ပေးသည်",
    options: {
      correct: "ပြန်ပေးသည်",
      wrong: ["ယူသည်", "ထားခဲ့သည်", "ဝယ်သည်"],
    },
  },
  {
    id: 102,
    chinese: "环境",
    pinyin: "huánjìng",
    myanmar: "ပတ်ဝန်းကျင်",
    options: {
      correct: "ပတ်ဝန်းကျင်",
      wrong: ["ရာသီဥတု", "လူဦးရေ", "စီးပွားရေး"],
    },
  },
  {
    id: 103,
    chinese: "换",
    pinyin: "huàn",
    myanmar: "လဲလှယ်သည်",
    options: {
      correct: "လဲလှယ်သည်",
      wrong: ["သိမ်းထားသည်", "ပစ်လိုက်သည်", "ပြင်ဆင်သည်"],
    },
  },
  {
    id: 104,
    chinese: "黄河",
    pinyin: "huánghé",
    myanmar: "မြစ်ဝါမြစ်",
    options: {
      correct: "မြစ်ဝါမြစ်",
      wrong: ["ဧရာဝတီမြစ်", "နိုင်းမြစ်", "ပင်လယ်နီ"],
    },
  },
  {
    id: 105,
    chinese: "回答",
    pinyin: "huídá",
    myanmar: "ဖြေကြားသည်",
    options: {
      correct: "ဖြေကြားသည်",
      wrong: ["မေးမြန်းသည်", "နားထောင်သည်", "စာဖတ်သည်"],
    },
  },
  {
    id: 106,
    chinese: "会议",
    pinyin: "huìyì",
    myanmar: "အစည်းအဝေး",
    options: {
      correct: "အစည်းအဝေး",
      wrong: ["ပွဲတော်", "အားကစားပွဲ", "ဈေးရောင်းပွဲ"],
    },
  },
  {
    id: 107,
    chinese: "或者",
    pinyin: "huòzhě",
    myanmar: "သို့မဟုတ် (အဖြေဝါကျ)",
    options: {
      correct: "သို့မဟုတ် (အဖြေဝါကျ)",
      wrong: ["ဒါပေမယ့်", "ဘာလို့လဲဆိုတော့", "ပြီးနောက်"],
    },
  },
  {
    id: 108,
    chinese: "几乎",
    pinyin: "jīhū",
    myanmar: "နီးပါး/သလောက်",
    options: {
      correct: "နီးပါး/သလောက်",
      wrong: ["လုံးဝမရှိ", "အမြဲတမ်း", "သေချာပေါက်"],
    },
  },
  {
    id: 109,
    chinese: "机会",
    pinyin: "jīhuì",
    myanmar: "အခွင့်အရေး",
    options: {
      correct: "အခွင့်အရေး",
      wrong: ["ပြဿနာ", "ကံဆိုးမှု", "အလုပ်"],
    },
  },
  {
    id: 110,
    chinese: "极",
    pinyin: "jí",
    myanmar: "အလွန်အမင်း/အဆုံးစွန်",
    options: {
      correct: "အလွန်အမင်း/အဆုံးစွန်",
      wrong: ["အနည်းငယ်", "မရှိသလောက်", "ပုံမှန်"],
    },
  },
  {
    id: 111,
    chinese: "记得",
    pinyin: "jìde",
    myanmar: "မှတ်မိသည်",
    options: {
      correct: "မှတ်မိသည်",
      wrong: ["မေ့လျော့သည်", "သိရှိသည်", "စဉ်းစားသည်"],
    },
  },
  {
    id: 112,
    chinese: "季节",
    pinyin: "jìjié",
    myanmar: "ရာသီ",
    options: {
      correct: "ရာသီ",
      wrong: ["နေ့ရက်", "အချိန်", "ရာစုနှစ်"],
    },
  },
  {
    id: 113,
    chinese: "检查",
    pinyin: "jiǎnchá",
    myanmar: "စစ်ဆေးသည်",
    options: {
      correct: "စစ်ဆေးသည်",
      wrong: ["ဖျက်ဆီးသည်", "တည်ဆောက်သည်", "လျှော့ချသည်"],
    },
  },
  {
    id: 114,
    chinese: "简单",
    pinyin: "jiǎndān",
    myanmar: "ရိုးရှင်းသော",
    options: {
      correct: "ရိုးရှင်းသော",
      wrong: ["ရှုပ်ထွေးသော", "ခက်ခဲသော", "ဈေးကြီးသော"],
    },
  },
  {
    id: 115,
    chinese: "健康",
    pinyin: "jiànkāng",
    myanmar: "ကျန်းမာသော",
    options: {
      correct: "ကျန်းမာသော",
      wrong: ["ဖျားနာသော", "ပင်ပန်းသော", "အားနည်းသော"],
    },
  },
  {
    id: 116,
    chinese: "见面",
    pinyin: "jiànmiàn",
    myanmar: "တွေ့ဆုံသည်",
    options: {
      correct: "တွေ့ဆုံသည်",
      wrong: ["နှုတ်ဆက်ခွဲခွာသည်", "ဖုန်းပြောသည်", "စာရေးသည်"],
    },
  },
  {
    id: 117,
    chinese: "讲",
    pinyin: "jiǎng",
    myanmar: "ပြောပြသည်/ဟောပြောသည်",
    options: {
      correct: "ပြောပြသည်/ဟောပြောသည်",
      wrong: ["နားထောင်သည်", "ကြည့်သည်", "ပြေးသည်"],
    },
  },
  {
    id: 118,
    chinese: "教",
    pinyin: "jiāo",
    myanmar: "သင်ကြားပေးသည်",
    options: {
      correct: "သင်ကြားပေးသည်",
      wrong: ["လေ့လာသည်", "ကစားသည်", "အလုပ်လုပ်သည်"],
    },
  },
  {
    id: 119,
    chinese: "角",
    pinyin: "jiǎo",
    myanmar: "ထောင့်/ငွေကြေးယူနစ်",
    options: {
      correct: "ထောင့်/ငွေကြေးယူနစ်",
      wrong: ["စက်ဝိုင်း", "အပေါ်ယံ", "အလယ်"],
    },
  },
  {
    id: 120,
    chinese: "脚",
    pinyin: "jiǎo",
    myanmar: "ခြေထောက်",
    options: {
      correct: "ခြေထောက်",
      wrong: ["လက်", "ခေါင်း", "ဗိုက်"],
    },
  },
  {
    id: 121,
    chinese: "接",
    pinyin: "jiē",
    myanmar: "ကြိုသည်/လက်ခံသည်",
    options: {
      correct: "ကြိုသည်/လက်ခံသည်",
      wrong: ["ပို့သည်", "လွှတ်သည်", "ပစ်သည်"],
    },
  },
  {
    id: 122,
    chinese: "街道",
    pinyin: "jiēdào",
    myanmar: "လမ်းမ",
    options: {
      correct: "လမ်းမ",
      wrong: ["တံတား", "တောင်တက်လမ်း", "အိမ်ခန်း"],
    },
  },
  {
    id: 123,
    chinese: "结婚",
    pinyin: "jiéhūn",
    myanmar: "လက်ထပ်သည်",
    options: {
      correct: "လက်ထပ်သည်",
      wrong: ["ကွာရှင်းသည်", "မွေးဖွားသည်", "ကျောင်းတက်သည်"],
    },
  },
  {
    id: 124,
    chinese: "结束",
    pinyin: "jiéshù",
    myanmar: "ပြီးဆုံးသည်",
    options: {
      correct: "ပြီးဆုံးသည်",
      wrong: ["စတင်သည်", "ဆက်လုပ်သည်", "ကြန့်ကြာသည်"],
    },
  },
  {
    id: 125,
    chinese: "节目",
    pinyin: "jiémù",
    myanmar: "အစီအစဉ်",
    options: {
      correct: "အစီအစဉ်",
      wrong: ["သတင်း", "ရုပ်ရှင်", "ကြော်ငြာ"],
    },
  },
  {
    id: 126,
    chinese: "节日",
    pinyin: "jiérì",
    myanmar: "ပွဲတော်",
    options: {
      correct: "ပွဲတော်",
      wrong: ["အလုပ်ရက်", "စာမေးပွဲရက်", "အားလပ်ရက်"],
    },
  },
  {
    id: 127,
    chinese: "解决",
    pinyin: "jiějué",
    myanmar: "ဖြေရှင်းသည်",
    options: {
      correct: "ဖြေရှင်းသည်",
      wrong: ["ရှုပ်ထွေးအောင်လုပ်သည်", "တောင်းဆိုသည်", "ငြင်းဆိုသည်"],
    },
  },
  {
    id: 128,
    chinese: "借",
    pinyin: "jiè",
    myanmar: "ငှားသည်",
    options: {
      correct: "ငှားသည်",
      wrong: ["ဝယ်သည်", "ရောင်းသည်", "ပေးကမ်းသည်"],
    },
  },
  {
    id: 129,
    chinese: "经常",
    pinyin: "jīngcháng",
    myanmar: "မကြာခဏ",
    options: {
      correct: "မကြာခဏ",
      wrong: ["တစ်ခါမှမလုပ်", "ခဲယဉ်းစွာ", "တစ်သက်လုံး"],
    },
  },
  {
    id: 130,
    chinese: "经过",
    pinyin: "jīngguò",
    myanmar: "ဖြတ်သန်းသွားသည်/ပြီးနောက်",
    options: {
      correct: "ဖြတ်သန်းသွားသည်/ပြီးနောက်",
      wrong: ["ရပ်နားသည်", "ရှေ့မှ", "မတိုင်ခင်"],
    },
  },
  {
    id: 131,
    chinese: "经理",
    pinyin: "jīnglǐ",
    myanmar: "မန်နေဂျာ",
    options: {
      correct: "မန်နေဂျာ",
      wrong: ["ဝန်ထမ်း", "ကျောင်းသား", "ဆရာဝန်"],
    },
  },
  {
    id: 132,
    chinese: "久",
    pinyin: "jiǔ",
    myanmar: "ကြာမြင့်သော",
    options: {
      correct: "ကြာမြင့်သော",
      wrong: ["မြန်ဆန်သော", "ခေတ္တခဏ", "ချက်ချင်း"],
    },
  },
  {
    id: 133,
    chinese: "旧",
    pinyin: "jiù",
    myanmar: "ဟောင်းသော",
    options: {
      correct: "ဟောင်းသော",
      wrong: ["သစ်သော", "လှသော", "ကြီးသော"],
    },
  },
  {
    id: 134,
    chinese: "句子",
    pinyin: "jùzi",
    myanmar: "ဝါကျ",
    options: {
      correct: "ဝါကျ",
      wrong: ["စကားလုံး", "အက္ခရာ", "စာမျက်နှာ"],
    },
  },
  {
    id: 135,
    chinese: "决定",
    pinyin: "juédìng",
    myanmar: "ဆုံးဖြတ်သည်",
    options: {
      correct: "ဆုံးဖြတ်သည်",
      wrong: ["တွေဝေသည်", "ငြင်းဆိုသည်", "မေ့လျော့သည်"],
    },
  },
  {
    id: 136,
    chinese: "渴",
    pinyin: "kě",
    myanmar: "ရေငတ်သော",
    options: {
      correct: "ရေငတ်သော",
      wrong: ["ဗိုက်ဆာသော", "ဗိုက်ဝသော", "အေးသော"],
    },
  },
  {
    id: 137,
    chinese: "可爱",
    pinyin: "kě'ài",
    myanmar: "ချစ်စရာကောင်းသော",
    options: {
      correct: "ချစ်စရာကောင်းသော",
      wrong: ["ကြောက်စရာကောင်းသော", "ဆိုးရွားသော", "ရုပ်ဆိုးသော"],
    },
  },
  {
    id: 138,
    chinese: "刻",
    pinyin: "kè",
    myanmar: "၁၅ မိနစ်",
    options: {
      correct: "၁၅ မိနစ်",
      wrong: ["၃၀ မိနစ်", "၆၀ မိနစ်", "၅ မိနစ်"],
    },
  },
  {
    id: 139,
    chinese: "客人",
    pinyin: "kèrén",
    myanmar: "ဧည့်သည်",
    options: {
      correct: "ဧည့်သည်",
      wrong: ["အိမ်ရှင်", "သူငယ်ချင်း", "အိမ်နီးချင်း"],
    },
  },
  {
    id: 140,
    chinese: "空调",
    pinyin: "kōngtiáo",
    myanmar: "အဲကွန်း",
    options: {
      correct: "အဲကွန်း",
      wrong: ["တီဗွီ", "ရေခဲသေတ္တာ", "ဖုန်း"],
    },
  },
  {
    id: 141,
    chinese: "口",
    pinyin: "kǒu",
    myanmar: "ပါးစပ်/အရေအတွက်ပြစကားလုံး",
    options: {
      correct: "ပါးစပ်/အရေအတွက်ပြစကားလုံး",
      wrong: ["မျက်လုံး", "နားရွက်", "နှာခေါင်း"],
    },
  },
  {
    id: 142,
    chinese: "哭",
    pinyin: "kū",
    myanmar: "ငိုသည်",
    options: {
      correct: "ငိုသည်",
      wrong: ["ရယ်သည်", "အော်သည်", "ခုန်သည်"],
    },
  },
  {
    id: 143,
    chinese: "裤子",
    pinyin: "kùzi",
    myanmar: "ဘောင်းဘီ",
    options: {
      correct: "ဘောင်းဘီ",
      wrong: ["အင်္ကျီ", "ခြေအိတ်", "ဦးထုပ်"],
    },
  },
  {
    id: 144,
    chinese: "筷子",
    pinyin: "kuàizi",
    myanmar: "တူ (ထမင်းစားသုံးသော)",
    options: {
      correct: "တူ (ထမင်းစားသုံးသော)",
      wrong: ["ဇွန်း", "ခက်ရင်း", "ပန်းကန်"],
    },
  },
  {
    id: 145,
    chinese: "蓝",
    pinyin: "lán",
    myanmar: "အပြာရောင်",
    options: {
      correct: "အပြာရောင်",
      wrong: ["အနီရောင်", "အဝါရောင်", "အစိမ်းရောင်"],
    },
  },
  {
    id: 146,
    chinese: "老",
    pinyin: "lǎo",
    myanmar: "အိုသော",
    options: {
      correct: "အိုသော",
      wrong: ["ငယ်သော", "လှသော", "သစ်သော"],
    },
  },
  {
    id: 147,
    chinese: "离开",
    pinyin: "líkāi",
    myanmar: "ထွက်ခွာသည်",
    options: {
      correct: "ထွက်ခွာသည်",
      wrong: ["ရောက်ရှိသည်", "နေထိုင်သည်", "စောင့်ဆိုင်းသည်"],
    },
  },
  {
    id: 148,
    chinese: "礼物",
    pinyin: "lǐwù",
    myanmar: "လက်ဆောင်",
    options: {
      correct: "လက်ဆောင်",
      wrong: ["အဝတ်အစား", "အစားအစာ", "စာအုပ်"],
    },
  },
  {
    id: 149,
    chinese: "历史",
    pinyin: "lìshǐ",
    myanmar: "သမိုင်း",
    options: {
      correct: "သမိုင်း",
      wrong: ["ပထဝီ", "သင်္ချာ", "သိပ္ပံ"],
    },
  },
  {
    id: 150,
    chinese: "脸",
    pinyin: "liǎn",
    myanmar: "မျက်နှာ",
    options: {
      correct: "မျက်နှာ",
      wrong: ["လက်", "ခြေထောက်", "ခါး"],
    },
  },
  {
    id: 151,
    chinese: "聊天",
    pinyin: "liáotiān",
    myanmar: "စကားစမြည်ပြောသည်",
    options: {
      correct: "စကားစမြည်ပြောသည်",
      wrong: ["အိပ်ပျော်သည်", "အလုပ်လုပ်သည်", "အားကစားလုပ်သည်"],
    },
  },
  {
    id: 152,
    chinese: "练习",
    pinyin: "liànxí",
    myanmar: "လေ့ကျင့်ခန်းလုပ်သည်",
    options: {
      correct: "လေ့ကျင့်ခန်းလုပ်သည်",
      wrong: ["အနားယူသည်", "စားသောက်သည်", "ရုပ်ရှင်ကြည့်သည်"],
    },
  },
  {
    id: 153,
    chinese: "辆",
    pinyin: "liàng",
    myanmar: "စီး (ယာဉ်များအတွက်)",
    options: {
      correct: "စီး (ယာဉ်များအတွက်)",
      wrong: ["ကောင်", "ထည်", "ခု"],
    },
  },
  {
    id: 154,
    chinese: "了解",
    pinyin: "liǎojiě",
    myanmar: "နားလည်သဘောပေါက်သည်",
    options: {
      correct: "နားလည်သဘောပေါက်သည်",
      wrong: ["မသိနားမလည်", "မေ့လျော့သည်", "ငြင်းဆိုသည်"],
    },
  },
  {
    id: 155,
    chinese: "邻居",
    pinyin: "línjū",
    myanmar: "အိမ်နီးနားချင်း",
    options: {
      correct: "အိမ်နီးနားချင်း",
      wrong: ["ဆွေမျိုး", "ရန်သူ", "သူစိမ်း"],
    },
  },
  {
    id: 156,
    chinese: "留学",
    pinyin: "liúxué",
    myanmar: "နိုင်ငံခြားသို့ကျောင်းသွားတက်သည်",
    options: {
      correct: "နိုင်ငံခြားသို့ကျောင်းသွားတက်သည်",
      wrong: ["အလုပ်ထွက်သည်", "ခရီးသွားသည်", "အိမ်ပြန်သည်"],
    },
  },
  {
    id: 157,
    chinese: "楼",
    pinyin: "lóu",
    myanmar: "အဆောက်အဦး/ထပ်",
    options: {
      correct: "အဆောက်အဦး/ထပ်",
      wrong: ["လမ်းမ", "ဥယျာဉ်", "မြေကွက်"],
    },
  },
  {
    id: 158,
    chinese: "绿",
    pinyin: "lǜ",
    myanmar: "အစိမ်းရောင်",
    options: {
      correct: "အစိမ်းရောင်",
      wrong: ["အနက်ရောင်", "အဖြူရောင်", "လိမ္မော်ရောင်"],
    },
  },
  {
    id: 159,
    chinese: "马",
    pinyin: "mǎ",
    myanmar: "မြင်း",
    options: {
      correct: "မြင်း",
      wrong: ["နွား", "ဆင်", "ခွေး"],
    },
  },
  {
    id: 160,
    chinese: "马上",
    pinyin: "mǎshàng",
    myanmar: "ချက်ချင်း",
    options: {
      correct: "ချက်ချင်း",
      wrong: ["ခဏနေမှ", "မနက်ဖြန်", "နောက်မှ"],
    },
  },
  {
    id: 161,
    chinese: "满意",
    pinyin: "mǎnyì",
    myanmar: "ကျေနပ်အားရသော",
    options: {
      correct: "ကျေနပ်အားရသော",
      wrong: ["စိတ်ပျက်သော", "ဒေါသထွက်သော", "ဝမ်းနည်းသော"],
    },
  },
  {
    id: 162,
    chinese: "帽子",
    pinyin: "màozi",
    myanmar: "ဦးထုပ်",
    options: {
      correct: "ဦးထုပ်",
      wrong: ["ဖိနပ်", "မျက်မှန်", "ခါးပတ်"],
    },
  },
  {
    id: 163,
    chinese: "米",
    pinyin: "mǐ",
    myanmar: "ဆန် (သို့) မီတာ",
    options: {
      correct: "ဆန် (သို့) မီတာ",
      wrong: ["ရေ", "ဆီ", "ဂျုံ"],
    },
  },
  {
    id: 164,
    chinese: "面包",
    pinyin: "miànbāo",
    myanmar: "ပေါင်မုန့်",
    options: {
      correct: "ပေါင်မုန့်",
      wrong: ["ကိတ်မုန့်", "သကြားလုံး", "ဟင်းသီးဟင်းရွက်"],
    },
  },
  {
    id: 165,
    chinese: "明白",
    pinyin: "míngbai",
    myanmar: "ရှင်းလင်းသော/နားလည်သော",
    options: {
      correct: "ရှင်းလင်းသော/နားလည်သော",
      wrong: ["ရှုပ်ထွေးသော", "မှားယွင်းသော", "နားမလည်သော"],
    },
  },
  {
    id: 166,
    chinese: "拿",
    pinyin: "ná",
    myanmar: "ယူဆောင်သည်/ကိုင်သည်",
    options: {
      correct: "ယူဆောင်သည်/ကိုင်သည်",
      wrong: ["ချထားသည်", "ပစ်လိုက်သည်", "ပေးသည်"],
    },
  },
  {
    id: 167,
    chinese: "奶奶",
    pinyin: "nǎinai",
    myanmar: "အဖွား (ဖခင်ဘက်)",
    options: {
      correct: "အဖွား (ဖခင်ဘက်)",
      wrong: ["အဘိုး", "အမေ", "အဒေါ်"],
    },
  },
  {
    id: 168,
    chinese: "南",
    pinyin: "nán",
    myanmar: "တောင်ဘက်",
    options: {
      correct: "တောင်ဘက်",
      wrong: ["မြောက်ဘက်", "အရှေ့ဘက်", "အနောက်ဘက်"],
    },
  },
  {
    id: 169,
    chinese: "难",
    pinyin: "nán",
    myanmar: "ခက်ခဲသော",
    options: {
      correct: "ခက်ခဲသော",
      wrong: ["လွယ်ကူသော", "ပျော်စရာကောင်းသော", "မြန်ဆန်သော"],
    },
  },
  {
    id: 170,
    chinese: "难过",
    pinyin: "nánguò",
    myanmar: "ဝမ်းနည်းသော",
    options: {
      correct: "ဝမ်းနည်းသော",
      wrong: ["ပျော်ရွှင်သော", "စိတ်လှုပ်ရှားသော", "စိတ်ဝင်စားသော"],
    },
  },
  {
    id: 171,
    chinese: "年级",
    pinyin: "niánjí",
    myanmar: "အတန်း (ကျောင်း)",
    options: {
      correct: "အတန်း (ကျောင်း)",
      wrong: ["အသက်", "နှစ်", "လ"],
    },
  },
  {
    id: 172,
    chinese: "年轻",
    pinyin: "niánqīng",
    myanmar: "ငယ်ရွယ်သော",
    options: {
      correct: "ငယ်ရွယ်သော",
      wrong: ["အိုမင်းသော", "လေးလံသော", "ကြီးမားသော"],
    },
  },
  {
    id: 173,
    chinese: "鸟",
    pinyin: "niǎo",
    myanmar: "ငှက်",
    options: {
      correct: "ငှက်",
      wrong: ["ကြောင်", "ငါး", "ယုန်"],
    },
  },
  {
    id: 174,
    chinese: "努力",
    pinyin: "nǔlì",
    myanmar: "ကြိုးစားအားထုတ်သော",
    options: {
      correct: "ကြိုးစားအားထုတ်သော",
      wrong: ["ပျင်းရိသော", "လျစ်လျူရှုသော", "မေ့လျော့သော"],
    },
  },
  {
    id: 175,
    chinese: "爬山",
    pinyin: "páshān",
    myanmar: "တောင်တက်သည်",
    options: {
      correct: "တောင်တက်သည်",
      wrong: ["ရေကူးသည်", "ဘောလုံးကန်သည်", "လမ်းလျှောက်သည်"],
    },
  },
  {
    id: 176,
    chinese: "盘子",
    pinyin: "pánzi",
    myanmar: "ပန်းကန်ပြား",
    options: {
      correct: "ပန်းကန်ပြား",
      wrong: ["ဖန်ခွက်", "ပန်းကန်လုံး", "တူ"],
    },
  },
  {
    id: 177,
    chinese: "胖",
    pinyin: "pàng",
    myanmar: "ဝသော",
    options: {
      correct: "ဝသော",
      wrong: ["ပိန်သော", "ပုသော", "ရှည်သော"],
    },
  },
  {
    id: 178,
    chinese: "啤酒",
    pinyin: "píjiǔ",
    myanmar: "ဘီယာ",
    options: {
      correct: "ဘီယာ",
      wrong: ["ကော်ဖီ", "လက်ဖက်ရည်", "နွားနို့"],
    },
  },
  {
    id: 179,
    chinese: "皮鞋",
    pinyin: "píxié",
    myanmar: "သားရေဖိနပ်",
    options: {
      correct: "သားရေဖိနပ်",
      wrong: ["ခြေအိတ်", "ဦးထုပ်", "လက်အိတ်"],
    },
  },
  {
    id: 180,
    chinese: "瓶子",
    pinyin: "píngzi",
    myanmar: "ပုလင်း",
    options: {
      correct: "ပုလင်း",
      wrong: ["သေတ္တာ", "အိတ်", "စက္ကူ"],
    },
  },
  {
    id: 181,
    chinese: "其实",
    pinyin: "qíshí",
    myanmar: "တကယ်တော့",
    options: {
      correct: "တကယ်တော့",
      wrong: ["ဒါပေမယ့်", "ပြီးနောက်", "ဒါကြောင့်"],
    },
  },
  {
    id: 182,
    chinese: "其他",
    pinyin: "qítā",
    myanmar: "အခြားသော",
    options: {
      correct: "အခြားသော",
      wrong: ["မိမိ", "အားလုံး", "တူညီသော"],
    },
  },
  {
    id: 183,
    chinese: "骑",
    pinyin: "qí",
    myanmar: "စီးသည် (စက်ဘီး/မြင်း)",
    options: {
      correct: "စီးသည် (စက်ဘီး/မြင်း)",
      wrong: ["မောင်းသည်", "လျှောက်သည်", "ထိုင်သည်"],
    },
  },
  {
    id: 184,
    chinese: "奇怪",
    pinyin: "qíguài",
    myanmar: "ထူးဆန်းသော",
    options: {
      correct: "ထူးဆန်းသော",
      wrong: ["ပုံမှန်", "လှပသော", "ရိုးရှင်းသော"],
    },
  },
  {
    id: 185,
    chinese: "起来",
    pinyin: "qǐlái",
    myanmar: "ထသည်",
    options: {
      correct: "ထသည်",
      wrong: ["အိပ်သည်", "ထိုင်သည်", "လဲသည်"],
    },
  },
  {
    id: 186,
    chinese: "起飞",
    pinyin: "qǐfēi",
    myanmar: "ပျံတက်သည်",
    options: {
      correct: "ပျံတက်သည်",
      wrong: ["ဆင်းသက်သည်", "မောင်းနှင်သည်", "ရပ်နားသည်"],
    },
  },
  {
    id: 187,
    chinese: "清楚",
    pinyin: "qīngchu",
    myanmar: "ရှင်းလင်းပြတ်သားသော",
    options: {
      correct: "ရှင်းလင်းပြတ်သားသော",
      wrong: ["ဝေဝါးသော", "မှားယွင်းသော", "ခက်ခဲသော"],
    },
  },
  {
    id: 188,
    chinese: "请假",
    pinyin: "qǐngjià",
    myanmar: "ခွင့်တိုင်သည်",
    options: {
      correct: "ခွင့်တိုင်သည်",
      wrong: ["အလုပ်ဝင်သည်", "ကျောင်းတက်သည်", "အစည်းအဝေးလုပ်သည်"],
    },
  },
  {
    id: 189,
    chinese: "秋",
    pinyin: "qiū",
    myanmar: "ဆောင်းဦးရာသီ",
    options: {
      correct: "ဆောင်းဦးရာသီ",
      wrong: ["နွေဦးရာသီ", "နွေရာသီ", "ဆောင်ရာသီ"],
    },
  },
  {
    id: 190,
    chinese: "裙子",
    pinyin: "qúnzi",
    myanmar: "စကတ်",
    options: {
      correct: "စကတ်",
      wrong: ["ဘောင်းဘီ", "အင်္ကျီ", "ဖိနပ်"],
    },
  },
  {
    id: 191,
    chinese: "然后",
    pinyin: "ránhòu",
    myanmar: "ပြီးနောက်",
    options: {
      correct: "ပြီးနောက်",
      wrong: ["အရင်က", "ချက်ချင်း", "ဒါကြောင့်"],
    },
  },
  {
    id: 192,
    chinese: "热情",
    pinyin: "rèqíng",
    myanmar: "နွေးထွေးပျူငှာသော/စိတ်အားထက်သန်သော",
    options: {
      correct: "နွေးထွေးပျူငှာသော/စိတ်အားထက်သန်သော",
      wrong: ["အေးစက်သော", "ကြောက်ရွံ့သော", "ပျင်းရိသော"],
    },
  },
  {
    id: 193,
    chinese: "认为",
    pinyin: "rènwéi",
    myanmar: "ယူဆသည်/ထင်မြင်သည်",
    options: {
      correct: "ယူဆသည်/ထင်မြင်သည်",
      wrong: ["မေ့လျော့သည်", "သိရှိသည်", "ကြားသိသည်"],
    },
  },
  {
    id: 194,
    chinese: "认真",
    pinyin: "rènzhēn",
    myanmar: "အလေးအနက်ထားသော",
    options: {
      correct: "အလေးအနက်ထားသော",
      wrong: ["ပေါ့ပေါ့တန်တန်လုပ်သော", "ပျင်းရိသော", "မေ့လျော့သော"],
    },
  },
  {
    id: 195,
    chinese: "容易",
    pinyin: "róngyì",
    myanmar: "လွယ်ကူသော",
    options: {
      correct: "လွယ်ကူသော",
      wrong: ["ခက်ခဲသော", "ပင်ပန်းသော", "ဝေးလံသော"],
    },
  },
  {
    id: 196,
    chinese: "如果",
    pinyin: "rúguǒ",
    myanmar: "အကယ်၍/လျှင်",
    options: {
      correct: "အကယ်၍/လျှင်",
      wrong: ["ဘာလို့လဲဆိုတော့", "ပြီးနောက်", "ဒါပေမယ့်"],
    },
  },
  {
    id: 197,
    chinese: "伞",
    pinyin: "sǎn",
    myanmar: "ထီး",
    options: {
      correct: "ထီး",
      wrong: ["ဦးထုပ်", "အိတ်", "မျက်မှန်"],
    },
  },
  {
    id: 198,
    chinese: "上网",
    pinyin: "shàngwǎng",
    myanmar: "အင်တာနက်သုံးသည်",
    options: {
      correct: "အင်တာနက်သုံးသည်",
      wrong: ["စာဖတ်သည်", "အိပ်သည်", "အားကစားလုပ်သည်"],
    },
  },
  {
    id: 199,
    chinese: "生气",
    pinyin: "shēngqì",
    myanmar: "ဒေါသထွက်သည်",
    options: {
      correct: "ဒေါသထွက်သည်",
      wrong: ["ပျော်ရွှင်သည်", "ရယ်သည်", "အိပ်ချင်သည်"],
    },
  },
  {
    id: 200,
    chinese: "声音",
    pinyin: "shēngyīn",
    myanmar: "အသံ",
    options: {
      correct: "အသံ",
      wrong: ["အလင်း", "အရောင်", "အနံ့"],
    },
  },
  {
    id: 201,
    chinese: "试",
    pinyin: "shì",
    myanmar: "စမ်းသပ်သည်/စမ်းကြည့်သည်",
    options: {
      correct: "စမ်းသပ်သည်/စမ်းကြည့်သည်",
      wrong: ["ပြီးဆုံးသည်", "စတင်သည်", "ဝယ်သည်"],
    },
  },
  {
    id: 202,
    chinese: "世界",
    pinyin: "shìjiè",
    myanmar: "ကမ္ဘာလောက",
    options: {
      correct: "ကမ္ဘာလောက",
      wrong: ["နိုင်ငံ", "မြို့တော်", "ကျေးရွာ"],
    },
  },
  {
    id: 203,
    chinese: "瘦",
    pinyin: "shòu",
    myanmar: "ပိန်သော",
    options: {
      correct: "ပိန်သော",
      wrong: ["ဝသော", "ရှည်သော", "ကြီးသော"],
    },
  },
  {
    id: 204,
    chinese: "舒服",
    pinyin: "shūfu",
    myanmar: "နေထိုင်ကောင်းသော/သက်သောင့်သက်သာရှိသော",
    options: {
      correct: "နေထိုင်ကောင်းသော/သက်သောင့်သက်သာရှိသော",
      wrong: ["နာကျင်သော", "ပင်ပန်းသော", "စိတ်ညစ်သော"],
    },
  },
  {
    id: 205,
    chinese: "叔叔",
    pinyin: "shūshu",
    myanmar: "ဦးလေး",
    options: {
      correct: "ဦးလေး",
      wrong: ["အဖိုး", "အစ်ကို", "အဒေါ်"],
    },
  },
  {
    id: 206,
    chinese: "树",
    pinyin: "shù",
    myanmar: "သစ်ပင်",
    options: {
      correct: "သစ်ပင်",
      wrong: ["မြက်", "ပန်း", "တောင်"],
    },
  },
  {
    id: 207,
    chinese: "数学",
    pinyin: "shùxué",
    myanmar: "သင်္ချာ",
    options: {
      correct: "သင်္ချာ",
      wrong: ["သမိုင်း", "ပထဝီ", "စာပေ"],
    },
  },
  {
    id: 208,
    chinese: "刷牙",
    pinyin: "shuāyá",
    myanmar: "သွားတိုက်သည်",
    options: {
      correct: "သွားတိုက်သည်",
      wrong: ["မျက်နှာသစ်သည်", "ရေချိုးသည်", "ခေါင်းလျှော်သည်"],
    },
  },
  {
    id: 209,
    chinese: "双",
    pinyin: "shuāng",
    myanmar: "အစုံ/တစ်စုံ",
    options: {
      correct: "အစုံ/တစ်စုံ",
      wrong: ["တစ်ခု", "တစ်ကောင်", "တစ်ထည်"],
    },
  },
  {
    id: 210,
    chinese: "水平",
    pinyin: "shuǐpíng",
    myanmar: "အဆင့်/အရည်အချင်း",
    options: {
      correct: "အဆင့်/အရည်အချင်း",
      wrong: ["အမြန်နှုန်း", "အလေးချိန်", "အမြင့်"],
    },
  },
  {
    id: 211,
    chinese: "司机",
    pinyin: "sījī",
    myanmar: "ယာဉ်မောင်း",
    options: {
      correct: "ယာဉ်မောင်း",
      wrong: ["ရဲ", "ဆရာဝန်", "ကျောင်းသား"],
    },
  },
  {
    id: 212,
    chinese: "太阳",
    pinyin: "tàiyáng",
    myanmar: "နေမင်း",
    options: {
      correct: "နေမင်း",
      wrong: ["လမင်း", "ကြယ်", "မိုးတိမ်"],
    },
  },
  {
    id: 213,
    chinese: "特别",
    pinyin: "tèbié",
    myanmar: "ထူးခြားသော/အထူးသဖြင့်",
    options: {
      correct: "ထူးခြားသော/အထူးသဖြင့်",
      wrong: ["ရိုးရိုး", "အမြဲတမ်း", "ပုံမှန်"],
    },
  },
  {
    id: 214,
    chinese: "疼",
    pinyin: "téng",
    myanmar: "နာကျင်သည်",
    options: {
      correct: "နာကျင်သည်",
      wrong: ["ယားယံသည်", "အေးသည်", "နွေးသည်"],
    },
  },
  {
    id: 215,
    chinese: "提高",
    pinyin: "tígāo",
    myanmar: "မြှင့်တင်သည်/တိုးတက်စေသည်",
    options: {
      correct: "မြှင့်တင်သည်/တိုးတက်စေသည်",
      wrong: ["လျှော့ချသည်", "ဖျက်ဆီးသည်", "ရပ်တန့်သည်"],
    },
  },
  {
    id: 216,
    chinese: "体育",
    pinyin: "tǐyù",
    myanmar: "ကာယ/အားကစား",
    options: {
      correct: "ကာယ/အားကစား",
      wrong: ["ဂီတ", "ပန်းချီ", "သိပ္ပံ"],
    },
  },
  {
    id: 217,
    chinese: "甜",
    pinyin: "tián",
    myanmar: "ချိုသော",
    options: {
      correct: "ချိုသော",
      wrong: ["ခါးသော", "စပ်သော", "ငန်သော"],
    },
  },
  {
    id: 218,
    chinese: "条",
    pinyin: "tiáo",
    myanmar: "ခု/ထည် (အရှည်လိုက်အရာများအတွက်)",
    options: {
      correct: "ခု/ထည် (အရှည်လိုက်အရာများအတွက်)",
      wrong: ["ကောင်", "စုံ", "ယောက်"],
    },
  },
  {
    id: 219,
    chinese: "同事",
    pinyin: "tóngshì",
    myanmar: "လုပ်ဖော်ကိုင်ဖက်",
    options: {
      correct: "လုပ်ဖော်ကိုင်ဖက်",
      wrong: ["အတန်းဖော်", "အိမ်နီးချင်း", "ဆွေမျိုး"],
    },
  },
  {
    id: 220,
    chinese: "同意",
    pinyin: "tóngyì",
    myanmar: "သဘောတူသည်",
    options: {
      correct: "သဘောတူသည်",
      wrong: ["ငြင်းဆိုသည်", "စောင့်ဆိုင်းသည်", "တွေဝေသည်"],
    },
  },
  {
    id: 221,
    chinese: "头发",
    pinyin: "tóufa",
    myanmar: "ဆံပင်",
    options: {
      correct: "ဆံပင်",
      wrong: ["မျက်ခုံး", "လက်သည်း", "သွား"],
    },
  },
  {
    id: 222,
    chinese: "突然",
    pinyin: "tūrán",
    myanmar: "ရုတ်တရက်",
    options: {
      correct: "ရုတ်တရက်",
      wrong: ["ဖြည်းဖြည်းချင်း", "အမြဲတမ်း", "နောက်မှ"],
    },
  },
  {
    id: 223,
    chinese: "图书馆",
    pinyin: "túshūguǎn",
    myanmar: "စာကြည့်တိုက်",
    options: {
      correct: "စာကြည့်တိုက်",
      wrong: ["စာသင်ခန်း", "ရုံးခန်း", "အားကစားရုံ"],
    },
  },
  {
    id: 224,
    chinese: "腿",
    pinyin: "tuǐ",
    myanmar: "ခြေထောက် (ပေါင်မှခြေကျင်းဝတ်)",
    options: {
      correct: "ခြေထောက် (ပေါင်မှခြေကျင်းဝတ်)",
      wrong: ["လက်မောင်း", "ဗိုက်", "ကျော"],
    },
  },
  {
    id: 225,
    chinese: "完成",
    pinyin: "wánchéng",
    myanmar: "ပြီးမြောက်အောင်မြင်သည်",
    options: {
      correct: "ပြီးမြောက်အောင်မြင်သည်",
      wrong: ["စတင်သည်", "ဝတ်ဆင်သည်", "လဲလှယ်သည်"],
    },
  },
  {
    id: 226,
    chinese: "碗",
    pinyin: "wǎn",
    myanmar: "ပန်းကန်လုံး",
    options: {
      correct: "ပန်းကန်လုံး",
      wrong: ["ဇွန်း", "တူ", "ဖန်ခွက်"],
    },
  },
  {
    id: 227,
    chinese: "万",
    pinyin: "wàn",
    myanmar: "တစ်သောင်း",
    options: {
      correct: "တစ်သောင်း",
      wrong: ["တစ်ထောင်", "တစ်သိန်း", "တစ်သန်း"],
    },
  },
  {
    id: 228,
    chinese: "忘记",
    pinyin: "wàngjì",
    myanmar: "မေ့လျော့သည်",
    options: {
      correct: "မေ့လျော့သည်",
      wrong: ["မှတ်မိသည်", "စဉ်းစားသည်", "ရှာဖွေသည်"],
    },
  },
  {
    id: 229,
    chinese: "为",
    pinyin: "wèi",
    myanmar: "အတွက်",
    options: {
      correct: "အတွက်",
      wrong: ["ကြောင့်", "နှင့်", "သို့"],
    },
  },
  {
    id: 230,
    chinese: "为了",
    pinyin: "wèile",
    myanmar: "ရည်ရွယ်ချက်အတွက်/စေရန်အတွက်",
    options: {
      correct: "ရည်ရွယ်ချက်အတွက်/စေရန်အတွက်",
      wrong: ["ဒါကြောင့်", "ဒါပေမယ့်", "ဘာလို့လဲဆိုတော့"],
    },
  },
  {
    id: 231,
    chinese: "位",
    pinyin: "wèi",
    myanmar: "ပါး/ယောက် (ယဉ်ကျေးစွာသုံးနှုန်းသောအရေအတွက်ပြ)",
    options: {
      correct: "ပါး/ယောက် (ယဉ်ကျေးစွာသုံးနှုန်းသောအရေအတွက်ပြ)",
      wrong: ["ကောင်", "စီး", "ထည်"],
    },
  },
  {
    id: 232,
    chinese: "文化",
    pinyin: "wénhuà",
    myanmar: "ယဉ်ကျေးမှု",
    options: {
      correct: "ယဉ်ကျေးမှု",
      wrong: ["ပညာရေး", "နိုင်ငံရေး", "စီးပွားရေး"],
    },
  },
  {
    id: 233,
    chinese: "西",
    pinyin: "xī",
    myanmar: "အနောက်ဘက်",
    options: {
      correct: "အနောက်ဘက်",
      wrong: ["အရှေ့ဘက်", "တောင်ဘက်", "မြောက်ဘက်"],
    },
  },
  {
    id: 234,
    chinese: "习惯",
    pinyin: "xíguàn",
    myanmar: "အလေ့အကျင့်/အကျင့်ဖြစ်သည်",
    options: {
      correct: "အလေ့အကျင့်/အကျင့်ဖြစ်သည်",
      wrong: ["ဝါသနာ", "အလုပ်", "အိပ်မက်"],
    },
  },
  {
    id: 235,
    chinese: "洗手间",
    pinyin: "xǐshǒujiān",
    myanmar: "အိမ်သာ/လက်ဆေးခန်း",
    options: {
      correct: "အိမ်သာ/လက်ဆေးခန်း",
      wrong: ["ဧည့်ခန်း", "မီးဖိုချောင်", "အိပ်ခန်း"],
    },
  },
  {
    id: 236,
    chinese: "洗澡",
    pinyin: "xǐzǎo",
    myanmar: "ရေချိုးသည်",
    options: {
      correct: "ရေချိုးသည်",
      wrong: ["မျက်နှာသစ်သည်", "အဝတ်လျှော်သည်", "အိပ်စက်သည်"],
    },
  },
  {
    id: 237,
    chinese: "夏",
    pinyin: "xià",
    myanmar: "နွေရာသီ",
    options: {
      correct: "နွေရာသီ",
      wrong: ["ဆောင်ရာသီ", "မိုးရာသီ", "နွေဦးရာသီ"],
    },
  },
  {
    id: 238,
    chinese: "先",
    pinyin: "xiān",
    myanmar: "အရင်/ဦးစွာ",
    options: {
      correct: "အရင်/ဦးစွာ",
      wrong: ["နောက်မှ", "ချက်ချင်း", "မကြာခဏ"],
    },
  },
  {
    id: 239,
    chinese: "香蕉",
    pinyin: "xiāngjiāo",
    myanmar: "ငှက်ပျောသီး",
    options: {
      correct: "ငှက်ပျောသီး",
      wrong: ["ပန်းသီး", "လိမ္မော်သီး", "ဖရဲသီး"],
    },
  },
  {
    id: 240,
    chinese: "相信",
    pinyin: "xiāngxìnbelieve",
    myanmar: "ယုံကြည်သည်",
    options: {
      correct: "ယုံကြည်သည်",
      wrong: ["သံသယဖြစ်သည်", "မုန်းတီးသည်", "မေ့လျော့သည်"],
    },
  },
  {
    id: 241,
    chinese: "向",
    pinyin: "xiàng",
    myanmar: "ဘက်သို့/ဆီသို့",
    options: {
      correct: "ဘက်သို့/ဆီသို့",
      wrong: ["မှ", "ကြောင့်", "တွင်"],
    },
  },
  {
    id: 242,
    chinese: "像",
    pinyin: "xiàng",
    myanmar: "တူညီသော/ပုံစံတူသော",
    options: {
      correct: "တူညီသော/ပုံစံတူသော",
      wrong: ["ကွဲပြားသော", "ကြီးမားသော", "အသစ်ဖြစ်သော"],
    },
  },
  {
    id: 243,
    chinese: "小心",
    pinyin: "xiǎoxīn",
    myanmar: "သတိထားသည်/ဂရုစိုက်သည်",
    options: {
      correct: "သတိထားသည်/ဂရုစိုက်သည်",
      wrong: ["ပေါ့ဆသည်", "ပျင်းရိသည်", "အိပ်ငိုက်သည်"],
    },
  },
  {
    id: 244,
    chinese: "校长",
    pinyin: "xiàozhǎng",
    myanmar: "ကျောင်းအုပ်ကြီး",
    options: {
      correct: "ကျောင်းအုပ်ကြီး",
      wrong: ["ဆရာ", "ကျောင်းသား", "ဝန်ထမ်း"],
    },
  },
  {
    id: 245,
    chinese: "新闻",
    pinyin: "xīnwén",
    myanmar: "သတင်း",
    options: {
      correct: "သတင်း",
      wrong: ["ပုံပြင်", "ရုပ်ရှင်", "သီချင်း"],
    },
  },
  {
    id: 246,
    chinese: "新鲜",
    pinyin: "xīnxiān",
    myanmar: "လတ်ဆတ်သော",
    options: {
      correct: "လတ်ဆတ်သော",
      wrong: ["ပုပ်သိုးသော", "ဟောင်းနွမ်းသော", "ခြောက်သွေ့သော"],
    },
  },
  {
    id: 247,
    chinese: "信用卡",
    pinyin: "xìnyòngkǎ",
    myanmar: "ခရက်ဒစ်ကတ်",
    options: {
      correct: "ခရက်ဒစ်ကတ်",
      wrong: ["မှတ်ပုံတင်", "စာကြည့်တိုက်ကတ်", "ကျောင်းသားကတ်"],
    },
  },
  {
    id: 248,
    chinese: "行李箱",
    pinyin: "xínglixiāng",
    myanmar: "ခရီးဆောင်အိတ်",
    options: {
      correct: "ခရီးဆောင်အိတ်",
      wrong: ["စာအုပ်အိတ်", "လက်ကိုင်အိတ်", "ပိုက်ဆံအိတ်"],
    },
  },
  {
    id: 249,
    chinese: "熊猫",
    pinyin: "xióngmāo",
    myanmar: "ပန်ဒါဝက်ဝံ",
    options: {
      correct: "ပန်ဒါဝက်ဝံ",
      wrong: ["ကျား", "ခြင်္သေ့", "ဆင်"],
    },
  },
  {
    id: 250,
    chinese: "需要",
    pinyin: "xūyào",
    myanmar: "လိုအပ်သည်",
    options: {
      correct: "လိုအပ်သည်",
      wrong: ["ပိုလျှံသည်", "ပစ်လိုက်သည်", "မုန်းတီးသည်"],
    },
  },
  {
    id: 251,
    chinese: "选择",
    pinyin: "xuǎnzé",
    myanmar: "ရွေးချယ်သည်",
    options: {
      correct: "ရွေးချယ်သည်",
      wrong: ["ငြင်းဆိုသည်", "စွန့်ပစ်သည်", "သိမ်းထားသည်"],
    },
  },
  {
    id: 252,
    chinese: "要求",
    pinyin: "yāoqiú",
    myanmar: "တောင်းဆိုချက်/လိုအပ်ချက်",
    options: {
      correct: "တောင်းဆိုချက်/လိုအပ်ချက်",
      wrong: ["အဖြေ", "လက်ဆောင်", "အကြံဉာဏ်"],
    },
  },
  {
    id: 253,
    chinese: "爷爷",
    pinyin: "yéye",
    myanmar: "အဘိုး (ဖခင်ဘက်)",
    options: {
      correct: "အဘိုး (ဖခင်ဘက်)",
      wrong: ["အဖွား", "ဦးလေး", "အဖေ"],
    },
  },
  {
    id: 254,
    chinese: "一定",
    pinyin: "yídìng",
    myanmar: "သေချာပေါက်/ဧကန်အမှန်",
    options: {
      correct: "သေချာပေါက်/ဧကန်အမှန်",
      wrong: ["မသေချာပါ", "မဖြစ်နိုင်ပါ", "တစ်ခါတစ်ရံ"],
    },
  },
  {
    id: 255,
    chinese: "一共",
    pinyin: "yígòng",
    myanmar: "စုစုပေါင်း",
    options: {
      correct: "စုစုပေါင်း",
      wrong: ["တစ်စိတ်တစ်ပိုင်း", "အနည်းငယ်", "ဘာမှမရှိ"],
    },
  },
  {
    id: 256,
    chinese: "一会儿",
    pinyin: "yíhuìr",
    myanmar: "ခေတ္တခဏ/ခဏလေး",
    options: {
      correct: "ခေတ္တခဏ/ခဏလေး",
      wrong: ["တစ်နေကုန်", "တစ်သက်လုံး", "အကြာကြီး"],
    },
  },
  {
    id: 257,
    chinese: "一样",
    pinyin: "yíyàng",
    myanmar: "အတူတူပဲ/တူညီသော",
    options: {
      correct: "အတူတူပဲ/တူညီသော",
      wrong: ["မတူညီသော", "ဆန့်ကျင်ဘက်", "အသစ်ဖြစ်သော"],
    },
  },
  {
    id: 258,
    chinese: "以前",
    pinyin: "yǐqián",
    myanmar: "အရင်က/မတိုင်ခင်က",
    options: {
      correct: "အရင်က/မတိုင်ခင်က",
      wrong: ["နောက်မှ", "အခု", "နောင်တွင်"],
    },
  },
  {
    id: 259,
    chinese: "一般",
    pinyin: "yìbān",
    myanmar: "ယေဘုယျအားဖြင့်/ပုံမှန်အားဖြင့်",
    options: {
      correct: "ယေဘုယျအားဖြင့်/ပုံမှန်အားဖြင့်",
      wrong: ["ထူးထူးခြားခြား", "အလွန်အမင်း", "ရှားရှားပါးပါး"],
    },
  },
  {
    id: 260,
    chinese: "一边",
    pinyin: "yìbiān",
    myanmar: "တစ်ဖက်/တစ်ပြိုင်နက်တည်း (လုပ်ဆောင်ခြင်း)",
    options: {
      correct: "တစ်ဖက်/တစ်ပြိုင်နက်တည်း (လုပ်ဆောင်ခြင်း)",
      wrong: ["အလယ်", "နောက်ဘက်", "ပြီးဆုံးသည်"],
    },
  },
  {
    id: 261,
    chinese: "一直",
    pinyin: "yìzhí",
    myanmar: "တောက်လျှောက်/တန်းတန်းမတ်မတ်",
    options: {
      correct: "တောက်လျှောက်/တန်းတန်းမတ်မတ်",
      wrong: ["တစ်ခါတစ်ရံ", "ရပ်နားသည်", "လှည့်ပြန်သည်"],
    },
  },
  {
    id: 262,
    chinese: "音乐",
    pinyin: "yīnyuè",
    myanmar: "ဂီတ/သီချင်း",
    options: {
      correct: "ဂီတ/သီချင်း",
      wrong: ["စာပေ", "ရုပ်ရှင်", "အားကစား"],
    },
  },
  {
    id: 263,
    chinese: "银行",
    pinyin: "yínháng",
    myanmar: "ဘဏ်",
    options: {
      correct: "ဘဏ်",
      wrong: ["စာတိုက်", "ဆေးရုံ", "ကျောင်း"],
    },
  },
  {
    id: 264,
    chinese: "饮料",
    pinyin: "yǐnliào",
    myanmar: "ဖျော်ရည်/သောက်စရာ",
    options: {
      correct: "ဖျော်ရည်/သောက်စရာ",
      wrong: ["ထမင်း", "မုန့်", "အသား"],
    },
  },
  {
    id: 265,
    chinese: "应该",
    pinyin: "yīnggāi",
    myanmar: "သင့်တော်သည်/လုပ်သင့်သည်",
    options: {
      correct: "သင့်တော်သည်/လုပ်သင့်သည်",
      wrong: ["မလုပ်ရပါ", "မဖြစ်နိုင်ပါ", "ကြောက်သည်"],
    },
  },
  {
    id: 266,
    chinese: "影响",
    pinyin: "yǐngxiǎng",
    myanmar: "သက်ရောက်မှု/လွှမ်းမိုးမှု",
    options: {
      correct: "သက်ရောက်မှု/လွှမ်းမိုးမှု",
      wrong: ["ရလဒ်", "အကြောင်းပြချက်", "အစ"],
    },
  },
  {
    id: 267,
    chinese: "用",
    pinyin: "yòng",
    myanmar: "အသုံးပြုသည်",
    options: {
      correct: "အသုံးပြုသည်",
      wrong: ["ပစ်လိုက်သည်", "ရောင်းသည်", "မေ့သွားသည်"],
    },
  },
  {
    id: 268,
    chinese: "游戏",
    pinyin: "yóuxì",
    myanmar: "ဂိမ်း/ကစားနည်း",
    options: {
      correct: "ဂိမ်း/ကစားနည်း",
      wrong: ["အလုပ်", "စာသင်ခြင်း", "အိပ်စက်ခြင်း"],
    },
  },
  {
    id: 269,
    chinese: "有名",
    pinyin: "yǒumíng",
    myanmar: "နာမည်ကြီးသော/ကျော်ကြားသော",
    options: {
      correct: "နာမည်ကြီးသော/ကျော်ကြားသော",
      wrong: ["နာမည်မရှိသော", "ရုပ်ဆိုးသော", "ဆင်းရဲသော"],
    },
  },
  {
    id: 270,
    chinese: "又",
    pinyin: "yòu",
    myanmar: "ထပ်ပြီး (အတိတ်ကဖြစ်ရပ်)",
    options: {
      correct: "ထပ်ပြီး (အတိတ်ကဖြစ်ရပ်)",
      wrong: ["မကြာခင်", "အရင်က", "ဘယ်တော့မှ"],
    },
  },
  {
    id: 271,
    chinese: "遇到",
    pinyin: "yùdào",
    myanmar: "ကြုံတွေ့သည်/တွေ့ဆုံသည်",
    options: {
      correct: "ကြုံတွေ့သည်/တွေ့ဆုံသည်",
      wrong: ["လွဲချော်သည်", "မေ့လျော့သည်", "ထားခဲ့သည်"],
    },
  },
  {
    id: 272,
    chinese: "元",
    pinyin: "yuán",
    myanmar: "ယွမ် (တရုတ်ငွေကြေးယူနစ်)",
    options: {
      correct: "ယွမ် (တရုတ်ငွေကြေးယူနစ်)",
      wrong: ["ဒေါ်လာ", "ကျပ်", "ယူရို"],
    },
  },
  {
    id: 273,
    chinese: "愿意",
    pinyin: "yuànyì",
    myanmar: "ဆန္ဒရှိသည်/ကြည်ဖြူသည်",
    options: {
      correct: "ဆန္ဒရှိသည်/ကြည်ဖြူသည်",
      wrong: ["ငြင်းဆိုသည်", "မုန်းတီးသည်", "ကြောက်ရွံ့သည်"],
    },
  },
  {
    id: 274,
    chinese: "月亮",
    pinyin: "yuèliang",
    myanmar: "လမင်း",
    options: {
      correct: "လမင်း",
      wrong: ["နေမင်း", "ကြယ်", "တိမ်"],
    },
  },
  {
    id: 275,
    chinese: "越",
    pinyin: "yuè",
    myanmar: "ပို၍ (ပို... ပို...)",
    options: {
      correct: "ပို၍ (ပို... ပို...)",
      wrong: ["လျော့၍", "အတူတူ", "လျင်မြန်စွာ"],
    },
  },
  {
    id: 276,
    chinese: "站",
    pinyin: "zhàn",
    myanmar: "မှတ်တိုင်/ဘူတာ (သို့) မတ်တပ်ရပ်သည်",
    options: {
      correct: "မှတ်တိုင်/ဘူတာ (သို့) မတ်တပ်ရပ်သည်",
      wrong: ["အိမ်", "ကျောင်း", "ထိုင်သည်"],
    },
  },
  {
    id: 277,
    chinese: "张",
    pinyin: "zhāng",
    myanmar: "ချပ်/စောင် (စက္ကူကဲ့သို့အပြားများအတွက်)",
    options: {
      correct: "ချပ်/စောင် (စက္ကူကဲ့သို့အပြားများအတွက်)",
      wrong: ["ကောင်", "စီး", "ထည်"],
    },
  },
  {
    id: 278,
    chinese: "长",
    pinyin: "zhǎng",
    myanmar: "ကြီးထွားလာသည်",
    options: {
      correct: "ကြီးထွားလာသည်",
      wrong: ["သေးသွားသည်", "ပျက်စီးသည်", "လဲကျသည်"],
    },
  },
  {
    id: 279,
    chinese: "着急",
    pinyin: "zháojí",
    myanmar: "လောဆော်သည်/စိတ်ပူသည်",
    options: {
      correct: "လောဆော်သည်/စိတ်ပူသည်",
      wrong: ["အေးအေးဆေးဆေးနေသည်", "ပျော်ရွှင်သည်", "အိပ်ပျော်သည်"],
    },
  },
  {
    id: 280,
    chinese: "照顾",
    pinyin: "zhàogù",
    myanmar: "ဂရုစိုက်စောင့်ရှောက်သည်",
    options: {
      correct: "ဂရုစိုက်စောင့်ရှောက်သည်",
      wrong: ["ပစ်ထားသည်", "နှောင့်ယှက်သည်", "ခိုင်းစေသည်"],
    },
  },
  {
    id: 281,
    chinese: "照片",
    pinyin: "zhàopiàn",
    myanmar: "ဓာတ်ပုံ",
    options: {
      correct: "ဓာတ်ပုံ",
      wrong: ["ပန်းချီ", "စာအုပ်", "မှန်"],
    },
  },
  {
    id: 282,
    chinese: "照相机",
    pinyin: "zhàoxiàngjī",
    myanmar: "ကင်မရာ",
    options: {
      correct: "ကင်မရာ",
      wrong: ["တီဗွီ", "ဖုန်း", "ကွန်ပျူတာ"],
    },
  },
  {
    id: 283,
    chinese: "只",
    pinyin: "zhī",
    myanmar: "ကောင် (တိရစ္ဆာန်အရေအတွက်ပြ)",
    options: {
      correct: "ကောင် (တိရစ္ဆာန်အရေအတွက်ပြ)",
      wrong: ["ခု", "ထည်", "စီး"],
    },
  },
  {
    id: 284,
    chinese: "只",
    pinyin: "zhǐ",
    myanmar: "သာလျှင်/ပဲ",
    options: {
      correct: "သာလျှင်/ပဲ",
      wrong: ["အများကြီး", "အားလုံး", "ဘာမှမရှိ"],
    },
  },
  {
    id: 285,
    chinese: "只有……才……",
    pinyin: "zhǐyǒu…cái…",
    myanmar: "မှသာလျှင်……",
    options: {
      correct: "မှသာလျှင်……",
      wrong: ["ဒါကြောင့်", "ဒါပေမယ့်", "ပြီးနောက်"],
    },
  },
  {
    id: 286,
    chinese: "中文",
    pinyin: "zhōngwén",
    myanmar: "တရုတ်စာ/တရုတ်ဘာသာ",
    options: {
      correct: "တရုတ်စာ/တရုတ်ဘာသာ",
      wrong: ["အင်္ဂလိပ်စာ", "ဂျပန်စာ", "မြန်မာစာ"],
    },
  },
  {
    id: 287,
    chinese: "中间",
    pinyin: "zhōngjiān",
    myanmar: "အလယ်",
    options: {
      correct: "အလယ်",
      wrong: ["ဘေး", "အပေါ်", "အောက်"],
    },
  },
  {
    id: 288,
    chinese: "终于",
    pinyin: "zhōngyú",
    myanmar: "နောက်ဆုံးတော့",
    options: {
      correct: "နောက်ဆုံးတော့",
      wrong: ["အစမှာတော့", "ချက်ချင်း", "မကြာခဏ"],
    },
  },
  {
    id: 289,
    chinese: "种",
    pinyin: "zhǒng",
    myanmar: "မျိုးနွယ်/အမျိုးအစား",
    options: {
      correct: "မျိုးနွယ်/အမျိုးအစား",
      wrong: ["အရောင်", "အရွယ်အစား", "စျေးနှုန်း"],
    },
  },
  {
    id: 290,
    chinese: "重要",
    pinyin: "zhòngyào",
    myanmar: "အရေးကြီးသော",
    options: {
      correct: "အရေးကြီးသော",
      wrong: ["အရေးမကြီးသော", "လွယ်ကူသော", "ပျော်စရာကောင်းသော"],
    },
  },
  {
    id: 291,
    chinese: "周末",
    pinyin: "zhōumò",
    myanmar: "ရုံးပိတ်ရက်/သီတင်းပတ်ကုန်",
    options: {
      correct: "ရုံးပိတ်ရက်/သီတင်းပတ်ကုန်",
      wrong: ["တနင်္လာနေ့", "အလုပ်ရက်", "နှစ်သစ်ကူး"],
    },
  },
  {
    id: 292,
    chinese: "主要",
    pinyin: "zhǔyào",
    myanmar: "အဓိကကျသော",
    options: {
      correct: "အဓိကကျသော",
      wrong: ["အရန်", "နောက်ဆုံး", "သေးငယ်သော"],
    },
  },
  {
    id: 293,
    chinese: "注意",
    pinyin: "zhùyì",
    myanmar: "ဂရုပြုသည်/အာရုံစိုက်သည်",
    options: {
      correct: "ဂရုပြုသည်/အာရုံစိုက်သည်",
      wrong: ["လျစ်လျူရှုသည်", "မေ့လျော့သည်", "အိပ်ပျော်သည်"],
    },
  },
  {
    id: 294,
    chinese: "自己",
    pinyin: "zìjǐ",
    myanmar: "မိမိကိုယ်တိုင်",
    options: {
      correct: "မိမိကိုယ်တိုင်",
      wrong: ["တခြားသူ", "သူငယ်ချင်း", "ရန်သူ"],
    },
  },
  {
    id: 295,
    chinese: "自行车",
    pinyin: "zìxíngchē",
    myanmar: "စက်ဘီး",
    options: {
      correct: "စက်ဘီး",
      wrong: ["ကား", "ဆိုင်ကယ်", "ရထား"],
    },
  },
  {
    id: 296,
    chinese: "总是",
    pinyin: "zǒngshì",
    myanmar: "အမြဲတမ်း",
    options: {
      correct: "အမြဲတမ်း",
      wrong: ["တစ်ခါတစ်ရံ", "ဘယ်တော့မှ", "ခဲယဉ်းစွာ"],
    },
  },
  {
    id: 297,
    chinese: "嘴",
    pinyin: "zuǐ",
    myanmar: "ပါးစပ်",
    options: {
      correct: "ပါးစပ်",
      wrong: ["နှာခေါင်း", "မျက်လုံး", "နား"],
    },
  },
  {
    id: 298,
    chinese: "最后",
    pinyin: "zuìhòu",
    myanmar: "နောက်ဆုံး",
    options: {
      correct: "နောက်ဆုံး",
      wrong: ["အစဆုံး", "အလယ်", "ချက်ချင်း"],
    },
  },
  {
    id: 299,
    chinese: "最近",
    pinyin: "zuìjìn",
    myanmar: "လောလောလတ်လတ်/မကြာသေးမီက",
    options: {
      correct: "လောလောလတ်လတ်/မကြာသေးမီက",
      wrong: ["ဟိုးအရင်က", "နောင်တွင်", "အမြဲတမ်း"],
    },
  },
  {
    id: 300,
    chinese: "作业",
    pinyin: "zuòyè",
    myanmar: "အိမ်စာ/တာဝန်",
    options: {
      correct: "အိမ်စာ/တာဝန်",
      wrong: ["ဂိမ်း", "ရုပ်ရှင်", "အားလပ်ရက်"],
    },
  },
];
export default datas



export const nouns = [
  { id: "n-001", word: "环境", pinyin: "huánjìng", myanmar: "ပတ်ဝန်းကျင်" },
  { id: "n-002", word: "会议", pinyin: "huìyì", myanmar: "အစည်းအဝေး" },
  { id: "n-003", word: "机会", pinyin: "jīhuì", myanmar: "အခွင့်အရေး" },
  { id: "n-004", word: "季节", pinyin: "jìjié", myanmar: "ရာသီ" },
  { id: "n-005", word: "街道", pinyin: "jiēdào", myanmar: "လမ်းမ" },
  { id: "n-006", word: "节目", pinyin: "jiémù", myanmar: "အစီအစဉ်" },
  { id: "n-007", word: "节日", pinyin: "jiérì", myanmar: "ပွဲတော်" },
  { id: "n-008", word: "经理", pinyin: "jīnglǐ", myanmar: "မန်နေဂျာ" },
  { id: "n-009", word: "句子", pinyin: "jùzi", myanmar: "ဝါကျ" },
  { id: "n-010", word: "客人", pinyin: "kèrén", myanmar: "ဧည့်သည်" },
  { id: "n-011", word: "空调", pinyin: "kōngtiáo", myanmar: "အဲကွန်း" },
  { id: "n-012", word: "裤子", pinyin: "kùzi", myanmar: "ဘောင်းဘီ" },
  { id: "n-013", word: "筷子", pinyin: "kuàizi", myanmar: "တူ" },
  { id: "n-014", word: "礼物", pinyin: "lǐwù", myanmar: "လက်ဆောင်" },
  { id: "n-015", word: "历史", pinyin: "lìshǐ", myanmar: "သမိုင်း" },
  { id: "n-016", word: "脸", pinyin: "liǎn", myanmar: "မျက်နှာ" },
  { id: "n-017", word: "邻居", pinyin: "línjū", myanmar: "အိမ်နီးနားချင်း" },
  { id: "n-018", word: "楼", pinyin: "lóu", myanmar: "အဆောက်အဦး/ထပ်" },
  { id: "n-019", word: "马", pinyin: "mǎ", myanmar: "မြင်း" },
  { id: "n-020", word: "帽子", pinyin: "màozi", myanmar: "ဦးထုပ်" },
  { id: "n-021", word: "面包", pinyin: "miànbāo", myanmar: "ပေါင်မုန့်" },
  { id: "n-022", word: "奶奶", pinyin: "nǎinai", myanmar: "အဖွား" },
  { id: "n-023", word: "鸟", pinyin: "niǎo", myanmar: "ငှက်" },
  { id: "n-024", word: "盘子", pinyin: "pánzi", myanmar: "ပန်းကန်ပြား" },
  { id: "n-025", word: "啤酒", pinyin: "píjiǔ", myanmar: "ဘီယာ" },
  { id: "n-026", word: "皮鞋", pinyin: "píxié", myanmar: "သားရေဖိနပ်" },
  { id: "n-027", word: "瓶子", pinyin: "píngzi", myanmar: "ပုလင်း" },
  { id: "n-028", word: "裙子", pinyin: "qúnzi", myanmar: "စကတ်" },
  { id: "n-029", word: "世界", pinyin: "shìjiè", myanmar: "ကမ္ဘာလောက" },
  { id: "n-030", word: "叔叔", pinyin: "shūshu", myanmar: "ဦးလေး" },
  { id: "n-031", word: "树", pinyin: "shù", myanmar: "သစ်ပင်" },
  { id: "n-032", word: "数学", pinyin: "shùxué", myanmar: "သင်္ချာ" },
  { id: "n-033", word: "司机", pinyin: "sījī", myanmar: "ယာဉ်မောင်း" },
  { id: "n-034", word: "太阳", pinyin: "tàiyáng", myanmar: "နေမင်း" },
  { id: "n-035", word: "体育", pinyin: "tǐyù", myanmar: "အားကစား" },
  { id: "n-036", word: "同事", pinyin: "tóngshì", myanmar: "လုပ်ဖော်ကိုင်ဖက်" },
  { id: "n-037", word: "头发", pinyin: "tóufa", myanmar: "ဆံပင်" },
  { id: "n-038", word: "图书馆", pinyin: "túshūguǎn", myanmar: "စာကြည့်တိုက်" },
  { id: "n-039", word: "腿", pinyin: "tuǐ", myanmar: "ခြေထောက်" },
  { id: "n-040", word: "碗", pinyin: "wǎn", myanmar: "ပန်းကန်လုံး" },
  { id: "n-041", word: "文化", pinyin: "wénhuà", myanmar: "ယဉ်ကျေးမှု" },
  { id: "n-042", word: "洗手间", pinyin: "xǐshǒujiān", myanmar: "အိမ်သာ" },
  { id: "n-043", word: "香蕉", pinyin: "xiāngjiāo", myanmar: "ငှက်ပျောသီး" },
  { id: "n-044", word: "校长", pinyin: "xiàozhǎng", myanmar: "ကျောင်းအုပ်" },
  { id: "n-045", word: "新闻", pinyin: "xīnwén", myanmar: "သတင်း" },
  { id: "n-046", word: "信用卡", pinyin: "xìnyòngkǎ", myanmar: "ခရက်ဒစ်ကတ်" },
  {
    id: "n-047",
    word: "行李箱",
    pinyin: "xínglixiāng",
    myanmar: "ခရီးဆောင်အိတ်",
  },
  { id: "n-048", word: "熊猫", pinyin: "xióngmāo", myanmar: "ပန်ဒါ" },
  { id: "n-049", word: "爷爷", pinyin: "yéye", myanmar: "အဘိုး" },
  { id: "n-050", word: "音乐", pinyin: "yīnyuè", myanmar: "ဂီတ" },
  { id: "n-051", word: "银行", pinyin: "yínháng", myanmar: "ဘဏ်" },
  { id: "n-052", word: "饮料", pinyin: "yǐnliào", myanmar: "ဖျော်ရည်" },
  { id: "n-053", word: "游戏", pinyin: "yóuxì", myanmar: "ဂိမ်း" },
  { id: "n-054", word: "月亮", pinyin: "yuèliang", myanmar: "လမင်း" },
  { id: "n-055", word: "照片", pinyin: "zhàopiàn", myanmar: "ဓာတ်ပုံ" },
  { id: "n-056", word: "照相机", pinyin: "zhàoxiàngjī", myanmar: "ကင်မရာ" },
  { id: "n-057", word: "中文", pinyin: "zhōngwén", myanmar: "တရုတ်စာ" },
  { id: "n-058", word: "嘴", pinyin: "zuǐ", myanmar: "ပါးစပ်" },
  { id: "n-059", word: "作业", pinyin: "zuòyè", myanmar: "အိမ်စာ" },
];

export const verbs = [
  { id: "v-001", word: "还", pinyin: "huán", myanmar: "ပြန်ပေးသည်" },
  { id: "v-002", word: "换", pinyin: "huàn", myanmar: "လဲလှယ်သည်" },
  { id: "v-003", word: "回答", pinyin: "huídá", myanmar: "ဖြေကြားသည်" },
  { id: "v-004", word: "记得", pinyin: "jìde", myanmar: "မှတ်မိသည်" },
  { id: "v-005", word: "检查", pinyin: "jiǎnchá", myanmar: "စစ်ဆေးသည်" },
  { id: "v-006", word: "见面", pinyin: "jiànmiàn", myanmar: "တွေ့ဆုံသည်" },
  { id: "v-007", word: "讲", pinyin: "jiǎng", myanmar: "ပြောပြသည်" },
  { id: "v-008", word: "教", pinyin: "jiāo", myanmar: "သင်ကြားပေးသည်" },
  { id: "v-009", word: "接", pinyin: "jiē", myanmar: "ကြိုသည်/လက်ခံသည်" },
  { id: "v-010", word: "结婚", pinyin: "jiéhūn", myanmar: "လက်ထပ်သည်" },
  { id: "v-011", word: "结束", pinyin: "jiéshù", myanmar: "ပြီးဆုံးသည်" },
  { id: "v-012", word: "解决", pinyin: "jiějué", myanmar: "ဖြေရှင်းသည်" },
  { id: "v-013", word: "借", pinyin: "jiè", myanmar: "ငှားသည်" },
  { id: "v-014", word: "决定", pinyin: "juédìng", myanmar: "ဆုံးဖြတ်သည်" },
  { id: "v-015", word: "哭", pinyin: "kū", myanmar: "ငိုသည်" },
  { id: "v-016", word: "离开", pinyin: "líkāi", myanmar: "ထွက်ခွာသည်" },
  {
    id: "v-017",
    word: "聊天",
    pinyin: "liáotiān",
    myanmar: "စကားစမြည်ပြောသည်",
  },
  { id: "v-018", word: "练习", pinyin: "liànxí", myanmar: "လေ့ကျင့်သည်" },
  {
    id: "v-019",
    word: "了解",
    pinyin: "liǎojiě",
    myanmar: "နားလည်သဘောပေါက်သည်",
  },
  {
    id: "v-020",
    word: "留学",
    pinyin: "liúxué",
    myanmar: "နိုင်ငံခြားကျောင်းသွားတက်သည်",
  },
  { id: "v-021", word: "拿", pinyin: "ná", myanmar: "ယူဆောင်သည်" },
  { id: "v-022", word: "爬山", pinyin: "páshān", myanmar: "တောင်တက်သည်" },
  { id: "v-023", word: "骑", pinyin: "qí", myanmar: "စီးသည် (စက်ဘီး/မြင်း)" },
  { id: "v-024", word: "起来", pinyin: "qǐlái", myanmar: "ထသည်" },
  { id: "v-025", word: "起飞", pinyin: "qǐfēi", myanmar: "ပျံတက်သည်" },
  { id: "v-026", word: "请假", pinyin: "qǐngjià", myanmar: "ခွင့်တိုင်သည်" },
  { id: "v-027", word: "认为", pinyin: "rènwéi", myanmar: "ယူဆသည်" },
  {
    id: "v-028",
    word: "上网",
    pinyin: "shàngwǎng",
    myanmar: "အင်တာနက်သုံးသည်",
  },
  { id: "v-029", word: "生气", pinyin: "shēngqì", myanmar: "ဒေါသထွက်သည်" },
  { id: "v-030", word: "试", pinyin: "shì", myanmar: "စမ်းသပ်သည်" },
  { id: "v-031", word: "刷牙", pinyin: "shuāyá", myanmar: "သွားတိုက်သည်" },
  { id: "v-032", word: "提高", pinyin: "tígāo", myanmar: "မြှင့်တင်သည်" },
  { id: "v-033", word: "同意", pinyin: "tóngyì", myanmar: "သဘောတူသည်" },
  { id: "v-034", word: "完成", pinyin: "wánchéng", myanmar: "ပြီးမြောက်သည်" },
  { id: "v-035", word: "忘记", pinyin: "wàngjì", myanmar: "မေ့လျော့သည်" },
  { id: "v-036", word: "习惯", pinyin: "xíguàn", myanmar: "အကျင့်ဖြစ်သည်" },
  { id: "v-037", word: "洗澡", pinyin: "xǐzǎo", myanmar: "ရေချိုးသည်" },
  { id: "v-038", word: "相信", pinyin: "xiāngxìn", myanmar: "ယုံကြည်သည်" },
  { id: "v-039", word: "小心", pinyin: "xiǎoxīn", myanmar: "သတိထားသည်" },
  { id: "v-040", word: "需要", pinyin: "xūyào", myanmar: "လိုအပ်သည်" },
  { id: "v-041", word: "选择", pinyin: "xuǎnzé", myanmar: "ရွေးချယ်သည်" },
  { id: "v-042", word: "愿意", pinyin: "yuànyì", myanmar: "ဆန္ဒရှိသည်" },
  { id: "v-043", word: "遇到", pinyin: "yùdào", myanmar: "ကြုံတွေ့သည်" },
  { id: "v-044", word: "照顾", pinyin: "zhàogù", myanmar: "ဂရုစိုက်သည်" },
  { id: "v-045", word: "注意", pinyin: "zhùyì", myanmar: "ဂရုပြုသည်" },
];


export const adj = [
  { id: "adj-001", word: "简单", pinyin: "jiǎndān", myanmar: "ရိုးရှင်းသော" },
  { id: "adj-002", word: "健康", pinyin: "jiànkāng", myanmar: "ကျန်းမာသော" },
  { id: "adj-003", word: "久", pinyin: "jiǔ", myanmar: "ကြာမြင့်သော" },
  { id: "adj-004", word: "旧", pinyin: "jiù", myanmar: "ဟောင်းသော" },
  { id: "adj-005", word: "渴", pinyin: "kě", myanmar: "ရေငတ်သော" },
  { id: "adj-006", word: "可爱", pinyin: "kě'ài", myanmar: "ချစ်စရာကောင်းသော" },
  { id: "adj-007", word: "蓝", pinyin: "lán", myanmar: "အပြာရောင်" },
  { id: "adj-008", word: "老", pinyin: "lǎo", myanmar: "အိုသော" },
  { id: "adj-009", word: "绿", pinyin: "lǜ", myanmar: "အစိမ်းရောင်" },
  { id: "adj-010", word: "满意", pinyin: "mǎnyì", myanmar: "ကျေနပ်သော" },
  { id: "adj-011", word: "明白", pinyin: "míngbai", myanmar: "ရှင်းလင်းသော" },
  { id: "adj-012", word: "难", pinyin: "nán", myanmar: "ခက်ခဲသော" },
  { id: "adj-013", word: "难过", pinyin: "nánguò", myanmar: "ဝမ်းနည်းသော" },
  { id: "adj-014", word: "年轻", pinyin: "niánqīng", myanmar: "ငယ်ရွယ်သော" },
  { id: "adj-015", word: "努力", pinyin: "nǔlì", myanmar: "ကြိုးစားသော" },
  { id: "adj-016", word: "胖", pinyin: "pàng", myanmar: "ဝသော" },
  { id: "adj-017", word: "奇怪", pinyin: "qíguài", myanmar: "ထူးဆန်းသော" },
  {
    id: "adj-018",
    word: "清楚",
    pinyin: "qīngchu",
    myanmar: "ရှင်းလင်းပြတ်သားသော",
  },
  {
    id: "adj-019",
    word: "热情",
    pinyin: "rèqíng",
    myanmar: "နွေးထွေးပျူငှာသော",
  },
  { id: "adj-020", word: "认真", pinyin: "rènzhēn", myanmar: "အလေးအနက်ထားသော" },
  { id: "adj-021", word: "容易", pinyin: "róngyì", myanmar: "လွယ်ကူသော" },
  { id: "adj-022", word: "瘦", pinyin: "shòu", myanmar: "ပိန်သော" },
  {
    id: "adj-023",
    word: "舒服",
    pinyin: "shūfu",
    myanmar: "သက်သောင့်သက်သာရှိသော",
  },
  { id: "adj-024", word: "特别", pinyin: "tèbié", myanmar: "ထူးခြားသော" },
  { id: "adj-025", word: "甜", pinyin: "tián", myanmar: "ချိုသော" },
  { id: "adj-026", word: "新鲜", pinyin: "xīnxiān", myanmar: "လတ်ဆတ်သော" },
  { id: "adj-027", word: "一般", pinyin: "yìbān", myanmar: "ပုံမှန်" },
  { id: "adj-028", word: "有名", pinyin: "yǒumíng", myanmar: "ကျော်ကြားသော" },
  { id: "adj-029", word: "重要", pinyin: "zhòngyào", myanmar: "အရေးကြီးသော" },
];


export const Adverbs = [
  { id: "adv-001", word: "几乎", pinyin: "jīhū", myanmar: "နီးပါး" },
  { id: "adv-002", word: "经常", pinyin: "jīngcháng", myanmar: "မကြာခဏ" },
  { id: "adv-003", word: "马上", pinyin: "mǎshàng", myanmar: "ချက်ချင်း" },
  { id: "adv-004", word: "其实", pinyin: "qíshí", myanmar: "တကယ်တော့" },
  { id: "adv-005", word: "然后", pinyin: "ránhòu", myanmar: "ပြီးနောက်" },
  { id: "adv-006", word: "一共", pinyin: "yígòng", myanmar: "စုစုပေါင်း" },
  { id: "adv-007", word: "一直", pinyin: "yìzhí", myanmar: "တောက်လျှောက်" },
  { id: "adv-008", word: "终于", pinyin: "zhōngyú", myanmar: "နောက်ဆုံးတော့" },
  { id: "adv-009", word: "总是", pinyin: "zǒngshì", myanmar: "အမြဲတမ်း" },
  { id: "adv-010", word: "最近", pinyin: "zuìjìn", myanmar: "လောလောလတ်လတ်" },
  { id: "conj-001", word: "或者", pinyin: "huòzhě", myanmar: "သို့မဟုတ်" },
  { id: "conj-002", word: "如果", pinyin: "rúguǒ", myanmar: "အကယ်၍" },
  { id: "prep-001", word: "为了", pinyin: "wèile", myanmar: "အတွက်/စေရန်" },
];