const datas = [
  {
    id: 1,
    chinese: "您",
    pinyin: "nín",
    correct: "သင်/အရှင် (ယဉ်ကျေးသမှု)",
    category: "Pronoun",
    options: ["သင်/အရှင် (ယဉ်ကျေးသမှု)", "ငါ", "သူမ"],
  },
  {
    id: 2,
    chinese: "它",
    pinyin: "tā",
    correct: "၎င်း (အရာဝတ္ထု/တိရစ္ဆာန်)",
    category: "Pronoun",
    options: ["၎င်း (အရာဝတ္ထု/တိရစ္ဆာန်)", "လူ", "ဆရာ"],
  },
  {
    id: 3,
    chinese: "大家",
    pinyin: "dàjiā",
    correct: "အားလုံး/လူတိုင်း",
    category: "Pronoun",
    options: ["အားလုံး/လူတိုင်း", "အိမ်နီးချင်း", "မိသားစု"],
  },
  {
    id: 4,
    chinese: "每",
    pinyin: "měi",
    correct: "တိုင်း/စီ",
    category: "Pronoun",
    options: ["တိုင်း/စီ", "အချို့", "အားလုံး"],
  },
  {
    id: 5,
    chinese: "为什么",
    pinyin: "wèishénme",
    correct: "ဘာကြောင့်လဲ",
    category: "Pronoun",
    options: ["ဘာကြောင့်လဲ", "ဘာလဲ", "ဘယ်သူလဲ"],
  },
  {
    id: 6,
    chinese: "零",
    pinyin: "líng",
    correct: "သုည",
    category: "Number",
    options: ["သုည", "တစ်ရာ", "တစ်ဆယ်"],
  },
  {
    id: 7,
    chinese: "两",
    pinyin: "liǎng",
    correct: "နှစ် (အရေအတွက်)",
    category: "Number",
    options: ["နှစ် (အရေအတွက်)", "သုံး", "ငါး"],
  },
  {
    id: 8,
    chinese: "百",
    pinyin: "bǎi",
    correct: "ရာ (တစ်ရာ)",
    category: "Number",
    options: ["ရာ (တစ်ရာ)", "ထောင်", "သောင်း"],
  },
  {
    id: 9,
    chinese: "千",
    pinyin: "qiā",
    correct: "ထောင် (တစ်ထောင်)",
    category: "Number",
    options: ["ထောင် (တစ်ထောင်)", "ရာ", "သန်း"],
  },
  {
    id: 10,
    chinese: "第一",
    pinyin: "dìyī",
    correct: "ပထမ",
    category: "Number",
    options: ["ပထမ", "ဒုတိယ", "နောက်ဆုံး"],
  },
  {
    id: 11,
    chinese: "次",
    pinyin: "cì",
    correct: "အကြိမ်",
    category: "Measure Word",
    options: ["အကြိမ်", "နာရီ", "နေ့"],
  },
  {
    id: 12,
    chinese: "件",
    pinyin: "jiàn",
    correct: "ခု/ထည် (အင်္ကျီသုံး measure word)",
    category: "Measure Word",
    options: ["ခု/ထည် (အင်္ကျီသုံး measure word)", "ယောက်", "အုပ်"],
  },
  {
    id: 13,
    chinese: "别",
    pinyin: "bié",
    correct: "မ...နှင့် (Don't)",
    category: "Adverb",
    options: ["မ...နှင့် (Don't)", "လုပ်ပါ", "သွားပါ"],
  },
  {
    id: 14,
    chinese: "非常",
    pinyin: "fēicháng",
    correct: "အလွန်အမင်း",
    category: "Adverb",
    options: ["အလွန်အမင်း", "နည်းနည်း", "မဆိုးပါဘူး"],
  },
  {
    id: 15,
    chinese: "也",
    pinyin: "yě",
    correct: "လည်း/လည်းပဲ",
    category: "Adverb",
    options: ["လည်း/လည်းပဲ", "သို့သော်", "ဘာလို့လဲ"],
  },
  {
    id: 16,
    chinese: "还",
    pinyin: "hái",
    correct: "ကျန်သေးသည်/ရှိသေးသည်",
    category: "Adverb",
    options: ["ကျန်သေးသည်/ရှိသေးသည်", "ပြီးပြီ", "မရှိတော့ဘူး"],
  },
  {
    id: 17,
    chinese: "最",
    pinyin: "zuì",
    correct: "အ...ဆုံး",
    category: "Adverb",
    options: ["အ...ဆုံး", "အရမ်း", "ပိုပြီး"],
  },
  {
    id: 18,
    chinese: "真",
    pinyin: "zhēn",
    correct: "တကယ်/တကယ့်",
    category: "Adverb",
    options: ["တကယ်/တကယ့်", "အတု", "ဖြစ်နိုင်သည်"],
  },
  {
    id: 19,
    chinese: "正在",
    pinyin: "zhèngzài",
    correct: "နေသည် (လုပ်ဆောင်ဆဲ)",
    category: "Adverb",
    options: ["နေသည် (လုပ်ဆောင်ဆဲ)", "ပြီးခဲ့ပြီ", "လုပ်တော့မည်"],
  },
  {
    id: 20,
    chinese: "已经",
    pinyin: "yǐjīng",
    correct: "ပြီးပြီ/ပြီးခဲ့ပြီ",
    category: "Adverb",
    options: ["ပြီးပြီ/ပြီးခဲ့ပြီ", "မလုပ်ရသေးဘူး", "လုပ်နေတုန်း"],
  },
  {
    id: 21,
    chinese: "一起",
    pinyin: "yìqǐ",
    correct: "အတူတူ",
    category: "Adverb",
    options: ["အတူတူ", "တစ်ယောက်တည်း", "သီးသန့်"],
  },
  {
    id: 22,
    chinese: "再",
    pinyin: "zài",
    correct: "ထပ်ပြီး",
    category: "Adverb",
    options: ["ထပ်ပြီး", "အရင်က", "နောက်ဆုံး"],
  },
  {
    id: 23,
    chinese: "就",
    pinyin: "jiù",
    correct: "ချက်ချင်း/ဆိုလျှင်",
    category: "Adverb",
    options: ["ချက်ချင်း/ဆိုလျှင်", "နောက်မှ", "ဖြည်းဖြည်း"],
  },
  {
    id: 24,
    chinese: "因为……所以……",
    pinyin: "yīnwèi…suǒyǐ…",
    correct: "ကြောင့်...ကြောင့်/ဖြစ်လို့",
    category: "Conjunction",
    options: ["ကြောင့်...ကြောင့်/ဖြစ်လို့", "ဒါပေမယ့်", "မဟုတ်ရင်"],
  },
  {
    id: 25,
    chinese: "虽然……但是……",
    pinyin: "suīrán…dànshì…",
    correct: "သော်လည်း...ဒါပေမယ့်",
    category: "Conjunction",
    options: ["သော်လည်း...ဒါပေမယ့်", "ကြောင့်မို့လို့", "ဒါကြောင့်"],
  },
  {
    id: 26,
    chinese: "从",
    pinyin: "cóng",
    correct: "မှ (From)",
    category: "Preposition",
    options: ["မှ (From)", "သို့", "မှာ"],
  },
  {
    id: 27,
    chinese: "比",
    pinyin: "bǐ",
    correct: "ထက် (နှိုင်းယှဉ်ချက်)",
    category: "Preposition",
    options: ["ထက် (နှိုင်းယှဉ်ချက်)", "တူတူပဲ", "နည်းတူ"],
  },
  {
    id: 28,
    chinese: "往",
    pinyin: "wǎng",
    correct: "သို့/ဘက်သို့",
    category: "Preposition",
    options: ["သို့/ဘက်သို့", "မှ", "ထဲမှာ"],
  },
  {
    id: 29,
    chinese: "离",
    pinyin: "lí",
    correct: "အကွာအဝေးကိုပြသောစကားလုံး",
    category: "Preposition",
    options: ["အကွာအဝေးကိုပြသောစကားလုံး", "အနီးနား", "အပေါ်ဘက်"],
  },
  {
    id: 30,
    chinese: "得",
    pinyin: "de",
    correct: "ရရှိသည်/ပြုလုပ်မှုအဆင့်အတန်းပြ",
    category: "Particle",
    options: ["ရရှိသည်/ပြုလုပ်မှုအဆင့်အတန်းပြ", "ပေးသည်", "ဆုံးရှုံးသည်"],
  },
  {
    id: 31,
    chinese: "着",
    pinyin: "zhe",
    correct: "နေသည် (အခြေအနေတစ်ခု ဆက်ဖြစ်နေခြင်း)",
    category: "Particle",
    options: ["နေသည် (အခြေအနေတစ်ခု ဆက်ဖြစ်နေခြင်း)", "ပြီးပြီ", "လုပ်တော့မည်"],
  },
  {
    id: 32,
    chinese: "过",
    pinyin: "guò",
    correct: "ဖူးသည် (အတွေ့အကြုံ)",
    category: "Particle",
    options: ["ဖူးသည် (အတွေ့အကြုံ)", "နေသည်", "လိမ့်မည်"],
  },
  {
    id: 33,
    chinese: "吧",
    pinyin: "ba",
    correct: "ပါ/လေ (တိုက်တွန်းခြင်း)",
    category: "Particle",
    options: ["ပါ/လေ (တိုက်တွန်းခြင်း)", "လား", "လဲ"],
  },
  {
    id: 34,
    chinese: "机场",
    pinyin: "jīchǎng",
    correct: "လေဆိပ်",
    category: "Noun",
    options: ["လေဆိပ်", "ဘူတာရုံ", "ကားဂိတ်"],
  },
  {
    id: 35,
    chinese: "教室",
    pinyin: "jiàoshì",
    correct: "စာသင်ခန်း",
    category: "Noun",
    options: ["စာသင်ခန်း", "အိမ်သာ", "ရုံးခန်း"],
  },
  {
    id: 36,
    chinese: "房间",
    pinyin: "fángjiān",
    correct: "အခန်း",
    category: "Noun",
    options: ["အခန်း", "တိုက်ခန်း", "အိမ်"],
  },
  {
    id: 37,
    chinese: "路",
    pinyin: "lù",
    correct: "လမ်း",
    category: "Noun",
    options: ["လမ်း", "တံတား", "မြစ်"],
  },
  {
    id: 38,
    chinese: "左边",
    pinyin: "zuǒbiān",
    correct: "ဘယ်ဘက်",
    category: "Noun",
    options: ["ဘယ်ဘက်", "ညာဘက်", "အလယ်"],
  },
  {
    id: 39,
    chinese: "右边",
    pinyin: "yòubiān",
    correct: "ညာဘက်",
    category: "Noun",
    options: ["ညာဘက်", "ဘယ်ဘက်", "အနောက်"],
  },
  {
    id: 40,
    chinese: "外",
    pinyin: "wài",
    correct: "အပြင်ဘက်",
    category: "Noun",
    options: ["အပြင်ဘက်", "အတွင်းဘက်", "အောက်ဘက်"],
  },
  {
    id: 41,
    chinese: "旁边",
    pinyin: "pángbiān",
    correct: "ဘေးနား",
    category: "Noun",
    options: ["ဘေးနား", "အဝေးကြီး", "အပေါ်"],
  },
  {
    id: 42,
    chinese: "一下",
    pinyin: "yīxià",
    correct: "ခဏလောက်",
    category: "Time",
    options: ["ခဏလောက်", "တစ်နေကုန်", "တစ်ပတ်လုံး"],
  },
  {
    id: 43,
    chinese: "早上",
    pinyin: "zǎoshàng",
    correct: "မနက်စောစော",
    category: "Time",
    options: ["မနက်စောစော", "ညနေ", "သန်းခေါင်"],
  },
  {
    id: 44,
    chinese: "晚上",
    pinyin: "wǎnshàng",
    correct: "ညဘက်",
    category: "Time",
    options: ["ညဘက်", "မွန်းတည့်", "မနက်ဖြန်"],
  },
  {
    id: 45,
    chinese: "小时",
    pinyin: "xiǎoshí",
    correct: "နာရီ (ကြာချိန်)",
    category: "Time",
    options: ["နာရီ (ကြာချိန်)", "မိနစ်", "စက္ကန့်"],
  },
  {
    id: 46,
    chinese: "时间",
    pinyin: "shíjiān",
    correct: "အချိန်",
    category: "Time",
    options: ["အချိန်", "နေရာ", "အလုပ်"],
  },
  {
    id: 47,
    chinese: "去年",
    pinyin: "qùnián",
    correct: "မနှစ်က",
    category: "Time",
    options: ["မနှစ်က", "ဒီနှစ်", "နောင်နှစ်"],
  },
  {
    id: 48,
    chinese: "日",
    pinyin: "rì",
    correct: "နေ့စွဲ",
    category: "Time",
    options: ["နေ့စွဲ", "လ", "နှစ်"],
  },
  {
    id: 49,
    chinese: "生日",
    pinyin: "shēngrì",
    correct: "မွေးနေ့",
    category: "Noun",
    options: ["မွေးနေ့", "နှစ်ပတ်လည်", "မင်္ဂလာဆောင်"],
  },
  {
    id: 50,
    chinese: "哥哥",
    pinyin: "gēge",
    correct: "အစ်ကို",
    category: "Noun",
    options: ["အစ်ကို", "မောင်လေး", "အစ်မ"],
  },
  {
    id: 51,
    chinese: "姐姐",
    pinyin: "jiějie",
    correct: "အစ်မ",
    category: "Noun",
    options: ["အစ်မ", "ညီမလေး", "အမေ"],
  },
  {
    id: 52,
    chinese: "弟弟",
    pinyin: "dìdi",
    correct: "ညီလေး/မောင်လေး",
    category: "Noun",
    options: ["ညီလေး/မောင်လေး", "အစ်ကို", "အဖေ"],
  },
  {
    id: 53,
    chinese: "妹妹",
    pinyin: "mèimei",
    correct: "ညီမလေး",
    category: "Noun",
    options: ["ညီမလေး", "အစ်မ", "သားမက်"],
  },
  {
    id: 54,
    chinese: "丈夫",
    pinyin: "zhàngfu",
    correct: "ခင်ပွန်း",
    category: "Noun",
    options: ["ခင်ပွန်း", "ဇနီး", "သူငယ်ချင်း"],
  },
  {
    id: 55,
    chinese: "妻子",
    pinyin: "qīzi",
    correct: "ဇနီး",
    category: "Noun",
    options: ["ဇနီး", "ခင်ပွန်း", "ဆရာမ"],
  },
  {
    id: 56,
    chinese: "孩子",
    pinyin: "háizi",
    correct: "ကလေး",
    category: "Noun",
    options: ["ကလေး", "လူကြီး", "ဆယ်ကျော်သက်"],
  },
  {
    id: 57,
    chinese: "男人",
    pinyin: "nánrén",
    correct: "အမျိုးသား/ယောက်ျား",
    category: "Noun",
    options: ["အမျိုးသား/ယောက်ျား", "အမျိုးသမီး", "တိရစ္ဆာန်"],
  },
  {
    id: 58,
    chinese: "女人",
    pinyin: "nǚrén",
    correct: "အမျိုးသမီး/မိန်းမ",
    category: "Noun",
    options: ["အမျိုးသမီး/မိန်းမ", "ယောက်ျား", "ကလေး"],
  },
  {
    id: 59,
    chinese: "服务员",
    pinyin: "fúwùyuán",
    correct: "ဝန်ထမ်း (စားပွဲထိုး)",
    category: "Noun",
    options: ["ဝန်ထမ်း (စားပွဲထိုး)", "ဆရာဝန်", "ကျောင်းအုပ်"],
  },
  {
    id: 60,
    chinese: "鱼",
    pinyin: "yú",
    correct: "ငါး",
    category: "Noun",
    options: ["ငါး", "ကြက်သား", "ဝက်သား"],
  },
  {
    id: 61,
    chinese: "羊肉",
    pinyin: "yángròu",
    correct: "ဆိတ်သား/သိုးသား",
    category: "Noun",
    options: ["ဆိတ်သား/သိုးသား", "အမဲသား", "ဝက်သား"],
  },
  {
    id: 62,
    chinese: "牛奶",
    pinyin: "niúnǎi",
    correct: "နွားနို့",
    category: "Noun",
    options: ["နွားနို့", "ကော်ဖီ", "ယမကာ"],
  },
  {
    id: 63,
    chinese: "鸡蛋",
    pinyin: "jīdàn",
    correct: "ကြက်ဥ",
    category: "Noun",
    options: ["ကြက်ဥ", "ဘဲဥ", "ငါးဥ"],
  },
  {
    id: 64,
    chinese: "西瓜",
    pinyin: "xīguā",
    correct: "ဖရဲသီး",
    category: "Noun",
    options: ["ဖရဲသီး", "ပန်းသီး", "ငှက်ပျောသီး"],
  },
  {
    id: 65,
    chinese: "咖啡",
    pinyin: "kāfēi",
    correct: "ကော်ဖီ",
    category: "Noun",
    options: ["ကော်ဖီ", "လက်ဖက်ရည်", "နွားနို့"],
  },
  {
    id: 66,
    chinese: "雪",
    pinyin: "xuě",
    correct: "နှင်း",
    category: "Noun",
    options: ["နှင်း", "မိုး", "နေရောင်"],
  },
  {
    id: 67,
    chinese: "药",
    pinyin: "yào",
    correct: "ဆေး",
    category: "Noun",
    options: ["ဆေး", "အဆိပ်", "အစားအစာ"],
  },
  {
    id: 68,
    chinese: "手机",
    pinyin: "shǒujī",
    correct: "လက်ကိုင်ဖုန်း",
    category: "Noun",
    options: ["လက်ကိုင်ဖုန်း", "တယ်လီဖုန်း", "ကွန်ပျူတာ"],
  },
  {
    id: 69,
    chinese: "手表",
    pinyin: "shǒubiǎo",
    correct: "လက်ပတ်နာရီ",
    category: "Noun",
    options: ["လက်ပတ်နာရီ", "နံရံကပ်နာရီ", "လက်ဝတ်ရတနာ"],
  },
  {
    id: 70,
    chinese: "眼睛",
    pinyin: "yǎnjing",
    correct: "မျက်လုံး",
    category: "Noun",
    options: ["မျက်လုံး", "နှာခေါင်း", "နား"],
  },
  {
    id: 71,
    chinese: "身体",
    pinyin: "shēntǐ",
    correct: "ခန္ဓာကိုယ်/ကျန်းမာရေး",
    category: "Noun",
    options: ["ခန္ဓာကိုယ်/ကျန်းမာရေး", "စိတ်ဓာတ်", "အလှအပ"],
  },
  {
    id: 72,
    chinese: "公共汽车",
    pinyin: "gōnggòng qìchē",
    correct: "ဘတ်စ်ကား",
    category: "Noun",
    options: ["ဘတ်စ်ကား", "ရထား", "လေယာဉ်ပျံ"],
  },
  {
    id: 73,
    chinese: "报纸",
    pinyin: "bàozhǐ",
    correct: "သတင်းစာ",
    category: "Noun",
    options: ["သတင်းစာ", "စာအုပ်", "မဂ္ဂဇင်း"],
  },
  {
    id: 74,
    chinese: "门",
    pinyin: "mén",
    correct: "တံခါး",
    category: "Noun",
    options: ["တံခါး", "ပြတင်းပေါက်", "နံရံ"],
  },
  {
    id: 75,
    chinese: "题",
    pinyin: "tí",
    correct: "မေးခွန်း/ခေါင်းစဉ်",
    category: "Noun",
    options: ["မေးခွန်း/ခေါင်းစဉ်", "အဖြေ", "စာပိုဒ်"],
  },
  {
    id: 76,
    chinese: "课",
    pinyin: "kè",
    correct: "သင်ခန်းစာ",
    category: "Noun",
    options: ["သင်ခန်းစာ", "အားကစား", "အနားယူခြင်း"],
  },
  {
    id: 77,
    chinese: "姓",
    pinyin: "xìng",
    correct: "မျိုးရိုးအမည်",
    category: "Noun",
    options: ["မျိုးရိုးအမည်", "နာမည်", "အလုပ်အကိုင်"],
  },
  {
    id: 78,
    chinese: "问题",
    pinyin: "wèntí",
    correct: "မေးခွန်း/ပြဿနာ",
    category: "Noun",
    options: ["မေးခွန်း/ပြဿနာ", "အစီရင်ခံစာ", "သတင်း"],
  },
  {
    id: 79,
    chinese: "事情",
    pinyin: "shìqing",
    correct: "ကိစ္စ/အကြောင်းအရာ",
    category: "Noun",
    options: ["ကိစ္စ/အကြောင်းအရာ", "ပစ္စည်း", "နေရာ"],
  },
  {
    id: 80,
    chinese: "考试",
    pinyin: "kǎoshì",
    correct: "စာမေးပွဲ",
    category: "Noun",
    options: ["စာမေးပွဲ", "အတန်းတက်ခြင်း", "အားလပ်ရက်"],
  },
  {
    id: 81,
    chinese: "票",
    pinyin: "piào",
    correct: "လက်မှတ်",
    category: "Noun",
    options: ["လက်မှတ်", "ပိုက်ဆံ", "စာအုပ်"],
  },
  {
    id: 82,
    chinese: "意思",
    pinyin: "yìsi",
    correct: "အဓိပ္ပယ်",
    category: "Noun",
    options: ["အဓိပ္ပာယ်", "အသံထွက်", "စာလုံးအလှ"],
  },
  {
    id: 83,
    chinese: "颜色",
    pinyin: "yánsè",
    correct: "အရောင်",
    category: "Noun",
    options: ["အရောင်", "ပုံသဏ္ဍာန်", "အရွယ်အစား"],
  },
  {
    id: 84,
    chinese: "铅笔",
    pinyin: "qiānbǐ",
    correct: "ခဲတံ",
    category: "Noun",
    options: ["ခဲတံ", "ဘောပင်", "ပေတံ"],
  },
  {
    id: 85,
    chinese: "面条",
    pinyin: "miàntiáo",
    correct: "ခေါက်ဆွဲ",
    category: "Noun",
    options: ["ခေါက်ဆွဲ", "ပေါင်မုန့်", "ကိတ်မုန့်"],
  },
  {
    id: 86,
    chinese: "火车站",
    pinyin: "huǒchēzhàn",
    correct: "မီးရထားဘူတာ",
    category: "Noun",
    options: ["မီးရထားဘူတာ", "လေဆိပ်", "ကားဂိတ်"],
  },
  {
    id: 87,
    chinese: "公司",
    pinyin: "gōngsī",
    correct: "ကုမ္ပဏီ",
    category: "Noun",
    options: ["ကုမ္ပဏီ", "ဈေး", "ပန်းခြံ"],
  },
  {
    id: 88,
    chinese: "宾馆",
    pinyin: "bīnguǎn",
    correct: "ဟိုတယ်/တည်းခိုခန်း",
    category: "Noun",
    options: ["ဟိုတယ်/တည်းခိုခန်း", "ကျောင်း", "ဆေးရုံ"],
  },
  {
    id: 89,
    chinese: "说话",
    pinyin: "shuōhuà",
    correct: "စကားပြောသည်",
    category: "Verb",
    options: ["စကားပြောသည်", "စာဖတ်သည်", "အိပ်သည်"],
  },
  {
    id: 90,
    chinese: "卖",
    pinyin: "mài",
    correct: "ရောင်းသည်",
    category: "Verb",
    options: ["ရောင်းသည်", "ဝယ်သည်", "ပေးသည်"],
  },
  {
    id: 91,
    chinese: "问",
    pinyin: "wèn",
    correct: "မေးမြန်းသည်",
    category: "Verb",
    options: ["မေးမြန်းသည်", "ဖြေကြားသည်", "ပြောကြားသည်"],
  },
  {
    id: 92,
    chinese: "走",
    pinyin: "zǒu",
    correct: "လမ်းလျှောက်သည်/သွားသည်",
    category: "Verb",
    options: ["လမ်းလျှောက်သည်/သွားသည်", "ပြေးသည်", "ထိုင်သည်"],
  },
  {
    id: 93,
    chinese: "进",
    pinyin: "jìn",
    correct: "ဝင်သည်",
    category: "Verb",
    options: ["ဝင်သည်", "ထွက်သည်", "တက်သည်"],
  },
  {
    id: 94,
    chinese: "出",
    pinyin: "chū",
    correct: "ထွက်သည်",
    category: "Verb",
    options: ["ထွက်သည်", "ဝင်သည်", "ဆင်းသည်"],
  },
  {
    id: 95,
    chinese: "跑步",
    pinyin: "pǎobù",
    correct: "အပြေးလေ့ကျင့်သည်",
    category: "Verb",
    options: ["အပြေးလေ့ကျင့်သည်", "လမ်းလျှောက်သည်", "ရေကူးသည်"],
  },
  {
    id: 96,
    chinese: "到",
    pinyin: "dào",
    correct: "ရောက်ရှိသည်",
    category: "Verb",
    options: ["ရောက်ရှိသည်", "ထွက်ခွာသည်", "နေထိုင်သည်"],
  },
  {
    id: 97,
    chinese: "穿",
    pinyin: "chuān",
    correct: "ဝတ်ဆင်သည်",
    category: "Verb",
    options: ["ဝတ်ဆင်သည်", "ချွတ်သည်", "လျှော်ဖွတ်သည်"],
  },
  {
    id: 98,
    chinese: "洗",
    pinyin: "xǐ",
    correct: "ဆေးကြောသည်/လျှော်သည်",
    category: "Verb",
    options: ["ဆေးကြောသည်/လျှော်သည်", "သုတ်သည်", "ညစ်ပတ်သည်"],
  },
  {
    id: 99,
    chinese: "给",
    pinyin: "gěi",
    correct: "ပေးသည်",
    category: "Verb",
    options: ["ပေးသည်", "ယူသည်", "ဝယ်သည်"],
  },
  {
    id: 100,
    chinese: "找",
    pinyin: "zhǎo",
    correct: "ရှာဖွေသည်",
    category: "Verb",
    options: ["ရှာဖွေသည်", "တွေ့ရှိသည်", "ထားခဲ့သည်"],
  },
  {
    id: 101,
    chinese: "懂",
    pinyin: "dǒng",
    correct: "နားလည်သည်",
    category: "Verb",
    options: ["နားလည်သည်", "မေ့သွားသည်", "မသိပါ"],
  },
  {
    id: 102,
    chinese: "笑",
    pinyin: "xiào",
    correct: "ရယ်မောသည်",
    category: "Verb",
    options: ["ရယ်မောသည်", "ငိုသည်", "အော်ဟစ်သည်"],
  },
  {
    id: 103,
    chinese: "告诉",
    pinyin: "gàosù",
    correct: "ပြောပြသည်/အသိပေးသည်",
    category: "Verb",
    options: ["ပြောပြသည်/အသိပေးသည်", "နားထောင်သည်", "မေးမြန်းသည်"],
  },
  {
    id: 104,
    chinese: "准备",
    pinyin: "zhǔnbèi",
    correct: "ပြင်ဆင်သည်",
    category: "Verb",
    options: ["ပြင်ဆင်သည်", "စတင်သည်", "ပြီးဆုံးသည်"],
  },
  {
    id: 105,
    chinese: "开始",
    pinyin: "kāishǐ",
    correct: "စတင်သည်",
    category: "Verb",
    options: ["စတင်သည်", "ပြင်ဆင်သည်", "ရပ်တန့်သည်"],
  },
  {
    id: 106,
    chinese: "介绍",
    pinyin: "jièshào",
    correct: "မိတ်ဆက်ပေးသည်",
    category: "Verb",
    options: ["မိတ်ဆက်ပေးသည်", "နှုတ်ဆက်သည်", "ဖိတ်ကြားသည်"],
  },
  {
    id: 107,
    chinese: "帮助",
    pinyin: "bāngzhù",
    correct: "ကူညီသည်",
    category: "Verb",
    options: ["ကူညီသည်", "တားဆီးသည်", "နှောင့်ယှက်သည်"],
  },
  {
    id: 108,
    chinese: "玩",
    pinyin: "wán",
    correct: "ကစားသည်/အလည်သွားသည်",
    category: "Verb",
    options: ["ကစားသည်/အလည်သွားသည်", "အလုပ်လုပ်သည်", "လေ့လာသည်"],
  },
  {
    id: 109,
    chinese: "送",
    pinyin: "sòng",
    correct: "ပို့ဆောင်သည်/လက်ဆောင်ပေးသည်",
    category: "Verb",
    options: ["ပို့ဆောင်သည်/လက်ဆောင်ပေးသည်", "ယူဆောင်လာသည်", "ဝယ်ယူသည်"],
  },
  {
    id: 110,
    chinese: "等",
    pinyin: "děng",
    correct: "စောင့်ဆိုင်းသည်",
    category: "Verb",
    options: ["စောင့်ဆိုင်းသည်", "ထွက်ခွာသည်", "အလျင်လိုသည်"],
  },
  {
    id: 111,
    chinese: "让",
    pinyin: "ràng",
    correct: "ခွင့်ပြုသည်/စေခိုင်းသည်",
    category: "Verb",
    options: ["ခွင့်ပြုသည်/စေခိုင်းသည်", "တားမြစ်သည်", "အမိန့်ပေးသည်"],
  },
  {
    id: 112,
    chinese: "起床",
    pinyin: "qǐchuáng",
    correct: "အိပ်ရာထသည်",
    category: "Verb",
    options: ["အိပ်ရာထသည်", "အိပ်စက်သည်", "နားနေသည်"],
  },
  {
    id: 113,
    chinese: "唱歌",
    pinyin: "chànggē",
    correct: "သီချင်းဆိုသည်",
    category: "Verb",
    options: ["သီချင်းဆိုသည်", "ကခုန်သည်", "တူရိယာတီးသည်"],
  },
  {
    id: 114,
    chinese: "跳舞",
    pinyin: "tiàowǔ",
    correct: "ကခုန်သည်",
    category: "Verb",
    options: ["ကခုန်သည်", "သီချင်းဆိုသည်", "ရုပ်ရှင်ကြည့်သည်"],
  },
  {
    id: 115,
    chinese: "旅游",
    pinyin: "lǚyóu",
    correct: "ခရီးသွားသည်",
    category: "Verb",
    options: ["ခရီးသွားသည်", "အလုပ်ဆင်းသည်", "ကျောင်းတက်သည်"],
  },
  {
    id: 116,
    chinese: "上班",
    pinyin: "shàngbān",
    correct: "အလုပ်တက်သည်",
    category: "Verb",
    options: ["အလုပ်တက်သည်", "အလုပ်ဆင်းသည်", "အနားယူသည်"],
  },
  {
    id: 117,
    chinese: "生病",
    pinyin: "shēngbìng",
    correct: "ဖျားနာသည်",
    category: "Verb",
    options: ["ဖျားနာသည်", "ကျန်းမာသည်", "ဆေးကုသည်"],
  },
  {
    id: 118,
    chinese: "休息",
    pinyin: "xiūxi",
    correct: "အနားယူသည်",
    category: "Verb",
    options: ["အနားယူသည်", "အလုပ်လုပ်သည်", "အားကစားလုပ်သည်"],
  },
  {
    id: 119,
    chinese: "运动",
    pinyin: "yùndòng",
    correct: "ကိုယ်လက်လှုပ်ရှားသည်",
    category: "Verb",
    options: ["ကိုယ်လက်လှုပ်ရှားသည်", "ထိုင်နေသည်", "စာဖတ်သည်"],
  },
  {
    id: 120,
    chinese: "游泳",
    pinyin: "yóuyǒng",
    correct: "ရေကူးသည်",
    category: "Verb",
    options: ["ရေကူးသည်", "ရေချိုးသည်", "ရေလွှာလျှောစီးသည်"],
  },
  {
    id: 121,
    chinese: "踢足球",
    pinyin: "tī zúqiú",
    correct: "ဘောလုံးကန်သည်",
    category: "Verb",
    options: ["ဘောလုံးကန်သည်", "ဘတ်စကက်ဘောကစားသည်", "တင်းနစ်ရိုက်သည်"],
  },
  {
    id: 122,
    chinese: "打篮球",
    pinyin: "dǎ lánqiú",
    correct: "ဘတ်စကက်ဘောကစားသည်",
    category: "Verb",
    options: ["ဘတ်စကက်ဘောကစားသည်", "ဘောလုံးကန်သည်", "ရေကူးသည်"],
  },
  {
    id: 123,
    chinese: "完",
    pinyin: "wán",
    correct: "ပြီးဆုံးသည်/ကုန်ဆုံးသည်",
    category: "Verb",
    options: ["ပြီးဆုံးသည်/ကုန်ဆုံးသည်", "စတင်သည်", "ပြင်ဆင်သည်"],
  },
  {
    id: 124,
    chinese: "觉得",
    pinyin: "juédé",
    correct: "ထင်မြင်သည်/ခံစားရသည်",
    category: "Verb",
    options: ["ထင်မြင်သည်/ခံစားရသည်", "သိရှိသည်", "မေ့လျော့သည်"],
  },
  {
    id: 125,
    chinese: "知道",
    pinyin: "zhīdao",
    correct: "သိသည်/နားလည်သည်",
    category: "Verb",
    options: ["သိသည်/နားလည်သည်", "ထင်သည်", "မေးမြန်းသည်"],
  },
  {
    id: 126,
    chinese: "希望",
    pinyin: "xīwàng",
    correct: "မျှော်လင့်သည်",
    category: "Verb",
    options: ["မျှော်လင့်သည်", "ကြောက်ရွံ့သည်", "စိတ်ပျက်သည်"],
  },
  {
    id: 127,
    chinese: "可以",
    pinyin: "kěyǐ",
    correct: "ရသည်/နိုင်သည်",
    category: "Verb",
    options: ["ရသည်/နိုင်သည်", "မရပါ", "မဖြစ်နိုင်ပါ"],
  },
  {
    id: 128,
    chinese: "要",
    pinyin: "yào",
    correct: "အလိုရှိသည်/ယူမည်",
    category: "Verb",
    options: ["အလိုရှိသည်/ယူမည်", "ပေးမည်", "ရောင်းမည်"],
  },
  {
    id: 129,
    chinese: "可能",
    pinyin: "kěnéng",
    correct: "ဖြစ်နိုင်သည်/ကောင်းရှိမည်",
    category: "Verb",
    options: ["ဖြစ်နိုင်သည်/ကောင်းရှိမည်", "သေချာသည်", "မဖြစ်နိုင်ပါ"],
  },
  {
    id: 130,
    chinese: "高",
    pinyin: "gāo",
    correct: "မြင့်သော/အရပ်ရှည်သော",
    category: "Adjective",
    options: ["မြင့်သော/အရပ်ရှည်သော", "နိမ့်သော", "တိုသော"],
  },
  {
    id: 131,
    chinese: "红",
    pinyin: "hóng",
    correct: "အနီရောင်",
    category: "Adjective",
    options: ["အနီရောင်", "အဖြူရောင်", "အနက်ရောင်"],
  },
  {
    id: 132,
    chinese: "白",
    pinyin: "bái",
    correct: "အဖြူရောင်",
    category: "Adjective",
    options: ["အဖြူရောင်", "အနီရောင်", "အဝါရောင်"],
  },
  {
    id: 133,
    chinese: "黑",
    pinyin: "hēi",
    correct: "အနက်ရောင်",
    category: "Adjective",
    options: ["အနက်ရောင်", "အဖြူရောင်", "အစိမ်းရောင်"],
  },
  {
    id: 134,
    chinese: "忙",
    pinyin: "máng",
    correct: "အလုပ်ရှုပ်သော",
    category: "Adjective",
    options: ["အလုပ်ရှုပ်သော", "အားလပ်သော", "အိပ်ချင်သော"],
  },
  {
    id: 135,
    chinese: "快",
    pinyin: "kuài",
    correct: "မြန်သော",
    category: "Adjective",
    options: ["မြန်သော", "နှေးသော", "ဝေးသော"],
  },
  {
    id: 136,
    chinese: "慢",
    pinyin: "màn",
    correct: "နှေးသော",
    category: "Adjective",
    options: ["နှေးသော", "မြန်သော", "နီးသော"],
  },
  {
    id: 137,
    chinese: "远",
    pinyin: "yuǎn",
    correct: "ဝေးသော",
    category: "Adjective",
    options: ["ဝေးသော", "နီးသော", "ကျယ်သော"],
  },
  {
    id: 138,
    chinese: "近",
    pinyin: "jìn",
    correct: "နီးသော",
    category: "Adjective",
    options: ["နီးသော", "ဝေးသော", "မြင့်သော"],
  },
  {
    id: 139,
    chinese: "好吃",
    pinyin: "hǎochī",
    correct: "စားကောင်းသော",
    category: "Adjective",
    options: ["စားကောင်းသော", "သောက်ကောင်းသော", "လှပသော"],
  },
  {
    id: 140,
    chinese: "累",
    pinyin: "lèi",
    correct: "ပင်ပန်းသော",
    category: "Adjective",
    options: ["ပင်ပန်းသော", "ပျော်ရွှင်သော", "လန်းဆန်းသော"],
  },
  {
    id: 141,
    chinese: "长",
    pinyin: "cháng",
    correct: "ရှည်သော",
    category: "Adjective",
    options: ["ရှည်သော", "တိုသော", "သေးသော"],
  },
  {
    id: 142,
    chinese: "新",
    pinyin: "xīn",
    correct: "သစ်သော",
    category: "Adjective",
    options: ["သစ်သော", "ဟောင်းသော", "ညစ်ပတ်သော"],
  },
  {
    id: 143,
    chinese: "贵",
    pinyin: "guì",
    correct: "ဈေးကြီးသော",
    category: "Adjective",
    options: ["ဈေးကြီးသော", "ဈေးပေါသော", "ရိုးရှင်းသော"],
  },
  {
    id: 144,
    chinese: "便宜",
    pinyin: "piányi",
    correct: "ဈေးပေါသော",
    category: "Adjective",
    options: ["ဈေးပေါသော", "ဈေးကြီးသော", "လှပသော"],
  },
  {
    id: 145,
    chinese: "晴",
    pinyin: "qíng",
    correct: "သာယာသော (ရာသီဥတု)",
    category: "Adjective",
    options: ["သာယာသော (ရာသီဥတု)", "အုံ့မှိုင်းသော", "မိုးရွာသော"],
  },
  {
    id: 146,
    chinese: "阴",
    pinyin: "yīn",
    correct: "အုံ့မှိုင်းသော",
    category: "Adjective",
    options: ["အုံ့မှိုင်းသော", "နေသာသော", "ပူပြင်းသော"],
  },
  {
    id: 147,
    chinese: "错",
    pinyin: "cuò",
    correct: "မှားယွင်းသော",
    category: "Adjective",
    options: ["မှားယွင်းသော", "မှန်ကန်သော", "ကောင်းမွန်သော"],
  },
  {
    id: 148,
    chinese: "快樂",
    pinyin: "kuàilè",
    correct: "ပျော်ရွှင်သော",
    category: "Adjective",
    options: ["ပျော်ရွှင်သော", "ဝမ်းနည်းသော", "ဗိုက်ဆာသော"],
  },
  {
    id: 149,
    chinese: "对",
    pinyin: "duì",
    correct: "သို့/ဘက်သို့ (Preposition)",
    category: "Preposition",
    options: ["သို့/ဘက်သို့ (Preposition)", "မှ", "အကြောင်း"],
  },
  {
    id: 150,
    chinese: "对",
    pinyin: "duì",
    correct: "မှန်ကန်သော",
    category: "Adjective",
    options: ["မှန်ကန်သော", "မှားယွင်းသော", "မသေချာသော"],
  },
];

export default datas;
export const hsk2adj = [
  { id: 1, chinese: "高", pinyin: "gāo", myanmar: "မြင့်သော/အရပ်ရှည်သော" },
  { id: 2, chinese: "红", pinyin: "hóng", myanmar: "အနီရောင်" },
  { id: 3, chinese: "白", pinyin: "bái", myanmar: "အဖြူရောင်" },
  { id: 4, chinese: "黑", pinyin: "hēi", myanmar: "အနက်ရောင်" },
  { id: 5, chinese: "忙", pinyin: "máng", myanmar: "အလုပ်ရှုပ်သော" },
  { id: 6, chinese: "快", pinyin: "kuài", myanmar: "မြန်သော" },
  { id: 7, chinese: "慢", pinyin: "màn", myanmar: "နှေးသော" },
  { id: 8, chinese: "远", pinyin: "yuǎn", myanmar: "ဝေးသော" },
  { id: 9, chinese: "近", pinyin: "jìn", myanmar: "နီးသော" },
  { id: 10, chinese: "好吃", pinyin: "hǎochī", myanmar: "စားကောင်းသော" },
  { id: 11, chinese: "累", pinyin: "lèi", myanmar: "ပင်ပန်းသော" },
  { id: 12, chinese: "长", pinyin: "cháng", myanmar: "ရှည်သော" },
  { id: 13, chinese: "新", pinyin: "xīn", myanmar: "သစ်သော" },
  { id: 14, chinese: "贵", pinyin: "guì", myanmar: "ဈေးကြီးသော" },
  { id: 15, chinese: "便宜", pinyin: "piányi", myanmar: "ဈေးပေါသော" },
  { id: 16, chinese: "晴", pinyin: "qíng", myanmar: "သာယာသော (ရာသီဥတု)" },
  { id: 17, chinese: "阴", pinyin: "yīn", myanmar: "အုံ့မှိုင်းသော" },
  { id: 18, chinese: "错", pinyin: "cuò", myanmar: "မှားယွင်းသော" },
  { id: 19, chinese: "快乐", pinyin: "kuàilè", myanmar: "ပျော်ရွှင်သော" },
];


export const hsk2verbs = [
  { id: 1, chinese: "说话", pinyin: "shuōhuà", myanmar: "စကားပြောသည်" },
  { id: 2, chinese: "卖", pinyin: "mài", myanmar: "ရောင်းသည်" },
  { id: 3, chinese: "问", pinyin: "wèn", myanmar: "မေးမြန်းသည်" },
  { id: 4, chinese: "走", pinyin: "zǒu", myanmar: "လမ်းလျှောက်သည်" },
  { id: 5, chinese: "进", pinyin: "jìn", myanmar: "ဝင်သည်" },
  { id: 6, chinese: "出", pinyin: "chū", myanmar: "ထွက်သည်" },
  { id: 7, chinese: "跑步", pinyin: "pǎobù", myanmar: "အပြေးလေ့ကျင့်သည်" },
  { id: 8, chinese: "到", pinyin: "dào", myanmar: "ရောက်ရှိသည်" },
  { id: 9, chinese: "穿", pinyin: "chuān", myanmar: "ဝတ်ဆင်သည်" },
  { id: 10, chinese: "洗", pinyin: "xǐ", myanmar: "ဆေးကြောသည်/လျှော်သည်" },
  { id: 11, chinese: "给", pinyin: "gěi", myanmar: "ပေးသည်" },
  { id: 12, chinese: "找", pinyin: "zhǎo", myanmar: "ရှာဖွေသည်" },
  { id: 13, chinese: "懂", pinyin: "dǒng", myanmar: "နားလည်သည်" },
  { id: 14, chinese: "笑", pinyin: "xiào", myanmar: "ရယ်မောသည်" },
  { id: 15, chinese: "告诉", pinyin: "gàosù", myanmar: "ပြောပြသည်" },
  { id: 16, chinese: "准备", pinyin: "zhǔnbèi", myanmar: "ပြင်ဆင်သည်" },
  { id: 17, chinese: "开始", pinyin: "kāishǐ", myanmar: "စတင်သည်" },
  { id: 18, chinese: "介绍", pinyin: "jièshào", myanmar: "မိတ်ဆက်ပေးသည်" },
  { id: 19, chinese: "帮助", pinyin: "bāngzhù", myanmar: "ကူညီသည်" },
  { id: 20, chinese: "玩", pinyin: "wán", myanmar: "ကစားသည်" },
  {
    id: 21,
    chinese: "送",
    pinyin: "sòng",
    myanmar: "ပို့ဆောင်သည်/လက်ဆောင်ပေးသည်",
  },
  { id: 22, chinese: "等", pinyin: "děng", myanmar: "စောင့်ဆိုင်းသည်" },
  { id: 23, chinese: "让", pinyin: "ràng", myanmar: "ခွင့်ပြုသည်/စေခိုင်းသည်" },
  { id: 24, chinese: "起床", pinyin: "qǐchuáng", myanmar: "အိပ်ရာထသည်" },
  { id: 25, chinese: "唱歌", pinyin: "chànggē", myanmar: "သီချင်းဆိုသည်" },
  { id: 26, chinese: "跳舞", pinyin: "tiàowǔ", myanmar: "ကခုန်သည်" },
  { id: 27, chinese: "旅游", pinyin: "lǚyóu", myanmar: "ခရီးသွားသည်" },
  { id: 28, chinese: "上班", pinyin: "shàngbān", myanmar: "အလုပ်တက်သည်" },
  { id: 29, chinese: "生病", pinyin: "shēngbìng", myanmar: "ဖျားနာသည်" },
  { id: 30, chinese: "休息", pinyin: "xiūxi", myanmar: "အနားယူသည်" },
  {
    id: 31,
    chinese: "运动",
    pinyin: "yùndòng",
    myanmar: "ကိုယ်လက်လှုပ်ရှားသည်",
  },
  { id: 32, chinese: "游泳", pinyin: "yóuyǒng", myanmar: "ရေကူးသည်" },
  { id: 33, chinese: "踢足球", pinyin: "tī zúqiú", myanmar: "ဘောလုံးကန်သည်" },
  {
    id: 34,
    chinese: "打篮球",
    pinyin: "dǎ lánqiú",
    myanmar: "ဘတ်စကက်ဘောကစားသည်",
  },
  { id: 35, chinese: "觉得", pinyin: "juédé", myanmar: "ထင်မြင်သည်" },
  { id: 36, chinese: "知道", pinyin: "zhīdao", myanmar: "သိသည်" },
  { id: 37, chinese: "希望", pinyin: "xīwàng", myanmar: "မျှော်လင့်သည်" },
  { id: 38, chinese: "可以", pinyin: "kěyǐ", myanmar: "ရသည်/နိုင်သည်" },
  { id: 39, chinese: "要", pinyin: "yào", myanmar: "အလိုရှိသည်" },
];


export const hsk2nouns = [
  { id: 1, chinese: "机场", pinyin: "jīchǎng", myanmar: "လေဆိပ်" },
  { id: 2, chinese: "教室", pinyin: "jiàoshì", myanmar: "စာသင်ခန်း" },
  { id: 3, chinese: "房间", pinyin: "fángjiān", myanmar: "အခန်း" },
  { id: 4, chinese: "路", pinyin: "lù", myanmar: "လမ်း" },
  { id: 5, chinese: "左边", pinyin: "zuǒbiān", myanmar: "ဘယ်ဘက်" },
  { id: 6, chinese: "右边", pinyin: "yòubiān", myanmar: "ညာဘက်" },
  { id: 7, chinese: "外", pinyin: "wài", myanmar: "အပြင်ဘက်" },
  { id: 8, chinese: "旁边", pinyin: "pángbiān", myanmar: "ဘေးနား" },
  { id: 9, chinese: "哥哥", pinyin: "gēge", myanmar: "အစ်ကို" },
  { id: 10, chinese: "姐姐", pinyin: "jiějie", myanmar: "အစ်မ" },
  { id: 11, chinese: "弟弟", pinyin: "dìdi", myanmar: "ညီလေး/မောင်လေး" },
  { id: 12, chinese: "妹妹", pinyin: "mèimei", myanmar: "ညီမလေး" },
  { id: 13, chinese: "丈夫", pinyin: "zhàngfu", myanmar: "ခင်ပွန်း" },
  { id: 14, chinese: "妻子", pinyin: "qīzi", myanmar: "ဇနီး" },
  { id: 15, chinese: "孩子", pinyin: "háizi", myanmar: "ကလေး" },
  { id: 16, chinese: "男人", pinyin: "nánrén", myanmar: "အမျိုးသား" },
  { id: 17, chinese: "女人", pinyin: "nǚrén", myanmar: "အမျိုးသမီး" },
  { id: 18, chinese: "服务员", pinyin: "fúwùyuán", myanmar: "ဝန်ထမ်း" },
  { id: 19, chinese: "鱼", pinyin: "yú", myanmar: "ငါး" },
  { id: 20, chinese: "羊肉", pinyin: "yángròu", myanmar: "ဆိတ်သား/သိုးသား" },
  { id: 21, chinese: "牛奶", pinyin: "niúnǎi", myanmar: "နွားနို့" },
  { id: 22, chinese: "鸡蛋", pinyin: "jīdàn", myanmar: "ကြက်ဥ" },
  { id: 23, chinese: "西瓜", pinyin: "xīguā", myanmar: "ဖရဲသီး" },
  { id: 24, chinese: "咖啡", pinyin: "kāfēi", myanmar: "ကော်ဖီ" },
  { id: 25, chinese: "雪", pinyin: "xuě", myanmar: "နှင်း" },
  { id: 26, chinese: "药", pinyin: "yào", myanmar: "ဆေး" },
  { id: 27, chinese: "手机", pinyin: "shǒujī", myanmar: "လက်ကိုင်ဖုန်း" },
  { id: 28, chinese: "手表", pinyin: "shǒubiǎo", myanmar: "လက်ပတ်နာရီ" },
  { id: 29, chinese: "眼睛", pinyin: "yǎnjing", myanmar: "မျက်လုံး" },
  { id: 30, chinese: "身体", pinyin: "shēntǐ", myanmar: "ခန္ဓာကိုယ်" },
  {
    id: 31,
    chinese: "公共汽车",
    pinyin: "gōnggòng qìchē",
    myanmar: "ဘတ်စ်ကား",
  },
  { id: 32, chinese: "报纸", pinyin: "bàozhǐ", myanmar: "သတင်းစာ" },
  { id: 33, chinese: "门", pinyin: "mén", myanmar: "တံခါး" },
  { id: 34, chinese: "题", pinyin: "tí", myanmar: "မေးခွန်း/ခေါင်းစဉ်" },
  { id: 35, chinese: "课", pinyin: "kè", myanmar: "သင်ခန်းစာ" },
  { id: 36, chinese: "姓", pinyin: "xìng", myanmar: "မျိုးရိုးအမည်" },
  { id: 37, chinese: "问题", pinyin: "wèntí", myanmar: "ပြဿနာ" },
  { id: 38, chinese: "事情", pinyin: "shìqing", myanmar: "ကိစ္စ" },
  { id: 39, chinese: "考试", pinyin: "kǎoshì", myanmar: "စာမေးပွဲ" },
  { id: 40, chinese: "票", pinyin: "piào", myanmar: "လက်မှတ်" },
  { id: 41, chinese: "意思", pinyin: "yìsi", myanmar: "အဓိပ္ပာယ်" },
  { id: 42, chinese: "颜色", pinyin: "yánsè", myanmar: "အရောင်" },
  { id: 43, chinese: "铅笔", pinyin: "qiānbǐ", myanmar: "ခဲတံ" },
  { id: 44, chinese: "面条", pinyin: "miàntiáo", myanmar: "ခေါက်ဆွဲ" },
  { id: 45, chinese: "火车站", pinyin: "huǒchēzhàn", myanmar: "မီးရထားဘူတာ" },
  { id: 46, chinese: "公司", pinyin: "gōngsī", myanmar: "ကုမ္ပဏီ" },
  { id: 47, chinese: "宾馆", pinyin: "bīnguǎn", myanmar: "ဟိုတယ်" },
  { id: 48, chinese: "天气", pinyin: "tiānqì", myanmar: "ရာသီဥတု" },
  { id: 49, chinese: "东西", pinyin: "dōngxi", myanmar: "ပစ္စည်း" },
  { id: 50, chinese: "人", pinyin: "rén", myanmar: "လူ" },
  { id: 51, chinese: "名字", pinyin: "míngzi", myanmar: "နာမည်" },
  { id: 52, chinese: "书", pinyin: "shū", myanmar: "စာအုပ်" },
  { id: 53, chinese: "汉语", pinyin: "hànyǔ", myanmar: "တရုတ်စကား" },
  { id: 54, chinese: "字", pinyin: "zì", myanmar: "စာလုံး" },
  { id: 55, chinese: "桌子", pinyin: "zhuōzi", myanmar: "စားပွဲ" },
  { id: 56, chinese: "椅子", pinyin: "yǐzi", myanmar: "ကုလားထိုင်" },
];


export const hsk2adverbs = [
  { id: 1, chinese: "非常", pinyin: "fēicháng", myanmar: "အလွန်အမင်း" },
  { id: 2, chinese: "也", pinyin: "yě", myanmar: "လည်း/လည်းပဲ" },
  { id: 3, chinese: "还", pinyin: "hái", myanmar: "ကျန်သေးသည်/ရှိသေးသည်" },
  { id: 4, chinese: "最", pinyin: "zuì", myanmar: "အ...ဆုံး" },
  { id: 5, chinese: "真", pinyin: "zhēn", myanmar: "တကယ်/တကယ့်" },
  {
    id: 6,
    chinese: "正在",
    pinyin: "zhèngzài",
    myanmar: "နေသည် (လုပ်ဆောင်ဆဲ)",
  },
  { id: 7, chinese: "已经", pinyin: "yǐjīng", myanmar: "ပြီးပြီ/ပြီးခဲ့ပြီ" },
  { id: 8, chinese: "一起", pinyin: "yìqǐ", myanmar: "အတူတူ" },
  { id: 9, chinese: "再", pinyin: "zài", myanmar: "ထပ်ပြီး" },
  { id: 10, chinese: "就", pinyin: "jiù", myanmar: "ချက်ချင်း/ဆိုလျှင်" },
  { id: 11, chinese: "别", pinyin: "bié", myanmar: "မ...နှင့် (Don't)" },
];


export const commons = [
  { id: 1, chinese: "你好！", pinyin: "Nǐ hǎo!", myanmar: "မင်္ဂလာပါ!" },
  {
    id: 2,
    chinese: "谢谢你。",
    pinyin: "Xièxie nǐ.",
    myanmar: "ကျေးဇူးတင်ပါတယ်။",
  },
  {
    id: 3,
    chinese: "不客气。",
    pinyin: "Bú kèqi.",
    myanmar: "ကိစ္စမရှိပါဘူး / ရပါတယ်။",
  },
  {
    id: 4,
    chinese: "对不起。",
    pinyin: "Duìbuqǐ.",
    myanmar: "တောင်းပန်ပါတယ်။",
  },
  {
    id: 5,
    chinese: "没关系。",
    pinyin: "Méi guānxi.",
    myanmar: "ဘာမှမဖြစ်ပါဘူး / ရပါတယ်။",
  },
  {
    id: 6,
    chinese: "再见。",
    pinyin: "Zàijiàn.",
    myanmar: "သွားဦးမယ် / ပြန်တွေ့ကြတာပေါ့။",
  },
  { id: 7, chinese: "请坐。", pinyin: "Qǐng zuò.", myanmar: "ထိုင်ပါ။" },
  {
    id: 8,
    chinese: "请喝茶。",
    pinyin: "Qǐng hē chá.",
    myanmar: "လက်ဖက်ရည်သောက်ပါဦး။",
  },
  {
    id: 9,
    chinese: "没问题。",
    pinyin: "Méi wèntí.",
    myanmar: "ပြဿနာမရှိပါဘူး။",
  },
  { id: 10, chinese: "别客气。", pinyin: "Bié kèqi.", myanmar: "အားမနာပါနဲ့။" },
  { id: 11, chinese: "我知道。", pinyin: "Wǒ zhīdào.", myanmar: "ငါသိတယ်။" },
  {
    id: 12,
    chinese: "我不知道。",
    pinyin: "Wǒ bù zhīdào.",
    myanmar: "ငါမသိဘူး။",
  },
  {
    id: 13,
    chinese: "没关系，慢慢来。",
    pinyin: "Méi guānxi, mànman lái.",
    myanmar: "ရပါတယ်၊ ဖြည်းဖြည်းချင်းလုပ်ပါ။",
  },
  {
    id: 14,
    chinese: "请问，几点了？",
    pinyin: "Qǐngwèn, jǐ diǎn le?",
    myanmar: "တစ်ဆိတ်လောက်၊ ဘယ်နှစ်နာရီရှိပြီလဲ?",
  },
  {
    id: 15,
    chinese: "现在三点。",
    pinyin: "Xiànzài sān diǎn.",
    myanmar: "အခု သုံးနာရီပါ။",
  },
  {
    id: 16,
    chinese: "你去哪儿？",
    pinyin: "Nǐ qù nǎr? ",
    myanmar: "မင်း ဘယ်သွားမလို့လဲ?",
  },
  {
    id: 17,
    chinese: "我去学校。",
    pinyin: "Wǒ qù xuéxiào.",
    myanmar: "ငါ ကျောင်းသွားမလို့။",
  },
  { id: 18, chinese: "欢迎！", pinyin: "Huānyíng!", myanmar: "ကြိုဆိုပါတယ်!" },
  {
    id: 19,
    chinese: "生日快乐！",
    pinyin: "Shēngrì kuàilè!",
    myanmar: "မွေးနေ့မှာ ပျော်ရွှင်ပါစေ!",
  },
  {
    id: 20,
    chinese: "祝你身体健康。",
    pinyin: "Zhù nǐ shēntǐ jiànkāng.",
    myanmar: "ကျန်းမာပါစေလို့ ဆုတောင်းပေးပါတယ်။",
  },
  {
    id: 21,
    chinese: "太好了！",
    pinyin: "Tài hǎo le!",
    myanmar: "အရမ်းကောင်းတာပဲ!",
  },
  {
    id: 22,
    chinese: "我累了。",
    pinyin: "Wǒ lèi le.",
    myanmar: "ငါ ပင်ပန်းနေပြီ။",
  },
  {
    id: 23,
    chinese: "我饿了。",
    pinyin: "Wǒ è le.",
    myanmar: "ငါ ဗိုက်ဆာပြီ။",
  },
  {
    id: 24,
    chinese: "等一下。",
    pinyin: "Děng yíxià.",
    myanmar: "ခဏစောင့်ပါ။",
  },
  {
    id: 25,
    chinese: "好的。",
    pinyin: "Hǎo de.",
    myanmar: "ဟုတ်ကဲ့ / ကောင်းပါပြီ။",
  },
  { id: 26, chinese: "行吗？", pinyin: "Xíng ma?", myanmar: "ရမလား?" },
  { id: 27, chinese: "不行。", pinyin: "Bù xíng.", myanmar: "မရပါဘူး။" },
  { id: 28, chinese: "真的吗？", pinyin: "Zhēn de ma?", myanmar: "တကယ်လား?" },
  {
    id: 29,
    chinese: "当然可以。",
    pinyin: "Dāngrán kěyǐ.",
    myanmar: "သေချာပေါက် ရတာပေါ့။",
  },
  {
    id: 30,
    chinese: "谁在那儿？",
    pinyin: "Shéi zài nàr?",
    myanmar: "ဟိုမှာ ဘယ်သူလဲ?",
  },
  {
    id: 31,
    chinese: "我是你的老师。",
    pinyin: "Wǒ shì nǐ de lǎoshī.",
    myanmar: "ငါက မင်းရဲ့ဆရာပါ။",
  },
  {
    id: 32,
    chinese: "他是我的同学。",
    pinyin: "Tā shì wǒ de tóngxué.",
    myanmar: "သူက ငါ့ရဲ့အတန်းဖော်ပါ။",
  },
  {
    id: 33,
    chinese: "我在看书。",
    pinyin: "Wǒ zài kànshū.",
    myanmar: "ငါ စာဖတ်နေတယ်။",
  },
  {
    id: 34,
    chinese: "你在做什么？",
    pinyin: "Nǐ zài zuò shénme?",
    myanmar: "မင်း ဘာလုပ်နေတာလဲ?",
  },
  {
    id: 35,
    chinese: "我在看电视。",
    pinyin: "Wǒ zài kàn diànshì.",
    myanmar: "ငါ တီဗွီကြည့်နေတယ်။",
  },
  {
    id: 36,
    chinese: "医院在哪儿？",
    pinyin: "Yīyuàn zài nǎr?",
    myanmar: "ဆေးရုံက ဘယ်မှာလဲ?",
  },
  {
    id: 37,
    chinese: "火车站不远。",
    pinyin: "Huǒchēzhàn bù yuǎn.",
    myanmar: "ရထားဘူတာက မဝေးဘူး။",
  },
  {
    id: 38,
    chinese: "往左走。",
    pinyin: "Wǎng zuǒ zǒu.",
    myanmar: "ဘယ်ဘက်ကိုသွားပါ။",
  },
  {
    id: 39,
    chinese: "往右拐。",
    pinyin: "Wǎng yòu guǎi.",
    myanmar: "ညာဘက်ကို ကွေ့ပါ။",
  },
  {
    id: 40,
    chinese: "公共汽车站到了။",
    pinyin: "Gōnggòng qìchēzhàn dào le.",
    myanmar: "ဘတ်စ်ကားဂိတ်ကို ရောက်ပြီ။",
  },
  {
    id: 41,
    chinese: "机场很大。",
    pinyin: "Jīchǎng hěn dà.",
    myanmar: "လေဆိပ်က အရမ်းကြီးတယ်။",
  },
  {
    id: 42,
    chinese: "我坐出租车去。",
    pinyin: "Wǒ zuò chūzūchē qù.",
    myanmar: "ငါ တက္ကစီနဲ့သွားမယ်။",
  },
  {
    id: 43,
    chinese: "你的房间在那儿。",
    pinyin: "Nǐ de fángjiān zài nàr.",
    myanmar: "မင်းရဲ့အခန်းက ဟိုမှာပါ။",
  },
  {
    id: 44,
    chinese: "我家离公司很近。",
    pinyin: "Wǒjiā lí gōngsī hěn jìn.",
    myanmar: "ငါ့အိမ်က ကုမ္ပဏီနဲ့ အရမ်းနီးတယ်။",
  },
  {
    id: 45,
    chinese: "宾馆在商店旁边。",
    pinyin: "Bīnguǎn zài shāngdiàn pángbiān.",
    myanmar: "ဟိုတယ်က စတိုးဆိုင်ဘေးမှာပါ။",
  },
  {
    id: 46,
    chinese: "桌子上有一本书。",
    pinyin: "Zhuōzi shàng yǒu yì běn shū.",
    myanmar: "စားပွဲပေါ်မှာ စာအုပ်တစ်အုပ်ရှိတယ်။",
  },
  {
    id: 47,
    chinese: "椅子下面有一只猫。",
    pinyin: "Yǐzi xiàmiàn yǒu yì zhī māo.",
    myanmar: "ကုလားထိုင်အောက်မှာ ကြောင်တစ်ကောင်ရှိတယ်။",
  },
  {
    id: 48,
    chinese: "门外有人。",
    pinyin: "Mén wài yǒu rén.",
    myanmar: "တံခါးအပြင်မှာ လူရှိတယ်။",
  },
  {
    id: 49,
    chinese: "你住在哪儿？",
    pinyin: "Nǐ zhù zài nǎr?",
    myanmar: "မင်း ဘယ်မှာနေသလဲ?",
  },
  {
    id: 50,
    chinese: "我住在二号楼。",
    pinyin: "Wǒ zhù zài èr hào lóu.",
    myanmar: "ငါ အဆောက်အဦးနံပါတ် (၂) မှာနေတယ်။",
  },
  {
    id: 51,
    chinese: "教室里有十个学生。",
    pinyin: "Jiàoshì lǐ yǒu shí gè xuéshēng.",
    myanmar: "စာသင်ခန်းထဲမှာ ကျောင်းသား ၁၀ ယောက်ရှိတယ်။",
  },
  {
    id: 52,
    chinese: "电脑在桌子上。",
    pinyin: "Diànnǎo zài zhuōzi shàng.",
    myanmar: "ကွန်ပျူတာက စားပွဲပေါ်မှာပါ။",
  },
  {
    id: 53,
    chinese: "这里不能停车。",
    pinyin: "Zhèlǐ bùnéng tíngchē.",
    myanmar: "ဒီမှာ ကားမရပ်ရဘူး။",
  },
  {
    id: 54,
    chinese: "请问，怎么走？",
    pinyin: "Qǐngwèn, zěnme zǒu?",
    myanmar: "တစ်ဆိတ်လောက်၊ ဘယ်လိုသွားရမလဲ?",
  },
  {
    id: 55,
    chinese: "你的手机在哪儿？",
    pinyin: "Nǐ de shǒujī zài nǎr?",
    myanmar: "မင်းဖုန်း ဘယ်မှာလဲ?",
  },
  {
    id: 56,
    chinese: "手机在书包里。",
    pinyin: "Shǒujī zài shūbāo lǐ.",
    myanmar: "ဖုန်းက လွယ်အိတ်ထဲမှာပါ။",
  },
  {
    id: 57,
    chinese: "这个多少钱？",
    pinyin: "Zhège duōshao qián?",
    myanmar: "ဒါ ဘယ်လောက်လဲ?",
  },
  {
    id: 58,
    chinese: "太贵了，便宜点儿。",
    pinyin: "Tài guì le, piányi diǎnr.",
    myanmar: "အရမ်းဈေးကြီးတယ်၊ နည်းနည်းလျှော့ပေးပါ။",
  },
  {
    id: 59,
    chinese: "我想买一件衣服。",
    pinyin: "Wǒ xiǎng mǎi yí jiàn yīfu.",
    myanmar: "ငါ အင်္ကျီတစ်ထည် ဝယ်ချင်တယ်။",
  },
  {
    id: 60,
    chinese: "商店几点开门？",
    pinyin: "Shāngdiàn jǐ diǎn kāimén?",
    myanmar: "ဆိုင်က ဘယ်နှစ်နာရီ ဖွင့်မလဲ?",
  },
  {
    id: 61,
    chinese: "商店晚上八点关门。",
    pinyin: "Shāngdiàn wǎnshàng bā diǎn guānmén.",
    myanmar: "ဆိုင်က ည ၈ နာရီ ပိတ်ပါတယ်။",
  },
  {
    id: 62,
    chinese: "我要买张票。",
    pinyin: "Wǒ yào mǎi zhāng piào.",
    myanmar: "ငါ လက်မှတ်တစ်စောင် ဝယ်မယ်။",
  },
  {
    id: 63,
    chinese: "这里有药店吗？",
    pinyin: "Zhèlǐ yǒu yàodiàn ma?",
    myanmar: "ဒီမှာ ဆေးဆိုင်ရှိလား? ",
  },
  {
    id: 64,
    chinese: "药店在前面。",
    pinyin: "Yàodiàn zài qiánmiàn.",
    myanmar: "ဆေးဆိုင်က ရှေ့မှာပါ။",
  },
  {
    id: 65,
    chinese: "你开车慢点儿。",
    pinyin: "Nǐ kāichē màn diǎnr.",
    myanmar: "ကားကို ဖြည်းဖြည်းမောင်းပါ။",
  },
  {
    id: 66,
    chinese: "今天天气怎么样？",
    pinyin: "Jīntiān tiānqì zěnmeyàng?",
    myanmar: "ဒီနေ့ ရာသီဥတု ဘယ်လိုလဲ?",
  },
  {
    id: 67,
    chinese: "今天是晴天。",
    pinyin: "Jīntiān shì qíngtiān.",
    myanmar: "ဒီနေ့ နေသာတယ်။",
  },
  {
    id: 68,
    chinese: "明天会下雪。",
    pinyin: "Míngtiān huì xià xuě.",
    myanmar: "မနက်ဖြန် နှင်းကျလိမ့်မယ်။",
  },
  {
    id: 69,
    chinese: "外面在下雨。",
    pinyin: "Wài miàn zài xià yǔ.",
    myanmar: "အပြင်မှာ မိုးရွာနေတယ်။",
  },
  {
    id: 70,
    chinese: "阴天，不出去了。",
    pinyin: "Yīn tiān, bù chūqù le.",
    myanmar: "မိုးအုံ့နေတယ်၊ အပြင်မသွားတော့ဘူး။",
  },
  {
    id: 71,
    chinese: "你怎么了？",
    pinyin: "Nǐ zěnme le?",
    myanmar: "မင်း ဘာဖြစ်လို့လဲ?",
  },
  {
    id: 72,
    chinese: "我生病了。",
    pinyin: "Wǒ shēngbìng le.",
    myanmar: "ငါ နေမကောင်းဘူး။",
  },
  {
    id: 73,
    chinese: "我头疼。",
    pinyin: "Wǒ tóuténg.",
    myanmar: "ငါ ခေါင်းကိုက်တယ်။",
  },
  {
    id: 74,
    chinese: "医生说我要休息。",
    pinyin: "Yīshēng shuō wǒ yào xiūxi.",
    myanmar: "ဆရာဝန်က ငါ့ကို အနားယူခိုင်းတယ်။",
  },
  {
    id: 75,
    chinese: "记得吃药。",
    pinyin: "Jìde chī yào.",
    myanmar: "ဆေးသောက်ဖို့ သတိရပါ။",
  },
  {
    id: 76,
    chinese: "你多喝点儿水。",
    pinyin: "Nǐ duō hē diǎnr shuǐ.",
    myanmar: "ရေများများသောက်ပါ။",
  },
  {
    id: 77,
    chinese: "你觉得怎么样？",
    pinyin: "Nǐ juéde zěnmeyàng?",
    myanmar: "မင်း ဘယ်လိုခံစားရလဲ?",
  },
  {
    id: 78,
    chinese: "我觉得好多了。",
    pinyin: "Wǒ juéde hǎo duō le.",
    myanmar: "ငါ တော်တော်သက်သာသွားပြီ။",
  },
  {
    id: 79,
    chinese: "你喜欢运动吗？",
    pinyin: "Nǐ xǐhuan yùndòng ma?",
    myanmar: "မင်း အားကစားလုပ်ရတာ ကြိုက်လား?",
  },
  {
    id: 80,
    chinese: "我喜欢跑步。",
    pinyin: "Wǒ xǐhuan pǎobù.",
    myanmar: "ငါ အပြေးလေ့ကျင့်ရတာ ကြိုက်တယ်။",
  },
  {
    id: 81,
    chinese: "我们一起游泳吧。",
    pinyin: "Wǒmen yìqǐ yóuyǒng ba.",
    myanmar: "ငါတို့ အတူတူ ရေကူးကြရအောင်။",
  },
  {
    id: 82,
    chinese: "他打篮球打得很好။",
    pinyin: "Tā dǎ lánqiú dǎ de hěn hǎo.",
    myanmar: "သူ ဘတ်စကက်ဘော အရမ်းတော်တယ်။",
  },
  {
    id: 83,
    chinese: "我在踢足球。",
    pinyin: "Wǒ zài tī zúqiú.",
    myanmar: "ငါ ဘောလုံးကန်နေတယ်။",
  },
  {
    id: 84,
    chinese: "你会唱歌吗？",
    pinyin: "Nǐ huì chànggē ma?",
    myanmar: "မင်း သီချင်းဆိုတတ်လား?",
  },
  {
    id: 85,
    chinese: "她跳舞跳得很漂亮。",
    pinyin: "Tā tiàowǔ tiào de hěn piàoliang.",
    myanmar: "သူမ ကတာ အရမ်းလှတယ်။",
  },
  {
    id: 86,
    chinese: "我想学习跳舞。",
    pinyin: "Wǒ xiǎng xuéxí tiàowǔ.",
    myanmar: "ငါ ကတာ သင်ချင်တယ်။",
  },
  {
    id: 87,
    chinese: "这里的菜很好吃。",
    pinyin: "Zhèlǐ de cài hěn hǎochī.",
    myanmar: "ဒီက ဟင်းတွေက အရမ်းစားကောင်းတယ်။",
  },
  {
    id: 88,
    chinese: "我不爱吃羊肉。",
    pinyin: "Wǒ bú ài chī yángròu.",
    myanmar: "ငါ ဆိတ်သား/သိုးသား စားရတာ မကြိုက်ဘူး။",
  },
  {
    id: 89,
    chinese: "请给我一杯咖啡。",
    pinyin: "Qǐng gěi wǒ yì bēi kāfēi.",
    myanmar: "ကော်ဖီတစ်ခွက် ပေးပါ။",
  },
  {
    id: 90,
    chinese: "我想喝热牛奶。",
    pinyin: "Wǒ xiǎng hē rè niúnǎi.",
    myanmar: "ငါ နွားနို့ပူပူ သောက်ချင်တယ်။",
  },
  {
    id: 91,
    chinese: "鱼肉很新鲜。",
    pinyin: "Yúròu hěn xīnxiān.",
    myanmar: "ငါးသားက အရမ်းလတ်ဆတ်တယ်။",
  },
  {
    id: 92,
    chinese: "你想吃什么？",
    pinyin: "Nǐ xiǎng chī shénme?",
    myanmar: "မင်း ဘာစားချင်လဲ?",
  },
  {
    id: 93,
    chinese: "我想吃面条。",
    pinyin: "Wǒ xiǎng chī miàntiáo.",
    myanmar: "ငါ ခေါက်ဆွဲစားချင်တယ်။",
  },
  {
    id: 94,
    chinese: "别说话，听老师讲。",
    pinyin: "Bié shuōhuà, tīng lǎoshī jiǎng.",
    myanmar: "စကားမပြောနဲ့၊ ဆရာပြောတာ နားထောင်။",
  },
  {
    id: 95,
    chinese: "我听懂了。",
    pinyin: "Wǒ tīng dǒng le.",
    myanmar: "ငါ နားလည်သွားပြီ။",
  },
  {
    id: 101,
    chinese: "我在上班。",
    pinyin: "Wǒ zài shàngbān.",
    myanmar: "ငါ အလုပ်လုပ်နေတယ်။",
  },
  {
    id: 102,
    chinese: "他已经在公司了。",
    pinyin: "Tā yǐjīng zài gōngsī le.",
    myanmar: "သူ ကုမ္ပဏီကို ရောက်နေပြီ။",
  },
  {
    id: 103,
    chinese: "经理出去了。",
    pinyin: "Jīnglǐ chūqù le.",
    myanmar: "မန်နေဂျာ အပြင်ထွက်သွားတယ်။",
  },
  {
    id: 104,
    chinese: "什么时候开始开会？",
    pinyin: "Shénme shíhou kāishǐ kāihuì?",
    myanmar: "အစည်းအဝေး ဘယ်အချိန်စမလဲ?",
  },
  {
    id: 105,
    chinese: "会议还没结束。",
    pinyin: "Huìyì hái méi jiéshù.",
    myanmar: "အစည်းအဝေး မပြီးသေးဘူး။",
  },
  {
    id: 106,
    chinese: "准备好了吗？",
    pinyin: "Zhǔnbèi hǎo le ma?",
    myanmar: "ပြင်ဆင်ပြီးပြီလား?",
  },
  {
    id: 107,
    chinese: "还没准备好。",
    pinyin: "Hái méi zhǔnbèi hǎo.",
    myanmar: "မပြင်ဆင်ရသေးပါဘူး။",
  },
  {
    id: 108,
    chinese: "我要做这件事情。",
    pinyin: "Wǒ yào zuò zhè jiàn shìqing.",
    myanmar: "ငါ ဒီကိစ္စကို လုပ်ရမယ်။",
  },
  {
    id: 109,
    chinese: "这件事很重要。",
    pinyin: "Zhè jiàn shì hěn zhòngyào.",
    myanmar: "ဒီကိစ္စက အရမ်းအရေးကြီးတယ်။",
  },
  {
    id: 110,
    chinese: "你能帮帮我吗？",
    pinyin: "Nǐ néng bāngbang wǒ ma?",
    myanmar: "မင်း ငါ့ကို ကူညီနိုင်မလား?",
  },
  {
    id: 111,
    chinese: "谢谢你的帮助。",
    pinyin: "Xièxie nǐ de bāngzhù.",
    myanmar: "မင်းရဲ့အကူအညီအတွက် ကျေးဇူးပါ။",
  },
  {
    id: 112,
    chinese: "没问题，不用客气。",
    pinyin: "Méi wèntí, búyòng kèqi.",
    myanmar: "ရပါတယ်၊ အားနာစရာမလိုပါဘူး။",
  },
  {
    id: 113,
    chinese: "我在北京学习汉语。",
    pinyin: "Wǒ zài Běijīng xuéxí Hànyǔ.",
    myanmar: "ငါ ပေကျင်းမှာ တရုတ်စာ သင်နေတယ်။",
  },
  {
    id: 114,
    chinese: "汉语不难。",
    pinyin: "Hànyǔ bù nán.",
    myanmar: "တရုတ်စာ မခက်ပါဘူး။",
  },
  {
    id: 115,
    chinese: "汉字很有意思。",
    pinyin: "Hànzì hěn yǒu yìsi.",
    myanmar: "တရုတ်စာလုံးတွေက အရမ်းစိတ်ဝင်စားဖို့ကောင်းတယ်။",
  },
  {
    id: 116,
    chinese: "我会说一点儿汉语。",
    pinyin: "Wǒ huì shuō yìdiǎnr Hànyǔ.",
    myanmar: "ငါ တရုတ်စကား နည်းနည်း ပြောတတ်တယ်။",
  },
  {
    id: 117,
    chinese: "请你说慢一点儿。",
    pinyin: "Qǐng nǐ shuō màn yìdiǎnr.",
    myanmar: "နည်းနည်းလောက် ဖြည်းဖြည်းပြောပေးပါ။",
  },
  {
    id: 118,
    chinese: "我不懂这个词的意思。",
    pinyin: "Wǒ bù dǒng zhège cí de yìsi.",
    myanmar: "ဒီစကားလုံးရဲ့ အဓိပ္ပာယ်ကို ငါနားမလည်ဘူး။",
  },
  {
    id: 119,
    chinese: "我去过中国两次。",
    pinyin: "Wǒ qùguo Zhōngguó liǎng cì.",
    myanmar: "ငါ တရုတ်ပြည်ကို နှစ်ခေါက် ရောက်ဖူးတယ်။",
  },
  {
    id: 120,
    chinese: "去年我还在上学。",
    pinyin: "Qùnián wǒ hái zài shàngxué.",
    myanmar: "မနှစ်က ငါ ကျောင်းတက်နေတုန်းပဲ။",
  },
  {
    id: 121,
    chinese: "考试什么时候开始？",
    pinyin: "Kǎoshì shénme shíhou kāishǐ?",
    myanmar: "စာမေးပွဲ ဘယ်တော့စမှာလဲ?",
  },
  {
    id: 122,
    chinese: "希望你能考好。",
    pinyin: "Xīwàng nǐ néng kǎo hǎo.",
    myanmar: "မင်း စာမေးပွဲ ကောင်းကောင်းဖြေနိုင်ပါစေ။",
  },
  {
    id: 123,
    chinese: "题太多了，我没做完。",
    pinyin: "Tí tài duō le, wǒ méi zuò wán.",
    myanmar: "မေးခွန်းတွေ အရမ်းများလို့ ငါမပြီးလိုက်ဘူး။",
  },
  {
    id: 124,
    chinese: "这节课结束了。",
    pinyin: "Zhè jié kè jiéshù le.",
    myanmar: "ဒီအချိန်သင်ခန်းစာ ပြီးသွားပြီ။",
  },
  {
    id: 125,
    chinese: "同学们再见。",
    pinyin: "Tóngxuémén zàijiàn.",
    myanmar: "ကျောင်းသားတို့ရေ၊ သွားတော့မယ်။",
  },
  {
    id: 126,
    chinese: "现在几点了？",
    pinyin: "Xiànzài jǐ diǎn le?",
    myanmar: "အခု ဘယ်နှစ်နာရီရှိပြီလဲ?",
  },
  {
    id: 127,
    chinese: "現在是早上七点。",
    pinyin: "Xiànzài shì zǎoshang qī diǎn.",
    myanmar: "အခု မနက် ၇ နာရီပါ။",
  },
  {
    id: 128,
    chinese: "我八点半起床。",
    pinyin: "Wǒ bā diǎn bàn qǐchuáng.",
    myanmar: "ငါ ၈ နာရီခွဲ အိပ်ရာထတယ်။",
  },
  {
    id: 129,
    chinese: "我晚上十一点睡觉。",
    pinyin: "Wǒ wǎnshàng shíyī diǎn shuìjiào.",
    myanmar: "ငါ ည ၁၁ နာရီ အိပ်တယ်။",
  },
  {
    id: 130,
    chinese: "今天是星期几？",
    pinyin: "Jīntiān shì xīngqī jǐ?",
    myanmar: "ဒီနေ့ ဘယ်နေ့လဲ?",
  },
  {
    id: 131,
    chinese: "今天是我朋友的生日。",
    pinyin: "Jīntiān shì wǒ péngyou de shēngrì.",
    myanmar: "ဒီနေ့က ငါ့သူငယ်ချင်းရဲ့ မွေးနေ့ပါ။",
  },
  {
    id: 132,
    chinese: "这个月天气很热。",
    pinyin: "Zhège yuè tiānqì hěn rè.",
    myanmar: "ဒီလ ရာသီဥတုက အရမ်းပူတယ်။",
  },
  {
    id: 133,
    chinese: "下个星期我要去旅游。",
    pinyin: "Xià gè xīngqī wǒ yào qù lǚyóu.",
    myanmar: "နောက်အပတ်မှာ ငါခရီးသွားမလို့။",
  },
  {
    id: 134,
    chinese: "我们要坐两个小时的火车。",
    pinyin: "Wǒmen yào zuò liǎng gè xiǎoshí de huǒchē.",
    myanmar: "ငါတို့ မီးရထား ၂ နာရီ စီးရမယ်။",
  },
  {
    id: 135,
    chinese: "这里的商店很多。",
    pinyin: "Zhèlǐ de shāngdiàn hěn duō.",
    myanmar: "ဒီမှာ ဆိုင်တွေ အရမ်းများတယ်။",
  },
  {
    id: 136,
    chinese: "我喜欢喝这里的茶。",
    pinyin: "Wǒ xǐhuan hē zhèlǐ de chá.",
    myanmar: "ငါဒီက လက်ဖက်ရည်ကို သောက်ရတာ ကြိုက်တယ်။",
  },
  {
    id: 137,
    chinese: "这个西瓜很大。",
    pinyin: "Zhège xīguā hěn dà.",
    myanmar: "ဒီဖရဲသီးက အရမ်းကြီးတယ်။",
  },
  {
    id: 138,
    chinese: "我要买两斤苹果。",
    pinyin: "Wǒ yào mǎi liǎng jīn píngguǒ.",
    myanmar: "ငါ ပန်းသီး နှစ်ပိဿာ (တရုတ်ချိန်သီး) ဝယ်မယ်။",
  },
  {
    id: 139,
    chinese: "你有多少张票？",
    pinyin: "Nǐ yǒu duōshao zhāng piào?",
    myanmar: "မင်းမှာ လက်မှတ်ဘယ်နှစ်စောင်ရှိလဲ?",
  },
  {
    id: 140,
    chinese: "我有一张票。",
    pinyin: "Wǒ yǒu yì zhāng piào.",
    myanmar: "ငါ့မှာ လက်မှတ်တစ်စောင်ရှိတယ်။",
  },
  {
    id: 201,
    chinese: "你喜欢哪个颜色？",
    pinyin: "Nǐ xǐhuan nǎge yánsè?",
    myanmar: "မင်း ဘယ်အရောင်ကို ကြိုက်လဲ?",
  },
  {
    id: 202,
    chinese: "我最喜欢红色。",
    pinyin: "Wǒ zuì xǐhuan hóngsè.",
    myanmar: "ငါ အနီရောင်ကို အကြိုက်ဆုံးပဲ။",
  },
  {
    id: 203,
    chinese: "这件黑色的衣服怎么样？",
    pinyin: "Zhè jiàn hēisè de yīfu zěnmeyàng?",
    myanmar: "ဒီအနက်ရောင်အင်္ကျီက ဘယ်လိုလဲ?",
  },
  {
    id: 204,
    chinese: "我觉得很漂亮。",
    pinyin: "Wǒ juéde hěn piàoliang.",
    myanmar: "လှတယ်လို့ ငါထင်တယ်။",
  },
  {
    id: 205,
    chinese: "白色的桌子不贵。",
    pinyin: "Báisè de zhuōzi bú guì.",
    myanmar: "အဖြူရောင်စားပွဲက ဈေးမကြီးဘူး။",
  },
  {
    id: 206,
    chinese: "那是谁的手表？",
    pinyin: "Nà shì shéi de shǒubiǎo?",
    myanmar: "ဒါ ဘယ်သူ့လက်ပတ်နာရီလဲ?",
  },
  {
    id: 207,
    chinese: "是经理的手表。",
    pinyin: "Shì jīnglǐ de shǒubiǎo.",
    myanmar: "မန်နေဂျာရဲ့ နာရီပါ။",
  },
  {
    id: 208,
    chinese: "外面非常冷。",
    pinyin: "Wàimiàn fēicháng lěng.",
    myanmar: "အပြင်မှာ အရမ်းအေးတယ်။",
  },
  {
    id: 209,
    chinese: "今天比昨天冷。",
    pinyin: "Jīntiān bǐ zuótiān lěng.",
    myanmar: "ဒီနေ့က မနေ့ကထက် ပိုအေးတယ်။",
  },
  {
    id: 210,
    chinese: "他是我的新同学。",
    pinyin: "Tā shì wǒ de xīn tóngxué.",
    myanmar: "သူက ငါ့ရဲ့ အတန်းဖော်အသစ်ပါ။",
  },
  {
    id: 211,
    chinese: "我们要去北京旅游。",
    pinyin: "Wǒmen yào qù Běijīng lǚyóu.",
    myanmar: "ငါတို့ ပေကျင်းကို ခရီးထွက်ကြမယ်။",
  },
  {
    id: 212,
    chinese: "你会开车吗？",
    pinyin: "Nǐ huì kāichē ma?",
    myanmar: "မင်း ကားမောင်းတတ်လား?",
  },
  {
    id: 213,
    chinese: "我不会开，但我哥哥会。",
    pinyin: "Wǒ bú huì kāi, dàn wǒ gēge huì.",
    myanmar: "ငါမမောင်းတတ်ဘူး၊ ဒါပေမဲ့ ငါ့အစ်ကိုက မောင်းတတ်တယ်။",
  },
  {
    id: 214,
    chinese: "你会说英语吗？",
    pinyin: "Nǐ huì shuō Yīngyǔ ma?",
    myanmar: "မင်း အင်္ဂလိပ်စကား ပြောတတ်လား?",
  },
  {
    id: 215,
    chinese: "我会说一点儿。",
    pinyin: "Wǒ huì shuō yìdiǎnr.",
    myanmar: "နည်းနည်း ပြောတတ်ပါတယ်။",
  },
  {
    id: 216,
    chinese: "请给我介绍一下。",
    pinyin: "Qǐng gěi wǒ jièshào yíxià.",
    myanmar: "တစ်ဆိတ်လောက် မိတ်ဆက်ပေးပါဦး။",
  },
  {
    id: 217,
    chinese: "这是我的妻子。",
    pinyin: "Zhè shì wǒ de qīzi.",
    myanmar: "ဒါက ငါ့ရဲ့ဇနီးပါ။",
  },
  {
    id: 218,
    chinese: "那是我的丈夫。",
    pinyin: "Nà shì wǒ de zhàngfu.",
    myanmar: "ဒါက ငါ့ရဲ့ခင်ပွန်းပါ။",
  },
  {
    id: 219,
    chinese: "你有几个孩子？",
    pinyin: "Nǐ yǒu jǐ gè háizi?",
    myanmar: "မင်းမှာ ကလေးဘယ်နှစ်ယောက်ရှိလဲ?",
  },
  {
    id: 220,
    chinese: "我有一个女儿和一个儿子。",
    pinyin: "Wǒ yǒu yí gè nǚ'ér hé yí gè érzi.",
    myanmar: "ငါ့မှာ သမီးတစ်ယောက်နဲ့ သားတစ်ယောက်ရှိတယ်။",
  },
  {
    id: 221,
    chinese: "你妹妹在哪儿工作？",
    pinyin: "Nǐ mèimei zài nǎr gōngzuò?",
    myanmar: "မင်းညီမ ဘယ်မှာအလုပ်လုပ်လဲ?",
  },
  {
    id: 222,
    chinese: "她在医院工作。",
    pinyin: "Tā zài yīyuàn gōngzuò.",
    myanmar: "သူမ ဆေးရုံမှာ အလုပ်လုပ်တယ်။",
  },
  {
    id: 223,
    chinese: "她是个护士。",
    pinyin: "Tā shì gè hùshi.",
    myanmar: "သူမက သူနာပြုတစ်ယောက်ပါ။",
  },
  {
    id: 224,
    chinese: "你认识那个人吗？",
    pinyin: "Nǐ rènshi nàge rén ma?",
    myanmar: "မင်း အဲ့ဒီလူကို သိလား?",
  },
  {
    id: 225,
    chinese: "我不认识他。",
    pinyin: "Wǒ bú rènshi tā.",
    myanmar: "ငါသူ့ကို မသိဘူး။",
  },
  {
    id: 226,
    chinese: "他比我大三岁。",
    pinyin: "Tā bǐ wǒ dà sān suì.",
    myanmar: "သူက ငါ့ထက် ၃ နှစ်ကြီးတယ်။",
  },
  {
    id: 227,
    chinese: "我每天早上跑步。",
    pinyin: "Wǒ měitiān zǎoshang pǎobù.",
    myanmar: "ငါ နေ့တိုင်းမနက် အပြေးလေ့ကျင့်တယ်။",
  },
  {
    id: 228,
    chinese: "运动对身体很好。",
    pinyin: "Yùndòng duì shēntǐ hěn hǎo.",
    myanmar: "အားကစားလုပ်တာက ကျန်းမာရေးအတွက် အရမ်းကောင်းတယ်။",
  },
  {
    id: 229,
    chinese: "别看电视了，去睡觉吧。",
    pinyin: "Bié kàn diànshì le, qù shuìjiào ba.",
    myanmar: "တီဗွီမကြည့်နဲ့တော့၊ သွားအိပ်တော့။",
  },
  {
    id: 230,
    chinese: "我还没做完功课。",
    pinyin: "Wǒ hái méi zuò wán gōngkè.",
    myanmar: "ငါ အိမ်စာမပြီးသေးဘူး။",
  },
  {
    id: 231,
    chinese: "多吃水果，少喝咖啡。",
    pinyin: "Duō chī shuǐguǒ, shǎo hē kāfēi.",
    myanmar: "သစ်သီးများများစား၊ ကော်ဖီနည်းနည်းသောက်။",
  },
  {
    id: 232,
    chinese: "这道题怎么做？",
    pinyin: "Zhè dào tí zěnme zuò?",
    myanmar: "ဒီပုစ္ဆာကို ဘယ်လိုတွက်ရမလဲ?",
  },
  {
    id: 233,
    chinese: "请帮我看看这个字。",
    pinyin: "Qǐng bāng wǒ kànkan zhège zì.",
    myanmar: "ဒီစာလုံးကို တစ်ဆိတ်လောက် ကြည့်ပေးပါ။",
  },
  {
    id: 234,
    chinese: "这个意思我懂了。",
    pinyin: "Zhège yìsi wǒ dǒng le.",
    myanmar: "ဒီအဓိပ္ပာယ်ကို ငါနားလည်သွားပြီ။",
  },
  {
    id: 235,
    chinese: "请再说一次。",
    pinyin: "Qǐng zài shuō yí cì.",
    myanmar: "နောက်တစ်ခေါက်လောက် ပြန်ပြောပေးပါ။",
  },
  {
    id: 236,
    chinese: "你的汉语说得很流利。",
    pinyin: "Nǐ de Hànyǔ shuō de hěn liúlì.",
    myanmar: "မင်းရဲ့ တရုတ်စကားက အရမ်းသွက်တယ်။",
  },
  {
    id: 237,
    chinese: "哪里哪里，还要学习。",
    pinyin: "Nǎlǐ nǎlǐ, hái yào xuéxí.",
    myanmar: "မဟုတ်တာ၊ သင်ယူဖို့ လိုပါသေးတယ်။",
  },
  {
    id: 238,
    chinese: "电影什么时候开始？",
    pinyin: "Diànyǐng shénme shíhou kāishǐ?",
    myanmar: "ရုပ်ရှင် ဘယ်အချိန်စမလဲ?",
  },
  {
    id: 239,
    chinese: "快要开始了，快点儿！",
    pinyin: "Kuàiyào kāishǐ le, kuài diǎnr!",
    myanmar: "စတော့မယ်၊ မြန်မြန်လုပ်!",
  },
  {
    id: 240,
    chinese: "这家宾馆的服务很好。",
    pinyin: "Zhè jiā bīnguǎn de fúwù hěn hǎo.",
    myanmar: "ဒီဟိုတယ်ရဲ့ ဝန်ဆောင်မှုက အရမ်းကောင်းတယ်။",
  },
  {
    id: 241,
    chinese: "我想给妈妈打个电话。",
    pinyin: "Wǒ xiǎng gěi māma dǎ gè diànhuà.",
    myanmar: "ငါ အမေဆီ ဖုန်းဆက်ချင်တယ်။",
  },
  {
    id: 242,
    chinese: "她在忙什么呢？",
    pinyin: "Tā zài máng shénme ne?",
    myanmar: "သူမ ဘာတွေ အလုပ်ရှုပ်နေတာလဲ?",
  },
  {
    id: 243,
    chinese: "她正在做饭呢。",
    pinyin: "Tā zhèngzài zuòfàn ne.",
    myanmar: "သူမ ထမင်းဟင်း ချက်နေတာလေ။",
  },
  {
    id: 244,
    chinese: "别担心，一切都会好的。",
    pinyin: "Bié dānxīn, yíqiè dōu huì hǎo de.",
    myanmar: "မစိုးရိမ်ပါနဲ့၊ အားလုံး အဆင်ပြေသွားမှာပါ။",
  },
  {
    id: 245,
    chinese: "祝你一路平安。",
    pinyin: "Zhù nǐ yílù píng'ān.",
    myanmar: "လမ်းခရီး ချောမွေ့ပါစေ။",
  },
  {
    id: 246,
    chinese: "你的猫叫什么名字？",
    pinyin: "Nǐ de māo jiào shénme míngzi?",
    myanmar: "မင်းကြောင်လေး နာမည်က ဘာလဲ?",
  },
  {
    id: 247,
    chinese: "它叫小雪。",
    pinyin: "Tā jiào Xiǎoxuě.",
    myanmar: "သူ့နာမည်က ရှောင်ရွှယ် တဲ့။",
  },
  {
    id: 248,
    chinese: "它长得真可爱。",
    pinyin: "Tā zhǎng de zhēn kě'ài.",
    myanmar: "သူ့ပုံစံက တကယ် ချစ်စရာကောင်းတယ်။",
  },
  {
    id: 249,
    chinese: "你看见我的钥匙了吗？",
    pinyin: "Nǐ kànjiàn wǒ de yàoshi le ma?",
    myanmar: "ငါ့သော့ကို မြင်မိလား?",
  },
  {
    id: 250,
    chinese: "就在报纸下面。",
    pinyin: "Jiù zài bàozhǐ xiàmiàn.",
    myanmar: "သတင်းစာအောက်မှာတင် ရှိတာပါ။",
  },
  {
    id: 251,
    chinese: "今天是我第一天上班。",
    pinyin: "Jīntiān shì wǒ dì-yī tiān shàngbān.",
    myanmar: "ဒီနေ့က ငါ့ရဲ့ ပထမဆုံး အလုပ်တက်ရက်ပါ။",
  },
  {
    id: 252,
    chinese: "公司离我家很远。",
    pinyin: "Gōngsī lí wǒjiā hěn yuǎn.",
    myanmar: "ကုမ္ပဏီက ငါ့အိမ်နဲ့ ဝေးတယ်။",
  },
  {
    id: 253,
    chinese: "我得坐一个小时的地铁。",
    pinyin: "Wǒ děi zuò yí gè xiǎoshí de dìtiě.",
    myanmar: "ငါ မြေအောက်ရထား တစ်နာရီ စီးရမယ်။",
  },
  {
    id: 254,
    chinese: "这里的环境很舒服。",
    pinyin: "Zhèlǐ de huánjìng hěn shūfu.",
    myanmar: "ဒီက ပတ်ဝန်းကျင်က အရမ်းသက်သောင့်သက်သာရှိတယ်။",
  },
  {
    id: 255,
    chinese: "你想吃点儿什么？",
    pinyin: "Nǐ xiǎng chī diǎnr shénme?",
    myanmar: "မင်း ဘာနည်းနည်း စားချင်လဲ?",
  },
  {
    id: 256,
    chinese: "我不饿，只想喝水。",
    pinyin: "Wǒ bú è, zhǐ xiǎng hē shuǐ.",
    myanmar: "ငါဗိုက်မဆာဘူး၊ ရေသောက်ချင်ရုံပဲ။",
  },
  {
    id: 257,
    chinese: "我们下午去游乐场吧。",
    pinyin: "Wǒmen xiàwǔ qù yóulèchǎng ba.",
    myanmar: "ငါတို့ နေ့လယ်ကျရင် ကစားကွင်း သွားကြရအောင်။",
  },
  {
    id: 258,
    chinese: "好主意，几点见？",
    pinyin: "Hǎo zhǔyi, jǐ diǎn jiàn?",
    myanmar: "စိတ်ကူးကောင်းပဲ၊ ဘယ်နှစ်နာရီ တွေ့ကြမလဲ?",
  },
  {
    id: 259,
    chinese: "三点半在校门口见。",
    pinyin: "Sān diǎn bàn zài xiào ménkǒu jiàn.",
    myanmar: "သုံးနာရီခွဲ ကျောင်းဂိတ်ဝမှာ တွေ့ကြမယ်။",
  },
  {
    id: 260,
    chinese: "你看过那个电影吗？",
    pinyin: "Nǐ kànguo nàge diànyǐng ma?",
    myanmar: "မင်း အဲ့ဒီရုပ်ရှင် ကြည့်ဖူးလား?",
  },
  {
    id: 261,
    chinese: "我看过三次了。",
    pinyin: "Wǒ kànguo sān cì le.",
    myanmar: "ငါ သုံးခေါက်တောင် ကြည့်ဖူးပြီ။",
  },
  {
    id: 262,
    chinese: "真想再看一遍。",
    pinyin: "Zhēn xiǎng zài kàn yí biàn.",
    myanmar: "နောက်တစ်ခေါက် ထပ်ကြည့်ချင်သေးတယ်။",
  },
  {
    id: 263,
    chinese: "你觉得这个汉字怎么写？",
    pinyin: "Nǐ juéde zhège Hànzì zěnme xiě?",
    myanmar: "ဒီတရုတ်စာလုံးကို ဘယ်လိုရေးရမယ်လို့ မင်းထင်လဲ?",
  },
  {
    id: 264,
    chinese: "我可以教你。",
    pinyin: "Wǒ kěyǐ jiāo nǐ.",
    myanmar: "ငါ မင်းကို သင်ပေးလို့ရတယ်။",
  },
  {
    id: 265,
    chinese: "谢谢你，你真好。",
    pinyin: "Xièxie nǐ, nǐ zhēn hǎo.",
    myanmar: "ကျေးဇူးပါပဲ၊ မင်းက တကယ့်လူကောင်းပဲ။",
  },
  {
    id: 266,
    chinese: "外面的雪下得很大。",
    pinyin: "Wàimiàn de xuě xià de hěn dà.",
    myanmar: "အပြင်မှာ နှင်းတွေ အရမ်းကျနေတယ်။",
  },
  {
    id: 267,
    chinese: "天阴了，可能要下雨。",
    pinyin: "Tiān yīn le, kěnéng yào xià yǔ.",
    myanmar: "မိုးအုံ့နေပြီ၊ ရွာတော့မယ် ထင်တယ်။",
  },
  {
    id: 268,
    chinese: "记得带伞。",
    pinyin: "Jìde dài sǎn.",
    myanmar: "ထီးယူသွားဖို့ သတိရပါ။",
  },
  {
    id: 269,
    chinese: "这件衬衫太小了。",
    pinyin: "Zhè jiàn chènshān tài xiǎo le.",
    myanmar: "ဒီရှပ်အင်္ကျီက အရမ်းသေးလွန်းတယ်။",
  },
  {
    id: 270,
    chinese: "我想换个大号的。",
    pinyin: "Wǒ xiǎng huàn gè dà hào de.",
    myanmar: "ငါ ဆိုဒ်အကြီးတစ်ခုနဲ့ လဲချင်တယ်။",
  },
  {
    id: 271,
    chinese: "那家店的衣服很便宜。",
    pinyin: "Nà jiā diàn de yīfu hěn piányi.",
    myanmar: "ဟိုဆိုင်က အင်္ကျီတွေက ဈေးပေါတယ်။",
  },
  {
    id: 272,
    chinese: "你去过北京火车站吗？",
    pinyin: "Nǐ qùguo Běijīng huǒchēzhàn ma?",
    myanmar: "မင်း ပေကျင်းမီးရထားဘူတာကို ရောက်ဖူးလား?",
  },
  {
    id: 273,
    chinese: "没去过，但听说很大。",
    pinyin: "Méi qùguo, dàn tīngshuō hěn dà.",
    myanmar: "မရောက်ဖူးဘူး၊ ဒါပေမဲ့ ကြီးတယ်လို့ ကြားဖူးတယ်။",
  },
  {
    id: 274,
    chinese: "这是我送给你的礼物。",
    pinyin: "Zhè shì wǒ sòng gěi nǐ de lǐwù.",
    myanmar: "ဒါက ငါမင်းကို ပေးတဲ့လက်ဆောင်ပါ။",
  },
  {
    id: 275,
    chinese: "希望你喜欢。",
    pinyin: "Xīwàng nǐ xǐhuan.",
    myanmar: "မင်းကြိုက်လိမ့်မယ်လို့ မျှော်လင့်ပါတယ်။",
  },
  {
    id: 276,
    chinese: "哇，太漂亮了！",
    pinyin: "Wa, tài piàoliang le!",
    myanmar: "ဝါး... အရမ်းလှတာပဲ!",
  },
  {
    id: 277,
    chinese: "你在哪个房间？",
    pinyin: "Nǐ zài nǎge fángjiān?",
    myanmar: "မင်း ဘယ်အခန်းမှာလဲ?",
  },
  {
    id: 278,
    chinese: "我在302号房间。",
    pinyin: "Wǒ zài sān-líng-èr hào fángjiān.",
    myanmar: "ငါ အခန်းနံပါတ် ၃၀၂ မှာပါ။",
  },
  {
    id: 279,
    chinese: "那里的咖啡很出名。",
    pinyin: "Nàlǐ de kāfēi hěn chūmíng.",
    myanmar: "ဟိုက ကော်ဖီက အရမ်းနာမည်ကြီးတယ်။",
  },
  {
    id: 280,
    chinese: "你要不要尝尝？",
    pinyin: "Nǐ yào bú yào chángchang?",
    myanmar: "မင်း မြည်းကြည့်မလား?",
  },
  {
    id: 281,
    chinese: "今天的人很多。",
    pinyin: "Jīntiān de rén hěn duō.",
    myanmar: "ဒီနေ့ လူတွေ အရမ်းများတယ်။",
  },
  {
    id: 282,
    chinese: "因为今天是周末。",
    pinyin: "Yīnwèi jīntiān shì zhōumò.",
    myanmar: "ဘာလို့လဲဆိုတော့ ဒီနေ့က ဝီကန်း (ပိတ်ရက်) မို့လို့လေ။",
  },
  {
    id: 283,
    chinese: "你想喝点儿冷饮吗？",
    pinyin: "Nǐ xiǎng hē diǎnr lěngyǐn ma?",
    myanmar: "မင်း အအေးတစ်မျိုးမျိုး သောက်ချင်လား?",
  },
  {
    id: 284,
    chinese: "好的，来杯冰红茶。",
    pinyin: "Hǎo de, lái bēi bīng hóngchá.",
    myanmar: "ကောင်းပြီ၊ အိုက်စတီး (Ice Lemon Tea) တစ်ခွက်ပေး။",
  },
  {
    id: 285,
    chinese: "他的个子很高。",
    pinyin: "Tā de gèzi hěn gāo.",
    myanmar: "သူက အရပ်အရမ်းရှည်တယ်။",
  },
  {
    id: 286,
    chinese: "他比他爸爸还要高。",
    pinyin: "Tā bǐ tā bàba hái yào gāo.",
    myanmar: "သူက သူ့အဖေထက်တောင် အရပ်ရှည်သေးတယ်။",
  },
  {
    id: 287,
    chinese: "你的汉语考了多少分？",
    pinyin: "Nǐ de Hànyǔ kǎo le duōshao fēn?",
    myanmar: "မင်း တရုတ်စာ စာမေးပွဲ ဘယ်နှစ်မှတ်ရလဲ?",
  },
  {
    id: 288,
    chinese: "我考了95分。",
    pinyin: "Wǒ kǎo le jiǔshí-wǔ fēn.",
    myanmar: "ငါ ၉၅ မှတ် ရတယ်။",
  },
  {
    id: 289,
    chinese: "考得真不错！",
    pinyin: "Kǎo de zhēn búcuò!",
    myanmar: "တကယ်ကို မဆိုးဘူး (တော်တယ်)။",
  },
  {
    id: 290,
    chinese: "我们快走吧，要迟到了。",
    pinyin: "Wǒmen kuài zǒu ba, yào chídào le.",
    myanmar: "ငါတို့ မြန်မြန်သွားကြရအောင်၊ နောက်ကျတော့မယ်။",
  },
  {
    id: 291,
    chinese: "别着急，还有十分钟呢。",
    pinyin: "Bié zháojí, hái yǒu shí fēnzhōng ne.",
    myanmar: "မလောပါနဲ့၊ ၁၀ မိနစ်တောင် လိုသေးတာပဲ။",
  },
  {
    id: 292,
    chinese: "这件衣服太贵了，有便宜点儿的吗？",
    pinyin: "Zhè jiàn yīfu tài guì le, yǒu piányi diǎnr de ma?",
    myanmar: "ဒီအင်္ကျီက အရမ်းဈေးကြီးတယ်၊ ဈေးသက်သာတာ ရှိလား?",
  },
  {
    id: 293,
    chinese: "那边的更便宜。",
    pinyin: "Nàbiān de gèng piányi.",
    myanmar: "ဟိုဘက်ကဟာတွေက ပိုဈေးသက်သာတယ်။",
  },
  {
    id: 294,
    chinese: "今天是我最后一天在这里。",
    pinyin: "Jīntiān shì wǒ zuìhòu yì tiān zài zhèlǐ.",
    myanmar: "ဒီနေ့က ငါဒီမှာရှိနေမယ့် နောက်ဆုံးရက်ပဲ။",
  },
  {
    id: 295,
    chinese: "我会想念大家的。",
    pinyin: "Wǒ huì xiǎngniàn dàjiā de.",
    myanmar: "ငါ အားလုံးကို လွမ်းနေမှာပါ။",
  },
  {
    id: 296,
    chinese: "常联系，再见。",
    pinyin: "Cháng liánxì, zàijiàn.",
    myanmar: "အမြဲအဆက်အသွယ်လုပ်ပါ၊ နှုတ်ဆက်ပါတယ်နော်။",
  },
  {
    id: 297,
    chinese: "祝你学习进步。",
    pinyin: "Zhù nǐ xuéxí jìnbù.",
    myanmar: "ပညာရေးမှာ တိုးတက်ပါစေ။",
  },
  {
    id: 298,
    chinese: "万事如意。",
    pinyin: "Wànshì rúyì.",
    myanmar: "အရာရာ စိတ်တိုင်းကျ ဖြစ်ပါစေ။",
  },
  {
    id: 299,
    chinese: "身体健康。",
    pinyin: "Shēntǐ jiànkāng.",
    myanmar: "ကျန်းမာပါစေ။",
  },
  {
    id: 300,
    chinese: "天天快乐。",
    pinyin: "Tiāntiān kuàilè.",
    myanmar: "နေ့တိုင်း ပျော်ရွှင်ပါစေ။",
  },
];