export const maindata = [
  {
    id: 1,
    kanji: "明かり",
    hiragana: "あかり",
    type: "Noun",
    myanmar: "အလင်းရောင် / မီးရောင်",
    flashcard: {
      question: "明かり (あかり) means?",
      correct_answer: "အလင်းရောင်",
      false_answers: ["အမှောင်", "နေရောင်"],
    },
  },
  {
    id: 2,
    kanji: "明ける",
    hiragana: "あける",
    type: "Verb, Ichidan verb",
    myanmar: "မိုးလင်းသည် / (နှစ်သစ်) ကူးပြောင်းသည်",
    flashcard: {
      question: "明ける (あける) means?",
      correct_answer: "မိုးလင်းသည်",
      false_answers: ["မိုးချုပ်သည်", "အိပ်ပျော်သည်"],
    },
  },
  {
    id: 3,
    kanji: "明らか",
    hiragana: "あきらか",
    type: "Adjective, な-adjective",
    myanmar: "ထင်ရှားသော / ရှင်းလင်းသော",
    flashcard: {
      question: "明らか (あきらか) means?",
      correct_answer: "ထင်ရှားသော",
      false_answers: ["ဝေဝါးသော", "လျှို့ဝှက်သော"],
    },
  },
  {
    id: 4,
    kanji: "悪魔",
    hiragana: "あくま",
    type: "Noun",
    myanmar: "မိစ္ဆာ / နတ်ဆိုး",
    flashcard: {
      question: "悪魔 (あくま) means?",
      correct_answer: "နတ်ဆိုး",
      false_answers: ["နတ်သမီး", "ဘုရားသခင်"],
    },
  },
  {
    id: 5,
    kanji: "暗記",
    hiragana: "あんき",
    type: "Noun, Suru verb",
    myanmar: "အလွတ်ကျက်မှတ်ခြင်း",
    flashcard: {
      question: "暗記 (あんき) means?",
      correct_answer: "အလွတ်ကျက်ခြင်း",
      false_answers: ["မေ့လျော့ခြင်း", "ရေးသားခြင်း"],
    },
  },
  {
    id: 6,
    kanji: "新た",
    hiragana: "あらた",
    type: "Noun, な-adjective",
    myanmar: "အသစ်စက်စက် / ဆန်းသစ်သော",
    flashcard: {
      question: "新た (あらた) means?",
      correct_answer: "အသစ်စက်စက်",
      false_answers: ["ဟောင်းနွမ်းသော", "သာမန်"],
    },
  },
  {
    id: 7,
    kanji: "有らゆる",
    hiragana: "あらゆる",
    type: "Pre-noun adjectival",
    myanmar: "ခပ်သိမ်းသော / ရှိသမျှအားလုံး",
    flashcard: {
      question: "あらゆる means?",
      correct_answer: "ရှိသမျှအားလုံး",
      false_answers: ["အနည်းငယ်", "တစ်ခုတည်းသော"],
    },
  },
  {
    id: 8,
    kanji: "集まり",
    hiragana: "あつまり",
    type: "Noun",
    myanmar: "စုဝေးပွဲ / အစည်းအဝေး",
    flashcard: {
      question: "集まり (あつまり) means?",
      correct_answer: "စုဝေးပွဲ",
      false_answers: ["လမ်းခွဲခြင်း", "တစ်ဦးတည်း"],
    },
  },
  {
    id: 9,
    kanji: "部分",
    hiragana: "ぶぶん",
    type: "Noun",
    myanmar: "အစိတ်အပိုင်း / ကဏ္ဍ",
    flashcard: {
      question: "部分 (ぶぶん) means?",
      correct_answer: "အစိတ်အပိုင်း",
      false_answers: ["တစ်ခုလုံး", "အပြင်ဘက်"],
    },
  },
  {
    id: 10,
    kanji: "分",
    hiragana: "ぶん",
    type: "Noun, Suffix",
    myanmar: "ဝေစု / အပိုင်းအခြား",
    flashcard: {
      question: "分 (ぶん) means?",
      correct_answer: "ဝေစု",
      false_answers: ["အမြတ်", "အရင်း"],
    },
  },
  {
    id: 11,
    kanji: "文明",
    hiragana: "ぶんめい",
    type: "Noun",
    myanmar: "ယဉ်ကျေးမှုထွန်းကားခြင်း / ကမ္ဘာ့ယဉ်ကျေးမှု",
    flashcard: {
      question: "文明 (ぶんめい) means?",
      correct_answer: "ယဉ်ကျေးမှုထွန်းကားခြင်း",
      false_answers: ["ရိုင်းစိုင်းမှု", "သဘာဝတရား"],
    },
  },
  {
    id: 12,
    kanji: "分析",
    hiragana: "ぶんせき",
    type: "Noun, Suru verb",
    myanmar: "ခွဲခြမ်းစိတ်ဖြာခြင်း",
    flashcard: {
      question: "分析 (ぶんせき) means?",
      correct_answer: "ခွဲခြမ်းစိတ်ဖြာခြင်း",
      false_answers: ["ပေါင်းစပ်ခြင်း", "ဖျက်ဆီးခြင်း"],
    },
  },
  {
    id: 13,
    kanji: "分野",
    hiragana: "ぶんや",
    type: "Noun",
    myanmar: "နယ်ပယ် / ဘာသာရပ်ကဏ္ဍ",
    flashcard: {
      question: "分野 (ぶんや) means?",
      correct_answer: "နယ်ပယ်",
      false_answers: ["လမ်းမ", "တောင်ကုန်း"],
    },
  },
  {
    id: 14,
    kanji: "父親",
    hiragana: "ちちおや",
    type: "Noun",
    myanmar: "ဖခင် / အဖေ",
    flashcard: {
      question: "父親 (ちちおや) means?",
      correct_answer: "ဖခင်",
      false_answers: ["မိခင်", "သား"],
    },
  },
  {
    id: 15,
    kanji: "地平線",
    hiragana: "ちへいせん",
    type: "Noun",
    myanmar: "မြေပြင်မိုးကုတ်စက်ဝိုင်း",
    flashcard: {
      question: "地平線 means?",
      correct_answer: "မိုးကုတ်စက်ဝိုင်း",
      false_answers: ["ပင်လယ်ပြင်", "တောင်တန်း"],
    },
  },
  {
    id: 16,
    kanji: "地位",
    hiragana: "ちい",
    type: "Noun",
    myanmar: "ဂုဏ်ဒြပ် / အဆင့်အတန်း",
    flashcard: {
      question: "地位 (ちい) means?",
      correct_answer: "အဆင့်အတန်း",
      false_answers: ["အမည်", "အရည်အချင်း"],
    },
  },
  {
    id: 17,
    kanji: "長期",
    hiragana: "ちょうき",
    type: "Noun",
    myanmar: "ကာလရှည်",
    flashcard: {
      question: "長期 (ちょうき) means?",
      correct_answer: "ကာလရှည်",
      false_answers: ["ခဏတာ", "ယနေ့"],
    },
  },
  {
    id: 18,
    kanji: "中",
    hiragana: "ちゅう",
    type: "Noun, Prefix, Suffix",
    myanmar: "အတွင်း / အလယ် / လုပ်ဆောင်နေဆဲ",
    flashcard: {
      question: "中 (ちゅう) means?",
      correct_answer: "အတွင်း/လုပ်ဆောင်နေဆဲ",
      false_answers: ["အပြင်", "အစ"],
    },
  },
  {
    id: 19,
    kanji: "中学",
    hiragana: "ちゅうがく",
    type: "Noun",
    myanmar: "အလယ်တန်းကျောင်း",
    flashcard: {
      question: "中学 means?",
      correct_answer: "အလယ်တန်းကျောင်း",
      false_answers: ["မူလတန်းကျောင်း", "တက္ကသိုလ်"],
    },
  },
  {
    id: 20,
    kanji: "昼食",
    hiragana: "ちゅうしょく",
    type: "Noun",
    myanmar: "နေ့လယ်စာ",
    flashcard: {
      question: "昼食 means?",
      correct_answer: "နေ့လယ်စာ",
      false_answers: ["မနက်စာ", "ညစာ"],
    },
  },
  {
    id: 21,
    kanji: "大部分",
    hiragana: "だいぶぶん",
    type: "Noun",
    myanmar: "အများစု / အဓိကအပိုင်း",
    flashcard: {
      question: "大部分 means?",
      correct_answer: "အများစု",
      false_answers: ["အနည်းငယ်", "တစ်ဝက်"],
    },
  },
  {
    id: 22,
    kanji: "駄目",
    hiragana: "だめ",
    type: "Noun, な-adjective",
    myanmar: "မရပါ / မဖြစ်နိုင်ပါ / မကောင်းပါ",
    flashcard: {
      question: "駄目 (だめ) means?",
      correct_answer: "မရပါ",
      false_answers: ["ကောင်းပါသည်", "ရပါသည်"],
    },
  },
  {
    id: 23,
    kanji: "男子",
    hiragana: "だんし",
    type: "Noun",
    myanmar: "ယောကျ်ားလေး / လူငယ်",
    flashcard: {
      question: "男子 (だんし) means?",
      correct_answer: "ယောကျ်ားလေး",
      false_answers: ["မိန်းကလေး", "လူကြီး"],
    },
  },
  {
    id: 24,
    kanji: "出会い",
    hiragana: "であい",
    type: "Noun",
    myanmar: "တွေ့ဆုံခြင်း / ဆုံစည်းမှု",
    flashcard: {
      question: "出会い means?",
      correct_answer: "တွေ့ဆုံခြင်း",
      false_answers: ["နှုတ်ဆက်ခြင်း", "ရန်ဖြစ်ခြင်း"],
    },
  },
  {
    id: 25,
    kanji: "出会う",
    hiragana: "であう",
    type: "Verb",
    myanmar: "မတော်တဆတွေ့ဆုံသည် / ဆုံမိသည်",
    flashcard: {
      question: "出会う means?",
      correct_answer: "ဆုံမိသည်",
      false_answers: ["ရှာဖွေသည်", "ဖုန်းခေါ်သည်"],
    },
  },
  {
    id: 26,
    kanji: "読書",
    hiragana: "どくしょ",
    type: "Noun, Suru verb",
    myanmar: "စာဖတ်ခြင်း",
    flashcard: {
      question: "読書 (どくしょ) means?",
      correct_answer: "စာဖတ်ခြင်း",
      false_answers: ["စာရေးခြင်း", "စကားပြောခြင်း"],
    },
  },
  {
    id: 27,
    kanji: "努力",
    hiragana: "どりょく",
    type: "Noun, Suru verb",
    myanmar: "ကြိုးစားအားထုတ်မှု",
    flashcard: {
      question: "努力 (どりょく) means?",
      correct_answer: "ကြိုးစားခြင်း",
      false_answers: ["အပျင်းထူခြင်း", "ပျော်ပါးခြင်း"],
    },
  },
  {
    id: 28,
    kanji: "同一",
    hiragana: "どういつ",
    type: "な-adjective",
    myanmar: "ထပ်တူကျသော / တစ်ခုတည်းသော",
    flashcard: {
      question: "同一 means?",
      correct_answer: "ထပ်တူကျသော",
      false_answers: ["ကွဲပြားသော", "ဆန့်ကျင်ဘက်"],
    },
  },
  {
    id: 29,
    kanji: "円",
    hiragana: "えん",
    type: "Noun",
    myanmar: "ယန်း (ဂျပန်ငွေ) / စက်ဝိုင်း",
    flashcard: {
      question: "円 (えん) means?",
      correct_answer: "ယန်းငွေ",
      false_answers: ["ဒေါ်လာ", "စတုရန်း"],
    },
  },
  {
    id: 30,
    kanji: "不利",
    hiragana: "ふり",
    type: "Noun, な-adjective",
    myanmar: "မသာယာသော / အားနည်းချက်ဖြစ်သော",
    flashcard: {
      question: "不利 (ふり) means?",
      correct_answer: "အားနည်းချက်",
      false_answers: ["အခွင့်အရေး", "အောင်မြင်မှု"],
    },
  },
  {
    id: 31,
    kanji: "不足",
    hiragana: "ふそく",
    type: "Noun, Suru verb",
    myanmar: "မလုံလောက်ခြင်း / လိုအပ်ချက်",
    flashcard: {
      question: "不足 (ふそく) means?",
      correct_answer: "မလုံလောက်ခြင်း",
      false_answers: ["ပိုလျှံခြင်း", "ပြည့်စုံခြင်း"],
    },
  },
  {
    id: 32,
    kanji: "再び",
    hiragana: "ふたたび",
    type: "Adverb",
    myanmar: "နောက်တစ်ကြိမ် / တစ်ဖန်",
    flashcard: {
      question: "再び means?",
      correct_answer: "နောက်တစ်ကြိမ်",
      false_answers: ["ပထမဆုံး", "နောက်ဆုံး"],
    },
  },
  {
    id: 33,
    kanji: "外交",
    hiragana: "がいこう",
    type: "Noun",
    myanmar: "နိုင်ငံခြားရေးရာ / သံတမန်ရေး",
    flashcard: {
      question: "外交 (がいこう) means?",
      correct_answer: "သံတမန်ရေး",
      false_answers: ["ပြည်တွင်းရေး", "စီးပွားရေး"],
    },
  },
  {
    id: 34,
    kanji: "外出",
    hiragana: "がいしゅつ",
    type: "Noun, Suru verb",
    myanmar: "အပြင်ထွက်ခြင်း",
    flashcard: {
      question: "外出 means?",
      correct_answer: "အပြင်ထွက်ခြင်း",
      false_answers: ["အိမ်ပြန်ခြင်း", "အိပ်ခြင်း"],
    },
  },
  {
    id: 35,
    kanji: "学期",
    hiragana: "がっき",
    type: "Noun",
    myanmar: "စာသင်နှစ် / စာသင်ကာလ",
    flashcard: {
      question: "学期 (がっき) means?",
      correct_answer: "စာသင်ကာလ",
      false_answers: ["နွေရာသီ", "ကျောင်းပိတ်ရက်"],
    },
  },
  {
    id: 36,
    kanji: "学",
    hiragana: "がく",
    type: "Noun, Suffix",
    myanmar: "ပညာရပ် / လေ့လာမှု",
    flashcard: {
      question: "学 (がく) means?",
      correct_answer: "ပညာရပ်",
      false_answers: ["အားကစား", "အနုပညာ"],
    },
  },
  {
    id: 37,
    kanji: "学問",
    hiragana: "がくもん",
    type: "Noun, Suru verb",
    myanmar: "ပညာရပ်ဆိုင်ရာလေ့လာမှု",
    flashcard: {
      question: "学問 means?",
      correct_answer: "ပညာရပ်",
      false_answers: ["မေးခွန်း", "အဖြေ"],
    },
  },
  {
    id: 38,
    kanji: "学者",
    hiragana: "がくしゃ",
    type: "Noun",
    myanmar: "ပညာရှင်",
    flashcard: {
      question: "学者 (がくしゃ) means?",
      correct_answer: "ပညာရှင်",
      false_answers: ["ကျောင်းသား", "လုပ်သား"],
    },
  },
  {
    id: 39,
    kanji: "学習",
    hiragana: "がくしゅう",
    type: "Noun, Suru verb",
    myanmar: "သင်ယူလေ့လာခြင်း",
    flashcard: {
      question: "学習 means?",
      correct_answer: "သင်ယူခြင်း",
      false_answers: ["ကစားခြင်း", "အနားယူခြင်း"],
    },
  },
  {
    id: 40,
    kanji: "議長",
    hiragana: "ぎちょう",
    type: "Noun",
    myanmar: "ဥက္ကဋ္ဌ / အစည်းအဝေးဦးဆောင်သူ",
    flashcard: {
      question: "議長 (ぎちょう) means?",
      correct_answer: "ဥက္ကဋ္ဌ",
      false_answers: ["ဝန်ထမ်း", "အတွင်းရေးမှူး"],
    },
  },
  {
    id: 41,
    kanji: "議会",
    hiragana: "ぎかい",
    type: "Noun",
    myanmar: "လွှတ်တော်",
    flashcard: {
      question: "議会 (ぎかい) means?",
      correct_answer: "လွှတ်တော်",
      false_answers: ["ဈေးကွက်", "ပန်းခြံ"],
    },
  },
  {
    id: 42,
    kanji: "語学",
    hiragana: "ごがく",
    type: "Noun",
    myanmar: "ဘာသာစကားလေ့လာမှု",
    flashcard: {
      question: "語学 means?",
      correct_answer: "ဘာသာစကားလေ့လာမှု",
      false_answers: ["သင်္ချာ", "သိပ္ပံ"],
    },
  },
  {
    id: 43,
    kanji: "激しい",
    hiragana: "はげしい",
    type: "Adjective",
    myanmar: "ပြင်းထန်သော / ကြမ်းတမ်းသော",
    flashcard: {
      question: "激しい means?",
      correct_answer: "ပြင်းထန်သော",
      false_answers: ["ညင်သာသော", "အေးမြသော"],
    },
  },
  {
    id: 44,
    kanji: "母親",
    hiragana: "ははおや",
    type: "Noun",
    myanmar: "မိခင် / အမေ",
    flashcard: {
      question: "母親 (ははおや) means?",
      correct_answer: "မိခင်",
      false_answers: ["ဖခင်", "ညီမ"],
    },
  },
  {
    id: 45,
    kanji: "博物館",
    hiragana: "はくぶつかん",
    type: "Noun",
    myanmar: "ပြတိုက်",
    flashcard: {
      question: "博物館 means?",
      correct_answer: "ပြတိုက်",
      false_answers: ["စာကြည့်တိုက်", "ရုပ်ရှင်ရုံ"],
    },
  },
  {
    id: 46,
    kanji: "販売",
    hiragana: "はんばい",
    type: "Noun, Suru verb",
    myanmar: "ရောင်းချခြင်း / ဈေးကွက်တင်ခြင်း",
    flashcard: {
      question: "販売 means?",
      correct_answer: "ရောင်းချခြင်း",
      false_answers: ["ဝယ်ယူခြင်း", "ငှားရမ်းခြင်း"],
    },
  },
  {
    id: 47,
    kanji: "発明",
    hiragana: "はつめい",
    type: "Noun, Suru verb",
    myanmar: "တီထွင်ဆန်းသစ်မှု",
    flashcard: {
      question: "発明 (はつめい) means?",
      correct_answer: "တီထွင်ခြင်း",
      false_answers: ["အတုယူခြင်း", "ဖျက်ဆီးခြင်း"],
    },
  },
  {
    id: 48,
    kanji: "外す",
    hiragana: "はずす",
    type: "Verb",
    myanmar: "ဖယ်ရှားသည် / ချွတ်သည်",
    flashcard: {
      question: "外す (hazusu) means?",
      correct_answer: "ဖယ်ရှားသည်",
      false_answers: ["တပ်ဆင်သည်", "ကိုင်သည်"],
    },
  },
  {
    id: 49,
    kanji: "品",
    hiragana: "ひん",
    type: "Noun",
    myanmar: "ကုန်ပစ္စည်း / ယဉ်ကျေးမှု",
    flashcard: {
      question: "品 (hin) means?",
      correct_answer: "ကုန်ပစ္စည်း",
      false_answers: ["လူ", "တိရစ္ဆာန်"],
    },
  },
  {
    id: 50,
    kanji: "一言",
    hiragana: "ひとこと",
    type: "Noun, Suru verb",
    myanmar: "စကားတစ်ခွန်း / အနည်းငယ်",
    flashcard: {
      question: "一言 (ひとこと) means?",
      correct_answer: "စကားတစ်ခွန်း",
      false_answers: ["စကားများစွာ", "စာအုပ်"],
    },
  },
  {
    id: 51,
    kanji: "一人一人",
    hiragana: "ひとりひとり",
    type: "Noun",
    myanmar: "တစ်ယောက်ချင်းစီ",
    flashcard: {
      question: "一人一人 means?",
      correct_answer: "တစ်ယောက်ချင်းစီ",
      false_answers: ["အားလုံးအတူတူ", "တစ်ယောက်တည်း"],
    },
  },
  {
    id: 52,
    kanji: "本物",
    hiragana: "ほんもの",
    type: "Noun",
    myanmar: "အစစ်အမှန်",
    flashcard: {
      question: "本物 (ほんもの) means?",
      correct_answer: "အစစ်အမှန်",
      false_answers: ["အတု", "အရုပ်"],
    },
  },
  {
    id: 53,
    kanji: "本人",
    hiragana: "ほんにん",
    type: "Noun",
    myanmar: "ကာယကံရှင်ကိုယ်တိုင်",
    flashcard: {
      question: "本人 means?",
      correct_answer: "ကာယကံရှင်",
      false_answers: ["အခြားသူ", "သူငယ်ချင်း"],
    },
  },
  {
    id: 54,
    kanji: "一致",
    hiragana: "いっち",
    type: "Noun, Suru verb",
    myanmar: "ကိုက်ညီခြင်း / တိုက်ဆိုင်ခြင်း",
    flashcard: {
      question: "一致 means?",
      correct_answer: "ကိုက်ညီခြင်း",
      false_answers: ["ကွဲလွဲခြင်း", "အမှား"],
    },
  },
  {
    id: 55,
    kanji: "一時",
    hiragana: "いちじ",
    type: "Noun",
    myanmar: "တစ်နာရီ / ခဏတာ",
    flashcard: {
      question: "一時 means?",
      correct_answer: "တစ်နာရီ",
      false_answers: ["နှစ်နာရီ", "အမြဲတမ်း"],
    },
  },
  {
    id: 56,
    kanji: "意外",
    hiragana: "いがい",
    type: "な-adjective",
    myanmar: "မထင်မှတ်ထားသော / အံ့ဩစရာ",
    flashcard: {
      question: "意外 means?",
      correct_answer: "မထင်မှတ်ထားသော",
      false_answers: ["ပုံမှန်", "သိပြီးသား"],
    },
  },
  {
    id: 57,
    kanji: "一家",
    hiragana: "いっか",
    type: "Noun",
    myanmar: "မိသားစုတစ်စုလုံး",
    flashcard: {
      question: "一家 (いっか) means?",
      correct_answer: "မိသားစုတစ်စု",
      false_answers: ["အိမ်နီးချင်း", "ကျောင်း"],
    },
  },
  {
    id: 58,
    kanji: "今に",
    hiragana: "いまに",
    type: "Adverb",
    myanmar: "မကြာမီ / မကြာခင်မှာ",
    flashcard: {
      question: "今に means?",
      correct_answer: "မကြာမီ",
      false_answers: ["ယခင်က", "ဘယ်တော့မှ"],
    },
  },
  {
    id: 59,
    kanji: "今にも",
    hiragana: "いまにも",
    type: "Adverb",
    myanmar: "အခုချက်ချင်းပဲ (ဖြစ်တော့မည့်ပုံစံ)",
    flashcard: {
      question: "今にも means?",
      correct_answer: "အခုချက်ချင်း",
      false_answers: ["နောက်မှ", "ကြာပြီ"],
    },
  },
  {
    id: 60,
    kanji: "一般",
    hiragana: "いっぱん",
    type: "Noun, な-adjective",
    myanmar: "ယေဘုယျ / သာမန်",
    flashcard: {
      question: "一般 means?",
      correct_answer: "ယေဘုယျ",
      false_answers: ["အထူးသီးသန့်", "ရှားပါးသော"],
    },
  },
  {
    id: 61,
    kanji: "一方",
    hiragana: "いっぽう",
    type: "Noun",
    myanmar: "တစ်ဖက်တွင် / တစ်ဖက်သတ်",
    flashcard: {
      question: "一方 means?",
      correct_answer: "တစ်ဖက်တွင်",
      false_answers: ["နှစ်ဖက်စလုံး", "အလယ်"],
    },
  },
  {
    id: 62,
    kanji: "一生",
    hiragana: "いっしょう",
    type: "Noun",
    myanmar: "တစ်သက်လုံး",
    flashcard: {
      question: "一生 means?",
      correct_answer: "တစ်သက်လုံး",
      false_answers: ["တစ်ရက်", "တစ်နှစ်"],
    },
  },
  {
    id: 63,
    kanji: "一種",
    hiragana: "いっしゅ",
    type: "Noun",
    myanmar: "အမျိုးအစားတစ်ခု",
    flashcard: {
      question: "一種 (いっしゅ) means?",
      correct_answer: "အမျိုးအစားတစ်ခု",
      false_answers: ["အားလုံး", "မတူညီမှု"],
    },
  },
  {
    id: 64,
    kanji: "一瞬",
    hiragana: "いっしゅん",
    type: "Noun",
    myanmar: "ခဏတာ / မျက်တောင်တစ်ခတ်",
    flashcard: {
      question: "一瞬 means?",
      correct_answer: "ခဏတာ",
      false_answers: ["အချိန်အကြာကြီး", "အမြဲ"],
    },
  },
  {
    id: 65,
    kanji: "一層",
    hiragana: "いっそう",
    type: "Adverb",
    myanmar: "ပို၍ / ပိုမို၍",
    flashcard: {
      question: "一層 (いっそう) means?",
      correct_answer: "ပို၍",
      false_answers: ["နည်း၍", "တူတူပဲ"],
    },
  },
  {
    id: 66,
    kanji: "一体",
    hiragana: "いったい",
    type: "Adverb",
    myanmar: "တကယ်တမ်းတော့ / ဘာဖြစ်လို့လဲ (အံ့ဩသံ)",
    flashcard: {
      question: "一体 means?",
      correct_answer: "တကယ်တမ်းတော့",
      false_answers: ["ခဏနေ", "အပြင်မှာ"],
    },
  },
  {
    id: 67,
    kanji: "所謂",
    hiragana: "いわゆる",
    type: "Pre-noun adjectival",
    myanmar: "ခေါ်ဝေါ်ကြသော / ဆိုကြပါစို့",
    flashcard: {
      question: "いわゆる means?",
      correct_answer: "ခေါ်ဝေါ်ကြသော",
      false_answers: ["မသိရသော", "နာမည်မဲ့"],
    },
  },
  {
    id: 68,
    kanji: "邪魔",
    hiragana: "じゃま",
    type: "Noun, な-adjective",
    myanmar: "အနှောင့်အယှက်",
    flashcard: {
      question: "邪魔 (じゃま) means?",
      correct_answer: "အနှောင့်အယှက်",
      false_answers: ["အကူအညီ", "ပျော်ရွှင်မှု"],
    },
  },
  {
    id: 69,
    kanji: "化学",
    hiragana: "かがく",
    type: "Noun",
    myanmar: "ဓာတုဗေဒ",
    flashcard: {
      question: "化学 (かがく) means?",
      correct_answer: "ဓာတုဗေဒ",
      false_answers: ["ရူပဗေဒ", "သင်္ချာ"],
    },
  },
  {
    id: 70,
    kanji: "会",
    hiragana: "かい",
    type: "Noun, Suffix",
    myanmar: "အစည်းအဝေး / အသင်းအဖွဲ့",
    flashcard: {
      question: "会 (かい) means?",
      correct_answer: "အသင်းအဖွဲ့",
      false_answers: ["ကျောင်း", "ဈေး"],
    },
  },
  {
    id: 71,
    kanji: "会員",
    hiragana: "かいいん",
    type: "Noun",
    myanmar: "အသင်းဝင်",
    flashcard: {
      question: "会員 means?",
      correct_answer: "အသင်းဝင်",
      false_answers: ["ဧည့်သည်", "သူစိမ်း"],
    },
  },
  {
    id: 72,
    kanji: "海外",
    hiragana: "かいがい",
    type: "Noun",
    myanmar: "နိုင်ငံခြား / ပင်လယ်ရပ်ခြား",
    flashcard: {
      question: "海外 means?",
      correct_answer: "နိုင်ငံခြား",
      false_answers: ["ပြည်တွင်း", "အိမ်"],
    },
  },
  {
    id: 73,
    kanji: "会合",
    hiragana: "かいごう",
    type: "Noun, Suru verb",
    myanmar: "လူစုလူဝေး / တွေ့ဆုံပွဲ",
    flashcard: {
      question: "会合 means?",
      correct_answer: "တွေ့ဆုံပွဲ",
      false_answers: ["လမ်းခွဲပွဲ", "အိပ်ခြင်း"],
    },
  },
  {
    id: 74,
    kanji: "会計",
    hiragana: "かいけい",
    type: "Noun",
    myanmar: "စာရင်းကိုင် / ငွေပေးချေမှု",
    flashcard: {
      question: "会計 means?",
      correct_answer: "ငွေပေးချေမှု",
      false_answers: ["မှာယူမှု", "ဟင်းချက်ခြင်း"],
    },
  },
  {
    id: 75,
    kanji: "開始",
    hiragana: "かいし",
    type: "Noun, Suru verb",
    myanmar: "စတင်ခြင်း",
    flashcard: {
      question: "開始 (かいし) means?",
      correct_answer: "စတင်ခြင်း",
      false_answers: ["ပြီးဆုံးခြင်း", "နားခြင်း"],
    },
  },
  {
    id: 76,
    kanji: "科目",
    hiragana: "かもく",
    type: "Noun",
    myanmar: "ဘာသာရပ်",
    flashcard: {
      question: "科目 (かもく) means?",
      correct_answer: "ဘာသာရပ်",
      false_answers: ["ကျောင်းသား", "စာအုပ်"],
    },
  },
  {
    id: 77,
    kanji: "権利",
    hiragana: "けんり",
    type: "Noun",
    myanmar: "အခွင့်အရေး / ရပိုင်ခွင့်",
    flashcard: {
      question: "権利 (けんり) means?",
      correct_answer: "ရပိုင်ခွင့်",
      false_answers: ["တာဝန်", "ပြစ်ဒဏ်"],
    },
  },
  {
    id: 78,
    kanji: "基本",
    hiragana: "きほん",
    type: "Noun",
    myanmar: "အခြေခံ",
    flashcard: {
      question: "基本 (きほん) means?",
      correct_answer: "အခြေခံ",
      false_answers: ["အထက်တန်း", "နောက်ဆုံး"],
    },
  },
  {
    id: 79,
    kanji: "記事",
    hiragana: "きじ",
    type: "Noun",
    myanmar: "ဆောင်းပါး / သတင်း",
    flashcard: {
      question: "記事 (きじ) means?",
      correct_answer: "ဆောင်းပါး",
      false_answers: ["ဓာတ်ပုံ", "သီချင်း"],
    },
  },
  {
    id: 80,
    kanji: "気味",
    hiragana: "きみ",
    type: "Noun",
    myanmar: "ခံစားချက် / အငွေ့အသက်",
    flashcard: {
      question: "気味 means?",
      correct_answer: "ခံစားချက်",
      false_answers: ["အနံ့", "အရောင်"],
    },
  },
  {
    id: 81,
    kanji: "記念",
    hiragana: "きねん",
    type: "Noun, Suru verb",
    myanmar: "အမှတ်တရ / ဂုဏ်ပြုခြင်း",
    flashcard: {
      question: "記念 means?",
      correct_answer: "အမှတ်တရ",
      false_answers: ["မေ့လျော့ခြင်း", "အနာဂတ်"],
    },
  },
  {
    id: 82,
    kanji: "気に入る",
    hiragana: "きにいる",
    type: "Verb",
    myanmar: "သဘောကျသည်",
    flashcard: {
      question: "気に入る means?",
      correct_answer: "သဘောကျသည်",
      false_answers: ["မုန်းသည်", "ကြောက်သည်"],
    },
  },
  {
    id: 83,
    kanji: "記入",
    hiragana: "きにゅう",
    type: "Noun, Suru verb",
    myanmar: "ဖြည့်စွက်ရေးသားခြင်း",
    flashcard: {
      question: "記入 means?",
      correct_answer: "ဖြည့်စွက်ခြင်း",
      false_answers: ["ဖျက်ထုတ်ခြင်း", "ဖတ်ခြင်း"],
    },
  },
  {
    id: 84,
    kanji: "記憶",
    hiragana: "きおく",
    type: "Noun, Suru verb",
    myanmar: "မှတ်ဉာဏ် / မှတ်မိခြင်း",
    flashcard: {
      question: "記憶 (きおく) means?",
      correct_answer: "မှတ်ဉာဏ်",
      false_answers: ["အိပ်မက်", "မေ့ခြင်း"],
    },
  },
  {
    id: 85,
    kanji: "記者",
    hiragana: "きしゃ",
    type: "Noun",
    myanmar: "သတင်းထောက်",
    flashcard: {
      question: "記者 means?",
      correct_answer: "သတင်းထောက်",
      false_answers: ["ဆရာဝန်", "မင်းသား"],
    },
  },
  {
    id: 86,
    kanji: "期待",
    hiragana: "きたい",
    type: "Noun, Suru verb",
    myanmar: "မျှော်လင့်ခြင်း",
    flashcard: {
      question: "期待 (きたい) means?",
      correct_answer: "မျှော်လင့်ခြင်း",
      false_answers: ["စိတ်ပျက်ခြင်း", "ကြောက်ရွံ့ခြင်း"],
    },
  },
  {
    id: 87,
    kanji: "国家",
    hiragana: "こっか",
    type: "Noun",
    myanmar: "နိုင်ငံ / တိုင်းပြည်",
    flashcard: {
      question: "国家 (こっか) means?",
      correct_answer: "နိုင်ငံ",
      false_answers: ["မြို့", "ရွာ"],
    },
  },
  {
    id: 88,
    kanji: "国会",
    hiragana: "こっかい",
    type: "Noun",
    myanmar: "အမျိုးသားလွှတ်တော်",
    flashcard: {
      question: "国会 means?",
      correct_answer: "လွှတ်တော်",
      false_answers: ["တရားရုံး", "ကျောင်း"],
    },
  },
  {
    id: 89,
    kanji: "国境",
    hiragana: "こっきょう",
    type: "Noun",
    myanmar: "နိုင်ငံခြားနယ်စပ်",
    flashcard: {
      question: "国境 (こっきょう) means?",
      correct_answer: "နယ်စပ်",
      false_answers: ["မြို့လယ်", "ပင်လယ်"],
    },
  },
  {
    id: 90,
    kanji: "国語",
    hiragana: "こくご",
    type: "Noun",
    myanmar: "မိခင်ဘာသာစကား / နိုင်ငံတော်ဘာသာ",
    flashcard: {
      question: "国語 (こくご) means?",
      correct_answer: "မိခင်ဘာသာစကား",
      false_answers: ["အင်္ဂလိပ်စာ", "သင်္ချာ"],
    },
  },
  {
    id: 91,
    kanji: "国民",
    hiragana: "こくみん",
    type: "Noun",
    myanmar: "နိုင်ငံသား / လူမျိုး",
    flashcard: {
      question: "国民 means?",
      correct_answer: "နိုင်ငံသား",
      false_answers: ["ဧည့်သည်", "သူစိမ်း"],
    },
  },
  {
    id: 92,
    kanji: "今後",
    hiragana: "こんご",
    type: "Noun, Adverb",
    myanmar: "နောင်နောင်တွင် / ယခုမှစ၍",
    flashcard: {
      question: "今後 means?",
      correct_answer: "နောင်နောင်တွင်",
      false_answers: ["ယခင်က", "ယနေ့"],
    },
  },
  {
    id: 93,
    kanji: "今回",
    hiragana: "こんかい",
    type: "Noun, Adverb",
    myanmar: "ဒီတစ်ကြိမ် / ယခုတစ်ခေါက်",
    flashcard: {
      question: "今回 means?",
      correct_answer: "ဒီတစ်ကြိမ်",
      false_answers: ["ပြီးခဲ့သည့်အကြိမ်", "နောက်တစ်ကြိမ်"],
    },
  },
  {
    id: 94,
    kanji: "今日",
    hiragana: "こんにち",
    type: "Noun",
    myanmar: "ယနေ့ခေတ် / ယနေ့",
    flashcard: {
      question: "今日 (こんにち) means?",
      correct_answer: "ယနေ့",
      false_answers: ["မနေ့က", "မနက်ဖြန်"],
    },
  },
  {
    id: 95,
    kanji: "転ぶ",
    hiragana: "ころぶ",
    type: "Verb",
    myanmar: "လဲကျသည်",
    flashcard: {
      question: "転ぶ (ころぶ) means?",
      correct_answer: "လဲကျသည်",
      false_answers: ["ထိုင်သည်", "ခုန်သည်"],
    },
  },
  {
    id: 96,
    kanji: "高速",
    hiragana: "こうそく",
    type: "Noun, な-adjective",
    myanmar: "အရှိန်ပြင်း / အမြန်နှုန်း",
    flashcard: {
      question: "高速 means?",
      correct_answer: "အရှိန်ပြင်း",
      false_answers: ["နှေးကွေးသော", "သာမန်"],
    },
  },
  {
    id: 97,
    kanji: "訓練",
    hiragana: "くんれん",
    type: "Noun, Suru verb",
    myanmar: "လေ့ကျင့်ခန်း / လေ့ကျင့်ပေးခြင်း",
    flashcard: {
      question: "訓練 (くんれん) means?",
      correct_answer: "လေ့ကျင့်ခြင်း",
      false_answers: ["အနားယူခြင်း", "ကစားခြင်း"],
    },
  },
  {
    id: 98,
    kanji: "教科書",
    hiragana: "きょうかしょ",
    type: "Noun",
    myanmar: "သင်ရိုးညွှန်းတမ်းစာအုပ်",
    flashcard: {
      question: "教科書 means?",
      correct_answer: "သင်ရိုးစာအုပ်",
      false_answers: ["ဝတ္ထု", "သတင်းစာ"],
    },
  },
  {
    id: 99,
    kanji: "協力",
    hiragana: "きょうりょく",
    type: "Noun, Suru verb",
    myanmar: "ပူးပေါင်းဆောင်ရွက်ခြင်း",
    flashcard: {
      question: "協力 (kyouryoku) means?",
      correct_answer: "ပူးပေါင်းဆောင်ရွက်ခြင်း",
      false_answers: ["ရန်ဖြစ်ခြင်း", "တစ်ဦးတည်းလုပ်ခြင်း"],
    },
  },
  {
    id: 100,
    kanji: "強力",
    hiragana: "きょうりょく",
    type: "な-adjective",
    myanmar: "အင်အားကြီးမားသော",
    flashcard: {
      question: "強力 (kyouryoku) means?",
      correct_answer: "အင်အားကြီးသော",
      false_answers: ["အားနည်းသော", "သေးငယ်သော"],
    },
  },
  {
    id: 101,
    kanji: "急激",
    hiragana: "きゅうげき",
    type: "な-adjective",
    myanmar: "ရုတ်တရက်ပြင်းထန်သော / ရုတ်ခြည်းဖြစ်သော",
    flashcard: {
      question: "急激 (きゅうげき) means?",
      correct_answer: "ရုတ်တရက်ပြင်းထန်သော",
      false_answers: ["နှေးကွေးသော", "ပုံမှန်"],
    },
  },
  {
    id: 102,
    kanji: "急に",
    hiragana: "きゅうに",
    type: "Adverb",
    myanmar: "ရုတ်တရက် / အလျင်အမြန်",
    flashcard: {
      question: "急に (きゅうに) means?",
      correct_answer: "ရုတ်တရက်",
      false_answers: ["ဖြည်းဖြည်းချင်း", "နောက်မှ"],
    },
  },
  {
    id: 103,
    kanji: "吸収",
    hiragana: "きゅうしゅう",
    type: "Noun, Suru verb",
    myanmar: "စုပ်ယူခြင်း",
    flashcard: {
      question: "吸収 (きゅうしゅう) means?",
      correct_answer: "စုပ်ယူခြင်း",
      false_answers: ["ထုတ်လွှတ်ခြင်း", "ပက်ဖြန်းခြင်း"],
    },
  },
  {
    id: 104,
    kanji: "急速",
    hiragana: "きゅうそく",
    type: "Noun, な-adjective",
    myanmar: "လျင်မြန်သော (တိုးတက်မှု စသည်)",
    flashcard: {
      question: "急速 (きゅうそく) means?",
      correct_answer: "လျင်မြန်သော",
      false_answers: ["နှေးကွေးသော", "ရပ်တန့်သော"],
    },
  },
  {
    id: 105,
    kanji: "真面目",
    hiragana: "まじめ",
    type: "Noun, な-adjective",
    myanmar: "အလုပ်အကိုင်ရိုးသားကြိုးစားသော / တည်ကြည်သော",
    flashcard: {
      question: "真面目 (まじめ) means?",
      correct_answer: "ရိုးသားကြိုးစားသော",
      false_answers: ["ပျင်းရိသော", "လိမ်ညာသော"],
    },
  },
  {
    id: 106,
    kanji: "真っ赤",
    hiragana: "まっか",
    type: "Noun, な-adjective",
    myanmar: "ရဲရဲနီသော",
    flashcard: {
      question: "真っ赤 (まっか) means?",
      correct_answer: "ရဲရဲနီသော",
      false_answers: ["အပြာရောင်", "အနက်ရောင်"],
    },
  },
  {
    id: 107,
    kanji: "学ぶ",
    hiragana: "まなぶ",
    type: "Verb",
    myanmar: "သင်ယူလေ့လာသည်",
    flashcard: {
      question: "学ぶ (まなぶ) means?",
      correct_answer: "သင်ယူသည်",
      false_answers: ["ကစားသည်", "မေ့သည်"],
    },
  },
  {
    id: 108,
    kanji: "万一",
    hiragana: "まんいち",
    type: "Noun, Adverb",
    myanmar: "မတော်တဆ / တစ်ခုခုဖြစ်ခဲ့လျှင်",
    flashcard: {
      question: "万一 (まんいち) means?",
      correct_answer: "မတော်တဆဖြစ်ခဲ့လျှင်",
      false_answers: ["အမြဲတမ်း", "လုံးဝမဖြစ်နိုင်"],
    },
  },
  {
    id: 109,
    kanji: "満足",
    hiragana: "まんぞく",
    type: "Noun, Suru verb",
    myanmar: "ကျေနပ်အားရခြင်း",
    flashcard: {
      question: "満足 (まんぞく) means?",
      correct_answer: "ကျေနပ်ခြင်း",
      false_answers: ["စိတ်ဆိုးခြင်း", "မလုံလောက်ခြင်း"],
    },
  },
  {
    id: 110,
    kanji: "明確",
    hiragana: "めいかく",
    type: "な-adjective",
    myanmar: "တိကျပြတ်သားသော / ရှင်းလင်းသော",
    flashcard: {
      question: "明確 (めいかく) means?",
      correct_answer: "တိကျပြတ်သားသော",
      false_answers: ["ဝေဝါးသော", "မှားယွင်းသော"],
    },
  },
  {
    id: 111,
    kanji: "飯",
    hiragana: "めし",
    type: "Noun",
    myanmar: "ထမင်း / အစားအစာ",
    flashcard: {
      question: "飯 (めし) means?",
      correct_answer: "ထမင်း",
      false_answers: ["ရေ", "အသီး"],
    },
  },
  {
    id: 112,
    kanji: "味方",
    hiragana: "みかた",
    type: "Noun, Suru verb",
    myanmar: "မိမိဘက်တော်သား / ထောက်ခံသူ",
    flashcard: {
      question: "味方 (みかた) means?",
      correct_answer: "မိမိဘက်တော်သား",
      false_answers: ["ရန်သူ", "သူစိမ်း"],
    },
  },
  {
    id: 113,
    kanji: "魅力",
    hiragana: "みりょく",
    type: "Noun",
    myanmar: "ဆွဲဆောင်မှု",
    flashcard: {
      question: "魅力 (みりょく) means?",
      correct_answer: "ဆွဲဆောင်မှု",
      false_answers: ["ရွံရှာမှု", "ကြောက်ရွံ့မှု"],
    },
  },
  {
    id: 114,
    kanji: "木曜",
    hiragana: "もくよう",
    type: "Noun",
    myanmar: "ကြာသပတေးနေ့",
    flashcard: {
      question: "木曜 (もくよう) means?",
      correct_answer: "ကြာသပတေးနေ့",
      false_answers: ["အင်္ဂါနေ့", "သောကြာနေ့"],
    },
  },
  {
    id: 115,
    kanji: "半ば",
    hiragana: "なかば",
    type: "Noun",
    myanmar: "တစ်ဝက် / အလယ်",
    flashcard: {
      question: "半ば (なかば) means?",
      correct_answer: "တစ်ဝက်",
      false_answers: ["တစ်ခုလုံး", "အစ"],
    },
  },
  {
    id: 116,
    kanji: "熱心",
    hiragana: "ねっしん",
    type: "Noun, な-adjective",
    myanmar: "ထက်သန်သော / စိတ်အားထက်သန်သော",
    flashcard: {
      question: "熱心 (ねっしん) means?",
      correct_answer: "ထက်သန်သော",
      false_answers: ["ပျင်းရိသော", "အေးစက်သော"],
    },
  },
  {
    id: 117,
    kanji: "日本",
    hiragana: "にほん",
    type: "Noun",
    myanmar: "ဂျပန်နိုင်ငံ",
    flashcard: {
      question: "日本 means?",
      correct_answer: "ဂျပန်",
      false_answers: ["မြန်မာ", "တရုတ်"],
    },
  },
  {
    id: 118,
    kanji: "能力",
    hiragana: "のうりょく",
    type: "Noun",
    myanmar: "စွမ်းဆောင်ရည် / အရည်အချင်း",
    flashcard: {
      question: "能力 (のうりょく) means?",
      correct_answer: "အရည်အချင်း",
      false_answers: ["အမည်", "ရုပ်ရည်"],
    },
  },
  {
    id: 119,
    kanji: "入場",
    hiragana: "にゅうじょう",
    type: "Noun, Suru verb",
    myanmar: "ဝင်ရောက်ခြင်း",
    flashcard: {
      question: "入場 (にゅうじょう) means?",
      correct_answer: "ဝင်ရောက်ခြင်း",
      false_answers: ["ထွက်ခွာခြင်း", "ပျောက်ဆုံးခြင်း"],
    },
  },
  {
    id: 120,
    kanji: "お昼",
    hiragana: "おひる",
    type: "Noun",
    myanmar: "နေ့လယ်ခင်း / နေ့လယ်စာ",
    flashcard: {
      question: "お昼 means?",
      correct_answer: "နေ့လယ်ခင်း",
      false_answers: ["မနက်ခင်း", "ညဉ့်နက်"],
    },
  },
  {
    id: 121,
    kanji: "収める",
    hiragana: "おさめる",
    type: "Verb",
    myanmar: "ပေးသွင်းသည် / သိမ်းဆည်းသည်",
    flashcard: {
      question: "収める (osameru) means?",
      correct_answer: "ပေးသွင်းသည်",
      false_answers: ["ထုတ်ယူသည်", "ဖြုန်းတီးသည်"],
    },
  },
  {
    id: 122,
    kanji: "連続",
    hiragana: "れんぞく",
    type: "Noun, Suru verb",
    myanmar: "အဆက်မပြတ်ဖြစ်ခြင်း / ဆက်တိုက်",
    flashcard: {
      question: "連続 (れんぞく) means?",
      correct_answer: "အဆက်မပြတ်",
      false_answers: ["တစ်ခါတလေ", "ရပ်နားခြင်း"],
    },
  },
  {
    id: 123,
    kanji: "利益",
    hiragana: "りえき",
    type: "Noun, Suru verb",
    myanmar: "အမြတ်အစွန်း / အကျိုးအမြတ်",
    flashcard: {
      question: "利益 (りえき) means?",
      correct_answer: "အမြတ်အစွန်း",
      false_answers: ["အရှုံး", "အရင်း"],
    },
  },
  {
    id: 124,
    kanji: "利口",
    hiragana: "りこう",
    type: "Noun, な-adjective",
    myanmar: "ထက်မြက်သော / လိမ်မာသော",
    flashcard: {
      question: "利口 (りこう) means?",
      correct_answer: "ထက်မြက်သော",
      false_answers: ["ထုံအသော", "ဆိုးသွမ်းသော"],
    },
  },
  {
    id: 125,
    kanji: "留学",
    hiragana: "りゅうがく",
    type: "Noun, Suru verb",
    myanmar: "နိုင်ငံခြားပညာတော်သင်သွားခြင်း",
    flashcard: {
      question: "留学 means?",
      correct_answer: "နိုင်ငံခြားပညာသင်သွားခြင်း",
      false_answers: ["အလုပ်ထွက်ခြင်း", "အိမ်ပြန်ခြင်း"],
    },
  },
  {
    id: 126,
    kanji: "作品",
    hiragana: "さくひん",
    type: "Noun",
    myanmar: "လက်ရာ / ဖန်တီးမှုပစ္စည်း",
    flashcard: {
      question: "作品 (さくひん) means?",
      correct_answer: "လက်ရာ",
      false_answers: ["ကိရိယာ", "ကုန်ကြမ်း"],
    },
  },
  {
    id: 127,
    kanji: "左右",
    hiragana: "さゆう",
    type: "Noun, Suru verb",
    myanmar: "ဘယ်နှင့်ညာ / လွှမ်းမိုးခြင်း",
    flashcard: {
      question: "左右 (さゆう) means?",
      correct_answer: "ဘယ်နှင့်ညာ",
      false_answers: ["အပေါ်နှင့်အောက်", "ရှေ့နှင့်နောက်"],
    },
  },
  {
    id: 128,
    kanji: "成長",
    hiragana: "せいちょう",
    type: "Noun, Suru verb",
    myanmar: "ကြီးထွားလာခြင်း / ဖွံ့ဖြိုးခြင်း",
    flashcard: {
      question: "成長 (せいちょう) means?",
      correct_answer: "ကြီးထွားခြင်း",
      false_answers: ["သေးသိမ်ခြင်း", "ပျက်စီးခြင်း"],
    },
  },
  {
    id: 129,
    kanji: "製品",
    hiragana: "せいひん",
    type: "Noun",
    myanmar: "ထုတ်ကုန်ပစ္စည်း",
    flashcard: {
      question: "製品 (せいひん) means?",
      correct_answer: "ထုတ်ကုန်",
      false_answers: ["သဘာဝပစ္စည်း", "အစားအစာ"],
    },
  },
  {
    id: 130,
    kanji: "青年",
    hiragana: "せいねん",
    type: "Noun",
    myanmar: "လူငယ်",
    flashcard: {
      question: "青年 (せいねん) means?",
      correct_answer: "လူငယ်",
      false_answers: ["လူကြီး", "ကလေး"],
    },
  },
  {
    id: 131,
    kanji: "刺激",
    hiragana: "しげき",
    type: "Noun, Suru verb",
    myanmar: "လှုံ့ဆော်မှု / စိတ်ကြွမှု",
    flashcard: {
      question: "刺激 (しげき) means?",
      correct_answer: "လှုံ့ဆော်မှု",
      false_answers: ["ငြိမ်သက်မှု", "အိပ်စက်ခြင်း"],
    },
  },
  {
    id: 132,
    kanji: "資本",
    hiragana: "しほん",
    type: "Noun",
    myanmar: "အရင်းအနှီး / အရင်းအနှီးငွေ",
    flashcard: {
      question: "資本 (しほん) means?",
      correct_answer: "အရင်းအနှီး",
      false_answers: ["အမြတ်", "အကြွေး"],
    },
  },
  {
    id: 133,
    kanji: "品",
    hiragana: "しな",
    type: "Noun",
    myanmar: "ကုန်ပစ္စည်း / အရည်အသွေး",
    flashcard: {
      question: "品 (shina) means?",
      correct_answer: "ကုန်ပစ္စည်း",
      false_answers: ["ဈေးနှုန်း", "လူ"],
    },
  },
  {
    id: 134,
    kanji: "身長",
    hiragana: "しんちょう",
    type: "Noun",
    myanmar: "အရပ်အမောင်း",
    flashcard: {
      question: "身長 (しんちょう) means?",
      correct_answer: "အရပ်အမောင်း",
      false_answers: ["ကိုယ်အလေးချိန်", "အသက်"],
    },
  },
  {
    id: 135,
    kanji: "進学",
    hiragana: "しんがく",
    type: "Noun, Suru verb",
    myanmar: "အဆင့်မြင့်ကျောင်းသို့ တက်ရောက်ခြင်း",
    flashcard: {
      question: "進学 means?",
      correct_answer: "ကျောင်းဆက်တက်ခြင်း",
      false_answers: ["ကျောင်းထွက်ခြင်း", "အလုပ်ဝင်ခြင်း"],
    },
  },
  {
    id: 136,
    kanji: "新鮮",
    hiragana: "しんせん",
    type: "な-adjective",
    myanmar: "လတ်ဆတ်သော",
    flashcard: {
      question: "新鮮 (しんせん) means?",
      correct_answer: "လတ်ဆတ်သော",
      false_answers: ["ပုပ်သိုးသော", "ဟောင်းသော"],
    },
  },
  {
    id: 137,
    kanji: "支店",
    hiragana: "してん",
    type: "Noun",
    myanmar: "ဘဏ်ခွဲ / ဆိုင်ခွဲ",
    flashcard: {
      question: "支店 (してん) means?",
      correct_answer: "ဆိုင်ခွဲ",
      false_answers: ["ရုံးချုပ်", "ဈေး"],
    },
  },
  {
    id: 138,
    kanji: "使用",
    hiragana: "しよう",
    type: "Noun, Suru verb",
    myanmar: "အသုံးပြုခြင်း",
    flashcard: {
      question: "使用 (しよう) means?",
      correct_answer: "အသုံးပြုခြင်း",
      false_answers: ["စွန့်ပစ်ခြင်း", "ဝှက်ထားခြင်း"],
    },
  },
  {
    id: 139,
    kanji: "食品",
    hiragana: "しょくひん",
    type: "Noun",
    myanmar: "အစားအသောက်",
    flashcard: {
      question: "食品 means?",
      correct_answer: "အစားအသောက်",
      false_answers: ["အဝတ်အထည်", "ဆေးဝါး"],
    },
  },
  {
    id: 140,
    kanji: "書物",
    hiragana: "しょもつ",
    type: "Noun",
    myanmar: "စာအုပ်",
    flashcard: {
      question: "書物 (しょもつ) means?",
      correct_answer: "စာအုပ်",
      false_answers: ["ဘောပင်", "စားပွဲ"],
    },
  },
  {
    id: 141,
    kanji: "書類",
    hiragana: "しょるい",
    type: "Noun",
    myanmar: "စာရွက်စာတမ်း",
    flashcard: {
      question: "書類 (しょるい) means?",
      correct_answer: "စာရွက်စာတမ်း",
      false_answers: ["အိတ်", "ကွန်ပျူတာ"],
    },
  },
  {
    id: 142,
    kanji: "書斎",
    hiragana: "しょさい",
    type: "Noun",
    myanmar: "စာဖတ်ခန်း",
    flashcard: {
      question: "書斎 (しょさい) means?",
      correct_answer: "စာဖတ်ခန်း",
      false_answers: ["အိပ်ခန်း", "မီးဖိုချောင်"],
    },
  },
  {
    id: 143,
    kanji: "商売",
    hiragana: "しょうばい",
    type: "Noun",
    myanmar: "စီးပွားရေး / ရောင်းဝယ်ရေး",
    flashcard: {
      question: "商売 means?",
      correct_answer: "ရောင်းဝယ်ရေး",
      false_answers: ["အားကစား", "ပညာရေး"],
    },
  },
  {
    id: 144,
    kanji: "奨学金",
    hiragana: "しょうがくきん",
    type: "Noun",
    myanmar: "ပညာသင်ဆု",
    flashcard: {
      question: "奨学金 means?",
      correct_answer: "ပညာသင်ဆု",
      false_answers: ["အခွန်", "ဒဏ်ငွေ"],
    },
  },
  {
    id: 145,
    kanji: "正午",
    hiragana: "しょうご",
    type: "Noun",
    myanmar: "မွန်းတည့် ၁၂ နာရီ",
    flashcard: {
      question: "正午 (しょうご) means?",
      correct_answer: "မွန်းတည့်ချိန်",
      false_answers: ["ညသန်းခေါင်", "မနက်ခင်း"],
    },
  },
  {
    id: 146,
    kanji: "商品",
    hiragana: "しょうひん",
    type: "Noun",
    myanmar: "ကုန်စည်ပစ္စည်း",
    flashcard: {
      question: "商品 (しょうひん) means?",
      correct_answer: "ကုန်စည်",
      false_answers: ["ဝန်ဆောင်မှု", "ပိုက်ဆံ"],
    },
  },
  {
    id: 147,
    kanji: "少女",
    hiragana: "しょうじょ",
    type: "Noun",
    myanmar: "မိန်းကလေးငယ်",
    flashcard: {
      question: "少女 means?",
      correct_answer: "မိန်းကလေးငယ်",
      false_answers: ["လူကြီး", "ယောကျ်ားလေး"],
    },
  },
  {
    id: 148,
    kanji: "証明",
    hiragana: "しょうめい",
    type: "Noun, Suru verb",
    myanmar: "သက်သေပြခြင်း",
    flashcard: {
      question: "証明 (しょうめい) means?",
      correct_answer: "သက်သေပြခြင်း",
      false_answers: ["ငြင်းဆိုခြင်း", "ဝှက်ခြင်း"],
    },
  },
  {
    id: 149,
    kanji: "少年",
    hiragana: "しょうねん",
    type: "Noun",
    myanmar: "ယောကျ်ားလေးငယ် / လူငယ်",
    flashcard: {
      question: "少年 means?",
      correct_answer: "ယောကျ်ားလေးငယ်",
      false_answers: ["မိန်းကလေး", "အဘိုး"],
    },
  },
  {
    id: 150,
    kanji: "少々",
    hiragana: "しょうしょう",
    type: "Adverb",
    myanmar: "ခဏ / အနည်းငယ်",
    flashcard: {
      question: "少々 (しょうしょう) means?",
      correct_answer: "ခဏ/အနည်းငယ်",
      false_answers: ["အများကြီး", "အမြဲတမ်း"],
    },
  },
  {
    id: 151,
    kanji: "招待",
    hiragana: "しょうたい",
    type: "Noun, Suru verb",
    myanmar: "ဖိတ်ကြားခြင်း",
    flashcard: {
      question: "招待 means?",
      correct_answer: "ဖိတ်ကြားခြင်း",
      false_answers: ["နှင်ထုတ်ခြင်း", "မေ့ခြင်း"],
    },
  },
  {
    id: 152,
    kanji: "週",
    hiragana: "しゅう",
    type: "Noun",
    myanmar: "ရက်သတ္တပတ်",
    flashcard: {
      question: "週 (しゅう) means?",
      correct_answer: "အပတ်",
      false_answers: ["လ", "နှစ်"],
    },
  },
  {
    id: 153,
    kanji: "集中",
    hiragana: "しゅうちゅう",
    type: "Noun, Suru verb",
    myanmar: "အာရုံစူးစိုက်ခြင်း",
    flashcard: {
      question: "集中 means?",
      correct_answer: "အာရုံစိုက်ခြင်း",
      false_answers: ["ပျံ့လွင့်ခြင်း", "အိပ်ငိုက်ခြင်း"],
    },
  },
  {
    id: 154,
    kanji: "集団",
    hiragana: "しゅうだん",
    type: "Noun",
    myanmar: "အုပ်စု / လူစုလူဝေး",
    flashcard: {
      question: "集団 (しゅうだん) means?",
      correct_answer: "အုပ်စု",
      false_answers: ["တစ်ဦးတည်း", "အိမ်"],
    },
  },
  {
    id: 155,
    kanji: "収穫",
    hiragana: "しゅうかく",
    type: "Noun, Suru verb",
    myanmar: "ရိတ်သိမ်းခြင်း / အသီးအပွင့်",
    flashcard: {
      question: "収穫 means?",
      correct_answer: "ရိတ်သိမ်းခြင်း",
      false_answers: ["စိုက်ပျိုးခြင်း", "ဖျက်ဆီးခြင်း"],
    },
  },
  {
    id: 156,
    kanji: "週間",
    hiragana: "しゅうかん",
    type: "Noun",
    myanmar: "တစ်ပတ်တာ (ကာလ)",
    flashcard: {
      question: "週間 means?",
      correct_answer: "တစ်ပတ်တာ",
      false_answers: ["တစ်ရက်", "တစ်လ"],
    },
  },
  {
    id: 157,
    kanji: "週刊",
    hiragana: "しゅうかん",
    type: "Noun",
    myanmar: "အပတ်စဉ်ထုတ် (မဂ္ဂဇင်း စသည်)",
    flashcard: {
      question: "週刊 means?",
      correct_answer: "အပတ်စဉ်ထုတ်",
      false_answers: ["နေ့စဉ်ထုတ်", "နှစ်ပတ်လည်"],
    },
  },
  {
    id: 158,
    kanji: "収入",
    hiragana: "しゅうにゅう",
    type: "Noun",
    myanmar: "ဝင်ငွေ",
    flashcard: {
      question: "収入 (しゅうにゅう) means?",
      correct_answer: "ဝင်ငွေ",
      false_answers: ["ထွက်ငွေ", "အကြွေး"],
    },
  },
  {
    id: 159,
    kanji: "速度",
    hiragana: "そくど",
    type: "Noun",
    myanmar: "အမြန်နှုန်း",
    flashcard: {
      question: "速度 (そくど) means?",
      correct_answer: "အမြန်နှုန်း",
      false_answers: ["အလေးချိန်", "အကွာအဝေး"],
    },
  },
  {
    id: 160,
    kanji: "少しも",
    hiragana: "すこしも",
    type: "Adverb",
    myanmar: "အနည်းငယ်မျှ (မ...)",
    flashcard: {
      question: "少しも means?",
      correct_answer: "အနည်းငယ်မျှ",
      false_answers: ["အများကြီး", "အားလုံး"],
    },
  },
  {
    id: 161,
    kanji: "大半",
    hiragana: "たいはん",
    type: "Noun",
    myanmar: "အများစု",
    flashcard: {
      question: "大半 means?",
      correct_answer: "အများစု",
      false_answers: ["အနည်းစု", "တစ်ဝက်"],
    },
  },
  {
    id: 162,
    kanji: "大会",
    hiragana: "たいかい",
    type: "Noun",
    myanmar: "ပြိုင်ပွဲ / ညီလာခံ",
    flashcard: {
      question: "大会 (たいかい) means?",
      correct_answer: "ပြိုင်ပွဲ",
      false_answers: ["သင်တန်း", "ဈေး"],
    },
  },
  {
    id: 163,
    kanji: "大した",
    hiragana: "たいした",
    type: "Pre-noun adjectival",
    myanmar: "ကြီးကျယ်သော / အရေးကြီးသော",
    flashcard: {
      question: "大した means?",
      correct_answer: "ကြီးကျယ်သော",
      false_answers: ["သေးငယ်သော", "အရေးမပါသော"],
    },
  },
  {
    id: 164,
    kanji: "単なる",
    hiragana: "たんなる",
    type: "Pre-noun adjectival",
    myanmar: "ရိုးရိုး / သာမန်မျှသာ",
    flashcard: {
      question: "単なる means?",
      correct_answer: "သာမန်မျှသာ",
      false_answers: ["အထူး", "ရှုပ်ထွေးသော"],
    },
  },
  {
    id: 165,
    kanji: "多少",
    hiragana: "たしょう",
    type: "Adverb",
    myanmar: "အနည်းနှင့်အများ / အနည်းငယ်",
    flashcard: {
      question: "多少 means?",
      correct_answer: "အနည်းငယ်",
      false_answers: ["လုံးဝမဟုတ်", "အလွန်အကျွံ"],
    },
  },
  {
    id: 166,
    kanji: "手品",
    hiragana: "てじな",
    type: "Noun",
    myanmar: "မျက်လှည့်",
    flashcard: {
      question: "手品 (てじな) means?",
      correct_answer: "မျက်လှည့်",
      false_answers: ["အားကစား", "သီချင်း"],
    },
  },
  {
    id: 167,
    kanji: "哲学",
    hiragana: "てつがく",
    type: "Noun",
    myanmar: "ဒဿနဗေဒ",
    flashcard: {
      question: "哲学 (てつがく) means?",
      correct_answer: "ဒဿနဗေဒ",
      false_answers: ["ရာဇဝင်", "သိပ္ပံ"],
    },
  },
  {
    id: 168,
    kanji: "徹夜",
    hiragana: "てつや",
    type: "Noun, Suru verb",
    myanmar: "တစ်ညလုံး မအိပ်ဘဲနေခြင်း",
    flashcard: {
      question: "徹夜 means?",
      correct_answer: "တစ်ညလုံးမအိပ်ခြင်း",
      false_answers: ["အိပ်ရေးဝခြင်း", "နေ့လယ်အိပ်ခြင်း"],
    },
  },
  {
    id: 169,
    kanji: "土地",
    hiragana: "とち",
    type: "Noun",
    myanmar: "မြေနေရာ / မြေကွက်",
    flashcard: {
      question: "土地 (とち) means?",
      correct_answer: "မြေနေရာ",
      false_answers: ["ပင်လယ်", "ကောင်းကင်"],
    },
  },
  {
    id: 170,
    kanji: "都会",
    hiragana: "とかい",
    type: "Noun",
    myanmar: "မြို့ကြီးပြကြီး",
    flashcard: {
      question: "都会 (とかい) means?",
      correct_answer: "မြို့ကြီး",
      false_answers: ["ကျေးလက်", "တော"],
    },
  },
  {
    id: 171,
    kanji: "取れる",
    hiragana: "とれる",
    type: "Verb",
    myanmar: "ပြုတ်ထွက်သည် / ရရှိနိုင်သည်",
    flashcard: {
      question: "取れる (toreru) means?",
      correct_answer: "ပြုတ်ထွက်သည်",
      false_answers: ["ကပ်သည်", "ပျောက်သည်"],
    },
  },
  {
    id: 172,
    kanji: "取り上げる",
    hiragana: "とりあげる",
    type: "Verb",
    myanmar: "ကောက်ယူသည် / ဆွေးနွေးတင်ပြသည်",
    flashcard: {
      question: "取り上げる means?",
      correct_answer: "ကောက်ယူသည်",
      false_answers: ["ချထားသည်", "လွှတ်သည်"],
    },
  },
  {
    id: 173,
    kanji: "図書",
    hiragana: "としょ",
    type: "Noun",
    myanmar: "စာအုပ်စာပေ",
    flashcard: {
      question: "図書 means?",
      correct_answer: "စာအုပ်",
      false_answers: ["ရုပ်ရှင်", "ပန်းချီ"],
    },
  },
  {
    id: 174,
    kanji: "通学",
    hiragana: "つうがく",
    type: "Noun, Suru verb",
    myanmar: "ကျောင်းတက်ခြင်း / ကျောင်းသို့သွားခြင်း",
    flashcard: {
      question: "通学 means?",
      correct_answer: "ကျောင်းတက်ခြင်း",
      false_answers: ["အလုပ်သွားခြင်း", "ဈေးဝယ်ခြင်း"],
    },
  },
  {
    id: 175,
    kanji: "受け取る",
    hiragana: "うけとる",
    type: "Verb",
    myanmar: "လက်ခံရရှိသည် / နားလည်သည်",
    flashcard: {
      question: "受け取る means?",
      correct_answer: "လက်ခံရရှိသည်",
      false_answers: ["ငြင်းပယ်သည်", "ပေးကမ်းသည်"],
    },
  },
  {
    id: 176,
    kanji: "上手い",
    hiragana: "うまい",
    type: "Adjective",
    myanmar: "တော်သော / အရသာရှိသော",
    flashcard: {
      question: "上手い means?",
      correct_answer: "တော်သော/အရသာရှိသော",
      false_answers: ["ညံ့သော", "ခါးသော"],
    },
  },
  {
    id: 177,
    kanji: "運転",
    hiragana: "うんてん",
    type: "Noun, Suru verb",
    myanmar: "မောင်းနှင်ခြင်း",
    flashcard: {
      question: "運転 (うんてん) means?",
      correct_answer: "မောင်းနှင်ခြင်း",
      false_answers: ["လမ်းလျှောက်ခြင်း", "ပျံသန်းခြင်း"],
    },
  },
  {
    id: 178,
    kanji: "売れる",
    hiragana: "うれる",
    type: "Verb",
    myanmar: "ရောင်းကောင်းသည် / ပေါက်သည်",
    flashcard: {
      question: "売れる means?",
      correct_answer: "ရောင်းကောင်းသည်",
      false_answers: ["ဝယ်ရခက်သည်", "ဟောင်းသည်"],
    },
  },
  {
    id: 179,
    kanji: "分ける",
    hiragana: "わける",
    type: "Verb",
    myanmar: "ခွဲခြမ်းသည် / ပိုင်းခြားသည်",
    flashcard: {
      question: "分ける means?",
      correct_answer: "ခွဲခြားသည်",
      false_answers: ["ပေါင်းစပ်သည်", "ဖျက်သည်"],
    },
  },
  {
    id: 180,
    kanji: "悪口",
    hiragana: "わるぐち",
    type: "Noun, Suru verb",
    myanmar: "အတင်းပြောခြင်း / ဆဲဆိုခြင်း",
    flashcard: {
      question: "悪口 (わるぐち) means?",
      correct_answer: "အတင်းပြောခြင်း",
      false_answers: ["ချီးမွမ်းခြင်း", "နှုတ်ဆက်ခြင်း"],
    },
  },
  {
    id: 181,
    kanji: "夜明け",
    hiragana: "よあけ",
    type: "Noun",
    myanmar: "မိုးသောက်ချိန် / အရုဏ်တက်ချိန်",
    flashcard: {
      question: "夜明け (よあけ) means?",
      correct_answer: "မိုးသောက်ချိန်",
      false_answers: ["မိုးချုပ်ချိန်", "ညသန်းခေါင်"],
    },
  },
  {
    id: 182,
    kanji: "余分",
    hiragana: "よぶん",
    type: "Noun",
    myanmar: "ပိုလျှံသော / အပို",
    flashcard: {
      question: "余分 (よぶん) means?",
      correct_answer: "ပိုလျှံသော",
      false_answers: ["လိုအပ်သော", "မရှိမဖြစ်"],
    },
  },
  {
    id: 183,
    kanji: "読み",
    hiragana: "よみ",
    type: "Noun",
    myanmar: "အဖတ် (Kanji အဖတ် စသည်)",
    flashcard: {
      question: "読み (よみ) means?",
      correct_answer: "အဖတ်",
      false_answers: ["အရေး", "အပြော"],
    },
  },
  {
    id: 184,
    kanji: "夜中",
    hiragana: "よなか",
    type: "Noun",
    myanmar: "ညသန်းခေါင် / ညဉ့်နက်ချိန်",
    flashcard: {
      question: "夜中 means?",
      correct_answer: "ညဉ့်နက်ချိန်",
      false_answers: ["နေ့လယ်", "မနက်"],
    },
  },
  {
    id: 185,
    kanji: "宜しい",
    hiragana: "よろしい",
    type: "Adjective",
    myanmar: "ကောင်းပါပြီ / ရပါသည် (ယဉ်ကျေးသံ)",
    flashcard: {
      question: "宜しい means?",
      correct_answer: "ရပါသည် (Polite)",
      false_answers: ["မကောင်းပါ", "မရပါ"],
    },
  },
  {
    id: 186,
    kanji: "唯一",
    hiragana: "ゆいいつ",
    type: "Noun, Adverb",
    myanmar: "တစ်ခုတည်းသော / ထူးခြားသော",
    flashcard: {
      question: "唯一 means?",
      correct_answer: "တစ်ခုတည်းသော",
      false_answers: ["အများကြီး", "တူတူပဲ"],
    },
  },
  {
    id: 187,
    kanji: "輸入",
    hiragana: "ゆにゅう",
    type: "Noun, Suru verb",
    myanmar: "သွင်းကုန် / တင်သွင်းခြင်း",
    flashcard: {
      question: "輸入 means?",
      correct_answer: "တင်သွင်းခြင်း",
      false_answers: ["တင်ပို့ခြင်း", "ရောင်းချခြင်း"],
    },
  },
  {
    id: 188,
    kanji: "輸出",
    hiragana: "ゆしゅつ",
    type: "Noun, Suru verb",
    myanmar: "ပို့ကုန် / တင်ပို့ခြင်း",
    flashcard: {
      question: "輸出 means?",
      correct_answer: "တင်ပို့ခြင်း",
      false_answers: ["တင်သွင်းခြင်း", "ဝယ်ယူခြင်း"],
    },
  },
  {
    id: 189,
    kanji: "夕べ",
    hiragana: "ゆうべ",
    type: "Noun",
    myanmar: "မနေ့ညက / ညနေခင်း",
    flashcard: {
      question: "夕べ means?",
      correct_answer: "မနေ့ညက",
      false_answers: ["ဒီနေ့မနက်", "နက်ဖြန်"],
    },
  },
  {
    id: 190,
    kanji: "有利",
    hiragana: "yuuri",
    type: "な-adjective",
    myanmar: "အခွင့်သာသော / အကျိုးရှိသော",
    flashcard: {
      question: "有利 (ゆうり) means?",
      correct_answer: "အခွင့်သာသော",
      false_answers: ["နစ်နာသော", "ရှုံးသော"],
    },
  },
  {
    id: 191,
    kanji: "全国",
    hiragana: "ぜんこく",
    type: "Noun",
    myanmar: "တစ်နိုင်ငံလုံး",
    flashcard: {
      question: "全国 (ぜんこく) means?",
      correct_answer: "တစ်နိုင်ငံလုံး",
      false_answers: ["မြို့တော်", "ကမ္ဘာ"],
    },
  },
  {
    id: 192,
    kanji: "随分",
    hiragana: "ずいぶん",
    type: "Adverb",
    myanmar: "အတော်လေး / အလွန်",
    flashcard: {
      question: "随分 means?",
      correct_answer: "အတော်လေး",
      false_answers: ["နည်းနည်း", "လုံးဝ"],
    },
  },
];