export const data = [
  {
    id: 1,
    kanji: "氏",
    onyomi: "シ",
    kunyomi: "うじ",
    type: "Noun/Suffix",
    myanmar: "မျိုးနွယ်စု / မျိုးရိုးအမည် / (Mr. or Ms. - အဖြစ်လည်းသုံးသည်)",
    flashcard: {
      question: "氏 (し) is often used for?",
      correct_answer: "မျိုးရိုးအမည်",
      false_answers: ["အစားအစာ", "မြို့"],
    },
  },
  {
    id: 2,
    kanji: "統",
    onyomi: "トウ",
    kunyomi: "す(べる)",
    type: "Verb/Noun",
    myanmar: "အုပ်ချုပ်ခြင်း / စုစည်းခြင်း",
    flashcard: {
      question: "統 (とう) is in 伝統 (tradition) or 統合 (integration)?",
      correct_answer: "အထက်ပါနှစ်ခုလုံး",
      false_answers: ["နံရံ", "ဖိနပ်"],
    },
  },
  {
    id: 3,
    kanji: "基",
    onyomi: "キ",
    kunyomi: "もと",
    type: "Noun",
    myanmar: "အခြေခံ / အရင်းအမြစ်",
    flashcard: {
      question: "基 (き) means?",
      correct_answer: "အခြေခံ",
      false_answers: ["အဖျား", "အပေါ်ယံ"],
    },
  },
  {
    id: 4,
    kanji: "価",
    onyomi: "カ",
    kunyomi: "あたい",
    type: "Noun",
    myanmar: "တန်ဖိုး / စျေးနှုန်း",
    flashcard: {
      question: "価 (か) is in 物価 (prices)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "မသေချာပါ"],
    },
  },
  {
    id: 5,
    kanji: "提",
    onyomi: "テイ",
    kunyomi: "さ(げる)",
    type: "Verb/Noun",
    myanmar: "တင်ပြခြင်း / ကမ်းလှမ်းခြင်း / ဆွဲယူခြင်း",
    flashcard: {
      question: "提 (てい) is in 提案 (proposal)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "မသိပါ"],
    },
  },
  {
    id: 6,
    kanji: "挙",
    onyomi: "キョ",
    kunyomi: "あ(げる)",
    type: "Verb/Noun",
    myanmar: "မြှောက်ခြင်း / ပြုလုပ်ခြင်း / ရွေးကောက်ခြင်း",
    flashcard: {
      question: "挙 (きょ) is in 選挙 (election)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ကစားခြင်း"],
    },
  },
  {
    id: 7,
    kanji: "応",
    onyomi: "オウ",
    kunyomi: "こた(える)",
    type: "Verb/Noun",
    myanmar: "တုံ့ပြန်ခြင်း / လိုက်လျောညီထွေဖြစ်ခြင်း",
    flashcard: {
      question: "応 (おう) means?",
      correct_answer: "တုံ့ပြန်ခြင်း",
      false_answers: ["မေ့လျော့ခြင်း", "တားဆီးခြင်း"],
    },
  },
  {
    id: 8,
    kanji: "企",
    onyomi: "キ",
    kunyomi: "くわだ(てる)",
    type: "Verb/Noun",
    myanmar: "စီမံကိန်းချခြင်း / ကြိုးပမ်းခြင်း",
    flashcard: {
      question: "企 (き) is in 企業 (enterprise)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အနားယူခြင်း"],
    },
  },
  {
    id: 9,
    kanji: "検",
    onyomi: "ケン",
    kunyomi: "しら(べる)",
    type: "Noun/Verb",
    myanmar: "စစ်ဆေးခြင်း / စုံစမ်းခြင်း",
    flashcard: {
      question: "検 (けん) is in 検索 (search)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ချက်ပြုတ်ခြင်း"],
    },
  },
  {
    id: 10,
    kanji: "藤",
    onyomi: "トウ",
    kunyomi: "ふじ",
    type: "Noun",
    myanmar:
      "ဝစ္စတေးရီးယားပန်း (Wisteria) / ဂျပန်မျိုးရိုးအမည်များတွင် သုံးသည်",
    flashcard: {
      question: "藤 (ふじ) is often found in?",
      correct_answer: "ဂျပန်နာမည်များ",
      false_answers: ["နိုင်ငံအမည်များ", "တိရစ္ဆာန်အမည်များ"],
    },
  },
  {
    id: 11,
    kanji: "沢",
    onyomi: "タク",
    kunyomi: "さわ",
    type: "Noun",
    myanmar: "စိမ့်စမ်း / ရွှံ့နွံ / ကြွယ်ဝခြင်း",
    flashcard: {
      question: "沢 (さわ) relates to?",
      correct_answer: "ရေ/စိမ့်စမ်း",
      false_answers: ["မီး", "ကျောက်ခဲ"],
    },
  },
  {
    id: 12,
    kanji: "裁",
    onyomi: "サイ",
    kunyomi: "さば(く)",
    type: "Verb/Noun",
    myanmar: "တရားစီရင်ခြင်း / ဖြတ်တောက်ခြင်း (အထည်)",
    flashcard: {
      question: "裁 (さい) means?",
      correct_answer: "တရားစီရင်ခြင်း",
      false_answers: ["ကခုန်ခြင်း", "သီချင်းဆိုခြင်း"],
    },
  },
  {
    id: 13,
    kanji: "証",
    onyomi: "ショウ",
    kunyomi: "あかし",
    type: "Noun",
    myanmar: "သက်သေ / အထောက်အထား / လက်မှတ်",
    flashcard: {
      question: "証 (しょう) is in 証明 (proof)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အိပ်မက်"],
    },
  },
  {
    id: 14,
    kanji: "援",
    onyomi: "エン",
    kunyomi: "-",
    type: "Noun/Verb",
    myanmar: "ကူညီထောက်ပံ့ခြင်း",
    flashcard: {
      question: "援 (えん) is in 応援 (cheer/support)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "တိုက်ခိုက်ခြင်း"],
    },
  },
  {
    id: 15,
    kanji: "可",
    onyomi: "カ",
    kunyomi: "-",
    type: "Prefix/Noun",
    myanmar: "ဖြစ်နိုင်ခြင်း / ခွင့်ပြုခြင်း",
    flashcard: {
      question: "可 (か) is in 可能 (possible)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "မဖြစ်နိုင်"],
    },
  },
  {
    id: 16,
    kanji: "施",
    onyomi: "シ",
    kunyomi: "ほどこ(す)",
    type: "Verb/Noun",
    myanmar: "အကောင်အထည်ဖော်ခြင်း / ပေးကမ်းခြင်း",
    flashcard: {
      question: "施 (し) is in 実施 (implementation)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ရပ်တန့်ခြင်း"],
    },
  },
  {
    id: 17,
    kanji: "井",
    onyomi: "セイ",
    kunyomi: "い",
    type: "Noun",
    myanmar: "ရေတွင်း",
    flashcard: {
      question: "井 (い) means?",
      correct_answer: "ရေတွင်း",
      false_answers: ["တောင်", "သစ်ပင်"],
    },
  },
  {
    id: 18,
    kanji: "護",
    onyomi: "ゴ",
    kunyomi: "まも(る)",
    type: "Verb/Noun",
    myanmar: "စောင့်ရှောက်ခြင်း / ကာကွယ်ခြင်း",
    flashcard: {
      question: "護 (ご) is in 看護師 (nurse)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "စစ်သား"],
    },
  },
  {
    id: 19,
    kanji: "展",
    onyomi: "テン",
    kunyomi: "-",
    type: "Noun",
    myanmar: "ပြသခြင်း / တိုးချဲ့ခြင်း",
    flashcard: {
      question: "展 (てん) is in 展示 (exhibition)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ဖုံးကွယ်ခြင်း"],
    },
  },
  {
    id: 20,
    kanji: "態",
    onyomi: "タイ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "အခြေအနေ / အမူအရာ",
    flashcard: {
      question: "態 (たい) is in 状態 (condition)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အရောင်"],
    },
  },
  {
    id: 21,
    kanji: "鮮",
    onyomi: "セン",
    kunyomi: "あざ(やか)",
    type: "Adjective",
    myanmar: "လတ်ဆတ်သော / တောက်ပပြတ်သားသော",
    flashcard: {
      question: "鮮 (せん) is in 新鮮 (fresh)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ပုပ်သိုး"],
    },
  },
  {
    id: 22,
    kanji: "視",
    onyomi: "シ",
    kunyomi: "み(る)",
    type: "Verb/Noun",
    myanmar: "ကြည့်ရှုခြင်း / အမြင်",
    flashcard: {
      question: "視 (し) is in 視界 (visibility)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အနံ့"],
    },
  },
  {
    id: 23,
    kanji: "条",
    onyomi: "ジョウ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "အပိုဒ် / အချက် / စည်းကမ်းချက်",
    flashcard: {
      question: "条 (じょう) is in 条件 (condition/term)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ကဗျာ"],
    },
  },
  {
    id: 24,
    kanji: "幹",
    onyomi: "カン",
    kunyomi: "みき",
    type: "Noun",
    myanmar: "ပင်စည် / အဓိကအစိတ်အပိုင်း / စွမ်းဆောင်ရည်",
    flashcard: {
      question: "幹 (みき) means?",
      correct_answer: "ပင်စည်",
      false_answers: ["သစ်ရွက်", "အမြစ်"],
    },
  },
  {
    id: 25,
    kanji: "独",
    onyomi: "ドク",
    kunyomi: "ひと(り)",
    type: "Adjective/Noun",
    myanmar: "တစ်ဦးတည်း / တစ်ယောက်တည်း",
    flashcard: {
      question: "独 (どく) is in 独身 (single)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အိမ်ထောင်သည်"],
    },
  },
  {
    id: 26,
    kanji: "宮",
    onyomi: "キュウ",
    kunyomi: "みや",
    type: "Noun",
    myanmar: "နန်းတော် / နတ်ကွန်း",
    flashcard: {
      question: "宮 (みや) means?",
      correct_answer: "နတ်ကွန်း/နန်းတော်",
      false_answers: ["ဈေး", "ကျောင်း"],
    },
  },
  {
    id: 27,
    kanji: "率",
    onyomi: "リツ",
    kunyomi: "ひき(いる)",
    type: "Noun/Verb",
    myanmar: "နှုန်း / အချိုးအစား / ဦးဆောင်ခြင်း",
    flashcard: {
      question: "率 (りつ) means?",
      correct_answer: "နှုန်း",
      false_answers: ["အလေးချိန်", "အကွာအဝေး"],
    },
  },
  {
    id: 28,
    kanji: "衛",
    onyomi: "エイ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "ကာကွယ်စောင့်ရှောက်ခြင်း / ကျန်းမာရေး",
    flashcard: {
      question: "衛 (えい) is in 衛生 (hygiene)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ဖုန်"],
    },
  },
  {
    id: 29,
    kanji: "張",
    onyomi: "チョウ",
    kunyomi: "は(る)",
    type: "Verb/Noun",
    myanmar: "ဆန့်ထုတ်ခြင်း / တင်းခြင်း / ကပ်ခြင်း",
    flashcard: {
      question: "張 (はる) means?",
      correct_answer: "ဆန့်ခြင်း/ကပ်ခြင်း",
      false_answers: ["လျှော့ခြင်း", "ပြုတ်ကျခြင်း"],
    },
  },
  {
    id: 30,
    kanji: "監",
    onyomi: "カン",
    kunyomi: "-",
    type: "Noun/Verb",
    myanmar: "ကြီးကြပ်ခြင်း / စောင့်ကြည့်ခြင်း",
    flashcard: {
      question: "監 (かん) is in 監督 (director)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ကစားသမား"],
    },
  },

  {
    id: 101,
    kanji: "江",
    onyomi: "コウ",
    kunyomi: "え",
    type: "Noun",
    myanmar: "မြစ်လက်တက် / ပင်လယ်အော်ငယ်",
    flashcard: {
      question: "江 (え) means?",
      correct_answer: "မြစ်လက်တက်",
      false_answers: ["တောင်", "သစ်ပင်"],
    },
  },
  {
    id: 102,
    kanji: "僚",
    onyomi: "リョウ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "လုပ်ဖော်ကိုင်ဖက် / အရာရှိ",
    flashcard: {
      question: "僚 (りょう) is in 同僚 (colleague)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ရန်သူ"],
    },
  },
  {
    id: 103,
    kanji: "吉",
    onyomi: "キチ",
    kunyomi: "よし",
    type: "Noun/Adjective",
    myanmar: "ကံကောင်းခြင်း / မင်္ဂလာရှိခြင်း",
    flashcard: {
      question: "吉 (きち) means?",
      correct_answer: "ကံကောင်းခြင်း",
      false_answers: ["ကံဆိုးခြင်း", "နာကျင်ခြင်း"],
    },
  },
  {
    id: 104,
    kanji: "盛",
    onyomi: "セイ",
    kunyomi: "も(る)",
    type: "Verb/Noun",
    myanmar: "ထည့်သွင်းသည် / စည်ကားထွန်းကားသည်",
    flashcard: {
      question: "盛 (もる) means?",
      correct_answer: "ထည့်သွင်းသည်/ပုံသည်",
      false_answers: ["လျှော့သည်", "ဖျက်ဆီးသည်"],
    },
  },
  {
    id: 105,
    kanji: "皇",
    onyomi: "コウ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "ဧကရာဇ် / မင်းတရား",
    flashcard: {
      question: "皇 (こう) is in 天皇 (Emperor)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "စစ်သား"],
    },
  },
  {
    id: 106,
    kanji: "臨",
    onyomi: "リン",
    kunyomi: "のぞ(む)",
    type: "Verb",
    myanmar: "ရင်ဆိုင်သည် / တက်ရောက်သည် / အနားတွင်ရှိသည်",
    flashcard: {
      question: "臨 (のぞむ) means?",
      correct_answer: "ရင်ဆိုင်သည်/တက်ရောက်သည်",
      false_answers: ["ထွက်ပြေးသည်", "အိပ်ပျော်သည်"],
    },
  },
  {
    id: 107,
    kanji: "踏",
    onyomi: "トウ",
    kunyomi: "ふ(む)",
    type: "Verb",
    myanmar: "နင်းသည် / ခြေလှမ်းသည်",
    flashcard: {
      question: "踏 (ふむ) means?",
      correct_answer: "နင်းသည်",
      false_answers: ["ကိုင်သည်", "စားသည်"],
    },
  },
  {
    id: 108,
    kanji: "壊",
    onyomi: "カイ",
    kunyomi: "こわ(す)",
    type: "Verb",
    myanmar: "ဖျက်ဆီးသည် / ပျက်စီးသည်",
    flashcard: {
      question: "壊 (こわす) means?",
      correct_answer: "ဖျက်ဆီးသည်",
      false_answers: ["တည်ဆောက်သည်", "ဆေးသုတ်သည်"],
    },
  },
  {
    id: 109,
    kanji: "債",
    onyomi: "サイ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "အကြွေး / ငွေချေးသက်သေခံလက်မှတ်",
    flashcard: {
      question: "債 (さい) relates to?",
      correct_answer: "အကြွေး",
      false_answers: ["လက်ဆောင်", "လစာ"],
    },
  },
  {
    id: 110,
    kanji: "興",
    onyomi: "コウ",
    kunyomi: "おこ(す)",
    type: "Noun/Verb",
    myanmar: "စိတ်ဝင်စားခြင်း / ပြန်လည်နိုးထစေခြင်း",
    flashcard: {
      question: "興 (きょう) is in 興味 (interest)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ဗဟုသုတ"],
    },
  },
  {
    id: 111,
    kanji: "源",
    onyomi: "ゲン",
    kunyomi: "みなもと",
    type: "Noun",
    myanmar: "မြစ်ဖျားခံရာ / အရင်းအမြစ်",
    flashcard: {
      question: "源 (みなもと) means?",
      correct_answer: "အရင်းအမြစ်",
      false_answers: ["အဆုံးသတ်", "ပင်လယ်ကူးတို့"],
    },
  },
  {
    id: 112,
    kanji: "儀",
    onyomi: "ギ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "အခမ်းအနား / စည်းမျဉ်း",
    flashcard: {
      question: "儀 (ぎ) is in 儀式 (ceremony)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ကစားပွဲ"],
    },
  },
  {
    id: 113,
    kanji: "創",
    onyomi: "ソウ",
    kunyomi: "つく(る)",
    type: "Verb/Noun",
    myanmar: "တီထွင်ဖန်တီးခြင်း / အစပြုခြင်း",
    flashcard: {
      question: "創 (そう) is in 創作 (creation)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ဖျက်ဆီးခြင်း"],
    },
  },
  {
    id: 114,
    kanji: "障",
    onyomi: "ショウ",
    kunyomi: "さわ(る)",
    type: "Noun/Verb",
    myanmar: "အဟန့်အတား / ထိခိုက်မှု / ချို့ယွင်းမှု",
    flashcard: {
      question: "障 (しょう) is in 故障 (breakdown)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အောင်မြင်မှု"],
    },
  },
  {
    id: 115,
    kanji: "継",
    onyomi: "ケイ",
    kunyomi: "つ(ぐ)",
    type: "Verb",
    myanmar: "ဆက်ခံသည် / ဆက်လက်လုပ်ဆောင်သည်",
    flashcard: {
      question: "継 (つぐ) means?",
      correct_answer: "ဆက်ခံသည်",
      false_answers: ["ရပ်တန့်သည်", "မေ့ပစ်သည်"],
    },
  },
  {
    id: 116,
    kanji: "筋",
    onyomi: "キン",
    kunyomi: "すじ",
    type: "Noun",
    myanmar: "ကြွက်သား / အမျှင် / ဇာတ်လမ်းကျောရိုး",
    flashcard: {
      question: "筋 (きん) means?",
      correct_answer: "ကြွက်သား/အမျှင်",
      false_answers: ["အရိုး", "သွေး"],
    },
  },
  {
    id: 117,
    kanji: "狙",
    onyomi: "ソ",
    kunyomi: "ねら(u)",
    type: "Verb",
    myanmar: "ချိန်ရွယ်သည် / ပစ်မှတ်ထားသည်",
    flashcard: {
      question: "狙 (ねらう) means?",
      correct_answer: "ချိန်ရွယ်သည်",
      false_answers: ["လွှတ်ပေးသည်", "ကြည့်သည်"],
    },
  },
  {
    id: 118,
    kanji: "闘",
    onyomi: "トウ",
    kunyomi: "たたか(う)",
    type: "Verb/Noun",
    myanmar: "တိုက်ပွဲဝင်သည် / ယှဉ်ပြိုင်တိုက်ခိုက်သည်",
    flashcard: {
      question: "闘 (とう) is in 闘争 (struggle)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ငြိမ်းချမ်းရေး"],
    },
  },
  {
    id: 119,
    kanji: "葬",
    onyomi: "ソウ",
    kunyomi: "ほうむ(る)",
    type: "Verb/Noun",
    myanmar: "သင်္ဂြိုဟ်ခြင်း / မြှုပ်နှံခြင်း",
    flashcard: {
      question: "葬 (そう) is in 葬式 (funeral)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "မင်္ဂလာဆောင်"],
    },
  },
  {
    id: 120,
    kanji: "避",
    onyomi: "ヒ",
    kunyomi: "さ(ける)",
    type: "Verb",
    myanmar: "ရှောင်ကြဉ်သည် / ဖယ်ရှားသည်",
    flashcard: {
      question: "避 (さける) means?",
      correct_answer: "ရှောင်ကြဉ်သည်",
      false_answers: ["ရင်ဆိုင်သည်", "ကိုင်တွယ်သည်"],
    },
  },
  {
    id: 121,
    kanji: "司",
    onyomi: "shi",
    kunyomi: "つかさど(る)",
    type: "Noun/Verb",
    myanmar: "စီမံအုပ်ချုပ်သူ / တာဝန်ရှိသူ",
    flashcard: {
      question: "司 (し) is in 司会 (MC/Chairperson)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ပရိသတ်"],
    },
  },
  {
    id: 122,
    kanji: "康",
    onyomi: "コウ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "ကျန်းမာခြင်း / အေးချမ်းခြင်း",
    flashcard: {
      question: "康 (こう) is in 健康 (health)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ဖျားနာခြင်း"],
    },
  },
  {
    id: 123,
    kanji: "善",
    onyomi: "ゼン",
    kunyomi: "よ(い)",
    type: "Noun/Adjective",
    myanmar: "ကောင်းမြတ်ခြင်း / ကောင်းသော",
    flashcard: {
      question: "善 (ぜん) means?",
      correct_answer: "ကောင်းမြတ်ခြင်း",
      false_answers: ["ယုတ်မာခြင်း", "အမှား"],
    },
  },
  {
    id: 124,
    kanji: "逮",
    onyomi: "タイ",
    kunyomi: "-",
    type: "Noun/Verb",
    myanmar: "ဖမ်းဆီးခြင်း (ဥပဒေအရ)",
    flashcard: {
      question: "逮 (たい) is in 逮捕 (arrest)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "လွှတ်ပေးခြင်း"],
    },
  },
  {
    id: 125,
    kanji: "迫",
    onyomi: "ハク",
    kunyomi: "せま(る)",
    type: "Verb",
    myanmar: "နီးကပ်လာသည် / ဖိအားပေးသည်",
    flashcard: {
      question: "迫 (せまる) means?",
      correct_answer: "နီးကပ်လာသည်",
      false_answers: ["ဝေးသွားသည်", "ရပ်တန့်သည်"],
    },
  },
  {
    id: 126,
    kanji: "惑",
    onyomi: "ワク",
    kunyomi: "まど(う)",
    type: "Verb/Noun",
    myanmar: "တွေဝေသည် / လမ်းမှားသည် / စိတ်ရှုပ်ထွေးသည်",
    flashcard: {
      question: "惑 (わく) is in 迷惑 (trouble/annoyance)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ပျော်ရွှင်မှု"],
    },
  },
  {
    id: 127,
    kanji: "崩",
    onyomi: "ホウ",
    kunyomi: "くず(れる)",
    type: "Verb",
    myanmar: "ပြိုကျသည် / ပျက်စီးသည်",
    flashcard: {
      question: "崩 (くずれる) means?",
      correct_answer: "ပြိုကျသည်",
      false_answers: ["မြင့်တက်သည်", "ခိုင်မာသည်"],
    },
  },
  {
    id: 128,
    kanji: "紀",
    onyomi: "キ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "ရာစုနှစ် / မှတ်တမ်း / ခေတ်",
    flashcard: {
      question: "紀 (き) is in 世紀 (century)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "နာရီ"],
    },
  },
  {
    id: 129,
    kanji: "聴",
    onyomi: "チョウ",
    kunyomi: "き(く)",
    type: "Verb",
    myanmar: "နားထောင်သည် (အလေးအနက်)",
    flashcard: {
      question: "聴 (きく) means?",
      correct_answer: "နားထောင်သည်",
      false_answers: ["စကားပြောသည်", "လမ်းလျှောက်သည်"],
    },
  },
  {
    id: 130,
    kanji: "脱",
    onyomi: "ダツ",
    kunyomi: "ぬ(ぐ)",
    type: "Verb",
    myanmar: "ချွတ်သည် / လွတ်မြောက်သည်",
    flashcard: {
      question: "脱 (ぬぐ) refers to?",
      correct_answer: "အဝတ်အစားချွတ်ခြင်း",
      false_answers: ["အဝတ်အစားဝတ်ခြင်း", "ရေချိုးခြင်း"],
    },
  },
  {
    id: 131,
    kanji: "級",
    onyomi: "キュウ",
    kunyomi: "-",
    type: "Noun/Counter",
    myanmar: "အဆင့် / အတန်း",
    flashcard: {
      question: "級 (きゅう) is used for?",
      correct_answer: "အဆင့် (ဥပမာ N1, N2)",
      false_answers: ["အချိန်", "စျေးနှုန်း"],
    },
  },
  {
    id: 132,
    kanji: "博",
    onyomi: "ハク",
    kunyomi: "-",
    type: "Noun/Prefix",
    myanmar: "ဒေါက်တာ / ဗဟုသုတကြွယ်ဝခြင်း / ပြပွဲ",
    flashcard: {
      question: "博 (はく) is in 博物館 (museum)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "စားသောက်ဆိုင်"],
    },
  },
  {
    id: 133,
    kanji: "締",
    onyomi: "テイ",
    kunyomi: "し(まる)",
    type: "Verb",
    myanmar: "တင်းကျပ်သည် / ပိတ်သည် / ချုပ်ဆိုသည်",
    flashcard: {
      question: "締 (しめる) means?",
      correct_answer: "တင်းကျပ်သည်/ပိတ်သည်",
      false_answers: ["ဖွင့်သည်", "ချောင်သည်"],
    },
  },
  {
    id: 134,
    kanji: "救",
    onyomi: "キュウ",
    kunyomi: "すく(う)",
    type: "Verb/Noun",
    myanmar: "ကယ်ဆယ်သည် / ကူညီသည်",
    flashcard: {
      question: "救 (すကုu) means?",
      correct_answer: "ကယ်ဆယ်သည်",
      false_answers: ["တိုက်ခိုက်သည်", "ခိုးယူသည်"],
    },
  },
  {
    id: 135,
    kanji: "執",
    onyomi: "シツ",
    kunyomi: "と(る)",
    type: "Verb/Noun",
    myanmar: "ကိုင်တွယ်ဆောင်ရွက်သည် / အကောင်အထည်ဖော်သည်",
    flashcard: {
      question: "執 (しつ) is in 執行 (execution/carrying out)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အိပ်စက်ခြင်း"],
    },
  },
  {
    id: 136,
    kanji: "房",
    onyomi: "ボウ",
    kunyomi: "ふさ",
    type: "Noun",
    myanmar: "အဆုပ် (ဥပမာ စပျစ်သီး) / အခန်း / အဆွဲအပြွတ်",
    flashcard: {
      question: "房 (ふさ) means?",
      correct_answer: "အဆုပ်/အခန်း",
      false_answers: ["မြစ်", "လမ်း"],
    },
  },
  {
    id: 137,
    kanji: "撤",
    onyomi: "テツ",
    kunyomi: "-",
    type: "Noun/Verb",
    myanmar: "ရုပ်သိမ်းခြင်း / ဖယ်ရှားခြင်း",
    flashcard: {
      question: "撤 (てつ) is in 撤退 (withdrawal)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "တိုးတက်မှု"],
    },
  },
  {
    id: 138,
    kanji: "削",
    onyomi: "サク",
    kunyomi: "けず(る)",
    type: "Verb",
    myanmar: "လျှော့ချသည် / ခြစ်ထုတ်သည် / ရွှေသည်",
    flashcard: {
      question: "削 (けずる) means?",
      correct_answer: "လျှော့ချသည်/ရွှေသည်",
      false_answers: ["ပေါင်းထည့်သည်", "ဆေးသုတ်သည်"],
    },
  },
  {
    id: 139,
    kanji: "密",
    onyomi: "ミツ",
    kunyomi: "ひそ(か)",
    type: "Adjective/Noun",
    myanmar: "သိပ်သည်းသော / လျှို့ဝှက်သော / စေ့စပ်သော",
    flashcard: {
      question: "密 (みつ) means?",
      correct_answer: "သိပ်သည်းခြင်း/လျှို့ဝှက်ခြင်း",
      false_answers: ["ကျဲပါးခြင်း", "ပွင့်လင်းခြင်း"],
    },
  },
  {
    id: 140,
    kanji: "措",
    onyomi: "ソ",
    kunyomi: "お(く)",
    type: "Noun/Verb",
    myanmar: "စီမံဆောင်ရွက်မှု / ဖယ်ထားခြင်း",
    flashcard: {
      question: "措 (そ) is in 措置 (measures)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "သီချင်း"],
    },
  },
  {
    id: 141,
    kanji: "志",
    onyomi: "シ",
    kunyomi: "こころざし",
    type: "Noun",
    myanmar: "ရည်မှန်းချက် / စိတ်ဆန္ဒ",
    flashcard: {
      question: "志 (こころざし) means?",
      correct_answer: "ရည်မှန်းချက်",
      false_answers: ["အမှတ်တရ", "အမှား"],
    },
  },
  {
    id: 142,
    kanji: "載",
    onyomi: "サイ",
    kunyomi: "の(せる)",
    type: "Verb",
    myanmar: "တင်ဆောင်သည် / ဖော်ပြသည် (သတင်းစာ၊ စာအုပ်)",
    flashcard: {
      question: "載 (のせる) is in 掲載 (publication)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ဖျက်ပစ်ခြင်း"],
    },
  },
  {
    id: 143,
    kanji: "陣",
    onyomi: "ジン",
    kunyomi: "-",
    type: "Noun",
    myanmar: "တပ်စွဲရာနေရာ / အုပ်စု / အခိုက်အတန့်",
    flashcard: {
      question: "陣 (じん) relates to?",
      correct_answer: "စစ်တပ်/နေရာ",
      false_answers: ["အစားအစာ", "အဝတ်အစား"],
    },
  },
  {
    id: 144,
    kanji: "我",
    onyomi: "ガ",
    kunyomi: "われ",
    type: "Noun/Pronoun",
    myanmar: "ငါ / မိမိကိုယ်ကို",
    flashcard: {
      question: "我 (われ) means?",
      correct_answer: "ငါ (I)",
      false_answers: ["သူ (He)", "မင်း (You)"],
    },
  },
  {
    id: 145,
    kanji: "為",
    onyomi: "イ",
    kunyomi: "ため",
    type: "Noun/Verb",
    myanmar: "အတွက် / ပြုလုပ်ခြင်း / အကျိုးရှိခြင်း",
    flashcard: {
      question: "為 (ため) means?",
      correct_answer: "အတွက်/အကျိုး",
      false_answers: ["နောက်ကွယ်", "အရင်"],
    },
  },
  {
    id: 146,
    kanji: "抑",
    onyomi: "ヨク",
    kunyomi: "おさ(える)",
    type: "Verb",
    myanmar: "ထိန်းချုပ်သည် / ဖိနှိပ်သည်",
    flashcard: {
      question: "抑 (おさえる) means?",
      correct_answer: "ထိန်းချုပ်သည်",
      false_answers: ["လွှတ်ပေးသည်", "အားပေးသည်"],
    },
  },
  {
    id: 147,
    kanji: "幕",
    onyomi: "マク",
    kunyomi: "-",
    type: "Noun",
    myanmar: "လိုက်ကာ / ပြဇာတ်အခန်း / ခေတ်",
    flashcard: {
      question: "幕 (まく) means?",
      correct_answer: "လိုက်ကာ/အခန်း",
      false_answers: ["စာအုပ်", "ရေခဲသေတ္တာ"],
    },
  },
  {
    id: 148,
    kanji: "染",
    onyomi: "セン",
    kunyomi: "そ(める)",
    type: "Verb",
    myanmar: "ဆိုးဆေးဆိုးသည် / ကူးစက်သည်",
    flashcard: {
      question: "染 (そめる) means?",
      correct_answer: "ဆေးဆိုးသည်",
      false_answers: ["ဆေးကြောသည်", "ဖြူစင်သည်"],
    },
  },
  {
    id: 149,
    kanji: "奈",
    onyomi: "ナ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "နာရာစီရင်စု (Nara) / ဘာလဲ",
    flashcard: {
      question: "奈 (な) is often in?",
      correct_answer: "နာမည်များ (ဥပမာ 奈良)",
      false_answers: ["အစားအစာ", "အလုပ်အကိုင်"],
    },
  },
  {
    id: 150,
    kanji: "傷",
    onyomi: "ショウ",
    kunyomi: "きず",
    type: "Noun/Verb",
    myanmar: "ဒဏ်ရာ / အနာတရဖြစ်ခြင်း",
    flashcard: {
      question: "傷 (きず) means?",
      correct_answer: "ဒဏ်ရာ",
      false_answers: ["ပျော်ရွှင်မှု", "ကျန်းမာရေး"],
    },
  },
  {
    id: 151,
    kanji: "択",
    onyomi: "タク",
    kunyomi: "えら(ぶ)",
    type: "Verb/Noun",
    myanmar: "ရွေးချယ်ခြင်း",
    flashcard: {
      question: "択 (たく) is in 選択 (choice/selection)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ငြင်းပယ်ခြင်း"],
    },
  },
  {
    id: 152,
    kanji: "秀",
    onyomi: "シュウ",
    kunyomi: "ひい(でる)",
    type: "Verb/Adjective",
    myanmar: "ထူးချွန်သော / လှပသော",
    flashcard: {
      question: "秀 (しゅう) is in 優秀 (excellent)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ညံ့ဖျင်းသည်"],
    },
  },
  {
    id: 153,
    kanji: "徴",
    onyomi: "チョウ",
    kunyomi: "しるし",
    type: "Noun/Suffix",
    myanmar: "လက္ခဏာ / အချက်ပြ / စုဆောင်းခြင်း",
    flashcard: {
      question: "徴 (ちょう) is in 特徴 (characteristic)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အဝတ်အစား"],
    },
  },
  {
    id: 154,
    kanji: "弾",
    onyomi: "ダン",
    kunyomi: "たま",
    type: "Noun/Verb",
    myanmar: "ကျည်ဆန် / တီးခတ်သည် (ဂစ်တာ၊ စန္ဒယား)",
    flashcard: {
      question: "弾 (ひく) is used for?",
      correct_answer: "တူရိယာတီးခြင်း",
      false_answers: ["ထမင်းစားခြင်း", "အိပ်ခြင်း"],
    },
  },
  {
    id: 155,
    kanji: "償",
    onyomi: "ショウ",
    kunyomi: "つぐな(う)",
    type: "Verb/Noun",
    myanmar: "လျော်ကြေးပေးသည် / အစားထိုးကုသသည်",
    flashcard: {
      question: "償 (つぐなう) means?",
      correct_answer: "လျော်ကြေးပေးသည်",
      false_answers: ["ခိုးယူသည်", "ပေးကမ်းသည်"],
    },
  },
  {
    id: 156,
    kanji: "功",
    onyomi: "コウ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "အောင်မြင်မှု / ကုသိုလ် / ဂုဏ်ပြုချက်",
    flashcard: {
      question: "功 (こう) is in 成功 (success)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ရှုံးနိမ့်ခြင်း"],
    },
  },
  {
    id: 157,
    kanji: "拠",
    onyomi: "キョ",
    kunyomi: "よ(る)",
    type: "Noun/Suffix",
    myanmar: "အခြေခံစခန်း / အခြေပြုရာ",
    flashcard: {
      question: "拠 (きょ) is in 根拠 (grounds/evidence)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "လေလှိုင်း"],
    },
  },
  {
    id: 158,
    kanji: "秘",
    onyomi: "ヒ",
    kunyomi: "ひ(める)",
    type: "Noun/Verb",
    myanmar: "လျှို့ဝှက်ချက် / ဖုံးကွယ်ထားသည်",
    flashcard: {
      question: "秘 (ひ) is in 秘密 (secret)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "သတင်းအချက်အလက်"],
    },
  },
  {
    id: 159,
    kanji: "拒",
    onyomi: "キョ",
    kunyomi: "こば(む)",
    type: "Verb",
    myanmar: "ငြင်းပယ်သည် / လက်မခံပါ",
    flashcard: {
      question: "拒 (こばむ) means?",
      correct_answer: "ငြင်းပယ်သည်",
      false_answers: ["လက်ခံသည်", "ကမ်းလှမ်းသည်"],
    },
  },
  {
    id: 160,
    kanji: "刑",
    onyomi: "ケイ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "ပြစ်ဒဏ် / စီရင်ချက်",
    flashcard: {
      question: "刑 (けい) is in 刑事 (detective/criminal case)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အရောင်းစာရေး"],
    },
  },
  {
    id: 161,
    kanji: "塚",
    onyomi: "チョウ",
    kunyomi: "つက",
    type: "Noun",
    myanmar: "ကုန်းလျော / မြေပုံ",
    flashcard: {
      question: "塚 (つか) refers to?",
      correct_answer: "မြေပုံ/ကုန်း",
      false_answers: ["မြစ်", "ပင်လယ်"],
    },
  },
  {
    id: 162,
    kanji: "致",
    onyomi: "チ",
    kunyomi: "いた(す)",
    type: "Verb",
    myanmar: "ပြုလုပ်သည် (ယဉ်ကျေးသောစကား) / ပို့ဆောင်သည်",
    flashcard: {
      question: "致 (いたす) is the humble form of?",
      correct_answer: "する (do)",
      false_answers: ["食べる (eat)", "行く (go)"],
    },
  },
  {
    id: 163,
    kanji: "繰",
    onyomi: "ソウ",
    kunyomi: "く(る)",
    type: "Verb",
    myanmar: "လှည့်ပတ်သည် / တစ်ခုပြီးတစ်ခုလုပ်သည် / ကျော်ကြည့်သည်",
    flashcard: {
      question: "繰 (くる) is in 繰り返す (repeat)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "မေ့သည်"],
    },
  },
  {
    id: 164,
    kanji: "尾",
    onyomi: "ビ",
    kunyomi: "お",
    type: "Noun",
    myanmar: "အမြီး / အဆုံးသတ်",
    flashcard: {
      question: "尾 (お) means?",
      correct_answer: "အမြီး",
      false_answers: ["ခေါင်း", "လက်"],
    },
  },
  {
    id: 165,
    kanji: "描",
    onyomi: "ビョウ",
    kunyomi: "えが(く)",
    type: "Verb",
    myanmar: "ပုံဖော်သည် / ရေးဆွဲသည်",
    flashcard: {
      question: "描 (えがく) means?",
      correct_answer: "ပုံဖော်/ရေးဆွဲသည်",
      false_answers: ["ဖျက်ပစ်သည်", "စားသည်"],
    },
  },
  {
    id: 166,
    kanji: "鈴",
    onyomi: "リン",
    kunyomi: "すず",
    type: "Noun",
    myanmar: "ခေါင်းလောင်း / ဆည်းလည်း",
    flashcard: {
      question: "鈴 (すず) means?",
      correct_answer: "ဆည်းလည်း",
      false_answers: ["တူ", "ရွှေ"],
    },
  },
  {
    id: 167,
    kanji: "盤",
    onyomi: "バン",
    kunyomi: "-",
    type: "Noun",
    myanmar: "ဗန်း / အဝိုင်းပြား / ဘုတ်ပြား",
    flashcard: {
      question: "盤 (ばん) is in 地盤 (ground/foundation)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ကောင်းကင်"],
    },
  },
  {
    id: 168,
    kanji: "項",
    onyomi: "コウ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "အချက် / အပိုဒ်",
    flashcard: {
      question: "項 (こう) is in 項目 (item)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ရုပ်ရှင်"],
    },
  },
  {
    id: 169,
    kanji: "喪",
    onyomi: "ソウ",
    kunyomi: "も",
    type: "Noun/Verb",
    myanmar: "ဝမ်းနည်းခြင်း / ဆုံးရှုံးခြင်း",
    flashcard: {
      question: "喪 (そう) is in 喪失 (loss)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အောင်မြင်မှု"],
    },
  },
  {
    id: 170,
    kanji: "伴",
    onyomi: "ハン",
    kunyomi: "ともな(う)",
    type: "Verb",
    myanmar: "တွဲဖက်သည် / အတူလိုက်ပါသည်",
    flashcard: {
      question: "伴 (ともなう) means?",
      correct_answer: "အတူလိုက်ပါသည်",
      false_answers: ["ခွဲခွာသည်", "ထိုင်သည်"],
    },
  },
  {
    id: 171,
    kanji: "養",
    onyomi: "ヨウ",
    kunyomi: "やしな(う)",
    type: "Verb/Noun",
    myanmar: "မွေးမြူသည် / ကျွေးမွေးပြုစုသည်",
    flashcard: {
      question: "養 (やしなう) means?",
      correct_answer: "မွေးမြူပြုစုသည်",
      false_answers: ["စွန့်ပစ်သည်", "သတ်ဖြတ်သည်"],
    },
  },
  {
    id: 172,
    kanji: "懸",
    onyomi: "ケン",
    kunyomi: "か(ける)",
    type: "Verb/Noun",
    myanmar: "ချိတ်ဆွဲသည် / ဆိုင်းငံ့သည် / စိုးရိမ်သည်",
    flashcard: {
      question: "懸 (けん) is in 一生懸命 (with all one's might)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ပျင်းရိခြင်း"],
    },
  },
  {
    id: 173,
    kanji: "街",
    onyomi: "ガイ",
    kunyomi: "まち",
    type: "Noun",
    myanmar: "လမ်းမကြီး / မြို့",
    flashcard: {
      question: "街 (まち) means?",
      correct_answer: "လမ်းမ/မြို့",
      false_answers: ["ရွာ", "တော"],
    },
  },
  {
    id: 174,
    kanji: "契",
    onyomi: "ケイ",
    kunyomi: "ちぎ(る)",
    type: "Verb/Noun",
    myanmar: "ကတိပြုခြင်း / စာချုပ်ချုပ်ခြင်း",
    flashcard: {
      question: "契 (けい) is in 契約 (contract)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "လွတ်လပ်ခွင့်"],
    },
  },
  {
    id: 175,
    kanji: "掲",
    onyomi: "ケイ",
    kunyomi: "かか(げる)",
    type: "Verb",
    myanmar: "ကြေညာသည် / ကပ်ထားသည် (သတင်း)",
    flashcard: {
      question: "掲 (かかげる) is in 掲示板 (bulletin board)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "စားပွဲ"],
    },
  },
  {
    id: 176,
    kanji: "躍",
    onyomi: "ヤク",
    kunyomi: "odo(ru)",
    type: "Verb",
    myanmar: "ခုန်ပျံသည် / ထူးထူးခြားခြားဖြစ်ထွန်းသည်",
    flashcard: {
      question: "躍 (やく) is in 活躍 (activity/playing an active part)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အနားယူခြင်း"],
    },
  },
  {
    id: 177,
    kanji: "棄",
    onyomi: "キ",
    kunyomi: "す(てる)",
    type: "Verb",
    myanmar: "စွန့်ပစ်သည် / ပယ်ဖျက်သည်",
    flashcard: {
      question: "棄 (すてる) is in 破棄 (annulment/discard)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "သိမ်းဆည်းခြင်း"],
    },
  },
  {
    id: 178,
    kanji: "邸",
    onyomi: "テイ",
    kunyomi: "yashiki",
    type: "Noun",
    myanmar: "အိမ်ကြီးရခိုင် / နန်းတော်",
    flashcard: {
      question: "邸 (てい) means?",
      correct_answer: "အိမ်ကြီးရခိုင်",
      false_answers: ["ရဲစခန်း", "ဈေးဆိုင်"],
    },
  },
  {
    id: 179,
    kanji: "縮",
    onyomi: "シュク",
    kunyomi: "ちぢ(む)",
    type: "Verb",
    myanmar: "ကျုံ့သည် / လျှော့ချသည်",
    flashcard: {
      question: "縮 (ちぢむ) means?",
      correct_answer: "ကျုံ့သည်",
      false_answers: ["ကျယ်လာသည်", "ရှည်လာသည်"],
    },
  },
  {
    id: 180,
    kanji: "還",
    onyomi: "カン",
    kunyomi: "かえ(る)",
    type: "Verb/Noun",
    myanmar: "ပြန်ပို့သည် / ပြန်လည်ရောက်ရှိသည်",
    flashcard: {
      question: "還 (かん) is in 帰還 (return)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ထွက်ခွာခြင်း"],
    },
  },
  {
    id: 181,
    kanji: "属",
    onyomi: "ゾク",
    kunyomi: "tsuku",
    type: "Verb/Suffix",
    myanmar: "ပါဝင်သည် / လက်အောက်ခံဖြစ်သည်",
    flashcard: {
      question: "属 (ぞく) is in 所属 (belonging to)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "လွတ်လပ်သည်"],
    },
  },
  {
    id: 182,
    kanji: "慮",
    onyomi: "リョ",
    kunyomi: "omonpaku(ru)",
    type: "Noun/Verb",
    myanmar: "စဉ်းစားချင့်ချိန်ခြင်း / စိုးရိမ်ပူပန်ခြင်း",
    flashcard: {
      question: "慮 (りょ) is in 考慮 (consideration)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ပေါ့ဆမှု"],
    },
  },
  {
    id: 183,
    kanji: "枠",
    onyomi: "-",
    kunyomi: "わく",
    type: "Noun",
    myanmar: "ဘောင် / ကန့်သတ်ချက်",
    flashcard: {
      question: "枠 (わく) means?",
      correct_answer: "ဘောင်",
      false_answers: ["တံခါး", "အမိုး"],
    },
  },
  {
    id: 184,
    kanji: "恵",
    onyomi: "ケイ",
    kunyomi: "めぐ(む)",
    type: "Verb/Noun",
    myanmar: "ကျေးဇူးတော် / ကောင်းချီး / ကူညီသည်",
    flashcard: {
      question: "恵 (めぐむ) means?",
      correct_answer: "ကောင်းချီး/ကူညီသည်",
      false_answers: ["ဒုက္ခပေးသည်", "လုယူသည်"],
    },
  },
  {
    id: 185,
    kanji: "露",
    onyomi: "ロ",
    kunyomi: "tsuyu",
    type: "Noun",
    myanmar: "နှင်းရည် / ထုတ်ဖော်ပြသသည်",
    flashcard: {
      question: "露 (ろ) is in 露出 (exposure)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ဖုံးကွယ်ခြင်း"],
    },
  },
  {
    id: 186,
    kanji: "沖",
    onyomi: "チュウ",
    kunyomi: "おき",
    type: "Noun",
    myanmar: "ပင်လယ်ပြင် / ကမ်းဝေး",
    flashcard: {
      question: "沖 (おき) means?",
      correct_answer: "ပင်လယ်ပြင်",
      false_answers: ["ကုန်းတွင်း", "တောင်တန်း"],
    },
  },
  {
    id: 187,
    kanji: "緩",
    onyomi: "カン",
    kunyomi: "ゆる(い)",
    type: "Adjective/Verb",
    myanmar: "ချောင်သော / လျှော့ချသည် / နှေးကွေးသော",
    flashcard: {
      question: "緩 (ゆるい) means?",
      correct_answer: "ချောင်သော",
      false_answers: ["တင်းကျပ်သော", "မြန်သော"],
    },
  },
  {
    id: 188,
    kanji: "節",
    onyomi: "セツ",
    kunyomi: "ふし",
    type: "Noun",
    myanmar: "ရာသီ / အဆစ် / အပိုဒ် / စည်းချက်",
    flashcard: {
      question: "節 (せつ) is in 季節 (season)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အရောင်"],
    },
  },
  {
    id: 189,
    kanji: "需",
    onyomi: "ジュ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "လိုအပ်ချက် / ဝယ်လိုအား",
    flashcard: {
      question: "需 (じゅ) is in 需要 (demand)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ရောင်းလိုအား"],
    },
  },
  {
    id: 190,
    kanji: "射",
    onyomi: "シャ",
    kunyomi: "い(る)",
    type: "Verb",
    myanmar: "ပစ်ခတ်သည် / ထိုးဖောက်သည်",
    flashcard: {
      question: "射 (いる/うつ) means?",
      correct_answer: "ပစ်ခတ်သည်",
      false_answers: ["ဖမ်းဆီးသည်", "ကြည့်သည်"],
    },
  },
  {
    id: 191,
    kanji: "購",
    onyomi: "コウ",
    kunyomi: "-",
    type: "Noun/Verb",
    myanmar: "ဝယ်ယူခြင်း",
    flashcard: {
      question: "購 (こう) is in 購入 (purchase)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ရောင်းချခြင်း"],
    },
  },
  {
    id: 192,
    kanji: "揮",
    onyomi: "キ",
    kunyomi: "-",
    type: "Verb",
    myanmar: "ဝှေ့ယမ်းသည် / စွမ်းဆောင်ရည်ပြသည်",
    flashcard: {
      question: "揮 (き) is in 発揮 (demonstration of power)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အိပ်စက်ခြင်း"],
    },
  },
  {
    id: 193,
    kanji: "充",
    onyomi: "ジュウ",
    kunyomi: "あ(てる)",
    type: "Verb/Noun",
    myanmar: "ဖြည့်သွင်းသည် / ပြည့်စုံစေသည်",
    flashcard: {
      question: "充 (じゅう) is in 充電 (charging battery)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အားကုန်ခြင်း"],
    },
  },
  {
    id: 194,
    kanji: "貢",
    onyomi: "コウ",
    kunyomi: "みつ(ぐ)",
    type: "Verb/Noun",
    myanmar: "အခွန်ဆက်သည် / ထောက်ပံ့သည်",
    flashcard: {
      question: "貢 (みつぐ) means?",
      correct_answer: "ထောက်ပံ့သည်",
      false_answers: ["နှိပ်စက်သည်", "ယူသည်"],
    },
  },
  {
    id: 195,
    kanji: "鹿",
    onyomi: "ロク",
    kunyomi: "しか",
    type: "Noun",
    myanmar: "သမင်",
    flashcard: {
      question: "鹿 (しか) means?",
      correct_answer: "သမင်",
      false_answers: ["ကျား", "ဝက်"],
    },
  },
  {
    id: 196,
    kanji: "却",
    onyomi: "キャク",
    kunyomi: "-",
    type: "Noun/Verb",
    myanmar: "ငြင်းပယ်သည် / ပြန်လည်ရုပ်သိမ်းသည်",
    flashcard: {
      question: "却 (きゃく) is in 返却 (return item)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "လက်ခံသည်"],
    },
  },
  {
    id: 197,
    kanji: "端",
    onyomi: "タン",
    kunyomi: "はし",
    type: "Noun",
    myanmar: "အစွန်း / အစဖျား",
    flashcard: {
      question: "端 (はし) means?",
      correct_answer: "အစွန်း",
      false_answers: ["အလယ်", "အတွင်း"],
    },
  },
  {
    id: 198,
    kanji: "賃",
    onyomi: "チン",
    kunyomi: "-",
    type: "Noun",
    myanmar: "ငှားရမ်းခ / အခကြေးငွေ",
    flashcard: {
      question: "賃 (ちん) is in 家賃 (house rent)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "စျေးဝယ်ခြင်း"],
    },
  },
  {
    id: 199,
    kanji: "獲",
    onyomi: "カク",
    kunyomi: "え(る)",
    type: "Verb/Noun",
    myanmar: "ရရှိသည် / ဖမ်းဆီးရမိသည်",
    flashcard: {
      question: "獲 (かく) is in 獲得 (acquisition)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ဆုံးရှုံးခြင်း"],
    },
  },
  {
    id: 200,
    kanji: "郡",
    onyomi: "グン",
    kunyomi: "こおり",
    type: "Noun",
    myanmar: "ခရိုင် / နယ်မြေစု",
    flashcard: {
      question: "郡 (ぐん) refers to?",
      correct_answer: "ခရိုင်",
      false_answers: ["နိုင်ငံ", "လမ်း"],
    },
  },

  {
    id: 201,
    kanji: "併",
    onyomi: "ヘイ",
    kunyomi: "あわ(せる)",
    type: "Verb/Noun",
    myanmar: "ပူးတွဲခြင်း / စုစည်းခြင်း / တစ်ပြိုင်တည်းလုပ်ဆောင်ခြင်း",
    flashcard: {
      question: "併 (へい) is in 併用 (using together)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ခွဲခြားခြင်း"],
    },
  },
  {
    id: 202,
    kanji: "徹",
    onyomi: "テツ",
    kunyomi: "-",
    type: "Verb/Noun",
    myanmar: "ထိုးဖောက်ခြင်း / အဆုံးထိလုပ်ဆောင်ခြင်း / တစ်ညလုံးမအိပ်ဘဲနေခြင်း",
    flashcard: {
      question: "徹 (てつ) is in 徹底 (thorough)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "တစ်ဝက်တစ်ပျက်"],
    },
  },
  {
    id: 203,
    kanji: "貴",
    onyomi: "キ",
    kunyomi: "たっと(い)",
    type: "Adjective/Noun",
    myanmar: "အဖိုးတန်သော / မြင့်မြတ်သော / ဂုဏ်သရေရှိသော",
    flashcard: {
      question: "貴 (き) means?",
      correct_answer: "အဖိုးတန်သော",
      false_answers: ["စျေးပေါသော", "ညစ်ပတ်သော"],
    },
  },
  {
    id: 204,
    kanji: "埼",
    onyomi: "キ",
    kunyomi: "さき",
    type: "Noun",
    myanmar: "ကျွန်းဆွယ် / ကုန်းစွန်း (Saitama စီရင်စုအမည်တွင်သုံးသည်)",
    flashcard: {
      question: "埼 (き) is often found in which Prefecture?",
      correct_answer: "Saitama (埼玉県)",
      false_answers: ["Tokyo", "Osaka"],
    },
  },
  {
    id: 205,
    kanji: "衝",
    onyomi: "ショウ",
    kunyomi: "つ(く)",
    type: "Noun/Verb",
    myanmar: "တိုက်မိခြင်း / ထိုးနှက်ချက် / လမ်းမကြီး",
    flashcard: {
      question: "衝 (しょう) is in 衝突 (collision)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "နူးညံ့မှု"],
    },
  },
  {
    id: 206,
    kanji: "焦",
    onyomi: "ショウ",
    kunyomi: "あせ(る)",
    type: "Verb",
    myanmar: "လောခြင်း / စိတ်ပူပန်ခြင်း / တူးခြင်း (ထမင်းတူးခြင်း)",
    flashcard: {
      question: "焦る (あせる) means?",
      correct_answer: "လောသည်/စိတ်လှုပ်ရှားသည်",
      false_answers: ["အေးဆေးနေသည်", "ပျော်သည်"],
    },
  },
  {
    id: 207,
    kanji: "奪",
    onyomi: "ダツ",
    kunyomi: "うば(う)",
    type: "Verb",
    myanmar: "လုယူသည် / သိမ်းပိုက်သည် / အဓမ္မယူသည်",
    flashcard: {
      question: "奪う (うばう) means?",
      correct_answer: "လုယူသည်",
      false_answers: ["ပေးကမ်းသည်", "ချေးငှားသည်"],
    },
  },
  {
    id: 208,
    kanji: "災",
    onyomi: "サイ",
    kunyomi: "わざわ(い)",
    type: "Noun",
    myanmar: "ဘေးအန္တရာယ် / ကပ်ဆိုး",
    flashcard: {
      question: "災 (さい) is in 災害 (disaster)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ကံကောင်းခြင်း"],
    },
  },
  {
    id: 209,
    kanji: "浦",
    onyomi: "ホ",
    kunyomi: "うら",
    type: "Noun",
    myanmar: "ပင်လယ်အော် / ကမ်းခြေ",
    flashcard: {
      question: "浦 (うら) relates to?",
      correct_answer: "ပင်လယ်/ကမ်းခြေ",
      false_answers: ["တောင်ပေါ်", "သဲကန္တာရ"],
    },
  },
  {
    id: 210,
    kanji: "析",
    onyomi: "セキ",
    kunyomi: "-",
    type: "Noun/Verb",
    myanmar: "ခွဲခြမ်းစိတ်ဖြာခြင်း",
    flashcard: {
      question: "析 (せき) is in 分析 (analysis)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ပေါင်းစပ်ခြင်း"],
    },
  },
  {
    id: 211,
    kanji: "譲",
    onyomi: "ジョウ",
    kunyomi: "ゆず(る)",
    type: "Verb",
    myanmar: "လွှဲပြောင်းပေးသည် / လမ်းဖယ်ပေးသည် / လျှော့ပေးသည်",
    flashcard: {
      question: "譲る (ゆずる) means?",
      correct_answer: "လွှဲပြောင်းပေးသည်",
      false_answers: ["လက်ကိုင်ထားသည်", "ခိုးယူသည်"],
    },
  },
  {
    id: 212,
    kanji: "称",
    onyomi: "ショウ",
    kunyomi: "-",
    type: "Noun/Suffix",
    myanmar: "အမည်နာမ / ချီးမွမ်းခြင်း / ခေါ်ဝေါ်ခြင်း",
    flashcard: {
      question: "称 (しょう) is in 名称 (name/title)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အစားအစာ"],
    },
  },
  {
    id: 213,
    kanji: "納",
    onyomi: "ノウ",
    kunyomi: "おさ(める)",
    type: "Verb/Noun",
    myanmar: "ပေးသွင်းခြင်း / ပေးချေခြင်း / သိမ်းဆည်းခြင်း",
    flashcard: {
      question: "納 (のう) is in 納得 (understanding/consent)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ငြင်းပယ်ခြင်း"],
    },
  },
  {
    id: 214,
    kanji: "樹",
    onyomi: "ジュ",
    kunyomi: "き",
    type: "Noun",
    myanmar: "သစ်ပင် / တည်ထောင်ခြင်း",
    flashcard: {
      question: "樹 (じゅ) is in 樹木 (trees)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "မြက်"],
    },
  },
  {
    id: 215,
    kanji: "挑",
    onyomi: "chou",
    kunyomi: "いど(む)",
    type: "Verb/Noun",
    myanmar: "စိန်ခေါ်သည် / ကြိုးပမ်းသည်",
    flashcard: {
      question: "挑 (ちょう) is in 挑戦 (challenge)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "လက်လျှော့ခြင်း"],
    },
  },
  {
    id: 216,
    kanji: "誘",
    onyomi: "ユウ",
    kunyomi: "さそ(う)",
    type: "Verb",
    myanmar: "ဖိတ်ခေါ်သည် / သွေးဆောင်သည်",
    flashcard: {
      question: "誘う (さသောu) means?",
      correct_answer: "ဖိတ်ခေါ်သည်",
      false_answers: ["နှင်ထုတ်သည်", "အော်ဟစ်သည်"],
    },
  },
  {
    id: 217,
    kanji: "紛",
    onyomi: "フン",
    kunyomi: "まぎ(れる)",
    type: "Verb/Noun",
    myanmar: "ရှုပ်ထွေးခြင်း / ပျောက်ဆုံးခြင်း / အာရုံပြောင်းခြင်း",
    flashcard: {
      question: "紛 (ふん) is in 紛争 (dispute)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ငြိမ်းချမ်းရေး"],
    },
  },
  {
    id: 218,
    kanji: "至",
    onyomi: "シ",
    kunyomi: "いた(る)",
    type: "Verb/Noun",
    myanmar: "ရောက်ရှိသည် / အဆုံးစွန်ထိဖြစ်သည်",
    flashcard: {
      question: "至 (し) is in 至急 (urgent)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အနှေး"],
    },
  },
  {
    id: 219,
    kanji: "宗",
    onyomi: "シュウ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "ဘာသာရေး / ဂိုဏ်း / အဓိကအချက်",
    flashcard: {
      question: "宗 (しゅう) is in 宗教 (religion)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "သိပ္ပံ"],
    },
  },
  {
    id: 220,
    kanji: "促",
    onyomi: "ソク",
    kunyomi: "うなが(す)",
    type: "Verb",
    myanmar: "တိုက်တွန်းသည် / အားပေးသည် / မြန်ဆန်စေသည်",
    flashcard: {
      question: "促す (うながす) means?",
      correct_answer: "တိုက်တွန်းသည်",
      false_answers: ["တားဆီးသည်", "ရပ်တန့်သည်"],
    },
  },
  {
    id: 221,
    kanji: "慎",
    onyomi: "シン",
    kunyomi: "つつし(む)",
    type: "Verb/Adjective",
    myanmar: "သတိထားသည် / ဆင်ခြင်သည် / ရိုသေသည်",
    flashcard: {
      question: "慎 (しん) is in 慎重 (careful/prudent)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ပေါ့ဆသော"],
    },
  },
  {
    id: 222,
    kanji: "控",
    onyomi: "コウ",
    kunyomi: "ひか(える)",
    type: "Verb/Noun",
    myanmar: "စောင့်ဆိုင်းသည် / ချုပ်တည်းသည် / မှတ်သားသည်",
    flashcard: {
      question: "控える (ひかえる) means?",
      correct_answer: "စောင့်ဆိုင်း/ချုပ်တည်းသည်",
      false_answers: ["လွန်ကျူးသည်", "အော်သည်"],
    },
  },
  {
    id: 223,
    kanji: "智",
    onyomi: "チ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "ဉာဏ်ပညာ / အသိဉာဏ်",
    flashcard: {
      question: "智 (ち) means?",
      correct_answer: "ဉာဏ်ပညာ",
      false_answers: ["ခွန်အား", "အဝတ်အစား"],
    },
  },
  {
    id: 224,
    kanji: "握",
    onyomi: "アク",
    kunyomi: "nigi(ru)",
    type: "Verb/Noun",
    myanmar: "ဆုပ်ကိုင်သည် / လက်ဆွဲနှုတ်ဆက်သည်",
    flashcard: {
      question: "握る (にぎる) is used in?",
      correct_answer: "握手 (handshake)",
      false_answers: ["散歩 (stroll)", "読書 (reading)"],
    },
  },
  {
    id: 225,
    kanji: "宙",
    onyomi: "chuu",
    kunyomi: "-",
    type: "Noun",
    myanmar: "ဟင်းလင်းပြင် / အာကာသ / ကောင်းကင်",
    flashcard: {
      question: "宙 (ちゅう) is in 宇宙 (universe)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ပင်လယ်"],
    },
  },
  {
    id: 226,
    kanji: "俊",
    onyomi: "シュン",
    kunyomi: "-",
    type: "Adjective/Noun",
    myanmar: "ထူးချွန်သော / ဉာဏ်ကောင်းသော",
    flashcard: {
      question: "俊 (しゅん) means?",
      correct_answer: "ဉာဏ်ကောင်းသော",
      false_answers: ["အပျင်းကြီးသော", "ရုပ်ဆိုးသော"],
    },
  },
  {
    id: 227,
    kanji: "銭",
    onyomi: "セン",
    kunyomi: "ぜに",
    type: "Noun",
    myanmar: "ပိုက်ဆံ / အကြွေစေ့",
    flashcard: {
      question: "銭 (ぜに) means?",
      correct_answer: "ပိုက်ဆံ",
      false_answers: ["ကျောက်ခဲ", "စက္ကူ"],
    },
  },
  {
    id: 228,
    kanji: "渋",
    onyomi: "ジュウ",
    kunyomi: "しぶ(い)",
    type: "Adjective/Noun",
    myanmar: "ခါးသက်သော / ပြည့်ကျပ်နေသော (ယာဉ်ကြော)",
    flashcard: {
      question: "渋 (じゅう) is in 渋滞 (traffic jam)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "လမ်းရှင်းနေခြင်း"],
    },
  },
  {
    id: 229,
    kanji: "銃",
    onyomi: "ジュウ",
    kunyomi: "つつ",
    type: "Noun",
    myanmar: "သေနတ် / လက်နက်",
    flashcard: {
      question: "銃 (じゅう) means?",
      correct_answer: "သေနတ်",
      false_answers: ["ဓား", "လေး"],
    },
  },
  {
    id: 230,
    kanji: "操",
    onyomi: "ソウ",
    kunyomi: "あやつ(る)",
    type: "Verb/Noun",
    myanmar: "မောင်းနှင်သည် / ကိုင်တွယ်သည် / ကျင့်ဝတ်သိက္ခာ",
    flashcard: {
      question: "操る (あやつる) means?",
      correct_answer: "ကိုင်တွယ်မောင်းနှင်သည်",
      false_answers: ["အိပ်ပျော်သည်", "ပြုတ်ကျသည်"],
    },
  },
  {
    id: 231,
    kanji: "携",
    onyomi: "ケイ",
    kunyomi: "たずさ(える)",
    type: "Verb/Noun",
    myanmar: "သယ်ဆောင်သည် / ပါဝင်ပတ်သက်သည်",
    flashcard: {
      question: "携 (けい) is in 携帯 (mobile phone)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "တီဗီ"],
    },
  },
  {
    id: 232,
    kanji: "診",
    onyomi: "シン",
    kunyomi: "み(る)",
    type: "Verb/Noun",
    myanmar: "စစ်ဆေးသည် (ကျန်းမာရေး) / ရောဂါရှာဖွေသည်",
    flashcard: {
      question: "診 (しん) is in 診断 (diagnosis)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ချက်ပြုတ်ခြင်း"],
    },
  },
  {
    id: 233,
    kanji: "託",
    onyomi: "タク",
    kunyomi: "-",
    type: "Noun/Verb",
    myanmar: "အပ်နှံသည် / ယုံကြည်အပ်နှံသည်",
    flashcard: {
      question: "託 (たく) is in 信託 (trust)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ခိုးယူမှု"],
    },
  },
  {
    id: 234,
    kanji: "撮",
    onyomi: "サツ",
    kunyomi: "と(る)",
    type: "Verb",
    myanmar: "ဓာတ်ပုံရိုက်သည် / ဗီဒီယိုရိုက်သည်",
    flashcard: {
      question: "撮影 (さつえい) means?",
      correct_answer: "ဓာတ်ပုံ/ဗီဒီယို ရိုက်ကူးခြင်း",
      false_answers: ["စာရေးခြင်း", "သီချင်းဆိုခြင်း"],
    },
  },
  {
    id: 235,
    kanji: "誕",
    onyomi: "タン",
    kunyomi: "-",
    type: "Noun",
    myanmar: "မွေးဖွားခြင်း",
    flashcard: {
      question: "誕 (たん) is in 誕生日 (birthday)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "သေဆုံးခြင်း"],
    },
  },
  {
    id: 236,
    kanji: "侵",
    onyomi: "シン",
    kunyomi: "おか(す)",
    type: "Verb/Noun",
    myanmar: "ကျူးကျော်သည် / ချိုးဖောက်သည်",
    flashcard: {
      question: "侵 (しん) is in 侵入 (invasion)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ကာကွယ်ခြင်း"],
    },
  },
  {
    id: 237,
    kanji: "括",
    onyomi: "カツ",
    kunyomi: "くく(る)",
    type: "Verb/Noun",
    myanmar: "စုစည်းသည် / ချည်နှောင်သည်",
    flashcard: {
      question: "括 (かつ) is in 包括 (comprehensive/inclusion)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ခွဲထုတ်ခြင်း"],
    },
  },
  {
    id: 238,
    kanji: "謝",
    onyomi: "シャ",
    kunyomi: "あやま(る)",
    type: "Verb/Noun",
    myanmar: "တောင်းပန်သည် / ကျေးဇူးတင်သည်",
    flashcard: {
      question: "謝る (あやまる) means?",
      correct_answer: "တောင်းပန်သည်",
      false_answers: ["ကျိန်ဆဲသည်", "ရိုက်သည်"],
    },
  },
  {
    id: 239,
    kanji: "孝",
    onyomi: "コウ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "မိဘကိုသိတတ်ခြင်း / ဝတ္တရားကျေပွန်ခြင်း",
    flashcard: {
      question: "孝 (こう) is in 親孝行 (filial piety)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ရန်ဖြစ်ခြင်း"],
    },
  },
  {
    id: 240,
    kanji: "駆",
    onyomi: "ク",
    kunyomi: "か(ける)",
    type: "Verb",
    myanmar: "ပြေးလွှားသည် / မောင်းနှင်သည် / အပြည့်အဝသုံးသည်",
    flashcard: {
      question: "駆 (く) is in 駆ける (run/gallop)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အိပ်သည်"],
    },
  },
  {
    id: 241,
    kanji: "透",
    onyomi: "トウ",
    kunyomi: "す(く)",
    type: "Verb/Adjective",
    myanmar: "ဖောက်ထွင်းမြင်ရသော / ကြည်လင်သော",
    flashcard: {
      question: "透 (とう) is in 透明 (transparent)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "မည်းမှောင်သော"],
    },
  },
  {
    id: 242,
    kanji: "津",
    onyomi: "シン",
    kunyomi: "つ",
    type: "Noun",
    myanmar: "ဆိပ်ကမ်း / ကူးတို့ဆိပ်",
    flashcard: {
      question: "津 (つ) is in 津波 (tsunami)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "မီးတောင်"],
    },
  },
  {
    id: 243,
    kanji: "壁",
    onyomi: "ヘキ",
    kunyomi: "かべ",
    type: "Noun",
    myanmar: "နံရံ / အတားအဆီး",
    flashcard: {
      question: "壁 (かべ) means?",
      correct_answer: "နံရံ",
      false_answers: ["ကြမ်းပြင်", "မျက်နှာကျက်"],
    },
  },
  {
    id: 244,
    kanji: "稲",
    onyomi: "トウ",
    kunyomi: "いね",
    type: "Noun",
    myanmar: "စပါးပင်",
    flashcard: {
      question: "稲 (いね) means?",
      correct_answer: "စပါးပင်",
      false_answers: ["ဂျုံ", "ပြောင်းဖူး"],
    },
  },
  {
    id: 245,
    kanji: "仮",
    onyomi: "カ",
    kunyomi: "かり",
    type: "Noun/Adjective",
    myanmar: "ယာယီ / အတု / ဥပမာအားဖြင့်",
    flashcard: {
      question: "仮 (かり) is in 仮名 (kana/alias)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အမြဲတမ်း"],
    },
  },
  {
    id: 246,
    kanji: "裂",
    onyomi: "レツ",
    kunyomi: "さ(く)",
    type: "Verb",
    myanmar: "ဆုတ်ဖြဲသည် / အက်ကွဲသည်",
    flashcard: {
      question: "裂く (さく) means?",
      correct_answer: "ဆုတ်ဖြဲသည်",
      false_answers: ["ချုပ်သည်", "ဆေးသုတ်သည်"],
    },
  },
  {
    id: 247,
    kanji: "敏",
    onyomi: "ビン",
    kunyomi: "-",
    type: "Adjective",
    myanmar: "သွက်လက်သော / ထက်မြက်သော",
    flashcard: {
      question: "敏 (びん) is in 敏感 (sensitive)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ထုံထိုင်းသော"],
    },
  },
  {
    id: 248,
    kanji: "是",
    onyomi: "ゼ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "အမှန်တရား / တရားမျှတမှု / ဤအရာ",
    flashcard: {
      question: "是 (ぜ) is in 是非 (by all means)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ဘယ်တော့မှ"],
    },
  },
  {
    id: 249,
    kanji: "排",
    onyomi: "ハイ",
    kunyomi: "-",
    type: "Verb/Noun",
    myanmar: "ဖယ်ထုတ်ခြင်း / စွန့်ထုတ်ခြင်း",
    flashcard: {
      question: "排 (はい) is in 排除 (exclusion)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ထည့်သွင်းခြင်း"],
    },
  },
  {
    id: 250,
    kanji: "裕",
    onyomi: "ユウ",
    kunyomi: "-",
    type: "Adjective",
    myanmar: "ကြွယ်ဝသော / ပေါများသော / အချိန်ပိုရှိသော",
    flashcard: {
      question: "裕 (ゆう) is in 余裕 (leeway/room)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "မလောက်ငခြင်း"],
    },
  },
  {
    id: 251,
    kanji: "堅",
    onyomi: "ケン",
    kunyomi: "かた(i)",
    type: "Adjective",
    myanmar: "ခိုင်မာသော / တင်းကျပ်သော / ခိုင်ခံ့သော",
    flashcard: {
      question: "堅い (かたい) means?",
      correct_answer: "ခိုင်မာသော",
      false_answers: ["ပျော့ပြောင်းသော", "အရည်"],
    },
  },
  {
    id: 252,
    kanji: "訳",
    onyomi: "ヤク",
    kunyomi: "わけ",
    type: "Noun/Verb",
    myanmar: "ဘာသာပြန်ဆိုချက် / အကြောင်းပြချက်",
    flashcard: {
      question: "訳 (わけ) means?",
      correct_answer: "အကြောင်းပြချက်/အဓိပ္ပာယ်",
      false_answers: ["စျေးနှုန်း", "အရောင်"],
    },
  },
  {
    id: 253,
    kanji: "芝",
    onyomi: "シ",
    kunyomi: "しば",
    type: "Noun",
    myanmar: "မြက်ခင်း",
    flashcard: {
      question: "芝 (しば) means?",
      correct_answer: "မြက်ခင်း",
      false_answers: ["သစ်ပင်", "ပန်း"],
    },
  },
  {
    id: 254,
    kanji: "綱",
    onyomi: "コウ",
    kunyomi: "つな",
    type: "Noun",
    myanmar: "ကြိုးကြီး / အဓိကလမ်းညွှန်ချက်",
    flashcard: {
      question: "綱 (つな) means?",
      correct_answer: "ကြိုးကြီး",
      false_answers: ["အပ်", "စက္ကူ"],
    },
  },
  {
    id: 255,
    kanji: "典",
    onyomi: "テン",
    kunyomi: "-",
    type: "Noun",
    myanmar: "ကျမ်းဂန် / အခမ်းအနား / စံပြ",
    flashcard: {
      question: "典 (てん) is in 辞典 (dictionary)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "မဂ္ဂဇင်း"],
    },
  },
  {
    id: 256,
    kanji: "賀",
    onyomi: "ガ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "ဂုဏ်ပြုခြင်း / ဝမ်းမြောက်ခြင်း",
    flashcard: {
      question: "賀 (が) is in 年賀状 (New Year card)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ခရစ္စမတ်"],
    },
  },
  {
    id: 257,
    kanji: "扱",
    onyomi: "-",
    kunyomi: "あつか(い)",
    type: "Verb/Noun",
    myanmar: "ကိုင်တွယ်သည် / ဆက်ဆံသည်",
    flashcard: {
      question: "扱う (あつかう) means?",
      correct_answer: "ကိုင်တွယ်/ဆက်ဆံသည်",
      false_answers: ["လွှတ်ပစ်သည်", "စားသည်"],
    },
  },
  {
    id: 258,
    kanji: "顧",
    onyomi: "コ",
    kunyomi: "かえり(みる)",
    type: "Verb",
    myanmar: "ပြန်လည်သုံးသပ်သည် / နောက်ကြောင်းပြန်ကြည့်သည်",
    flashcard: {
      question: "顧 (こ) is in 顧問 (advisor)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ကျောင်းသား"],
    },
  },
  {
    id: 259,
    kanji: "弘",
    onyomi: "コウ",
    kunyomi: "ひろ(い)",
    type: "Adjective",
    myanmar: "ကျယ်ပြောသော / ပြန့်နှံ့သော",
    flashcard: {
      question: "弘 (こう) relates to?",
      correct_answer: "ကျယ်ပြန့်ခြင်း",
      false_answers: ["ကျဉ်းမြောင်းခြင်း", "နက်ရှိုင်းခြင်း"],
    },
  },
  {
    id: 260,
    kanji: "看",
    onyomi: "カン",
    kunyomi: "み(る)",
    type: "Verb",
    myanmar: "စောင့်ကြည့်သည် / ကြည့်ရှုပြုစုသည်",
    flashcard: {
      question: "看 (かん) is in 看板 (signboard)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ရေဒီယို"],
    },
  },
  {
    id: 261,
    kanji: "訟",
    onyomi: "ショウ",
    kunyomi: "-",
    type: "Noun/Verb",
    myanmar: "တရားစွဲဆိုခြင်း",
    flashcard: {
      question: "訟 (しょう) is in 訴訟 (lawsuit)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ကခုန်ခြင်း"],
    },
  },
  {
    id: 262,
    kanji: "戒",
    onyomi: "カイ",
    kunyomi: "いまし(める)",
    type: "Verb/Noun",
    myanmar: "သတိပေးသည် / ဆုံးမသည် / စောင့်စည်းသည်",
    flashcard: {
      question: "戒 (かい) is in 警戒 (vigilance/alert)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အိပ်ငိုက်ခြင်း"],
    },
  },
  {
    id: 263,
    kanji: "祉",
    onyomi: "シ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "သာယာဝပြောရေး / ကံကောင်းခြင်း",
    flashcard: {
      question: "福祉 (ふくし) means?",
      correct_answer: "လူမှုဖူလုံရေး/သာယာဝပြောရေး",
      false_answers: ["စစ်ပွဲ", "ဖျားနာခြင်း"],
    },
  },
  {
    id: 264,
    kanji: "誉",
    onyomi: "ヨ",
    kunyomi: "ほまれ",
    type: "Noun",
    myanmar: "ဂုဏ်သိက္ခာ / ဂုဏ်ယူခြင်း",
    flashcard: {
      question: "誉 (よ) is in 名誉 (honor)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အရှက်ရခြင်း"],
    },
  },
  {
    id: 265,
    kanji: "歓",
    onyomi: "カン",
    kunyomi: "よろこ(ぶ)",
    type: "Noun/Verb",
    myanmar: "ဝမ်းမြောက်ခြင်း / ကြိုဆိုခြင်း",
    flashcard: {
      question: "歓 (かん) is in 歓迎 (welcome)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "နှင်ထုတ်ခြင်း"],
    },
  },
  {
    id: 266,
    kanji: "奏",
    onyomi: "ソウ",
    kunyomi: "かな(でる)",
    type: "Verb",
    myanmar: "တီးခတ်သည် / တင်ပြသည်",
    flashcard: {
      question: "奏 (かなでる) is used for?",
      correct_answer: "တူရိယာတီးခြင်း",
      false_answers: ["ရေကူးခြင်း", "စာဖတ်ခြင်း"],
    },
  },
  {
    id: 267,
    kanji: "勧",
    onyomi: "カン",
    kunyomi: "すす(める)",
    type: "Verb",
    myanmar: "တိုက်တွန်းသည် / အကြံပေးသည်",
    flashcard: {
      question: "勧める (すすめる) means?",
      correct_answer: "တိုက်တွန်း/အကြံပေးသည်",
      false_answers: ["တားဆီးသည်", "မုန်းတီးသည်"],
    },
  },
  {
    id: 268,
    kanji: "騒",
    onyomi: "ソウ",
    kunyomi: "sawa(gu)",
    type: "Verb/Noun",
    myanmar: "ဆူညံသည် / ရုန်းရင်းဆန်ခတ်ဖြစ်သည်",
    flashcard: {
      question: "騒ぐ (さわぐ) means?",
      correct_answer: "ဆူညံအောင်လုပ်သည်",
      false_answers: ["တိတ်ဆိတ်နေသည်", "အိပ်သည်"],
    },
  },
  {
    id: 269,
    kanji: "閥",
    onyomi: "バツ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "ဂိုဏ်းဂဏ / အုပ်စု / မျိုးရိုး",
    flashcard: {
      question: "閥 (ばつ) is in 財閥 (zaibatsu/conglomerate)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ပန်းခြံ"],
    },
  },
  {
    id: 270,
    kanji: "甲",
    onyomi: "コウ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "ပထမအဆင့် / လက်ဖမိုး / အခွံ (လိပ်ခွံ)",
    flashcard: {
      question: "甲 (こう) often represents?",
      correct_answer: "ပထမ (A grade)",
      false_answers: ["ဒုတိယ (B grade)", "နောက်ဆုံး"],
    },
  },
  {
    id: 271,
    kanji: "縄",
    onyomi: "ジョウ",
    kunyomi: "なわ",
    type: "Noun",
    myanmar: "ကြိုး / ကျစ်ကြိုး",
    flashcard: {
      question: "縄 (なわ) is in Okinawa (沖縄)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "Osaka"],
    },
  },
  {
    id: 272,
    kanji: "郷",
    onyomi: "キョウ",
    kunyomi: "さと",
    type: "Noun",
    myanmar: "ဇာတိမြေ / ရွာ",
    flashcard: {
      question: "郷 (きょう) is in 故郷 (hometown)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "နိုင်ငံခြား"],
    },
  },
  {
    id: 273,
    kanji: "揺",
    onyomi: "ヨウ",
    kunyomi: "ゆ(れる)",
    type: "Verb",
    myanmar: "လှုပ်ခါသည် / ယိမ်းထိုးသည်",
    flashcard: {
      question: "揺れる (ゆれる) means?",
      correct_answer: "လှုပ်ခါသည်",
      false_answers: ["ငြိမ်နေသည်", "ပြေးသည်"],
    },
  },
  {
    id: 274,
    kanji: "免",
    onyomi: "メン",
    kunyomi: "-",
    type: "Noun/Verb",
    myanmar: "ကင်းလွတ်ခွင့် / လိုင်စင် / ထုတ်ပယ်ခြင်း",
    flashcard: {
      question: "免 (めん) is in 免許 (license)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "စာအုပ်"],
    },
  },
  {
    id: 275,
    kanji: "既",
    onyomi: "キ",
    kunyomi: "すで(に)",
    type: "Adverb",
    myanmar: "ပြီးနှင့်သော / အရင်ကတည်းက",
    flashcard: {
      question: "既に (すでに) means?",
      correct_answer: "ပြီးနှင့်ပြီ (already)",
      false_answers: ["မကြာမီ", "ဘယ်တော့မှ"],
    },
  },
  {
    id: 276,
    kanji: "薦",
    onyomi: "セン",
    kunyomi: "すす(める)",
    type: "Verb",
    myanmar: "ထောက်ခံချက်ပေးသည် / အကြံပြုသည်",
    flashcard: {
      question: "薦める (すすめる) is in 推薦 (recommendation)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ကန့်ကွက်ခြင်း"],
    },
  },
  {
    id: 277,
    kanji: "隣",
    onyomi: "リン",
    kunyomi: "tonari",
    type: "Noun",
    myanmar: "အိမ်နီးနားချင်း / ဘေးနား",
    flashcard: {
      question: "隣 (となりの) means?",
      correct_answer: "ဘေးနားက",
      false_answers: ["အဝေးက", "အပေါ်က"],
    },
  },
  {
    id: 278,
    kanji: "華",
    onyomi: "カ",
    kunyomi: "はな",
    type: "Noun/Adjective",
    myanmar: "တောက်ပသော / ခမ်းနားသော / ပန်း",
    flashcard: {
      question: "華 (か) is in 豪華 (gorgeous)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ရိုးရှင်းသော"],
    },
  },
  {
    id: 279,
    kanji: "範",
    onyomi: "ハン",
    kunyomi: "-",
    type: "Noun",
    myanmar: "အတိုင်းအတာ / ပုံစံ / နမူနာ",
    flashcard: {
      question: "範 (はん) is in 範囲 (range/scope)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အမှတ်"],
    },
  },
  {
    id: 280,
    kanji: "隠",
    onyomi: "イン",
    kunyomi: "かく(す)",
    type: "Verb",
    myanmar: "ဖုံးကွယ်သည် / ပုန်းအောင်းသည်",
    flashcard: {
      question: "隠す (かくす) means?",
      correct_answer: "ဖုံးကွယ်သည်",
      false_answers: ["ပြသသည်", "ဖွင့်သည်"],
    },
  },
  {
    id: 281,
    kanji: "徳",
    onyomi: "トク",
    kunyomi: "-",
    type: "Noun",
    myanmar: "ကိုယ်ကျင့်တရား / ကောင်းမှုကုသိုလ် / ဂုဏ်ကျေးဇူး",
    flashcard: {
      question: "徳 (とく) means?",
      correct_answer: "ကိုယ်ကျင့်တရား",
      false_answers: ["ဒေါသ", "မုသား"],
    },
  },
  {
    id: 282,
    kanji: "哲",
    onyomi: "テツ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "ဒဿန / ပညာရှိ",
    flashcard: {
      question: "哲 (てつ) is in 哲学 (philosophy)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "သင်္ချာ"],
    },
  },
  {
    id: 283,
    kanji: "杉",
    onyomi: "サン",
    kunyomi: "すぎ",
    type: "Noun",
    myanmar: "စီဒါပင် (Cedar)",
    flashcard: {
      question: "杉 (すぎ) means?",
      correct_answer: "စီဒါပင်",
      false_answers: ["ဝါးပင်", "အုန်းပင်"],
    },
  },
  {
    id: 284,
    kanji: "里",
    onyomi: "リ",
    kunyomi: "さと",
    type: "Noun",
    myanmar: "ရွာ / ဇာတိအိမ် / အကွာအဝေးတိုင်းတာမှု (Ri)",
    flashcard: {
      question: "里 (さと) means?",
      correct_answer: "ရွာ/ဇာတိ",
      false_answers: ["မြို့တော်", "ကမ်းခြေ"],
    },
  },
  {
    id: 285,
    kanji: "釈",
    onyomi: "シャク",
    kunyomi: "-",
    type: "Noun/Verb",
    myanmar: "ရှင်းလင်းချက် / လွှတ်ပေးခြင်း",
    flashcard: {
      question: "釈 (しゃく) is in 解釈 (interpretation)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ဖုံးကွယ်ခြင်း"],
    },
  },
  {
    id: 286,
    kanji: "己",
    onyomi: "コ",
    kunyomi: "おのれ",
    type: "Noun/Pronoun",
    myanmar: "မိမိကိုယ်ကို",
    flashcard: {
      question: "己 (おのれ) means?",
      correct_answer: "မိမိကိုယ်ကို (Self)",
      false_answers: ["သူတစ်ပါး", "ရန်သူ"],
    },
  },
  {
    id: 287,
    kanji: "妥",
    onyomi: "ダ",
    kunyomi: "-",
    type: "Adjective",
    myanmar: "သင့်တော်သော / ငြိမ်းချမ်းသော",
    flashcard: {
      question: "妥 (だ) is in 妥協 (compromise)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "တိုက်ခိုက်ခြင်း"],
    },
  },
  {
    id: 288,
    kanji: "威",
    onyomi: "イ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "အာဏာ / ဂုဏ်ဒြပ် / ခြိမ်းခြောက်ခြင်း",
    flashcard: {
      question: "威 (い) is in 威力 (power/force)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အားနည်းချက်"],
    },
  },
  {
    id: 289,
    kanji: "豪",
    onyomi: "ゴウ",
    kunyomi: "-",
    type: "Adjective/Noun",
    myanmar: "ခမ်းနားသော / အစွမ်းထက်သော / ဩစတေးလျ (အတိုကောက်)",
    flashcard: {
      question: "豪 (ごう) is in 豪華 (luxurious)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ဆင်းရဲသော"],
    },
  },
  {
    id: 290,
    kanji: "熊",
    onyomi: "ユウ",
    kunyomi: "くま",
    type: "Noun",
    myanmar: "ဝက်ဝံ",
    flashcard: {
      question: "熊 (くま) means?",
      correct_answer: "ဝက်ဝံ",
      false_answers: ["ကြောင်", "ခွေး"],
    },
  },
  {
    id: 291,
    kanji: "滞",
    onyomi: "タイ",
    kunyomi: "とどこお(る)",
    type: "Verb/Noun",
    myanmar: "နှောင့်နှေးခြင်း / တည်းခိုခြင်း / ကြန့်ကြာခြင်း",
    flashcard: {
      question: "滞 (たい) is in 滞在 (stay/sojourn)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ထွက်ခွာခြင်း"],
    },
  },
  {
    id: 292,
    kanji: "微",
    onyomi: "ビ",
    kunyomi: "かす(か)",
    type: "Adjective",
    myanmar: "သေးငယ်သော / သိမ်မွေ့သော",
    flashcard: {
      question: "微 (び) is in 微笑 (smile)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အော်ဟစ်ခြင်း"],
    },
  },
  {
    id: 293,
    kanji: "隆",
    onyomi: "リュウ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "ထွန်းကားခြင်း / မြင့်တက်ခြင်း",
    flashcard: {
      question: "隆 (りゅう) is in 隆盛 (prosperity)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ပျက်စီးခြင်း"],
    },
  },
  {
    id: 294,
    kanji: "症",
    onyomi: "ショウ",
    kunyomi: "-",
    type: "Noun",
    myanmar: "ရောဂါလက္ခဏာ",
    flashcard: {
      question: "症 (しょう) is in 症状 (symptoms)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "ဆေးဝါး"],
    },
  },
  {
    id: 295,
    kanji: "暫",
    onyomi: "ザン",
    kunyomi: "しばら(く)",
    type: "Adverb",
    myanmar: "ခဏတာ / ခေတ္တခဏ",
    flashcard: {
      question: "暫く (しばらく) means?",
      correct_answer: "ခဏတာ (For a while)",
      false_answers: ["အမြဲတမ်း", "မနေ့က"],
    },
  },
  {
    id: 296,
    kanji: "忠",
    onyomi: "chuu",
    kunyomi: "-",
    type: "Noun",
    myanmar: "သစ္စာရှိခြင်း / ရိုးသားခြင်း",
    flashcard: {
      question: "忠 (ちゅう) is in 忠実 (faithful)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "လိမ်ညာခြင်း"],
    },
  },
  {
    id: 297,
    kanji: "倉",
    onyomi: "ソウ",
    kunyomi: "くら",
    type: "Noun",
    myanmar: "ဂိုဒေါင် / သိုလှောင်ရုံ",
    flashcard: {
      question: "倉 (くら) means?",
      correct_answer: "ဂိုဒေါင်",
      false_answers: ["အိမ်သာ", "ဥယျာဉ်"],
    },
  },
  {
    id: 298,
    kanji: "彦",
    onyomi: "ゲン",
    kunyomi: "hiko",
    type: "Noun",
    myanmar: "ယောင်္ကျားလေး / သူရဲကောင်း (နာမည်များတွင်သုံးသည်)",
    flashcard: {
      question: "彦 (ひこ) is used for?",
      correct_answer: "ယောင်္ကျားလေးအမည်များ",
      false_answers: ["မိန်းကလေးအမည်များ", "မြို့အမည်များ"],
    },
  },
  {
    id: 299,
    kanji: "肝",
    onyomi: "kan",
    kunyomi: "kimo",
    type: "Noun",
    myanmar: "အသည်း / အဓိကအချက် / သတ္တိ",
    flashcard: {
      question: "肝 (きも) means?",
      correct_answer: "အသည်း",
      false_answers: ["နှလုံး", "အဆုတ်"],
    },
  },
  {
    id: 300,
    kanji: "喚",
    onyomi: "カン",
    kunyomi: "わめ(く)",
    type: "Verb",
    myanmar: "အော်ဟစ်သည် / ဆင့်ခေါ်သည်",
    flashcard: {
      question: "喚 (かん) is in 召喚 (summons)?",
      correct_answer: "မှန်သည်",
      false_answers: ["မှားသည်", "အိပ်ပျော်ခြင်း"],
    },
  },
];
